### ISSUE TITLE
Open Weather Map

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard4#10]
hi Michel,
the online weather data from OpenWeatherMap seems to be different from the actual ones.
I had my new API key from their website and queried for my observatory location (location id=2517643) but the data in MW4 are completely different. How can i set location in MW4?

In the attached image you can see the JSON data from a direct API call and on the right the values shown by MW4.

ferrante
![Screenshot from 2020-01-30 14-17-33](https://user-images.githubusercontent.com/38842860/73453122-a3fc3d00-436b-11ea-9245-4953358ce846.png)

**Comment by mworion** [comment]
Ferrante,

could you post a log from MW4 ? THat's the best way for countercheck for me.

Michel

**Comment by fenriques** [comment]
ok there it is.
Sequence of operation was (not relevant to the OpenWeatherMap issue):
- Start MW
- Turn on the mount
- Turn on INDI server.

Ferrante

[mw4-2020-01-30.log](https://github.com/mworion/MountWizzard4/files/4135034/mw4-2020-01-30.log)

**Comment by mworion** [comment]
Hi Ferrante, 

thanks for the log. Unfortunately you need to set the debug level to deeb debug to get this data.
MW4 tagest location from the mount. It should be the values shown in mount tab. The large numbers in temperature in json are in Kelvin, so you have to subtract 273.14 deg.

Michel

**Comment by fenriques** [comment]
hi Michel,
yes, I got that temperature in the json file were Kelvin and not Celsius.
But still all the data are quite different. 
The mount has the location set with 1-2 arcsec precision, so it should not be the cause.
Could it be that when I start MW4 the mount is still off so it cannot read the correct location from the mount?
Attached the deep level log.
[mw4-2020-01-30.log.zip](https://github.com/mworion/MountWizzard4/files/4135987/mw4-2020-01-30.log.zip)

Ferrante

**Comment by mworion** [comment]
Hi Ferrante, for some reason I don't see the log part for whatever reason.
Would you mind to update to actual version and make a deep debug again ?
Michel

**Comment by fenriques** [comment]
updated to the last version.
Ferrante
[mw4-2020-01-30.log.zip](https://github.com/mworion/MountWizzard4/files/4136068/mw4-2020-01-30.log.zip)

**Comment by mworion** [comment]
OK find no error so far. 
I am using the forecast api, not the current weather api. 
In forecast there is said:

More detailed forecast. For the upcoming 4 days (96 hours) you get forecast data for each hour means we provide you with data for 96 timestamps.
Higher geographic accuracy. The hourly forecast uses a model grid with 0.25 degrees step when for other forecasts we use grids with 0.5 and 0.6 degrees step.

This might be the difference. But I have to check, if the forecast really starts a now and not now + 1h

Michel

**Comment by fenriques** [comment]
ok, understood.
Thanks for investigating.
