### ISSUE TITLE
Direct Input and Slew to given RA/DEC and ALT/AZ

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#100]
Hi Michel,

in addition to the other topics, I stumbled upon one use case. During modelling the horizon line, I had to use a couple of time the Virtual Hand Pad in order to enter ALT/AZ coordinated directly. 

Therefore I think it would be a good idea to have the possibility to directly enter coordinates in two fields and a button to initiate the slew. Another filed good toggle the input reading between RA/DEC and ALT/AZ. So both use cases are covered with minimal loss of space, since only two input fields are required, one slew button and toggle switch.
The input of RA should be in "hh mm ss.s" and the DEC in d.d forma. ALT/AZ of course in ddd.d dd.d.

That would be the icy on the cake :)

Thank you for considering!

Cheers
Rüdiger

**Comment by mworion** [comment]
Have a look to 0.220.6 and Merry Christmas!
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

marvelous! I have only 2 points. 1 Bug, 2 suggestions.
Bug: When trying to enter a ALT value it is not accepted.

![2020-12-23_17h30_45](https://user-images.githubusercontent.com/65772654/103018087-e5c64100-4544-11eb-8d03-fcca04b09bda.png)

Suggestion 1: Instead of opening the input window, it would be easier to enter the value directly in the field, and give the hint for the format via tool tip. By this the switching between mouse and keyboard would be minimized. 

Suggestion 2: The activation order when jumping via Tab from field to field is wrong. Should be: Alt -> Az -> Slew Alt/Az, or RA -> DEC -> Slew RA/DEC

By suggestion one and two you can quickly work exclusively with keyboard (Tab, Numpad, and Enter). This would be much more fluent.

But anyway: Many thanks! what a nice gift.

Happy X-Mas! Stay safe and sound!

May greetings,
Rüdiger

**Comment by mworion** [comment]
Update in 0.220.7

**Comment by Ruediger3** [comment]
Almost perfect, except the RA/DEC slew button gets not active after values input and the h mm ss input is not converted to decimal if directly input (which is minor). 

![2020-12-23_18h39_11](https://user-images.githubusercontent.com/65772654/103023551-75242200-454e-11eb-97da-792b25c8510a.png)

**Comment by mworion** [comment]
...that's some work to do. Will happen after Christmas....

**Comment by Ruediger3** [comment]
Perfect! Thank you!
Stay healthy and enjoy X-Mas!

**Comment by Ruediger3** [comment]
Hello Michel,

One question: are the Re/Dec coordinates which you can enter J2000 or JNOW? It should be J2000. 
Thanks!

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
for me it has to be J2000 as the user can't do anything with JNow. I will convert them to JNow automatically
Michel

**Comment by Ruediger3** [comment]
Right, I totally agree. Just want to make that sure, since I cannot test with this weather ;)
Thanks!

**Comment by mworion** [comment]
Rüdiger,
Could you check if it is working ?
As I move to a first release, I just would like to collect feedback from all not closed issues.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

not yet. Everything is snow covered and not a a single clear night, But since I had created the horizon limits with it and it was working (except tracking started) we should close this issue. If there is a problem, I will create a new one. 

Cheers
Rüdiger

**Comment by mworion** [comment]
The tracking issue should be addressed as well in the actual release. I will keep the status before (tracking or non tracking)
