### ISSUE TITLE
Please update Ubuntu_Scripts for new version of MW4?

### ISSUE THREAD

**Issue by airscottdenning** [mworion/MountWizzard4#101]
Setting up a new machine and these still point to old dependencies

**Comment by mworion** [comment]
Scott,
quick question: you refer to ubuntu mate correct? All other script refer to the PyPi packet manager, which holds all dependencies.
Michel

**Comment by mworion** [comment]
Scott,
made an update to actual dependencies. But we have to think about another way. As I have to precompile it normally for each python version 3.7 - 3.9 (actually only for python 3.8) and all changes done anyway on PyPi. An all I could do, run it on my physical RPi4 which only supports python 3.8 right now.
I asked the maintainer of the used packages to build wheels for aarm64 as well, but still not all do it.
Michel

**Comment by airscottdenning** [comment]
Thank you for doing this!

I will try to update my MW4 today.

So appreciative of all you do with this software!

**Comment by mworion** [comment]
Hi Scott,
how things going ? I learned, that some guy's doing automation for GitHub Actions might allow building for more that ubuntu, windows and macOS. If they succeed I could offer an automatic build for aarch64.
If there is nothing new about it, I would close this issue. For the release candidate which will be soon there, the imported libraries should be stable and I will update the scripts with actual precompiled packages again.
Michel

**Comment by mworion** [comment]
Hi Scott,
I managed it to make an automatic build for the precompiled packages for arm64 architecture (e.g. RPi4) and I build some new scripts for installation. Would you mid once they are ready to test them in your setup. Right now I could support Ubuntu Mate 18.04.x and 20.04.x for python 3.7, 3.8 and 3.9.
Michel

**Comment by airscottdenning** [comment]
Hi Michel,

I urge you to go ahead and close the issue.

Your Ubuntu script does ion fact run on my Pi4 under ubuntu aarch64 (I gave up on ubuntu-mate for a number of reasons), and is able to build/manage the mount model.

But the performance on the Pi4 is so laggy that I gave up and just bought an inexpensive linux amd64 box to run my astro-gear. Now I’m getting snappy performance not only with MW4 but also with FireCapture, which I could never get to run properly on the Pi.

Sorry to have taken your time and effort chasing the Pi. It worked fine for image capture (KStars etc) but is too slow for other astro-tasks.

Your contributions to the open-source astro community are wonderful, and I am deeply grateful!

Scott

**Comment by mworion** [comment]
Scott,

don't worry. For my beside the astro imaging topic it's also a project to train sw-development. And arm will be in more an more computer anyway (might that some Mac users need it in future, too). Right now it's an automated build, I do not have to do anything manual to build the wheels and a user just need a script, that's all.
I close this topic.

Michel

BTW: I also have a fitlet intel base linux computer on my rig and everything is fine.
