### ISSUE TITLE
0.220.4b6 no go

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#102]
Updated recently to 0.220.4b6
Clear sky so first full model run.
MW4 started ok. All indicators green.
First run just a few points for a polar alignment.
Dome and mount both slewed ok.
But no image was taken.
After a manual image was taken in the image window, mw4 moved to the next point.
Again no image was taken and sequence stopped.
Tried other models. No go.
Restarted MW4 a few times. No change.
Gave up.

Moved over to ModelCreator.
That also failed on me with the domesync . . . . . .  sigh
A crisp clear sky at last and no model could be build.

Today downgraded again to last working version (for me) 0.152.0b4

Attached the 2 logs. before and after midnight.

[mw4-2020-12-25.log](https://github.com/mworion/MountWizzard4/files/5742024/mw4-2020-12-25.log)
[mw4-2020-12-24.log](https://github.com/mworion/MountWizzard4/files/5742025/mw4-2020-12-24.log)

**Comment by mworion** [comment]
Hello Arie,

thanks for testing and sorry to hear. There was a dome slew bug (did not report finished slewing), which made the dome slew, but not start the imaging as the dome didi not signal slews done. If you did a manual image, you made this signal manually. This was already discovered by another use and it's already fixed since 0.220.5. 
The actual version with some add-ons from Rüdiger is 0.220.7.

Michel

**Comment by ACMBakx** [comment]
Thank you Michel.
Before I upgrade again:
Is it possible that I have 2 instances installed of MW4?
In one folder I can run 0.152.0b4 as a fall-back option and in another folder I run later versions without affecting the "old" version?
Like that I will always have a working version available.
Obviously I cannot run them simultaneously.

Arie

**Comment by mworion** [comment]
Hello Arie,

Basically no problem. There are two ways doing that: 

The basic way (without syncing setting and data):
- Make a second (or third…) work dir. 
- Install MW$ Version into it.
- If you would like to share some settings, copy them between the workers as you would like.
- This is the preferred way as you have separate installation which do not interfere with each other. 

The experienced way (not often tested)-
you need to double the installations in the same workday, meaning having 2 times „venv“ folder and two sets of scripts
- doing a second temper, install a new version of MW4
- rename the „venv" folder to „venv2“
- copy this „venv2“ folder to your existing worker
- copy the MW4_Run.Bat to MW4_Run.bat
- edit the MW4_Run.bat and change there the references „venv“ to „venv2“
- do the same for MW4_Update if necessary
Now you have 2 installations working on the same user data and configs.
Please be aware that any changes (file deletions, config changes) will be done the the same data.

I would recommend staying with the basic way, as you might use the second installation for new tryout and testing. This should not harm you existing work, so having this in two separate folders make a lot of sense. Any interaction is done by yourself manually.

If the performance of the connection and the computer allows, with the basic setup you could run two versions of MW4 at the same time! This is not possible, when using the same worker as I did not implement file sharing protection.

Hope this helps,

Michel

**Comment by mworion** [comment]
… and as regarding to your task:

Stay with basic, copy you work folder and do the update in this copied folder. If you are satisfied, you have the old one as backup and keep working with the new one.

Michel

**Comment by ACMBakx** [comment]
Installed 0.220.7
Asscom focusser does not connect properly

Same issue as previous
start 3 point model.
Slewing dome to 1
Slewing mount to 1
Align model data refreshes
---and then nothing happens anymore--
manual image command
Slews to point 2
Exposed but image not download.

See logfile attached.

I had issues with a second installation in another folder.
The path's in the scripts were not valid anymore I think.
So I did some editing in the scripts, but could not get it to work.
Ended up with 0.220.7 in the "old" folder and in the new folder.
Tried to revert back to 0.152.0b4, but this could not be found anymore?

(venv) C:\Users\arieb\Desktop\MW4_0.150_Work\venv\Scripts>pip install mountwizzard==0.152.0b4
ERROR: Could not find a version that satisfies the requirement mountwizzard==0.152.0b4
ERROR: No matching distribution found for mountwizzard==0.152.0b4

I think I am up for a complete new fresh installation :-(

run.bat
venv\Scripts\activate && venv\Scripts\python.exe venv\Lib\site-packages\mw4\loader.py && deactivate


But what to keep and what to replace?

[mw4-2020-12-26newfolder.log](https://github.com/mworion/MountWizzard4/files/5743195/mw4-2020-12-26newfolder.log)
[mw4-2020-12-26oldfolder.log](https://github.com/mworion/MountWizzard4/files/5743196/mw4-2020-12-26oldfolder.log)

**Comment by ACMBakx** [comment]
Update
Got a 0.152.0b6 working in the copy folder.
I'd like to rename the folder, but afraid that file references will be lost or mingled again.

occasional error message, that can be removed by deleting config files, but then al settings are lost
last line where connection with nasa is sought is I think the culprit.

0-12-26 16:03:58.411][C][      loader.py][ 252] Traceback (most recent call last):
[2020-12-26 16:03:58.412][C][      loader.py][ 252]   File "C:\Users\arieb\Desktop\MW4Work_Copy\venv\Lib\site-packages\mw4\gui\mainWmixin\tabSettMisc.py", line 184, in updateDeltaT    self.app.mount.obsSite.loader('deltat.data', reload=True)
[2020-12-26 16:03:58.412][C][      loader.py][ 252]   File "C:\Users\arieb\Desktop\MW4Work_Copy\venv\lib\site-packages\skyfield\iokit.py", line 179, in __call__    path = self._fetch(url, filename, reload, backup)
[2020-12-26 16:03:58.412][C][      loader.py][ 252]   File "C:\Users\arieb\Desktop\MW4Work_Copy\venv\lib\site-packages\skyfield\iokit.py", line 200, in _fetch    download(url, path, self.verbose, backup=backup)
[2020-12-26 16:03:58.412][C][      loader.py][ 252]   File "C:\Users\arieb\Desktop\MW4Work_Copy\venv\lib\site-packages\skyfield\iokit.py", line 453, in download    raise e2
[2020-12-26 16:03:58.412][C][      loader.py][ 252] OSError: cannot get ftp://cddis.nasa.gov/products/iers/deltat.data because <urlopen error ftp error: TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)>
[2020-12-26 16:03:58.412][C][      loader.py][ 253]

**Comment by mworion** [comment]
Hi Arie,
at about 20:30 I will be online for 2 or 3 hours. If you have some more questions, I could answer them immediately. I will check all logs again to find out what happened.

To your installation:
venv) C:\Users\arieb\Desktop\MW4_0.150_Work\venv\Scripts>pip install mountwizzard==0.152.0b4
ERROR: Could not find a version that satisfies the requirement mountwizzard==0.152.0b4
ERROR: No matching distribution found for mountwizzard==0.152.0b4

there was a simple misspelling (mountwizzard instead of mountwizzard4), this caused the problem.
The nasa FTP server seems to be out of service some time or access limited. Have a look to this as well.

Michel

**Comment by ACMBakx** [comment]
If you like I can connect you up to my dome  thru Teamviewer ?
I'll have it up and running for you.
Via a webcam you can watch what's happening in the dome.

**Comment by ACMBakx** [comment]
There used to be an option to update the delta-UHC etc.
I do not see this anymore.

I'll be monitoring my dome over remote desktop to check.
Or send me a whatsapp at +31620430385

**Comment by ACMBakx** [comment]
For the dome offset calculations:
How do I determine the vertical offset at the moment?
Is it centre dome to RA/DEC cross or is it centre dome to bottom mount?

**Comment by ACMBakx** [comment]
Hi,
An update
I now have 2 folders on my desktop with MW4 in them.
One with 0.152.0b6 and one with with 0.220.7
They both start up ok.
0.220.7 still halts after the first slew. Alike 0.220.6 did.

**Comment by mworion** [comment]
Online now.

**Comment by mworion** [comment]
In the log files of 0.220.7 I still see Exceptions. Actually try to redo this on ASCOM simulator to check wy.

**Comment by mworion** [comment]
Hi Arie,
are you able to make me the dome driver available?
Michel

**Comment by mworion** [comment]
I found it on website and could download the driver. Have the same behavior now here like you experience. As result it is understood from my side now:

The ScopeDome driver is blocking in the slew call, what it must not doing:
<img width="1390" alt="Bildschirmfoto 2020-12-27 um 09 20 15" src="https://user-images.githubusercontent.com/6632980/103167972-f8d05e00-482f-11eb-82f7-e95711d0e79f.png">

This blocking call holds MW4 in overall (see the missing time updates) during waiting.
The only reason why this worked in earlier versions is that there I had a separate thread running for checking the "slewing" status on top. This allowed during the blocked MW4 application still to wait until slew finished and start work over. But still there the situation was blocking the whole application anyway. This is also the reason why you get these timeout messages, because nothing happens during slewing the dome.

Now I would like to address this issue to the developers (you should do this as customer as well) that they bug fix their driver to comply to the Ascom standard.

Secondly (like others e.g. SGPro...) try to find a workaround. It seems that this issues is more frequent than expected and ASCOM causes problems. So everybody finds his way around.

Now with the analysis done, it should be a matter of 1-2 days to implement the workaround for it.

Michel

**Comment by ACMBakx** [comment]
I recall that Martin had a similar problem with the scopedomedriver, when I was testing for him too . . . . tested a lot.
He contacted Scopedome about the ascom issue and I believe they did a fix.
MC slews the dome in 2 steps. First the dome make a swing, then the mount slews and last the dome is given a correction.
I think he then polls the mount for slewing or not (with a delay because the dome is responding rather slow to instructions)
Then the image is taken. We had it that the mount slew was done and because the dome did not start up immediately for the adjustment, MC did not see a slew in progress and the image was taken and then the dome woke up and made the position adjustment....... 

The scopedome software guy is Jacek Pala    jacek.pala@scopedome.com

I don't know what to tell them other then that you will speak on my behalf.

**Comment by ACMBakx** [comment]
About a special point sequence for dome-users.
I believe that my "problem" mainly exists because of the ratio GEM offset to dome radius.
My telescope barely fits inside the dome. Only a few centimeters left at some spots between the telescope and the dome roof. 
GEM being 35cm versus dome radius of <100cm.
This causes big adjustments to the dome-Az and the alignment is very critical.
Telescope aperture is 25cm, versus dome slot <60cm width.
I suppose that bigger domes (like Nicolas) need far less correction and are less critical.
The current method works good enough for me. So do not bother any further on this topic.
I model only a few times per year when the telescope has been removed from the mount.
Like now, after having cleaned the mirror and re-collimation.

I looked at SGP, Voyager, Prism, Scopedome, MC. All having a dome sync module.
Nina and APT don't have a build-in dome module.
With those I can sync the dome to the mount via the dome driver.
But that's slow, because the dome back-tracks the mount.
Which is ok for imaging but unfit for modelling. Unless you put a 30sec delay after a mount slew for each point...........to allow the dome to catch up.
However, they all use the distance from the Ra/Dec cross to the sphere centre for vertical offset.
That's because all mounts have a different size below this cross.
I was quite surprised to see that MW4 was incorporating the mount dimensions in the settings.
If you know it's not a problem, but now we have to use different values for this in MW4 and in the imaging software.
My sphere centre is at 163cm and the Ra/Dec cross at 175cm.
I.e. +12cm for GEM vert offset. But MW4 requires the bottom off the mount.
Not consistent. But who am I.

best regards
Arie

**Comment by mworion** [comment]
Hi Arie,
first of all to your last words: you are the user and have the right to get a reasonable solution. I don't have a dome so far but if I would argue the same.
I'm currently changing the parameter to fit to others. It makes a lot of sense. Also from measuring it might be easier. From logic, that's the difference to take into account as you want the GEM point (crossing point RA / DEC axis) to be in the center of the dome sphere.
The calculation I do respects small domes as well. There is no reason to make this corrections. As I do the target position for the mount first, I know where the dome has to slew and could slew both at the same time. This is better than syncing afterward. And this on step approach should fit (If I do my work correctly) to all geometries.
The workaround for the blocking issue is done. Also your remarks about slow responses of the dome should be OK as I'm testing now with the actual ScopeDome driver. And in my setup it works. Once the geometry issue is sorted out, I will give you a new release (probably in a joined session for test).
Michel

**Comment by ACMBakx** [comment]
Good news!
I am just looking in the 10M 1000hps manual page 57
They refer to base mount, but I think that is not correct.
You can see in the Scopedome driver how they define it.
Same for SGP, if you use it . . . you can look it up in their help file.

The dome Az pointing is absolutely good as it is with the GEM corrections applied.
Don't get me wrong. No complaints about that.
MW4 is dead on looking through the centre of the slot all around.
Even those 2 tricky positions NE and NW where the dome has to turn 180deg in the opposite direction.
MC still is less accurate. At quite some positions the telescope is partially blocked by the dome.
Martin does not quite understand how to implement it, he confessed.
But even at those positions a solvable image can be taken.

As I mentioned to Martin a while ago:
The dome is like an old man. A bit deaf and a bit slow in responding.
But that's build into the software I understood. There are so many settings and parameters in this Scopedome-driver.
The drive motors are 12V only and accelerations should be gentle.
You tell the dome to move. Then he waits a while and says, ughh?
Ok ok I am going . . . . . . and then slowly he starts to move.  :-)

I have the Az-accuracy set at 3deg, to prevent surging around a desired Az value.

Cheers
Arie

**Comment by Ruediger3** [comment]
> Nina and APT don't have a build-in dome module.

Hi Arie, 
NINA has a dome module and many controls for it. But you need the nightly branch.
![2020-12-27_16h05_42](https://user-images.githubusercontent.com/65772654/103173761-79598380-485d-11eb-9e8f-19a692dc25e9.png)

It even has all controls in the advanced sequencer. 
![2020-12-27_16h06_57](https://user-images.githubusercontent.com/65772654/103173788-a148e700-485d-11eb-80e4-003f6e55d13e.png)

CS
Rüdiger

**Comment by ACMBakx** [comment]
Aha! Thanks Ruediger.So that's new.
For long time the developer showed no interest in dome control.
So I never bothered to keep an eye on it, despite the very positive feedback from users.
I am familiarising with Voyager, but mostly fall back to my work horse SGP.

**Comment by Ruediger3** [comment]
I evaluated both of them. Voyager had to many issues and SGP was wired.
So I continued with NINA. the Nightly build is definitely as as powerful as the both competitors but for free. The new Advanced Sequencer is almost as powerful as Voyager's but click and drop elements. Very cool!

![2020-12-27_16h17_40](https://user-images.githubusercontent.com/65772654/103174025-0e10b100-485f-11eb-9636-2f5cc5914ed4.png)

**Comment by mworion** [comment]
Arie, 
I will offer both settings, this should be the easiest way. As I could calculate on from another. 
Michel

**Comment by ACMBakx** [comment]
Hey Ruediger,
So it's worth trying then?

Voyager is pretty slick and I get good support from the developer. (alike Michael :-) )
A lot of options. I am learning my way around in it. It can become quite complex.
SGP I have used a long time to my satisfaction. I really like the SGP framing wizzard.
Currently stuck at their last 3.6 version. I am not going to update to version4 and pay a yearly fee.
But this version is good enough for me and has no bugs to my knowledge.

But maybe if we give Michael a little more time, he may add a imaging/sequence module to MW4?
Then MW4 does it all !

**Comment by Ruediger3** [comment]
> Hey Ruediger,
> So it's worth trying then?
> 

Hi Arie,
for my point of view: Yes. It is still beta and you may wait a little bit more but NINA suits me perfectly. You may have glimpse on it in a cloudy night and not yet in productive use. It is absolutely stable for me and has less bug in the nightly as Voyager hat in its productive version.

I have made bad experience with Voyager and also with its support. I had personally connected Baader developers to the Voyager guy mid last year since there were serious issues, but this was fruitless. He was not really interested in getting things going, though Baader contacted him multiple times and provided all support. We gave up.
Also for me the UI and UX of Voyager is horrible, The only really extraordinary is the web interface and the elaborate scripting engine. But NINA closed the gap in scripting almost and grows fast. The advanced sequencer is great, but needs some accommodation time. But it is definitelly worth a look and trying it out. It may suit you. But as always it is also a matter of taste. :) 

@mworion : Sorry for hijacking this issue.
@ACMBakx : Arie if you have any question feel free to contact my. You can PN me in 10M forum

**Comment by mworion** [comment]
Hi Rüdiger, Arie,
no worries! if you want, there is also discussion section just not necessary to open an issue just for talking.
@Arie: there is no intend to make MW4 an imaging application. :-)
Michel

**Comment by ACMBakx** [comment]
OK Ruediger,
To the 10M forum then . . . . . 
I just installed Nina and have some questions.

**Comment by Ruediger3** [comment]
> To the 10M forum then . . . . .

Hi Arie, you are welcome. I have sent you my mail address via PM. This will makes things easier....

**Comment by ACMBakx** [comment]
Now you have my mail adress too.

Cheers
Arie

**Comment by ACMBakx** [comment]
found a bug in my testversion

tab TOOLS
Move Classic
no dome slew

See attached logfile @18:58 hrs

[mw4-2021-01-01.log](https://github.com/mworion/MountWizzard4/files/5759242/mw4-2021-01-01.log)

When I then give a command in Move Alt/Az the dome slews again with telescope.

**Comment by mworion** [comment]
Arie,
as I understand, In move classic there is no dome slew, but in Alt/Az and Ra/Dec mode correct? What about the Absolute tab there should be slewing as well?

Actually, that's no real bug, but the resulting behavior. The mount only could do the classic moves (which are available in the hand controller s well). If you are using them and having a dome, it has to connected and steered to the mount. 

Both other move commands (Move Alt/Az and Move Absolute) are not available on the mount, so I have to emulate them. When doing so I could respect a dome connected to MW4.

I should explains that better !

Michel

**Comment by ACMBakx** [comment]
OK Point taken. Absolutely no problem.
I am just playing.
Another observation.
The simulator. Intersection point moves out and in with the change of the dome radius.
However the displayed dome  remains the same size. As such the graphical display of the intersection point does not tell me if I am looking through through the center of the slot.
You do increase the diameter of the telescope when GEM offset is increased.
Maybe you can do the same with the dome?

**Comment by mworion** [comment]
Arie,
tanks for playing around. As said drawing is sometimes buggy. If you increase the size of the dome radius, the simulator should follow. This is not true for the GEM offset as this belong to the mount. If you have further remarks, please let me know. I'm thankful for any hint (and typo and things to clarify, ...)
Michel

**Comment by ACMBakx** [comment]
Michel,
As I mentioned, when I increase the GEM offset, the telescope increases in diameter on the simulator.
That's perfect!.
When I increase the dome radius, the purple intersection point moves outward, as it should of course, but the representation of the dome does not. That stays at the same size.
Well at least yesterday . . . . . . with me . . . . . on my computer . . . . . 
I understand this is work in progress, so I am only trying to help to make a very good product even better. :-)

**Comment by mworion** [comment]
Sure, I really appreciate all the feedback...

**Comment by mworion** [comment]
Hello Arie,

found the bug, why the dome radius in drawing was not adjusted. Did you have some other remarks. I released 0.230.0 and will do 0.230.1 next hour. There is a bug in the firmware 2.16.12 which gives a incorrect return value for a mount command. for this in 0.230.1 there is a workaround in. 

Michel

**Comment by ACMBakx** [comment]
Hi Michel
I am still on FW 2.16.11 (heard to many problems with the last one)
Good to hear you found the bug.
Let's see what do we have now:
-polar alignment
-model building
-model analysis
-limited imaging
-focus control
-dome control
-camera control
-filter wheel control

What else?
Imaging sequence building and execution !

Then you'll have the full pack!
:-)

**Comment by mworion** [comment]
Arie,
you’re right, I upgraded to 2.16.12 and first saw a bug in command protocol, where I have to put a workaround in.
As we had problems with downgrading, I’ll keep it. Otherwise the mount will be unusable.

Your major feature list is complete except the Satellite / Asteroid / Earth rotation Update.
Smaller add-on: simple live stacking, some tools for generating a horizon.

Michel

**Comment by ACMBakx** [comment]
I am not a satellite, comet guy . . . 
Where did you hide the a.o. Earth Rotation Update?
I don't see it anymore.

**Comment by mworion** [comment]
In the Release candidate 0.240.0 the Manuel has the entry. It’s under comets/asteroids entry today. 

Von meinem iPad gesendet

**Comment by ACMBakx** [comment]
Pointing is off.
Last night a clear sky at last.
I did a polar alignment and a 75 point model.
Very good PAE 33" and a RMS of 4,7, straight away.
But despite  these nice numbers, the pointing was way off.
Typically along the diagonal from left upper corner to right below.
Approx 1/4 of the diagonal length.
I asked you about the positioning of the subframe recently.
I used 80% this time.
It was very cold last night so I called it quits.
Log is attached.
Very strange. Never had this before . . . . . . Cannot explain.

PS
From the 75 pts, 3 failed.
@ #11  image was taken while dome was still slewing. (just happened to see it)
The other 2 were clouds passing over.

[mw4-2021-01-13.log](https://github.com/mworion/MountWizzard4/files/5815406/mw4-2021-01-13.log)

**Comment by ACMBakx** [comment]
[m-2021-01-13-20-23-02-file.zip](https://github.com/mworion/MountWizzard4/files/5815717/m-2021-01-13-20-23-02-file.zip)

**Comment by mworion** [comment]
Arie,
Sorry to hear. I never saw an observation before like this. 
I see the three not solved images. Have to find out, why the dome was moving during that time.
The subframe part is unchanged since 2019. And it's the same you had in earlier versions you tested OK.

Could you post on of the taken images ? (you have to zip it before). That's the only chance to have a closer look.
Thanks in advance,
Michel

**Comment by ACMBakx** [comment]
I didn't save any.
From the 3 failed images only #11 was because of the dome slewing.
The other 2 was clouds passing over.
What I do consider is a loose mirror. (mirror flop) in my newton telescope.
I recently removed/cleaned the primary mirror and re-installed/collimated it.
Hence the need to run a new model.
I cannot rule out that I did not tighten the mirror clips enough.
But I don't know.
Strange to me is that the PAE and RMS are so low, indicating that the alignment is A-OK.'
Yet the pointing is off.

**Comment by mworion** [comment]
I will check subframe with Han's ascom sky simulator. The subframe should be OK. Still I saw an error message from the ATIK driver at the beginning (not during your model session). I try to find out.
For the dome I added some more time before I look for the slewing signal. It might be to short (despite the fact that our test was ok).
I looked in the model file, which looks very nice and "normal". This would mean that during modeling we had a consistent setup and only afterwards something changed ???

**Comment by ACMBakx** [comment]
The Atik driver gives me more often problems.
They run it as a service which is then called upon by an application.
Both the camera and filter wheel make use of this.
When switching applications the camera does not always shift to the new app.
The Ascom driver shows that the camera is not available.
I have to go into Taskmanager. Stop the Atik service and then the camera connects again.

The dome timing is ok for 99%. I just happened to catch it red handed.
Nothing to do with MW4. With SGP and Voyager I experience this as well.

**Comment by ACMBakx** [comment]
And of course it is cloudy now . . . . . . .

**Comment by mworion** [comment]
I'm waiting from ore than 6 weeks to get a night which allows reasonable imaging time. (I have to setup everything!).
I checked the subframe, wich gives the same coordinates regardless which subframes I set.

**Comment by ACMBakx** [comment]
OK.
I did noticed once that in SGP for instance, subframe selection takes one of the corners from the chip.
Not the center. Found that very confusing.
That's why I was asking.
