### ISSUE TITLE
Python 3.9 support in documentation

### ISSUE THREAD

**Issue by razvan-astro** [mworion/MountWizzard4#106]
Hi Michel

Python 3.9 is listed as supported in several places in the documentation, but there's one place under https://mountwizzard4.readthedocs.io/en/latest/install/python.html#updating-python-in-your-existing-environment where the text still reads : "_Please be reminded that right now python 3.9 is not supported!_" - I guess it's a left over from the past.

It's a minor thing, of course.

**Comment by mworion** [comment]
Hi Razvan,
thanks for the hint.
Fixed now.
