### ISSUE TITLE
Hemisphare Window: Polar Diagram confusing orientation

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#108]
Hi Michel,

for me the orientation of the Polar Diagram is confusing. It is Wet-East flipped. Side by side with the other projection it is rather confusing, because it is vice-versa. Suggestion: swap East-West orientation of Polar Diagram.

Thank you!

Cheers Rüdiger

![2021-02-12_18h52_47](https://user-images.githubusercontent.com/65772654/107803925-955caa00-6d63-11eb-9446-941fb482e3ed.png)

**Comment by mworion** [comment]
Hi Rüdiger,

Understood. I'm oriented first of all on both sides, which display for itself is the most used. And both are correct. Problem is if you see them side by side it's mixing up. 

Also Per's Model Maker from the beginning on had this topic and he kept this:

![Bildschirmfoto 2021-02-13 um 09 43 21](https://user-images.githubusercontent.com/6632980/107845972-37ba7300-6de0-11eb-95ba-1591a02fdb42.png)

So just switching the polar diagram would mean changing all polar diagrams , which does not make sense. Let's think, what might be the best solution for it,

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

Per's Model Maker is history and I never used it. There is no reason to stay like it. Let's focus on making MW4 even better :)

The problem is not so immanent if you have an unobstructed 360 degree hemisphere. Than it is quite easy to read as you have shown in the screen shot of Per's MM. But the problems start if you have a irregular horizon line. You have to mirror it in brain and this is not very comfortable.

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
I have seen you have added a commit dealing this topic. Is this already released in 1.0.3?

**Comment by mworion** [comment]
Hi Rüdiger,
No, first steps are made, but not finished yet.
Michel

**Comment by Ruediger3** [comment]
No problem, I was just wondering whether I am too blind to see the switch :D

**Comment by mworion** [comment]
Available in v1.1.0b0 beta. Please reopen if problems occur.

**Comment by Ruediger3** [comment]
Hi Michel,

just installed, and works as expected. Many thanks!

Cheers
Rüdiger
