### ISSUE TITLE
Generate model points as grid - not generating points

### ISSUE THREAD

**Issue by kaythriemer** [mworion/MountWizzard4#11]
Hi Michel,
actually I am faced with another issue during my tests of MW4. Sorry.

When I try to "Generate model points as grid" and press Generate grid no model points will be created/shown in Hemisphere view.
The other generate model methods (e.g. Golden Spiral) are working.
I am using MW4 v0.148.0 on Ubuntu 18.04.

Kay.

**Comment by mworion** [comment]
Kay,

need a log for that. On my Ubuntu 18.04 system I get the points in hemisphere window.

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
please find attached the log. 
I started MW4 and wait until mount and camera was connected . At 2020-02-02 21:14:00 I pressed the Generate button.
Unfortunately I don't see anything in the log. I activated deep debug
[mw4-2020-02-02.log](https://github.com/mworion/MountWizzard4/files/4145237/mw4-2020-02-02.log)

Thank you.
Kay

**Comment by mworion** [comment]
Kay,

don't see anything either. Is it repeatable for you ? Please check if the limits set in Grid fit to the horizon limits set in the mount (they should be within the range). Otherwise MW4 removes them, because the mount won't slew to them. 

Michel

**Comment by kaythriemer** [comment]
Michel,
yes it is repeatable. It always does not create any model points, when I use "Generate model points as grid". In previous versions it was working.
 Also horizon limit in the mount is set to 0°. 
If I use all the other methods , e.g. Golden Spiral, it generates the model points as expected.
Can I do any other debugging ?
Kay

**Comment by mworion** [comment]
I think I will do a special build for testing that. Otherwise it will take too long.

**Comment by kaythriemer** [comment]
Michel,
a short video,

just to show that other methods generating points and "Generate model points as grid" not.
[MW4.zip](https://github.com/mworion/MountWizzard4/files/4151459/MW4.zip)
Kay

**Comment by mworion** [comment]
Video explained a lot. Problem is that you need equal numbers in columns. I put that constraint in the gut, but for some reason you have an unequal number in there. I have to fix it to avoid this situation. If you set an equal number in cols it should work.

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
thank you for your support. I will check this.
Kay.

**Comment by kaythriemer** [comment]
Yes, using even number for columns solves this issue.
Thank you.
Kay
