### ISSUE TITLE
ASTAP's H-series index files not recognized

### ISSUE THREAD

**Issue by razvan-astro** [mworion/MountWizzard4#113]
Hi Michel,

Something I found during indoors testing. The plate solver status was still red, although ASTAP was correctly configured. Upon debugging, I found that `astrometryASTAP.py` expects the ASTAP's index files to have the extension `290`. That is valid for the G17/G18 set of index files, but the newer H17/H18 files have the extension `1476` (see the announcement in red at the top of https://www.hnsky.org/astap.htm). My suggestion is to check for either. 

In my case, I have modified `astrometryASTAP.py` locally and then all worked as expected.

Thanks again for writing MW4!

**Comment by mworion** [comment]
Hi Razvan,
good point I have to add this as well in mainline. If you anyway have the solution would you mind to raise a pull request?
Michel

**Comment by razvan-astro** [comment]
Will do (need to set up the environment first). I made a quick workaround by replacing 290 with 1476 but both are needed.

**Comment by mworion** [comment]
If you have to setup, I could do it. But you are welcome to contribute anyhow!

**Comment by razvan-astro** [comment]
Thanks, to be truthful, if you do it it will be faster; MW4, ASTAP and everything are installed on the telescope NUC so have to take it down to bring it within reach of an internet connection, sorry about that.

**Comment by mworion** [comment]
Ok, I put it in. Will be available in the next service release v1.0.4. But might take some days.
Michel

**Comment by mworion** [comment]
Available in v1.0.4
