### ISSUE TITLE
Feature suggestion: emergency stop hotkey

### ISSUE THREAD

**Issue by razvan-astro** [mworion/MountWizzard4#114]
Consider this scenario: the user is running the model building and realizes the OTA is about to hit a tripod leg (possible with refractors with extension tubes), such as when the altitude of the model point was more than it should have been. Or a cable got caught during slewing. Things can happen, especially after a period in which everything has been fine.

There is no time to switch to the Mount tab and move the cursor to the Mount Stop button (particularly when using a touch pad instead of a mouse). What would be nice is to have a hot key (F12? being the rightmost one) issuing the :STOP# command, much like the button itself.  If this hot key is available in any screen, it'd be much faster to access. 

Thanks for considering it and, as always, for the entire MW4 itself.

**Comment by mworion** [comment]
Razvan,
what about opening the Keypad window as you have there the Stop button as well ?
Michel

**Comment by razvan-astro** [comment]
Hi Michel,

Speaking purely from a user standpoint, I'm afraid that would be too slow for an emergency stop - it requires a few seconds. I'm on a different computer now so don't remember exactly, but I think that opening the key pad from within MW4 requires navigating to a certain screen, then opening the virtual keypad then pressing Stop or hitting F3. 

But you gave me an idea: I can leave the virtual keypad open in another window and in an emergency, alt-tab to it then press F3 (the key assigned to Stop in that app). At least it doesn't require touchpad interaction which is the slowest link in the chain.

Again, from a selfish viewpoint of a user, an emergency stop hotkey available everywhere in the app would be better. Then, it doesn't matter whether it's model building, satellite tracking or something else. If something's wrong, one key press is enough. No need to navigate or wait for another app.

Of course, I'm grateful for all the time you've put into MW4 and you'll decide what to do with this suggestion, it was just an idea that crossed my mind.

Thanks.

**Comment by mworion** [comment]
Razvan,
the way I would go now is to enable a „virtual“ pushbutton on the time widget as second stop button. I will highlight the frame in red when enabled, so that everybody know that something happens and it could be pressed. 
Michel

**Comment by razvan-astro** [comment]
Much appreciated and hopefully it saves someone's equipment one day!

**Comment by mworion** [comment]
Available in v1.1.0b0 beta. Please reopen if problems occur.

**Comment by razvan-astro** [comment]
Thanks, Michel!
