### ISSUE TITLE
First use issues

### ISSUE THREAD

**Issue by mbalkham** [mworion/MountWizzard4#117]
Had my first chance to use mw4 tonight (just checked I was using version 0.220.8 which I have now updated after the fact to 1.0.3 which may resolve some of these issues. I hope to retest tomorrow night) on my new gm1000hps (on firmware 3.0). Running mw4 on macbook (big sur 11.2
.1). Connected to mount via indi running on kstars on rpi running stellarmate. Rpi connected via ethernet to mount. 

Horizon mask worked really well. Despite issues described below I was able to get an 18 point model with RMS of 4" and pa to <1".

3 issues observed include (log and images posted below):
1) during model build the mount would slew to but not image at some points, miss points entirely from slew and fail to solve at some points. I managed about 18 points from a model of 67. Some screenshots below show that at some model points no attempt was made to take an image. It also shows some of the failures which look like almost every other image at some point.

2) Also model build would hang at some point of running the build usually around 60-70% of the way through (happened on a 9 point model, 25 point model and 67 point model). When hanging there was no ongoing slew, imaging or solving. I needed to end model build clicking end button. 

3) I could not add points to the existing model. Even with keep points from existing generation checked the model would be cleared when I ran another build. 

All 3 issues could well be user error!

Will also post on 10m forum

**Comment by mbalkham** [comment]
![20210217_230019](https://user-images.githubusercontent.com/76722683/108197828-c253f700-717f-11eb-9290-9052a1f2e88c.jpg)
![20210217_225246](https://user-images.githubusercontent.com/76722683/108197840-c5e77e00-717f-11eb-8799-135399afe210.jpg)
![20210217_225224](https://user-images.githubusercontent.com/76722683/108197847-c6801480-717f-11eb-83b5-ad3be9a83f0a.jpg)
![20210217_224922](https://user-images.githubusercontent.com/76722683/108197865-cbdd5f00-717f-11eb-951b-73261241943f.jpg)
![20210217_224724](https://user-images.githubusercontent.com/76722683/108197872-cd0e8c00-717f-11eb-99f8-d69ed5095676.jpg)
![20210217_224430](https://user-images.githubusercontent.com/76722683/108197878-ce3fb900-717f-11eb-8cde-50c4bc20837b.jpg)
![20210217_224516](https://user-images.githubusercontent.com/76722683/108197883-ced84f80-717f-11eb-8587-62ebdf221000.jpg)
![20210217_224234](https://user-images.githubusercontent.com/76722683/108197890-d0a21300-717f-11eb-9e9c-a420d03e8acf.jpg)
![20210217_224213](https://user-images.githubusercontent.com/76722683/108197893-d1d34000-717f-11eb-8b32-91bf3b8e131a.jpg)
![20210217_220924](https://user-images.githubusercontent.com/76722683/108197898-d3046d00-717f-11eb-91b3-2c47ce0b9b83.jpg)
![20210217_194738](https://user-images.githubusercontent.com/76722683/108197900-d4359a00-717f-11eb-938f-45524d548e05.jpg)








![20210217_225200](https://user-images.githubusercontent.com/76722683/108197851-c7b14180-717f-11eb-95b3-3cbaa5de82f3.jpg)
![20210217_225117](https://user-images.githubusercontent.com/76722683/108197854-c97b0500-717f-11eb-93de-ba8a7a001c95.jpg)

**Comment by mbalkham** [comment]
Log here

[mw4-2021-02-17.log](https://github.com/mworion/MountWizzard4/files/5995264/mw4-2021-02-17.log)

**Comment by mworion** [comment]
Hi, I try to sort some parts:

> 1. during model build the mount would slew to but not image at some points, miss points entirely from slew and fail to solve at some points. I managed about 18 points from a model of 67. Some screenshots below show that at some model points no attempt was made to take an image. It also shows some of the failures which look like almost every other image at some point.

- I see attempts with wrong FL -> solver can't work.
- I see at least on time two starts of model build, wich at the end rund in parallel. I do not know how you made the trick. This should be impossible, but...
- astrometry.net from EKOS is good if you want to use WCS coordinates (as it calculates them, but ASTAP is much faster. 
- you have a big FL, it might be good to stay bin 2 (or even bin 3), but it might be necessary to increase exposure time to see more stars for solving. 
- Astrometry run in timeout once -> too less stars probably.
- the errors reported from the solves are big, so increasing FOV might be helpful
- the solving limit error was right now at 9999 arc seconds to invalidate a solve result -> I will increase that to 10 degrees meaning 36000 arc secs in next release.
-  your ortho error seems to be high, perhaps adjustment to align both axes would help (mine is about 20 arctic on FL of 570 refractor)
-  

> 2. Also model build would hang at some point of running the build usually around 60-70% of the way through (happened on a 9 point model, 25 point model and 67 point model). When hanging there was no ongoing slew, imaging or solving. I needed to end model build clicking end button.

That's I currently not understand. If you are willing, please make a test, close MW4 and make the following test "clean" with a new start. And keep the logs.

> 3. I could not add points to the existing model. Even with keep points from existing generation checked the model would be cleared when I ran another build.

That's truth and desired. MW4 does not build the model incremental, but batch wise. But you could program multiple batch runs (the model files generated) to a single model (if your mechanical setup did not change).

So far, looking for more feedback from your side.

Michel

**Comment by mbalkham** [comment]
Thanks Michel,

I know there were some teething issues with my first few attempts at plate solving. I tried both ASTAP and Astrometry solvers. Most of the settings I figured out eventually. The bigger issue is the model build moving on to the next point with no attempt to take and image or solve at some steps.

On the top photo above, the mount slewed to points 1 & 2 and took images and solved. Then slewed to point 4 took no image and then slewed to point 5 and took image 3 (which solved). Then it slewed to  point 6, took no image and slewed to point 7 where it took image 4. This pattern continues throughout the model build with some slew points not being imaged. This isnt about plate solving failing rather model points not taking images to be solved

On point 2 I'll save the log file after the first time the model build hangs next time out. Not sure what it is doing at this point but the model build reports 60-70% compete and everything just stops. 

On point 3 I'd hoped that the 'keep points from existing generation' might do this but I guess this just means keep them in the model and re capture/solve them. So at least I know I wasnt doing anything wrong when I couldnt work out how to add points. Is this possible in the hand control to add more points to the existing model?

Thanks again

Matt

**Comment by mbalkham** [comment]
Also your answer to Q3 confused me a little (perhaps my question was poorly worded!). I tried to build a 67 point model (crashed after 38 points and only 18 points solved). I saved this to the mount. Then I tried to run additional model build to add points (like I think you could do from the handcontrol?) but this cleared my 18 points and started again.  Is it possible to run batches of builds and add them to the current (single) mount model? Or do you have to replace the whole model and reimage each of the existing points?

**Comment by mworion** [comment]
Hi Matt,
For point 3: if you have models already build (also if only a part of it), MW4 stores them to the model folder as well. If you  ‚choose model from file and program‘ you could select multiple model files former parts) and program them as combined one to the mount. 
Michel

**Comment by mbalkham** [comment]
This sounds like what I want to try to achieve. How does one go about combining multiple part or complete models and send to the mount?

**Comment by mworion** [comment]
I'll do a quick video tonight. and post the link

**Comment by mbalkham** [comment]
Great thanks.

Had another go tonight after upgrade to v1 of mw4. All worked much better
no missed points. 37 point model was ~4"RMS and got pa to 15". All seems to
be working now.

Thanks so much

Matt

**Comment by mbalkham** [comment]
![20210218_221703](https://user-images.githubusercontent.com/76722683/108428671-c9742580-72a3-11eb-91d6-08302bd3fcd8.jpg)
![20210218_221650](https://user-images.githubusercontent.com/76722683/108428678-ced17000-72a3-11eb-8239-ec058f69cb8e.jpg)
![Uploading 20210218_221644.jpg…]()

**Comment by mworion** [comment]
Hi Matt, 

great to hear. Attached the video how to merge 2 models (or even more - up to 99 points):
https://user-images.githubusercontent.com/6632980/108531445-fbeb4600-72d6-11eb-9d3d-8e895ca3d071.mov

Closing the issue
