### ISSUE TITLE
Vertical offset  (Dome centre to GEM) limitation

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#118]
Hi Michel,

I just gave the official version of MW4 a test run (using v.1.0.5). It seems to work very well (real test will be this evening), but I found a minor issue concerning the dome set-up: When I try to enter the vertical offset (Dome centre to GEM), I am limited to 0.50m. In my observatory this offset is 0.53m, so slightly outside limits. Setting it to 0.50m does not affect operation too much, but I would appreciate this limit to be widened.

Thanks in advance,
best wishes,
Nicolàs

**Comment by mworion** [comment]
Nicolas,

I’ll change that for the next version.

Michel

**Comment by InFINNity-Deck** [comment]
Thanks Michel!

**Comment by mworion** [comment]
Implemented in v1.1.0b5
