### ISSUE TITLE
Run Model build not starting

### ISSUE THREAD

**Issue by kaythriemer** [mworion/MountWizzard4#12]
Hi Michel,
I found out (I assume), that "Run Model Build" will not start when the number of model points is greater than 99.
This is OK, because the mount can only handle 99 points.
But it would be nice, if a message either in Messages window or as popup window will show, that the model contains to many points and max value is 99.

Thank you.
Kay

**Comment by mworion** [comment]
Hi Kay,

good point, will add some messages. Should be in the next version.

Michel

**Comment by kaythriemer** [comment]
Michel,
thank you.
Kay.
