### ISSUE TITLE
Retries not working

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#122]
Hi Michel,

as mentioned on the 10Micron forum yesterday, I could not get the automatic retries to work. On you request I hereby attach the log-file. It contains two complete runs, both of which should have resulted in a retry, the first run even in two retries.

[mw4-2021-02-24.zip](https://github.com/mworion/MountWizzard4/files/6041851/mw4-2021-02-24.zip)

Nicolàs

**Comment by mworion** [comment]
Should be fixed in v1.0.6

**Comment by InFINNity-Deck** [comment]
Thanks! Weather permitting I will test it tomorrow.

Nicolàs
