### ISSUE TITLE
1.1.0b2: Satellite update fails

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#126]
Hi Michel,

just tried to update satellite data but it fails. Log attached.
The "file open" dialog stays open. It seams the file is missing or named differently. 
Thank you!

Cheers Rüdiger

[mw4-2021-02-27.zip](https://github.com/mworion/MountWizzard4/files/6054370/mw4-2021-02-27.zip)

**Comment by mworion** [comment]
Hi Rüdiger,
the zip is on 22 Byte. Nothing in it ?
Michel

**Comment by Ruediger3** [comment]
I have chosen to update the "Acive" satellites. Wrong?

![2021-02-27_15h45_13](https://user-images.githubusercontent.com/65772654/109390610-0202a780-7913-11eb-8017-6cf593074c72.png)
.

**Comment by mworion** [comment]
No, should be OK. In my setup I have no problem doing that. As the zip does not contain a log, could you resend it ?

**Comment by Ruediger3** [comment]
Sorry, I have misunderstood that. Thought you mean Satellite DB.
Just found out that 7ZIP cannot pack the log until
 it is opened. Please find it attached.  Thanks!

[mw4-2021-02-27.zip](https://github.com/mworion/MountWizzard4/files/6054892/mw4-2021-02-27.zip)

**Comment by mworion** [comment]
Rüdiger,
do you user the 3.0 installer ?
Michel

**Comment by Ruediger3** [comment]
No, still on 2.16.24.

**Comment by mworion** [comment]
Hi Rüdiger,
no chance to reproduce the in my environment. Not with the 3.0 updater neither with the 2.16.11 / 13 updater. It works with me on 32 and 64 bit. I guessed it worked already fo you. This part of the code is unchanged since then. As setup might change even with windows version, automation is a bad for doing it. MW4 does anyway store the file in the directory, son manually doing thing work. There will be at some point in time an update of the used package. We'll see if situation on 64bit also in speed improves.
Sorry to say.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

just retested and it failed again. The file is there. It is downloaded and up-to-date, but MW fails to fill out the file name in the dialogue. Also the message in the log window is confusing. It sais Uploading failed, programming success. Please see screenshot. 

Rüdiger

![2021-02-28_18h40_10](https://user-images.githubusercontent.com/65772654/109427858-8ed16200-79f4-11eb-9fdf-cc2bfc4ea610.png)

**Comment by Ruediger3** [comment]
Hi Michel,
just tested with 10M Updater FW3 and it fails in the same way. 

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Currently using 1.1.04b

**Comment by mworion** [comment]
I see the problem as the dict, which is generated by the automation package does not contain the referenced key as needed, but I could not setup any environment, which causes this problem.
Questions: Which windows10, Language settings etc. It is something which is related the the windows setup.

**Comment by mworion** [comment]
Corrected the message (should to state success anymore. Still open, because in my setup not reproducible the automation problem. I shift it to another milestone as I need an update of the automation package which the maintainer announced, but without any date.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,
sorry I have overseen your question before. I am using English language. b1 fails also.
The message attached below.

Cheers
Rüdiger


![2021-03-27_12h41_33](https://user-images.githubusercontent.com/65772654/112719570-d23ac580-8ef9-11eb-94fb-85337dee0778.png)

**Comment by Ruediger3** [comment]
Addition info: Earth nutation and MPC files work fine. Only satellites do fail.
Updater 3.0.4 and MW b11.

**Comment by Ruediger3** [comment]
There are also some error in the cmd window:

![2021-03-27_13h09_59](https://user-images.githubusercontent.com/65772654/112720317-d9fc6900-8efd-11eb-9c8a-df6121f83da9.png)

**Comment by mworion** [comment]
Hi Rüdiger,
I did a refactor especially for the new updater. It's still slow, but give it a chance. There should be no difference between the three uploads now.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

in b12 the error message is correct now. 

I notice the file chooser dialog opens the wrong path. instead of opening the correct folder it opens the folder of the last manual update (for me T:\) . There of course it cannot find the file

![2021-03-27_18h49_48](https://user-images.githubusercontent.com/65772654/112729630-75f19900-8f2d-11eb-97d0-5e02e81a180d.png)

![2021-03-27_18h51_43](https://user-images.githubusercontent.com/65772654/112729636-7be77a00-8f2d-11eb-9da3-7e77ad95f409.png)

**Comment by mworion** [comment]
Rüdiger,
please check if you wait the automation should set the path in a first step before entering the file name. Actually the driver name is included as well in the string.
Second, please check is you last manual update if done from the drive, the updater is installed works.
Michel

**Comment by Ruediger3** [comment]
1. I waited a couple of minutes and just retried. No path is set. It fails in the wrong path. Nor a filename is set.
2. Yes, I updated manually today. No problem at all.
3. Also when retrying and the correct path is opened, it fails. No file name is set.

![2021-03-27_19h06_50](https://user-images.githubusercontent.com/65772654/112730053-9f132900-8f2f-11eb-81c5-601b7096fe01.png)

![2021-03-27_19h04_47](https://user-images.githubusercontent.com/65772654/112730002-552a4300-8f2f-11eb-8625-eca267e45338.png)

[mw4-2021-03-27.zip](https://github.com/mworion/MountWizzard4/files/6216144/mw4-2021-03-27.zip)

**Comment by mworion** [comment]
We are back to square one.
Whatever I do, I come back, that I need an update of the underlying library.
I released v1.1.0 (which is now the official release to your used beta) there is one fix in more than your latest beta.

**Comment by Ruediger3** [comment]
Hi Michel, I have updated to 1.1.0 and the problem persists.

**Comment by mworion** [comment]
Rüdiger,
could you give me a feedback, if this is still present in recent 2.0 beta versions ?. I did some small rework and I do not see issues in my setup(s).
Thanks in advance,
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
Thanks for the reminder. I have forgotten it. Infill do asap. Currently it is raining.

Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
the problem persists. I cannot program DB to mount. Updater 3.04 and MW 2.0.0b17

![2021-06-26_21h52_26](https://user-images.githubusercontent.com/65772654/123524176-d5944780-d6c8-11eb-974b-7784bead9267.png)

![2021-06-26_21h53_26](https://user-images.githubusercontent.com/65772654/123524211-f2c91600-d6c8-11eb-9993-7982c28b0379.png)
[mw4-2021-06-26.log](https://github.com/mworion/MountWizzard4/files/6720625/mw4-2021-06-26.log)

**Comment by mworion** [comment]
Rüdiger,
still not solved, found i similar error message in the log. I would like to give you a test program to check the name, which is used in your environment. 
Only point if you succeed: I do not know, how to distiguish between the environments to set it up.

**Comment by Ruediger3** [comment]
Hi Michel,
Yes please provide the test prog. Thx!

Rüdiger

**Comment by mworion** [comment]
Rüdiger,

if I start the updater right now, there is nothing anymore in, which could update TLE files ?

![Bildschirmfoto 2021-06-28 um 19 38 16](https://user-images.githubusercontent.com/6632980/123679960-69d8e880-d848-11eb-9d1a-071033a32c40.png)

strange....
Is there anything I missed ?

**Comment by Ruediger3** [comment]
Mine looks like this:

![2021-06-28_20h04_00](https://user-images.githubusercontent.com/65772654/123683138-284a3c80-d84c-11eb-8e76-93ed57e50c9b.png)

**Comment by mworion** [comment]
Upload b18 with some more logging. Does not sort out the problem, but please run the TLE update with logging=Debug once and drop the log file.

The inspect file is a tool which runs in parallel to any GUI. please to the steps manual on updater and find the widget elements when selecting the file name input field. Please post a screenshot from this session. It might look like this:

![Bildschirmfoto 2021-06-28 um 20 21 57](https://user-images.githubusercontent.com/6632980/123685051-8546f200-d84e-11eb-98db-a3dd01a24825.png)


[inspect.exe.zip](https://github.com/mworion/MountWizzard4/files/6728424/inspect.exe.zip)

**Comment by Ruediger3** [comment]
Here we are (note: Mount is not connected, but this should be also ok. We have heavy thunderstorm rolling in):
![2021-06-28_20h47_59](https://user-images.githubusercontent.com/65772654/123688542-6ba7a980-d852-11eb-888a-c700ecc70c0c.png)

**Comment by Ruediger3** [comment]
Hi Michel,
just tried with attached mount with 18 and it failed completely. The file select dialog is not opening.Find log attached.

[mw4-2021-06-29.log](https://github.com/mworion/MountWizzard4/files/6731861/mw4-2021-06-29.log)

![2021-06-29_10h38_54](https://user-images.githubusercontent.com/65772654/123765650-39379400-d8c6-11eb-927e-3fb41f8c5763.png)

**Comment by mworion** [comment]
Rüdiger, 
you mentioned that MPC and Earth rotation works but not TLE. I found a small difference, which I adjusted. I upload b19 for a test. This could be a quick win.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
just tested and no difference. Still failing at the same position. Files selection dialog is not opened. Sorry.

Rüdiger

**Comment by Ruediger3** [comment]
**Important Update:**
I have tested out of curiosity the same on the NUC. This was working flawless! It tried to update the file. MW same version both Windows 10. One working, the other not. 
So at least what you have done in b19 worked there. Now to find out what prevents it from working on the other machine. Maybe related to Python version?

Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
I don’t think it’s the Python Version, but there might be differences in language settings. The language version of the windows is different to the language setting itself. For example I have a English version of win10, but you could set it to German as well. Still it’s an English version and vice versa.
The automation framework searches for strings given to the widgets. These could be different for different language versions.
But anyway it would be interesting where all differences between those two are. This also might be relevant to other users.

Michel

Von meinem iPad gesendet

**Comment by Ruediger3** [comment]
Hi Michel,
I use Win10 Pro EN with German localization, but English language.
Here is the screenshot of the NUC which is working:

![2021-06-29_23h05_17](https://user-images.githubusercontent.com/65772654/123867418-a121c500-d92e-11eb-92e4-c52ec3e0c44d.png)

**Comment by mworion** [comment]
Rüdiger,
if you start python in the MW4 virtual environment (go to the work dir, venv/scrips/activate to get the "(venv)" prefix),
then:
```
        import ctypes
        import locale
        windll = ctypes.windll.kernel32
        print(locale.windows_locale[windll.GetUserDefaultUILanguage()])
        print(locale.getdefaultlocale())
```
Do you see any differences ?
Out of the rest, I have no clue why the platforms behave different.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
can you please assist me. This does not work for me:

![2021-06-30_19h55_06](https://user-images.githubusercontent.com/65772654/124008873-3380a200-d9dd-11eb-92ae-f0d6c7545ddf.png)

**Comment by mworion** [comment]
Sorry my fault,

after starting venv, please run python and enter the commands from python console inside the terminal.

Michel

**Comment by Ruediger3** [comment]
Here the output of the failing system:

```
>>> print(locale.windows_locale[windll.GetUserDefaultUILanguage()])
en_US
>>> print(locale.getdefaultlocale())
('de_DE', 'cp1252')
>>>
```

Output of the working machine:
` >>> print(locale.windows_locale[windll.GetUserDefaultUILanguage()])
en_US
>>> print(locale.getdefaultlocale())
('en_DE', 'cp1252')
>>>`

**Comment by mworion** [comment]
Many thanks, is there a difference between the two machines ?

Von meinem iPad gesendet

**Comment by mworion** [comment]
I meant there is also no difference.

Von meinem iPad gesendet

**Comment by Ruediger3** [comment]
No, both machines are also on the same patch level: 20H2 Build 19042.1081.1
They are completely different hardware, but OS wise the are equal.

**Comment by mworion** [comment]
No clue, but my setup is different but work also:
```
print(locale.windows_locale[windll.GetUserDefaultUILanguage()])
en_GB
print(locale.getdefaultlocale())
('en_GB', 'cp1252')
```
But you have two machines with the same settings, which behave different.

**Comment by mworion** [comment]
Hi Rüdiger,
the only thing I could think of that the machine, which not works correctly (locale coding de_DE) is running a german GUI language, whereas the working machine does an english style (locale coding en_DE). Could you confirm this ?
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I am sorry. Both run English GUI.

**Comment by mworion** [comment]
OK give up.
I found a way to set the languages like your failing machine, but I could upload satellite data. Maybe there is a software installed, which adds some features for shortcuts or even I do not know.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

I am not sure what has happened, but it is suddenly working. The complete path is typed into the file dialogue. Te only change was, I have updated from .18 to .21 on the non working machine. 
Please do not ask why it is working now. I have just rebooted and tested again and it sill is working. 
Let's be happy and close this issue. 

Many thanks for your stamina and your kind support. 

Cheers
Rüdiger

**Comment by mworion** [comment]
Great that it works now.

**Comment by mworion** [comment]
Hi Rüdiger,
despite the fact that you got it to run i made a change in windows automation for Razvan, who ran in the same issue like you.
v2.0.0b33 should fix that. Out of his observations the issues seems not to be linked to any language settings, but more to timing delays if you have larger menus (which could be only the case in Satellite, not in Comets uploads. etc). So this fix should address you issue as well.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I have followed the discussion with Razvan and already updated MW. Waiting for acceptable whether to test :)

Cheers
Rüdiger
