### ISSUE TITLE
1.1.0b2: ASI Camera cooler not working

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#127]
Hi Michel,
when switching cooler on nothing happens. But it worked before.
Camera: ASI 6200 ; Log attached.

Thanks
Rüdiger

![2021-02-27_18h36_28](https://user-images.githubusercontent.com/65772654/109395148-266a7e00-792b-11eb-8a41-c9d4c306868a.png)

![2021-02-27_18h36_38](https://user-images.githubusercontent.com/65772654/109395157-31251300-792b-11eb-8fed-e4d48c4cf2d5.png)

[mw4-2021-02-27 - Copy.zip](https://github.com/mworion/MountWizzard4/files/6055009/mw4-2021-02-27.-.Copy.zip)

**Comment by mworion** [comment]
Please go one beta back v1.1.0b1

I have cameras who do not tell that they have a cooler, but have one and the other way round. I have to sort this out.

**Comment by mworion** [comment]
I think I found a basic topic in ASCOM and this should be covered in 1.1.0b3

**Comment by Ruediger3** [comment]
Thanks Micheal. I have installed b3 and I will test it asap, since I am imaging right now and the camera is in use.
I will report back.
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michael,
tested and works again. Issue fixed. Thx!

Cheers
Rüdiger
