### ISSUE TITLE
1.1.0b4:MW did not realize ASTAP crashed during model build

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#129]
Hi Michel,

I was just creating a model, when ASTAP crashed with a division by zero. MW continued and considered the missed points as successful. I quickly confirmed the error message and closed ASTAP and MW continued after 3 missed points as normal. I aborted the creation and started over. Hereby I noticed, that the successful marked points were still marked OK, though I completely restarted the run. Please see second screenshot. The points were not reset.

Cheers
Rüdiger

![2021-03-05_20h39_23](https://user-images.githubusercontent.com/65772654/110165628-7e095d80-7df3-11eb-90bf-9efa7ddc0b62.png)

![2021-03-05_20h40_59](https://user-images.githubusercontent.com/65772654/110166146-3800c980-7df4-11eb-806e-12fbfe39f2db.png)

[mw4-2021-03-05.zip](https://github.com/mworion/MountWizzard4/files/6092999/mw4-2021-03-05.zip)

**Comment by Ruediger3** [comment]
Update:
I have dropped a note to Han. It looks like ASTAP .510 is not as stable as the versions before.

**Comment by Ruediger3** [comment]
We could "solve" the Div by Zero problem. By chance I found out when toggling the setting in ASTAP back and forth the problem was gone. I could reproduce the problem with the Fits nr. 19. This was killing ASTAP instantly. 
The other points are still valid. MW does not realize when ASTAP is dead and points are not reset.

Cheers
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
could you post the FITs no. 19 that I could do a test against it. Then I'm able to address the issue not catching the crash from ASTAP as I do not have any chance to crash it manually inside a test.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I have sent you a mail with the link to the fits. Let me know, if I can help. Thank you!

Rüdiger

**Comment by mworion** [comment]
Sollte in v1.1.0b5 gelöst sein
