### ISSUE TITLE
Camera connection through Alpaca

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#13]
Installed version 0.148.2 (internal update did not work, used update.bat instead)
[mw4-2020-02-09.log](https://github.com/mworion/MountWizzard4/files/4177278/mw4-2020-02-09.log)
Managed to connect everything (ignore weatherdevice) through Alpaca.
All green.
Opened image window and pressed Expose.
Image taken? But no download of it . . . . . 

Checked in SGP. Alpaca connects camera ok. Download time is a lot shorter now.
8 seconds from a ASI071.

**Comment by mworion** [comment]
Might be a problem on my side: You ASI071 is a color cam right? I transfer the image just to a simple array. This works flawless with the Simulator. I try to get another camera attached. But with the log out of now I learned that I used a property which is not supported by the ASI driver. I have to find out another one to do the same, but which is standard.

**Comment by mworion** [comment]
Did a version 0.148.3 with a revised property. Hope this goes further. But still for the performance: I tried to implement fast download (but I do not know if the ASI supports it) and I don't know about the download speed via network. I tested it from a virtual machine (but the same computer) and my QSI690 size (3388x2712) takes about 5 seconds for download via network and 2 for the download from camera itself.

**Comment by ACMBakx** [comment]
[mw4-2020-02-09.log](https://github.com/mworion/MountWizzard4/files/4177649/mw4-2020-02-09.log)
As of 20:47hrs
Still no image downoad in the image window.
ASI071 is indeed a OSC camera,
Shall I try with a ASI1600Mono camera? Tomorrow?.
I have a Atik16200 mono CCD too.

**Comment by mworion** [comment]
OK one step further, did v0.148.4. Please try it with your ASC camera.

**Comment by ACMBakx** [comment]
Worse. Image not even taken now.
[mw4-2020-02-10.log](https://github.com/mworion/MountWizzard4/files/4180154/mw4-2020-02-10.log)

**Comment by mworion** [comment]
Hi,

please give 0.150.3 a try. Alpaca for camera and dome should work in a beta. I had it run for a full model in simulation mode (as I don't have ans ASCOM equipment running).

I close this point. In case of any problems, please reopen it.

Michel

**Comment by mworion** [comment]
Hi Arie,

uploaded 0.150.5. Alpaca should be full functioning. Closing this point. If you find any new issues, please open a dedicated on.

Michel

**Comment by ACMBakx** [comment]
I get everything connected now.
The camera even takes a picture.
But the image doesn’t look right when taking a single image.
Need further investigating.

Arie

Verstuurd vanaf mijn iPad
