### ISSUE TITLE
1.1.0b4; Some tracebacks in log cmd window

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#130]
Hi Michel,
some errors in the command window showed up. I don't know whether they are important.

Cheers Rüdiger

![2021-03-06_16h41_04](https://user-images.githubusercontent.com/65772654/110212282-f2e3a280-7e9a-11eb-924b-d1ffd939a728.png)

**Comment by mworion** [comment]
Hi Rüdiger,
cleaned up.

**Comment by Ruediger3** [comment]
Thanks!
