### ISSUE TITLE
Update 1.1.0b6 to b7 not possible: "MW4 not running in an virtual environment"

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#132]
Hi Michel,
I have tried to update to .7 but MW .6 refuses with following error: "MW4 not running in an virtual environment"
Log attached.

Cheers
Rüdiger

[mw4-2021-03-14.log](https://github.com/mworion/MountWizzard4/files/6137295/mw4-2021-03-14.log)

**Comment by mworion** [comment]
Rüdiger, v1.1.0b8 will solve this.

**Comment by Ruediger3** [comment]
Hi Michel,
I still cannot update to b8. Do I have to apply the well known workaround first, and then from 8 on it works?

**Comment by mworion** [comment]
Rüdiger, I did another build 1.1.0v9 right now. Either update it (if possible) from MW4, or do it manually.
Michel

**Comment by Ruediger3** [comment]
I did a manual upgrade to 8 and from there an in-app jump to 9

**Comment by mworion** [comment]
So finally it did work ?

**Comment by Ruediger3** [comment]
Yes. in-app from 8 to 9.

**Comment by mworion** [comment]
I Added a checkbox for the auto restart. Not all might love that feature.

**Comment by Ruediger3** [comment]
Many thanks. The tool-tip of the checkbox is wrong. It is showing wrong text.
Is it a "quit" or a "save and quit"?

**Comment by mworion** [comment]
Always the same: Cut Copy and forgetting to rewrite the text.

**Comment by Ruediger3** [comment]
No problem.
Well, both ways have their pros and cons. It is only very important to know how it works.
