### ISSUE TITLE
Version features: Beta 1.1.x <> Released 1.0.7

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#135]
Hi Michel,
I am a little bit confused which feature is currently in which branch. Currently I am running the Beta 1.1.0b11 but 1.0.07 was released. Also the Release notes are only shown for the Betas. If the main branch is selected, no release notes are shown.

Thanks!
Rüdiger

![2021-03-23_14h20_29](https://user-images.githubusercontent.com/65772654/112152799-f5f0c980-8be2-11eb-8da3-1a3a43ec570f.png)

**Comment by mworion** [comment]
Good point, this is an error. the release notes are started in v1.1, so there are no available for older releases. And therefore they should not be displayed.

**Comment by Ruediger3** [comment]
Actually they are not displayed. I got confused, since I was switching between Beta and 1.0.7 and only got information for the Beta. 
So my question; Are the beta Feature already in the released version? If no, in which version they are clubbed together?
Not a big thing, but I am using the features of the Beta-Branch and do not want to lose them by carelessly updating to a released version without. 

Thanks!
Rüdiger

**Comment by mworion** [comment]
Ok simple to explain:
official released is v1.0.x (x=fixes)
beta is v1.1.0by (y for betas)

official released (radiobutton there) is v1.0.7 if you are on v1.0.7, you should not see the massage „A new version....“

if you check beta, the newest one is v1.1.0b11, and if you are on beta less v1.1.0b11, the you should see the message.

Michel

**Comment by Ruediger3** [comment]
Many thanks! So the answer is: 1.1.b11 is still ahead. So I will stay with the Beta.

Cheers
Rüdiger
