### ISSUE TITLE
Feature request: Choose Meridian when satellite tracking

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#136]
Hi Michel,
I would kindly ask for the feature to chose the Meridian when tracking satellites analog the handpad.
The reason is, that very often only one hemisphere of the transit is visible for me and it makes only sense to track after Flip. If I start from West, I only lose time for flipping. please see example attached (red transit, actual Horizon of my home in the image). As you can see it makes no sense to track on the red curve the west part of the transit.

Thanks for evaluating!
Rüdiger

![2021-03-30_19h30_02](https://user-images.githubusercontent.com/65772654/113031222-b865e080-918e-11eb-91a2-cf6a5bf1e2ed.png)

![2021-03-30_19h33_05](https://user-images.githubusercontent.com/65772654/113031258-c61b6600-918e-11eb-95be-278104d9175a.png)

**Comment by mworion** [comment]
Rüdiger,
Did some tests, from calculation and GUI I'm ready. Only point: I have to build a track with Alt/Az coordinates (new feature in FW3.x). I do not know who asked for it and what the intense was as TLExx commands already did the job. Now I have to decide which type of coordinate transformation I have to choose to get the right coordinates. You will have to test somehow. I will start with Alt/Az apparent without refraction correction (as I hope this will be done in the mount).
I also revised the Satellites GUI to make it better readable: Here the example:
[https://www.dropbox.com/s/pjtfhezms2pirkh/Bildschirmvideo%20aufnehmen%202021-04-13%20um%2021.16.02.mov?dl=0](url)
Michel

**Comment by Ruediger3** [comment]
Hi Michael,

just watched the movie and it looks great. Of course I will test, but weather and the matching transit must occur.
But I will test asap.

Thank you very much! Looks marvelous!
Rüdiger

**Comment by Ruediger3** [comment]
Is there a beta, so I can provide a feedback for the new windows features?

**Comment by mworion** [comment]
Unfortunately not. There are still some tests to do, probably for the weekend. We‘ll see.

Von meinem iPad gesendet

**Comment by Ruediger3** [comment]
No problem.
Just let me know when and if I can support you. Thanks!

**Comment by mworion** [comment]
v2.0.0b3 shows some of the features. need to implement the programming (download will take >5 seconds to the mount computer).

**Comment by Ruediger3** [comment]
Hi Michel,

had a look an looks very nice. I do like the new graphs in the satellite window. I will test as soon as possible,

Many thanks!
Rüdiger

**Comment by mworion** [comment]
Please be reminded, that the tracking itself is still the same. v2.0.0b4 will offer old an new in comparison. v2.0.0b3 shows the new gui and selection features

**Comment by Ruediger3** [comment]
Hi Michel,

Many thanks for the update. I will test as soon as possible. 
1-10 arcsec should be ok for me, since I shoot at max 0,22"/p, so the offset is at max. 50p and the ISS is still in FOV. 
Horizontal line is a cool goody 👍 Question: the scope is waiting at the horizontal line for the satellite to rise and starts tracking when it is crossing it?

Greetings
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
I have installed it, but either I do something wrong or there is a failure: When double clicking e.g. ISS nothing happens, no calculations. Log is attached.

Cheers
Rüdiger

[mw4-2021-04-30.log](https://github.com/mworion/MountWizzard4/files/6407197/mw4-2021-04-30.log)

![2021-04-30_20h06_03](https://user-images.githubusercontent.com/65772654/116736229-e473bc00-a9ef-11eb-9c2b-6fddc3c12a16.png)

**Comment by mworion** [comment]
Had a priority to a running mount. Changes will occur in v2.0.0b5 and adding a simulating feature that you could do a test run without waiting for the real satellite.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

many thanks! I have installed it and did a quick tour without the mount attached. 2 things came up:

1. Color of the green transit is hard to read when close to custom horizon. Maybe switch one to blue?

![2021-05-01_19h50_34](https://user-images.githubusercontent.com/65772654/116790887-14d25d80-aab7-11eb-90f6-abc9852616cb.png)

2. The tool tip says ""prognosis ... satellite over horizon." Which horizon? Custom or standard horizon?

![2021-05-01_19h51_42](https://user-images.githubusercontent.com/65772654/116790901-2451a680-aab7-11eb-8a69-bb008f5208bf.png)

Many thanks!
Rüdiger

**Comment by mworion** [comment]
Rüdiger,

Colors are to be improved. I have to play around. The horizon is the standard. And if you could confirm the precision, It’s not a prognosis as I had before, but it’s the highest precision I could calculate. Still the position of a satellite due to the limited number of digits in the provided TLE parameters files is about 1km in space….

Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I will test precision (if you mean accuracy of tracking e.g. the ISS) as soon as possible. Currently it is raining cats and dogs.  We even have rain warning from DWD :(.
I am looking forward to test myself :)

Rüdiger

**Comment by mworion** [comment]
Same here, I switched colors to a more calm way as I might need it later.
![Bildschirmfoto 2021-05-01 um 21 22 26](https://user-images.githubusercontent.com/6632980/116792843-7b5d7880-aac3-11eb-8d39-c227831100eb.png)
Michel

**Comment by Ruediger3** [comment]
Looks good 👍

**Comment by Ruediger3** [comment]
Hi Michel,
just tested with internal math, and the ISS completely failed. The mount started tracking way before ISS rises. It was more than 90 degree off. It flipped just when ISS came over the horizon. 
I immediately reverted back to mount math and the ISS was precisely in the center of the camera at the CDK@2563 mm FL. Below the the setting. Before I had updated all the files crucial. 

![2021-05-29_22h46_47](https://user-images.githubusercontent.com/65772654/120084352-c1f8bf80-c0cf-11eb-8f1a-867c70504f09.png)

**Comment by mworion** [comment]
Hi Rüdiger,
just a quick question: was Long before about 70 seconds ?
Michel

**Comment by Ruediger3** [comment]
Yes, at minimum. But this is hard to tell. I was very bussy to get everything working correctly. There every second is a year ;).
But 70s might be matching.

**Comment by mworion** [comment]
The only thing I can think of are the 69.184 s time difference between TT Time System (MW4 base) and UTC Time system (mount base). I have to have a walk through to find out.

**Comment by Ruediger3** [comment]
Many thanks!
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
in fact that was most likely the issue. I did some satellite tracks in realtime and I now see no difference between internal and mount math track path. So hopefully it should be sorted out. v2.0.0b12 will have the fixes in and also some improvements for the GUI (adding mount Alt/Az pointer to the satellite view.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I have installed b12 and will check ASAP. Many thanks!
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
tested it and it again failed when Horizon is checked. It starts tracking immediately when the ISS is rising but not when crossing the user horizon. This is completely ignored. It starts tracking from user horizon start point at the same time the ISS rises over earth horizon.

![2021-05-30_21h29_58](https://user-images.githubusercontent.com/65772654/120117803-46f6de00-c18f-11eb-8f83-f0bcca95bc37.png)

Here horizon "Off" but also missed id. I was not able to get it into FOV.

![2021-05-30_21h32_00](https://user-images.githubusercontent.com/65772654/120117822-67269d00-c18f-11eb-80f1-170f2d1c3930.png)

[mw4-2021-05-30.log](https://github.com/mworion/MountWizzard4/files/6566811/mw4-2021-05-30.log)

**Comment by mworion** [comment]
Hi Rüdiger,
thanks for the detailed feedback. To clearify: Now tracking is good if not using horizon mask. Correct ? If enabled MW4 does not start right when crossing the horizon line.
So last issue is sorted out (with the 69.184 s), now I have to look into horizon topic.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
the tracking with user horizon was completely far away. When switched off, it was quite close (also cross checked live in Stellarium), but ISS did not come into FOV, which means a considderable deviation for the full frames camera like mine. 
I have tried to switch in a third attempt to mounts math during that pass, but it was to late. I have only seen ISS rushing through the image during flip.

Thank you!
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
the horizon issue should be fixed in v2.0.0b15. Regarding the ISS in FOV I recalculated your situation (TLE, Refraction, Location, Time) and compared it to the mount calculation. Attached the plots. If you have some ideas, why the difference  of 10 - 15 arcsec in Alt/Az leads to a situation of not having ISS in FOV (0.2 arcsec / pix) means about 50 pixel difference, please let me know.

![image](https://user-images.githubusercontent.com/6632980/120186975-81568e80-c214-11eb-954c-c11969e0e3cb.png)
![image](https://user-images.githubusercontent.com/6632980/120187127-b367f080-c214-11eb-8857-303afdcf1765.png)
![image](https://user-images.githubusercontent.com/6632980/120187142-b7940e00-c214-11eb-83d1-caa3f77a7c3e.png)

Michel

**Comment by Ruediger3** [comment]
I have installed the latest version via new updater. Worked fine. 
I will test asap. 

Could it be that some latency leads to that delay? When calculated on the mount's controller the result is intermediately transferred to the motors, whereas when calculating in MW the controller needs to interpret the controlling impulses and send it to the mount. Maybe this delay is too much? But this is only wild guessing.
BTW: Your linked images are not working. :(

One other thing I have notice: The position of the 3D simulator is not stored when restarting MW. Maybe a good idea to include it also in the profile. Also another point: When you have a window position outside your screen you cannot get it back. Happened to me copying my profiles from a multi screen workstation to my NUC. I could not get my windows back :(. It should be checked for boundaries. THX!
Should I open dedicated issues?
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
Latency should not be the problem as it is (after programming) all handled inside the mount. So programming does start time and tracking path and hands over to mount for execution. 
Images: Might be the case that they are not transferred through email. On the webpage they should be present.
Question about the position of 3D simulator: The window position is persistent and in the profile. Only point is that it does not open automatically. Reason for this is multi platform as not all platforms support 3D and this I handled be enabling or disabling Opening Window.
Windows outside the screen should be set automatically to x/y: 0, 0. I already check screenSize in x and y and if position exceeds this, I''ll set it back. But I improve this part.

No need for separate issue, will include this in b16 for test.
Michel

**Comment by mworion** [comment]
Hi Rüdiger,
anything new about the precision of the tracking ?
3D simulator and windows positioning should be already corrected
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

Sorry no. No ISS pass when wether would allow observing. It is still on the list, but currently I am busy not to float away... continuous rain 🤬

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
just tested with the 20:35 transit. The mount started at horizon, but ISS was not in FOV. The model is precise to get any target into FOV at least. It looks like the mount is a bit to slow. 
In the image you the the ISS position, the mounts position and the FOV.

Yet another point: If the mount is programmed you have no indicator that the mount is in hot stand by. You are not shure whether it is really waiting. Would be good if you would have some visual indicators. e.g. make the button "Start satellite tracking" green flashing.

Rüdiger

![2021-07-18_20h35_42](https://user-images.githubusercontent.com/65772654/126078745-adc0e1e4-5c83-4c79-91ac-a48a26ace808.png)

**Comment by mworion** [comment]
Hi Rüdiger,
Many thanks for checking. The indicator topic is a good idea. I will do that.
Regarding the tracking: Is the mount constantly too slow, meaning it's starting time is too late and the distance ISS and mount keeps constant ? How far away / too late it the mount actually? I have to check if I have a systematically error or I did not understand the new command protocol right. From calculation side the errors are within 10-15 arcsec, so this should not be an issue. I am missing something.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
just ran a test with tracking by the mount, but it also missed. So the question is why. Never had issues. I had updated the TLE before. The only difference: I am using GPS time for this test and before I had used PC time in high precision, which worked.

I am shooting with 0.15 "/pix @ approx. 8m FL.

Attached the screenshot from guiding with the mount's function. 

![2021-07-18_22h13_42](https://user-images.githubusercontent.com/65772654/126081146-ec32a8ae-e9cb-4169-a2d1-e4e32e793b04.png)

**Comment by Ruediger3** [comment]
Hi Michel,

sorry I have forgotten one info: The offset is constant (at least so far I could figure out in that very short time). 

Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,

I could do adding a time offset to correct this. Question is a systematic error. So with your remark, start time might be the very point. If you state it's a constant offset. Could you tell me the time difference? Out of the drawing back calculating the time difference is difficult as I do not know the actual angle velocity of the ISS.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

thanks for the feedback.
Please wait with the offset implementation. I will test (hopefully) today again with a bigger FOV to get it into FOV.
I am not sure why it is failing. Due to the fact it is not in FOV and it is so small I can hardly guess the offset in time, since I have no reference point. But it is far below 1s.

**Comment by Ruediger3** [comment]
Hi Michel,

just tested with huge FOV and the ISS was on the edge. My observations:
1. The offset is very constant
2. I did manual correction and it was almost constant
3. After the flip, the ISS was well focuses, but I am nit sure, whether it is due to the manual corrections before the flip. Do they remain after the flip as offset?

FOV: 48 x 32 arcmin (red box)

Before Flip: 

![2021-07-19_21h26_59](https://user-images.githubusercontent.com/65772654/126216866-fc23d10e-b72f-47be-8b06-e6f660af0fa8.png)

After Flip:
![AfterFlip](https://user-images.githubusercontent.com/65772654/126216886-e95ec283-78e9-4dd6-a1ca-c31b57dbf5c1.png)

**Comment by Ruediger3** [comment]
One information: PC time differs 503ms to mount which takes GPS time. This is roughly the time lag / offset.

**Comment by mworion** [comment]
Rüdiger,
Is there any difference between mount calculated and my calculation in terms of the observed offset.
The command protocol allows +- 999ms time correction when following a programmed track. So adjusting should be possible.
Michel

**Comment by mworion** [comment]
Addition: could you read out the GPS - UTC time difference stored in the mount ?

**Comment by Ruediger3** [comment]
How can I check this? Or do you mean comparing MW4 Sat track and Mount Sat track?
BTW: Just tried "Push mount time to PC" and it does not work. The time gap remains 500ms.

![2021-07-19_21h47_55](https://user-images.githubusercontent.com/65772654/126218337-53bbd91b-be0f-45c3-8e44-7d7422cb0e67.png)

**Comment by mworion** [comment]
If you would like to sync, enable connect clock sync and enable sync mount to pc clock. 

![Bildschirmfoto 2021-07-19 um 21 49 35](https://user-images.githubusercontent.com/6632980/126218555-f68de5c2-0b74-42c3-a9c7-decb509e7942.png)

**Comment by mworion** [comment]
please feel fret choose if you want update during tracking or not.

**Comment by mworion** [comment]
Rüdiger
The UTC-GPS delta is under settings in the handpad and should be 18s.
The offset I look for is between mount computed tracking path and MW4 computed tracking path.
Michel

**Comment by Ruediger3** [comment]
Ok, I was expecting when pressing "Push mount time to PC" it pushes the time regardless the settings below.

Offset seams to be correct-
![2021-07-19_21h59_54](https://user-images.githubusercontent.com/65772654/126219736-6ee082b2-e239-4f70-8b22-d4b45e9ee686.png)

How can I compare the track data?

**Comment by Ruediger3** [comment]
BTW pushing the time from mount to PC might be dangerous. Since the PC also detects a deviation a is forcing an update from time server. This might lead to an oscillation, or you have to switch off time server sync. This is a very bad idea in a network. Windows domains react extremely allergic to time differences. I have a very bad gut feeling. This is only a good idea for stand alone devices.

**Comment by mworion** [comment]
I agreed, this is really a user demand for send alone without being connected.
I wonder how much the MW4 tracking differs from internal mount calculation. 
Looking forward to your results. And still wondering why the difference is about 0.5s between GPS and PC

**Comment by Ruediger3** [comment]
The next test will be: PC and Mount using both GPS time. The very next test will be both using PC time.
But now clouds are rolling in :(

**Comment by Ruediger3** [comment]
Hi Michel,
Just tested with FPS both. failed again on both meridian sides. Mount was behind the ISS approx 1,5s.
Rüdiger

![2021-07-20_22h16_12](https://user-images.githubusercontent.com/65772654/126390159-6ddbc8a9-a7fe-4e75-b91b-018b5e48e47c.png)

**Comment by Ruediger3** [comment]
Hi Michel,
just tried with PC time and the ISS was in FOV (but very close to the edge).

Cheers
Rüdiger

**Comment by proceau** [comment]
I'm problem too

**Comment by mworion** [comment]
Hi Rüdiger,
many thanks for the intensive testing. To sum up in my words (to be clear where to move on), please confirm:
- There is no big difference in tracking and getting Sat in FOV between mount calculation and MW4 calculation (if you could describe the difference better, please try it.
- The deviation of spotting a sat in FOV is related to the used time base. GPS is off, PC time is in.

Just as remark: the model corrects also for time deviations. If the mount model is done with PC time and there was a GAP between PC and GPS time, Sat tracking with GPS time will not get the sat in FOV.

If all above is true and correct, the question is, why there is a difference between GPS and PC time. My thoughts:
PC time system via NTP is UTC based.
Mount time system is also UTC based.
Actually GPS - UTC difference is 18seconds (which is correct configured)

Strange...
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

thanks for your patience. It is very hard to say something is like, since the transits and weather only allows to repeat one or two tests for each setup combination. So I hesitate to say "it is". Simply there are too little count of tests.  I will try to repeat the identical test multiple times to be sure it is like this. Unfortunately that is in the nature of tracking ISS.

1. Yes. I had issues with both
2. Yes. The offset with PC time was less. But this could be by chance.

I have created a new 90 point model last night. I will retest with new model.

Yes, there is a difference between PC time and high precision mode of Windows. Now it is the question which one is the less wrong. Actually, GPS should be correct, since it is a stratum one layer time reference. May there is a delay in processing the updates timely from MGPBox to mount or something other wired. But it looks like that both times run slow.

The GPS offset cannot be changed anyway. I think it is not editable. I remember there was an issue with the10; Mount configurator which showed 19s offset. Maybe there is also a bug.


That said, I am not sure where the root cause lies. I will do following:
1. Setup everything to work with internal tracking
2. When 1 successful repeat the tests systematically. 

I have to ask for some patience since I can only test max. once a day due to the obstruction of my FOV.

Thank you!
Rüdiger

**Comment by proceau** [comment]
I'm test, the standard NTP of windows have 500ms of error, i'm change to other NTP stratum 2 and it's more correct.

**Comment by Ruediger3** [comment]
Yea thats true and thats why I do not use them. I use the NTPPool.org

**Comment by mworion** [comment]
Rüdiger, 
question: if the offset stays constant is it worth to try to adjust the time offset for tracking to catch the satellite?. Is this possible? Interesting question would be if that offset stays constant between different satellites and observing nights as I could persist this value then.
Michel

**Comment by Ruediger3** [comment]
Well, using a offset means to know it in advance. If this would be possible, I could adjust the clock too and have the same result. The problem is, an offset needs an reference point and here I am not sure.
This definitely needs more and systematic testing, since the results are not consistant.

**Comment by mworion** [comment]
Rüdiger,
I updated the GUI behavior to make it more clear what happens (changing text and color) in v2.0.0b28
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

I was testing yesterday and I missed ISS again. It was not in FOV. I will test again as soon as possible.

Cheers
Rüdiger

**Comment by mworion** [comment]
I anyway working on some features for finding near satellites which are visible and sun lit.
If that's running we should be able to find more and easier opportunities to select satellites for testing. I currently not know, why and for what reason I miss the FOV in MW4 math, when the satellite is in the FOV for 10micron calcs.

**Comment by squark-envoyer** [comment]
18s it's not second correction of GPS ? because some time 1s it's add or remove on UTC, the GPS have not correct ?

**Comment by mworion** [comment]
Actually (since 01-01-2017) the difference GPS - UTC is 18s. And as the gap is more closing, there might be for some years more no need increasing it further. But in result 18s delta is correct.

**Comment by squark-envoyer** [comment]
the TLE parameter it's on GPS time ou UTC time ? the 10micro correct internal time with 18s or not ?
because the pointing error it's coherent with that, and explain problem pointing ?

**Comment by mworion** [comment]
TLE should be as spec in UTC and the mount internally does all things in UTC. This fits nicely. If you are using a GPS for time sync you have to take care about the 18s.
It would be great to know if the deviation is only about time and nothing more and if so how much in each case. 

Maybe we have some other topics when using GPS as time source (and Rüdiger, this might also explain your observation that GPS time and NNTP time was different):

> Many general purpose GPS devices utilise NMEA protocol, which is a standard protocol for GPS devices. However, the problem with using these devices for as a GPS Clock for computer timing is that the NMEA sentances are often not synchronised to be generated at specific intervals.

>Many GPS devices therefore can only provide an accuracy of plus or minus 1 second, which is generally just not accurate enough for network timing purposes.

I will ask Martin, how his MGBox receiver is designed for that.

**Comment by squark-envoyer** [comment]
Would anyone have any idea how to simulate and time the simulation to get a feel for the fault?
When the mount is in simulation mode we know the chosen start time, it would be possible in simulation mode to set the starting time of the latter?
My idea is to simulate the same TLE with a laser on the mount, started at a given time and see when the laser passes a reference point of the trajectory and see if in PC UTS, the 18s offset is applied or not in addition.

**Comment by Ruediger3** [comment]
It looked like that MW was slow for a second but track ok.
I followed life in Stellarium and the mount was "behind" ISS. I guess around 1 second. What I also had noticed was a time difference of approx. 600ms between mount and PC.

**Comment by mworion** [comment]
Rüdiger,
if you say 1s behind, you reference a time system which you did from NTP service correct? So would the gap 600ms to mount add another 600ms, so in total 1.6s behind "Mount" or would this reduce the difference to 400ms ?

**Comment by mworion** [comment]
@squark-envoyer,
Starting the simulation in that precision is hard to do as execution times might differ. I made the calculation comparison between mount and MW4 if you use the same time base that you run inside a 10 arcsec window for Alt and AZ as the normal satellites have a "speed" of about 0.03 deg / s which is about 100 arc sec per second. So the sat should be in the FOV just by calculation.

**Comment by Ruediger3** [comment]
The 1s was a guess from watching screen.
The 584ms were displayed by the 10M clock sync tool, which was set not to sync.
I also noticed, MW says time not GPS time synced but the hand pad does. So there are many potential root causes, which makes it really tricky to tackle the root cause.

**Comment by mworion** [comment]
Rüdiger
Good point about handpad and MW4. I asked already 10micron because I see with :gtg# command that I loose sync sometimes. I have to check Handpad as well. 
Could you tell where to see if the time is synced on the handpad?

**Comment by Ruediger3** [comment]
Based on the symbol shown.
![image](https://user-images.githubusercontent.com/65772654/133128084-55e8b57a-e26d-49b7-bb26-c138d83b4b6c.jpeg)

**Comment by Ruediger3** [comment]
Here a screenshot from life system:
![image](https://user-images.githubusercontent.com/65772654/133131147-1a3ec2d3-d748-4f3f-b149-1080546ded78.jpeg)

**Comment by mworion** [comment]
Rüdiger,
many thanks. I think there is a different between "usage" and synced (at least the is some room for interpretation).

**Comment by Ruediger3** [comment]
Welcome. You are right. This is ambiguous.
Rüdiger

**Comment by mworion** [comment]
I close this point as there is no chance to sync mount time with high precision to GPS time.
I publish a 2.1.0 beta this evening with another extended Satellite feature set (search and tracking correction). You should be able to adjust track as a matter of time, ra or dec directly. So the time delta +- 1s along the track is now available in MW4.
Michel
