### ISSUE TITLE
Wrong activation sequnce in Goto Alt/AZ fields

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#137]
Hi Michel,

can you please have a look into the activation sequence of the ALt/Az Goto fields?
When you are in ALT field and you want to move on with tab, the cursor jumps to DEC instead of AZ.
Thank you!
Rüdiger

![2021-03-30_19h35_18](https://user-images.githubusercontent.com/65772654/113031744-5b1e5f00-918f-11eb-9a3f-d2d0bd1e4276.png)

**Comment by mworion** [comment]
Closed in next beta.
