### ISSUE TITLE
Model build doesn't start

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard4#14]
hi Michel, 
tonight I tried to build a model with the new version 0.148.4, the telescope slews to the first point (labeled with '0'), engage tracking but doesn't image. 
I then tested if camera was connected :  I used the 'image' tab and tried to capture 1s photo and solve it. Everything went fine.
I also tried different point generation algorithm and number of points but got the same results.
Attached the deep log.
Ferrante
[mw4-2020-02-10.log.zip](https://github.com/mworion/MountWizzard4/files/4182997/mw4-2020-02-10.log.zip)

**Comment by mworion** [comment]
Hi Ferrante, 

out of the log I don't see why. I will upload a new version 0.148.5 with more logging to it. If you only had 1 or two points on the hemisphere window, your were able to start modeling, but that was wrong, the mount needs at least 3 points and I kill the modeling process too late. This is corrected.
Never seen that before.

Michel

**Comment by fenriques** [comment]
hi Michel,
ok I will update and try again. unfortunately not this evening because the weather is not good at the observatory location.

ferrante

**Comment by fenriques** [comment]
hi Michel,
updated version and tried again but the model building doesn't work yet. It slews to first point, then doesn't start imaging. 
Everything else is working fine: expose and solve from 'image' tab are giving the expected result.
Attached the log.
Hope you can find what I'm doing wrong.
ferrante
[mw4-2020-02-13.log.zip](https://github.com/mworion/MountWizzard4/files/4201240/mw4-2020-02-13.log.zip)

**Comment by mworion** [comment]
Ferrante:
question: Do you use a dome? For me it seem's that MW4 wait for the dome to finish slew before starting the first image. As you are using a Talon, that's a Roll-On Roll-Off roof ? If so, please disable the dome driver as it only makes a following for the dome slit to be able to image.
Michel

**Comment by fenriques** [comment]
hi Michel,
yes, I'm using the Talon 6 Roll on Roof. And you're right it was preventing imagining to start.
In the older version (MW3) I was not using it but configuring the the new one I activated it.
Thanks again for helping.

Btw I saw that in the new version you added a lot of features and MW is getting better and better. It's really a great software.
