### ISSUE TITLE
2.0.0b2: Multiple issues when building model (repeating failed points)

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#144]
Hello Michel,
I have tried to create multiple models last night and experienced massive problems:

1. failed points were repeated but nor marked as successful
![No_propper_marking](https://user-images.githubusercontent.com/65772654/115849281-06d06d00-a425-11eb-96fa-0d4ab08275c2.png)

2. After repeating and successfully solving them, the model creation process was not triggered. MW stopped. I had to "End" the build process manually. After that the creation of the model was triggered. 

3. It took me several attempts to accomplish an small 19 point model. The following 96P model went smoothly. 

4. MW just stopped while repeating failed points

![Stalled on repeating](https://user-images.githubusercontent.com/65772654/115848593-51051e80-a424-11eb-9891-3e9c83022221.png)

I have attached the log file but it is quite huge. I have noted a time when I had problems: 22:10 CEST

Cheers
Rüdiger

[mw4-2021-04-22.log](https://github.com/mworion/MountWizzard4/files/6364153/mw4-2021-04-22.log)

**Comment by Ruediger3** [comment]
Another point: When repeating the failed points, it starts with the oldest point first, This may cause a meridian flip. This could be optimized by using "shortest slew track"

**Comment by mworion** [comment]
Rüdiger,
v2.0.0b3 should address all of your points.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

many thanks. I will test it as soon as possible. 
Had to install it vie work around and got on the first try following error below. Second attempt was successful.
Rüdiger

![2021-04-25_19h03_10](https://user-images.githubusercontent.com/65772654/116002256-26b88a00-a5f9-11eb-9dce-380459945bbe.png)

**Comment by mworion** [comment]
Rüdiger,
from my tests it's OK now. Closing the issue. If you have other insights, please reopen.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
that's ok. When creating a new model I will test it and reopen in case of a problem.

Many thanks!
Rüdiger
