### ISSUE TITLE
v.2.0.0b2 image coordinates not embedded anymore

### ISSUE THREAD

**Issue by Ginge70** [mworion/MountWizzard4#145]
Hi again, Michel!
After you helped me solve the issue with my model building in the previous version, I updated to v2.0.0b2 and now it seems MW is no longer getting coordinates for the captured images, resulting in failed solving when modelling. The change on my end was that upgraded the wifi environment, resulting in a new IP-address for the mount, which I changed in both the INDI environment using INDIGO control panel, and in MW4. Both applications seem to connect to the mount, so in theory MW4 should be able to pick the coordinates from INDI, right? I can also confirm the "Embed Data" in the imaging window is still checked. I'm now back to the situation where solving works when not building models, albeit with a substasntial error which leads me to suspect that MW4 is no longer getting the data from the scope even thoug it is connected via INDI in Devices>Settings.

Maybe I'm overlooking something, or did you make changes between the latest update and the previous that could affect this?

Best regards,
Ginge

**Comment by Ginge70** [comment]
[mw4-2021-04-22.log](https://github.com/mworion/MountWizzard4/files/6367160/mw4-2021-04-22.log)

**Comment by Ginge70** [comment]
Come to think of it, - another change I made was to add a bunch of simulatiors to INDI which I later removed. When looking in the INDI control Panel now I see that snoop devices are set to GPS Simulator and Dome Simulator, which made me think maybe adding the simulators and removing them has messed up MW$'s communication with the mount... Or maybe not, I really don't know, but thought I'd mention it in case the info was useful.

Best regards,
Ginge

<img width="1376" alt="Screen Shot 2021-04-23 at 21 10 17" src="https://user-images.githubusercontent.com/43574102/115919337-fba72c80-a478-11eb-9592-23d8892e4c77.png">

**Comment by mworion** [comment]
Ginge,
with the log, still we were probably back to the first situation where no RA/DEC data was in the header. At least the log shows ra = 0, dec = 0 as starting point. If you look to the snoop devices, the 10miron snoop devices are not important, but the devices you choose for the camera as the camera should look into the telescope driver (10micron) to fetch it's coordinates. Please check again.

But anyway as said last time, I will add some code to overcome this problem if no data for RA /DEC is added from EKOS I will tray to add this from MW4 side in the next beta

Michel

**Comment by Ginge70** [comment]
Yes, something I did caused it to lose the ability to add scope position. I'll make a note of your comments and add 10Micron as a snoop device for the camera in INDIGO control panel next time I'm at the observatory as the camera only shows up in the INDI control panel once connection is established. If that doesn't work, I'll wait for the next beta. Anyway this isn't going to be a problem for me until next season, my current model is working nicely.

Thanx!
Ginge

**Comment by mworion** [comment]
Ginge,
I put the workaround in, give it a try at any time. Closing this issue. v2.0.0b3 onwards would be the version to test.
Michel
