### ISSUE TITLE
REQUEST: power mount on/off using 1500 ms pulse from MGPBox?

### ISSUE THREAD

**Issue by airscottdenning** [mworion/MountWizzard4#149]
This is the purpose of the "P" in MGPBox. The box is serial-connected to the mount for GPS and can be separately connected via FTDI serial on USB to the computer.

In DOS/Windows, the command MGBox.exe -P COM?? -T 1500 causes the box to send a 1500 ms pulse to the relay on the mount control box, safely toggling power on or off. Here COM?? is the Windows COM port assigned to the MGPBox (actually an FTDI usb-to-serial converter).

I have tried this in wine, but I can't figure out how to map the /dev/ttyUSBx or /dev/ttySx port in linux to the MGPBox.

This seems like a nice piece of functionality for MW4.

**Comment by mworion** [comment]
Scott, closing under issues and following up in discussions.
