### ISSUE TITLE
Generate model points as grid -- up/down in-/decreases 2 steps

### ISSUE THREAD

**Issue by kaythriemer** [mworion/MountWizzard4#15]
Hi Michel,
I have just updated to MW4 Version 0.148.5 .
In Model Points tab I found out, that if i click on up/down for Rows, Cols, AltMin or AltMax the value is in-/decreased 2 steps. E.g. one klick on up for Rows the value is increased from 6 to 7 and to 8. Or one click on up arrowfor AltMin
[MW4_2.zip](https://github.com/mworion/MountWizzard4/files/4205833/MW4_2.zip)
 increases the value from 10 to 15 to 20. 
This happens for all Up/Down arrows.
Thank you.
CS
Kay.

**Comment by mworion** [comment]
Might be again a topic with ubuntu ??
Targeted behavior: Rows +-1, Col +-2 (as I need equal numbers), alt min/max +-5 
Michel

**Comment by kaythriemer** [comment]
Hi Michel,
yes it looks like the same Ubuntu issue as the last time.
Kay

**Comment by mworion** [comment]
Fixed with v0.148.6

**Comment by kaythriemer** [comment]
Thank you Michel. Successfully tested :-)
