### ISSUE TITLE
MW4 - ASCOM issues with 64/32bits

### ISSUE THREAD

**Issue by carlosgib** [mworion/MountWizzard4#155]
Hi Micheal, as explained in the 10Micron forum, I am having problem some ascom connections, either its 32bit running in a 64bit, a 64bits running in a 32bit. There other equipemnt , the camera and filter wheel does not show under an ascom driver , when I do have them (FLI) running under 64bits. I am providing some photos, maybe you can see the issue. I do not know what to do, I have installed MW4, Python as well as the FLI drivers. Run them under administrator. 
I however managed to work using MW3, the direct connection to SGP and connecting through Win32bit/Ascom managed to connect to the Camera/FW.

Thanks 
Charles

![20210626_115906](https://user-images.githubusercontent.com/43699731/123511486-d8b81500-d681-11eb-889f-1bbbc01787b9.jpg)
![20210626_115925](https://user-images.githubusercontent.com/43699731/123511488-d9e94200-d681-11eb-920c-db2d19edd4b9.jpg)
![20210626_115826](https://user-images.githubusercontent.com/43699731/123511491-da81d880-d681-11eb-81b0-fa3333b23d6c.jpg)
![20210626_115841](https://user-images.githubusercontent.com/43699731/123511494-dbb30580-d681-11eb-8b3e-906104362021.jpg)

**Comment by mworion** [comment]
OK, let's start from a clean install.
As you have QHYCCD camera with a large sesame (my guess), I would go for 64bit installations as some users reported issues with memory consumption in 32bit.

Could you post the log file from your work folder (install.log, run. log and the mw4 log file ?  - please run MW4 in Deep/Debug, Trace mode before) 

delete complete MW4 work folder (or start with a new one)
remove python if it's not 64 bit version. 

install python 64bit
download the 2.0 widows scripts
extract them in the new work folder
run the install script
script should tell that 64 bit python is installed in the terminal window
the official version is 1.1.1, my guess is you want to get to version 2 beta.
if you recently have downloaded the script, there should be a updateBeta in there as well (if not, please download the newest scripts)
run the update beta script

use the latest ASCOM 6.5 SP1 platform version. older ones had reported issues.
make sure, that you install for all your devices 64bit drivers. The FLI focuser is definitively a 32bit driver, which will not work.

run MW4
enable trace debug under settings/update
start to setup the first ASCOM driver

At this point, please report you status.

**Comment by Carlosgibb** [comment]
Hi, please find the three logs that you asked for, I am now going to start removing programs suggested, and reinstal again.

Charles


[mw4-2021-06-26.log](https://github.com/mworion/MountWizzard4/files/6720431/mw4-2021-06-26.log)
[update.log](https://github.com/mworion/MountWizzard4/files/6720432/update.log)
[install.log](https://github.com/mworion/MountWizzard4/files/6720433/install.log)

**Comment by carlosgib** [comment]
Hi Micheal, i follow the intsallation process, Installed Python 64b, installed MW4 2.0 scripts, I removed ASCOM and installed again 6.5, I runned beta script, I run MW4 and the FLI camera or the ASCOM Pulsar Dome could not be started. On the format because it cann find the FLI drives, and the latter the same as before a 64bits runing with a 32bits. I just left my observatory, will come back next friday, the only thing I did not do was the 'enable trace debug' 

Charles

**Comment by mworion** [comment]
Charles,
if we find some time we should try a co-working session via team if you don't mind.
Michel

**Comment by Carlosgibb** [comment]
Hi Micheal, yes please, I intend to travel to my observatory on Thrusday
night, if you have a free time on Friday I will be there, or Saturday.

Thanks
Charles

**Comment by mworion** [comment]
Charles,
Saturday (today) would be OK. Any time which might fit for you ?
Michel

**Comment by Carlosgibb** [comment]
Sorry Micheal, had to go back home from the observatory, some urgent matter
Can will arrange another day, will be in touch for next week. apologies and
thanks again

Charles

**Comment by mworion** [comment]
Please give me a short notice if you would like to move forward.

**Comment by Carlosgibb** [comment]
Good Afternoon Michael, I managed the Dome to work with MW4 and the FLI
focuser, and just put a question in ASCOM forum given that I try to load
FLI camera in Shapecap and couldn't find the FLI drives, FLI like always
weren't that helpful.

Let see what ASCOM forum come back with.

Thanks

Charles

**Comment by mworion** [comment]
Charles, 
good to hear. Please let me know when you need some help. If you don't mind (as I'm cleaning up for the next release) I close this issue. Please reopen or if you know more open a new issue for further topics.
Michel
