### ISSUE TITLE
Cannot program earth rotation data

### ISSUE THREAD

**Issue by mbalkham** [mworion/MountWizzard4#157]
Might not be a bug (could be operator error!) But I get "not running windows - upload not possible' error when I try to program earth rotation data. Both on 1.1.1 and v2.0.0b17

![20210628_201028](https://user-images.githubusercontent.com/76722683/123605669-31d5a380-d850-11eb-9179-420f5c0b15e9.jpg)

**Comment by mworion** [comment]
No, I believe no operator issue.
Could you describe your system (OS version, 32/64Bit, language settings, language version)
As I read menu attributes, these might change due to environment settings and I miss the widget.

There might be the necessity to gibt you a test program to check.
Michel

**Comment by mbalkham** [comment]
Thanks Michael. Having same issue with both stable and beta releases on windows 7 and macOS Catalina.

**Comment by mworion** [comment]
macOS does support uploading, that's fact as you need the 10micron updater program. And this is only available in windows.

If you try it on windows (you need the updater installed) and it does not work, please sent me the log. (and have set MW4 to debug mode under settings/debug

**Comment by mbalkham** [comment]
Thanks Michael. I'm away for a couple of days but will try with logging when I'm back.

**Comment by mbalkham** [comment]
I have tried it and have the updater installed. I am connected via wifi through a rpi running stellarmate. Do I need a direct connection to the mount?

**Comment by mworion** [comment]
Yes as the 10micron updater does the basic work. It needs a direct connection to the mount. This can't be routed through INDI and stellarmate. MW4 only automates the download of the necessary files and clicks for 10micron updater.

**Comment by mbalkham** [comment]
I've managed to update using the data files downloaded in mw4 using the 10 micron updater but not pushing to mount in mw4. Good enough for me for now!

**Comment by mworion** [comment]
OK whenever you like, give the automation a try and reopen the issue if it failed !
