### ISSUE TITLE
MW4 1.1.1 closes right after starting

### ISSUE THREAD

**Issue by matthisk2** [mworion/MountWizzard4#158]
Hello,

i just installed python 3.9.6 and MW4 on my W10 notebook. When starting the mw4_run script, i can see the cmd, the mw4 loading screen. The program starts but closes right after 2-3 secs.

Any idea?

Thank you! 
[mw4-2021-07-10.log](https://github.com/mworion/MountWizzard4/files/6794935/mw4-2021-07-10.log)

**Comment by mworion** [comment]
Hi,
seems that there is a test.txt file in your work dir. Just delete this file and it should work. 
Michel

**Comment by matthisk2** [comment]
Yes, this worked. Thank you. No idea why the test file got created by the scripts though ...

**Comment by matthisk2** [comment]
How can i use my pinpoint or the online version of astrometry.net? 

All i find is astrometry.net locally installed which is not each to do on windows. Tried to get it running with ansvr but pointing it to the application dir in C:\Program Files (x86)\Astrometry.net Local Solver and the index files at C:\Users\user\AppData\Local\cygwin_ansvr\usr\share\astrometry\data is not being accepted ...

**Comment by mworion** [comment]
You might have used an olde version of the "test" scripts for install. In this case in might be generated. I also had in in the repo. If you just cloned the repo part, you also might cloned this file.

I have to apologize, MW4 does not support an online version of astrometry.net (as it is compared to the new versions of local solver slower and has no advantage for modeling). The same is true for pinpoint as you need a license for using it (and I do not have one). I recommend ASTAP as a really good local solver, which is free, fast and very much reliable also for all sky solving.

Michel

**Comment by mworion** [comment]
closing this issue as it was solved.
