### ISSUE TITLE
Values inverted in Actual Parameters window

### ISSUE THREAD

**Issue by TomBootz** [mworion/MountWizzard4#16]
In "Sett./Conf.  Imaging" Tab, within the "Actual Parameters" window, the values in the second column for Resolution and FOV are inverted.

![MW4_screenshot_arrows](https://user-images.githubusercontent.com/61393144/75121112-a72ad600-5656-11ea-8309-303b8bffd956.png)

**Comment by mworion** [comment]
Good point, 
fixed in next release.
