### ISSUE TITLE
Multiple ASI cameras: Device connect always shows ASCOM.ASI.CAMER2

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#160]
Hi Michel,
I have two ASO connected to my NUC. When I select the first ASCOM Profile, MW keeps showing second profile, though it seems it connects the right camera.

Rüdiger

![2021-07-21_21h50_24](https://user-images.githubusercontent.com/65772654/126551427-cd9ffa32-dbbc-4872-9d42-cd2ce88d3748.png)

**Comment by mworion** [comment]
Hi Rüdiger,
please post the log.  If I open the ASCOm chooser, it will always start on default order. The device I use (which is defined by it's name) is the text string in MW4 pop up window. The log contains the real connection name fed back from the driver. So we could look.

Target: Profile 1 has Camera 1, Profile 2 has Camera 2 in settings. Right ?
You could look in the two profiles for the selected camera in the driver / ascom / camera section with an text editor, or just post the two profiles. 

Normally switching a profile should load the correct drivers stored.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

please find the log attached. 
You are right. But for testing I also switched the Camera to profile assignment. 

I was stumbling upon when I had tried to activate the cooler and it was not working. I found out the ASI 174 was connected which has no cooler. switching to the other profile helped, but MW always show Profile2, though it is working.

All not a big deal, but confusing.

Best wishes
Rüdiger


[mw4-2021-07-21.zip](https://github.com/mworion/MountWizzard4/files/6861198/mw4-2021-07-21.zip)

![2021-07-22_11h19_53](https://user-images.githubusercontent.com/65772654/126616710-cb1e4fda-84f4-4430-8e39-6de142c390a7.png)

![2021-07-22_11h20_03](https://user-images.githubusercontent.com/65772654/126616718-efac78bd-7262-4d4f-8a35-2fba6b156ce5.png)

**Comment by mworion** [comment]
Rüdiger,
misunderstanding on my side: I though about profile in MW4 you are talking in profile in ASCOM. As I'm not a heavy ASCOM user, Could you explain how to use ASCOM profiles ?
My assumption: If you change the ASCOM profile, you disconnect you actual device and connect a new one outside MW4. If so, I do not recognize the device name change.
Michel

**Comment by Ruediger3** [comment]
Sorry maybe I had not descried it properly.
1. in MW "Core device: Camera" I select the camera
2. There are two profiles (both created by ZWO ASCOM driver installation by default)
3. 3. Regardless what I choose, MW always shows that profile two was selcted, so it is actually not the case. MW connects the camera, which is linked to the profile. but MW does not show it.

![2021-07-22_11h28_50](https://user-images.githubusercontent.com/65772654/126618164-956127f7-b2cd-448e-a176-63d7755ca7e7.png)

![2021-07-22_11h28_35](https://user-images.githubusercontent.com/65772654/126618336-75f863a5-ae13-4ea2-bdef-de6b11971dae.png)

**Comment by mworion** [comment]
OK then I got it. 
I stepped over it in another topic if the camera driver also includes a filter driver. Same story.
What happens so far: there is only one driver (which is in you case ASICamera2...) loaded, which emulates multiple virtual drivers (as they use basically the same driver) by adding new devices in the drop down list. I currently have no chance to access this device name list as it seems is stored internally. For my the straight forward way (as QSI did with an update of their drivers - one manages ccd and filter at the same time) is that the driver reports in chooser two separate names. 

So actually if things do not change I have to set it to won't fix it.

Michel

**Comment by Ruediger3** [comment]
Then it would better not to show any number. Just "connected". But by showing a dedicated number it gets confusing and misleading.

**Comment by mworion** [comment]
The number is part of the ASCOM device name, so ASCOM generates this number in the name. So the text string is exactly the feedback from ASCOM and needed for distinguishing between real drivers.

**Comment by Ruediger3** [comment]
Too bad :(

**Comment by mworion** [comment]
Rüdiger, so far I close he issue with won't fix, but I keep in mind if there are some ideas to make it better.
