### ISSUE TITLE
request: retry failed points (GUI and model finishing)

### ISSUE THREAD

**Issue by airscottdenning** [mworion/MountWizzard4#162]
I guess this is two separate requests that both have to do with MW4 (v 1.1.1) retrying failed measurement points during a model run.

1) Please update the sky chart with checkmarks if the retry is successful. This will help me optimize sampling relative to obstructions by deleting points that fail every time vs just temporary failure due to clouds. 

and

2) Please trigger "End" modeling after failed points have been retried. Every time I have had MW4 retry failed points it just waits after solving the last point until I manually push "End" to trigger programming the mount.

**Comment by mworion** [comment]
Hi Scott, 
you are using v1.1 I guess, correct?
Michel

Von meinem iPad gesendet

**Comment by airscottdenning** [comment]
Yes, version 1.1.1

Should I be using v2 beta instead?

**Comment by mworion** [comment]
Scott,
Your issues should be already addressed in v2. I’m going to release within the next 2 weeks. So you could, but not need to use the beta if you are not in a hurry.
Michel

Von meinem iPad gesendet

> Am 25.07.2021 um 23:45 schrieb Scott Denning ***@***.***>:
> 
> ﻿
> Yes, version 1.1.1
> 
> Should I be using v2 beta instead?
>

**Comment by airscottdenning** [comment]
Thank you! No hurry. I can certainly work around these until v2 is released.

Scott

**Comment by mworion** [comment]
OK Scott,
 closing it and hopefully the result is as expected on your side.
Michel
