### ISSUE TITLE
(minor) Display of Alt-Az coordinates in Views/Coords 

### ISSUE THREAD

**Issue by razvan-astro** [mworion/MountWizzard4#164]
Hi Michel,

Apologies for writing up such a minor issue, just want to avoid some potential user confusion. 

In the Hemisphere window, under Views/Coords section, the Altitude and Azimuth fields normally display the coordinates of the mouse pointer inside the grid.  I noticed last time that when the cursor exits the grid, the coordinates stay populated with those of the "border point", through which the cursor exited the grid. It can be a bit confusing while the model building is going on, as those coordinates will not match what is happening during modeling. Ideally, the two fields would be cleared when the cursor leaves the grid.

Thanks for considering it.

**Comment by mworion** [comment]
Hi,
thanks for the hint, changed in next beta.
Michel
