### ISSUE TITLE
Install problems with matplotlib

### ISSUE THREAD

**Issue by Dagolaf** [mworion/MountWizzard4#165]
Dear Michel,

During execution of MW4_Run.bat and error is occuring and the installation stops. Pls have a look into the logs which I added as requested.
I tried Python 3.8.3 and latest 3.9.6 with the same result.

An MW4 log I did not notice probabaly because it was not installed.

I am working under Win 10 latest version.

Another "porblem" which I noticed but I think has nothing to do with the abouve:
The script always installs the virtual environment "venv" into C:\Windows\System32 no matter where I creat my working folder.

[install.log](https://github.com/mworion/MountWizzard4/files/6953260/install.log)
[run.log](https://github.com/mworion/MountWizzard4/files/6953261/run.log)

Thanks in advance for your help and your great work!

Best regards

Olaf

**Comment by mworion** [comment]
Hi Olaf,
the problem is already know on matplotlib side. Your could try either on of these options:

1. Update to MW4 v2 beta as there is a newer version of matplotlib used and there might be a good chance that itis already sorted out there. To do so, please run the MW4_update_beta script. V2 will be released soon and the actual state should be fine for you.

2: There is a hint that when manually activate the venv environment running installation of the MSVC runtime (pip install msvc-runtime) shoudl also solve the problem.

Hope this helps and please report back.
Michel

**Comment by Dagolaf** [comment]
Hi Michel,
thanks so much for your help.
I thought the update process should be started after the first "run" but I understood your suggestion to use the update_beta script before, so I did liek that and used the MW4_Run-bat AFTER and it was successfull. MW4 is starting now and it shows V1.1.1
Do I have to start MW4 always with this batch-file ?

Your second hint regarding VENV installing into System32, unfortunately I don´t understand. But as I can cut and paste the venv folder into my "working"-directory and MW4 looks still ok, I don´t care :D.

Thanks again Michel for your help and your great software!

All the best for you

Olaf

**Comment by mworion** [comment]
Hi Olaf, normally the scrip should place the venv right in your working directory. But on windows many system look in details different. There are only a few really important commands in the script for installing the venv, sourcing the venv and running MW4. You could do this always from a command windows yourself.

Yes, you need to start MW4 with the Run script always. If you don't want to see the command window -> you could make a link to it and edit the settings for it (e.g. visible or ICON)

The reason for this change to this setup was that boot times from an EXE (which contains all parts including python) got to more than 30 seconds (as all has to be extracted) and updating required replacing the exe completely (which was at the end about 100MBytes) and no chance to implement an internal updater. 

Updating from v2 on should not need the update script anymore as it could be don't internally. -> see YouTube videos.
Michel

**Comment by Dagolaf** [comment]
Thank you Michel for the explanation!
