### ISSUE TITLE
Platesolve solution shows a 90 deg angle whereas the camera is horizontal.

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#166]
In the imaging window it says Rotation 0.000 deg
The platesolve solutions says angle 90 deg
When I open the image with a fits viewer, the orientation is in portrait.
But when I take an image in NINA and platesolve it, the angle is 0 deg (as it should)

**Comment by mworion** [comment]
Could it be like a transpose of the Image. 
Sorry about this behavior, the more you discover the less confidence I get formte ascot simulation environment as I don’t work on ascom for my Astro work. Immaterial some changes to improve ascom download speed, it’s faster, but it might cause more problems. I really think about reverting back to the slow version, which was ok.
Michel

Von meinem iPad gesendet

**Comment by mworion** [comment]
Hi Arie,
sorted this out, v2.0.0b39 should do it. Uploading this afternoon after tests
Michel

**Comment by ACMBakx** [comment]
Yep, image orientation is correct now.
