### ISSUE TITLE
Fast allign: Not working - stays deactivated

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#168]
Hello Michel,

last night I would have needed the function "fast align" for the very first time (after collimation of the CDK). I was not able to get it active. Though camera, Solver everything was connected this function remained deactivated. The mount was configured to accept aliments in the setup.

I will not exclude a handling issue, but I could not figure out how to get it work.

Thank you!
Rüdiger

![2021-08-15_00h30_00](https://user-images.githubusercontent.com/65772654/129476145-740b54b7-ebe8-4c29-a9e1-631377752ca1.png)

**Comment by mworion** [comment]
Hi Rüdiger,
no handling issue, you were the first one stepped over it! Has to be sorted out.
Michel

**Comment by Ruediger3** [comment]
Cool, like always. ;)

**Comment by mworion** [comment]
:-) to be honest: I also never used it. It was a function, which came from MW2/3 as then people did a lot "quick" fixes for the model. 
BTW: if you are the only one using it :-) could you describe the use case in more detail, probably it makes sense to tailor it for that.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

this was also a quick fix. Yesterday night it was quite cloudy and only some holes. I did collimation on the CDK. By shifting the secondary of course the model became invalid (approx. 20'). 
Due to the clouds it was impossible to make new model, which would have been the mandatory next step for sure. So to continue with work and hit any desired target at 8m FL, I decided to sync the model since the secondary mirror shift introduced a constant offset. So this should work perfectly. 
Since it was not working in MW I did it in a planetary software and send a sync command from there via ASCOM, which I actually dislike, since I have to change settings in ASCOM driver. Next time your forget it to reverse....

I hope I could explain it.

For me the function in MW would have been perfect when it would had worked as described in the text next to it. The functionality is perfect. I should only work :)
For quick fix it is quite neat. 

Cheers
Rüdiger

**Comment by mworion** [comment]
v2.0.0b40 published

**Comment by Ruediger3** [comment]
Thx! Installed. 
Now only the weather must get better to test it.

Cheers
Rüdiger

**Comment by mworion** [comment]
Sure. BTW: Any remarks to the new updater. So far I did not got issues with it.

**Comment by Ruediger3** [comment]
Works very well. No issues. Only message window tells me there is a new version, so I have the latest Beta. That's confusing. 

![2021-08-15_22h39_03](https://user-images.githubusercontent.com/65772654/129492169-543dbf04-0f2b-40b9-8daf-5c3157fc291c.png)

**Comment by Ruediger3** [comment]
Thanks for fixing :)
b43 now suppresses the message.

**Comment by Ruediger3** [comment]
Hi Michel,
just tested an works as expected now. 
Was extremely useful. Just had to align the current model at FL=8855mm since FOV=0.16° for planetary imaging. 
Thx!

Cheers
Rüdiger
