### ISSUE TITLE
Precision in Adjust_Polar_Alignment window

### ISSUE THREAD

**Issue by TomBootz** [mworion/MountWizzard4#17]
Hi Michel;

Not sure if this in a issue or not.

In MW3 the precision in the "Adjust Polar Alignment" window was 2 decimal places. In MW4 it is currently 1 decimal place. When working at 380mm this left me with no hints as to which way to move the mount to improve PA. However, at 945mm the single decimal worked ok.

**Comment by mworion** [comment]
added one digit in the next release back in MW4
