### ISSUE TITLE
Hemispehere: Alt/Az view does not match polar view

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#172]
Hi Michel,

just noticed that both graphs do not match. Please see screenshot.
The mount circle indicating the mount at east an processing the model points there, but in polar you see the points processed West and the mount on the other side which is impossible.  

Cheers
Rüdiger

![2021-08-20_22h20_52](https://user-images.githubusercontent.com/65772654/130289677-2eb751f6-a5ba-41ad-b2ed-4c588bf3322c.png)

![2021-08-20_22h42_01](https://user-images.githubusercontent.com/65772654/130291278-618bef00-2ae7-40a9-82e3-d34598b0f5ef.png)

**Comment by mworion** [comment]
Rüdiger, you are right, they are mirrored, will be corrected in the next bugfix release.
Michel
