### ISSUE TITLE
044b not shutting down properly

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#173]
The focuser connects.
The WOL works now.
But,
When I start MW4 just to see if WOL is working, but without connecting all the ascom gear (incl the dome), and then select save&quit, MW4 gets into a loop. The main window closes, but the others remain open.
I see in the DOS window that MW4 cannot connect to the mount anymore, obviously . . . . . . . 
And that line is repeated, untill I close the DOS window.
There was one line referencing to the dome, which made me check this.
When I connect the dome and disconnect it again, MW4 does shut down properly.
Attached the log from this morning when I tested WOL.

Arie
[mw4-2021-08-21.log](https://github.com/mworion/MountWizzard4/files/7025291/mw4-2021-08-21.log)

**Comment by mworion** [comment]
Arie, found the issue only when dome device is configured. Will be solved in the first fix release of v2.
