### ISSUE TITLE
Image does not show

### ISSUE THREAD

**Issue by mhambuch** [mworion/MountWizzard4#174]
[mw4-2021-08-29.log](https://github.com/mworion/MountWizzard4/files/7072055/mw4-2021-08-29.log)

Hi Michel,

I have a new camera ASI6200 MM Full Frame. Image exposes, downloads but is not shown in the image window. 
Timeout like last time. Ascom Server is on the same PC as MW4 and all other Apps i use. 

i just notived that a couple of seconds after having taken the 2s exposure, the entire ascom server crashes, i get a notepad log that i also attached. There the issue is an out of memory. Eagle3 PC has 16GB Ram and the only  apps running at time of crash are ascom server, mw4 and MGbox. On the server configuration panel there is an option to run drivers in separate threads which is selected by default, nothing about memory allocation.

Use this ticket to ask one question. Does binning influence the result (quality) of the model? So does it make sense to bin 2x2 to speed up download and therefore model creation?

![image](https://user-images.githubusercontent.com/63575440/131241547-367280eb-6f28-4f8d-832b-2273ff029fa1.png)

[ASCOM.RemoteAccessServerException.0907.251850.txt](https://github.com/mworion/MountWizzard4/files/7072072/ASCOM.RemoteAccessServerException.0907.251850.txt)

**Comment by mworion** [comment]
Hi,
just by looking on the log I see the image is not fully downloaded, but MW4 tries to show it - which ended in some error messages. This I have to correct to be more robust against broken images. The reason why might be the ASCOM server and the memory (but that‘s just a guess). 
Important for you modeling: If you are using e.g. ASTAP for solving, there is no need to use the full image. ASTAP likes according to Han (the developer) about 1500 x 1500 pixel. So I definitely would go for bin2 or even bin3 or choose a subframe to reduce size. THis should not impact your model.
Michel

**Comment by Ruediger3** [comment]
Hi both,
I use the same camera and it works flawless with Bin2 for me. Also Bin1 had no issue, but it is not required. 

CS
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
thanks for the feedback, your are using ASCOM, where as the issue occurred with ALPACA. It might be the case, that the alpaca server tries to hold the complete image in memory.
Michel

**Comment by Ruediger3** [comment]
Had used 🦙 before native ASCOM was reimplemented and also had no issue as far as I remember.
But meanwhile a lot has been changed. 

CS and nice Weekend!
Rüdiger

**Comment by mworion** [comment]
Ok another point:
I see in the log an error relating the filter number. Somehow the ASI Filter seems not to transfer a number, but something else. Would you mind to make a short test for the filter with Trace mode in debug enabled an post this log? Many thanks.
Michel

**Comment by mhambuch** [comment]
Thanks Michel, Ruediger, 

I will post the result of the Filter later this afternoon.

**Comment by mhambuch** [comment]
Hi, i just started mw4 and changed the filter number. The display is effectively strange. 

Hope the log helps.

![image](https://user-images.githubusercontent.com/63575440/131256639-b5dbe4c4-ed48-4c01-a8d3-6736d9e8f2cf.png)


[mw4-2021-08-29.log](https://github.com/mworion/MountWizzard4/files/7072798/mw4-2021-08-29.log)

**Comment by mhambuch** [comment]
trace modus
[mw4-2021-08-29.log](https://github.com/mworion/MountWizzard4/files/7072808/mw4-2021-08-29.log)

**Comment by mworion** [comment]
Thanks for the extended Log. There is more to to as there is a missing link between filter driver and returned value on alpaca side. As I‘m currently not able to build MW4 (on a trip), this may take some time to find out.
Michel

**Comment by mhambuch** [comment]
No pb, thanks for your support. The app is really great!

**Comment by mworion** [comment]
Marc,
I think I got the image not show issue solved (at least on MW4 side). If the ALPACA server fails due to memory problems, MW4 should be robust against a not transmitted image.
Please submit the issue with the Exception also to ASCOM / ALPACA to get this topic solved. Please be sure that you have the latest ASCOM / ALPACA versions installed as there were some issues in earlier versions.  

To your question about the filter names: The come from the driver. The ASI FW driver should be able to set names for each filter. If MW4 does not get one, it will show 'not found'.

The ASCOM / ALPACA definition of filter positions is 0 to N-1,  so 0 to 6 would be OK, but the it should show the names define in the driver. In case the driver does automatically give the names as default and it is 1 to 7, so you have the explanation of the mismatch.
Michel

**Comment by mhambuch** [comment]
Thanks Michel, i will test it as soon as you deploy the beta with the fix. Marc

**Comment by mworion** [comment]
Marc,
there is a v2.0.2b1 uploaded, please try it and report back. I might not sort out all things, but I need to know if I'm on the right way.
Michel

**Comment by mhambuch** [comment]
Hi Michel,

Thanks a lot for having already pushed a correction. Alcapa is interesting as it allows me to focus in SGP before switching to MW4 (a focusing routine in MW4 would be "the hammer" i guess you say in Germany)

I tested the exposing n worked in bin2 full frame ; switched then to bin1 and camera gone + alcapa dump. On MW4 it stays on exposing 0s.

Marc

![image](https://user-images.githubusercontent.com/63575440/132133542-fbfc9356-c315-42c1-8649-5a8de27d1699.png)

[mw4-2021-09-05.log](https://github.com/mworion/MountWizzard4/files/7111955/mw4-2021-09-05.log)


[ASCOM.RemoteAccessServerException.1804.506310.txt](https://github.com/mworion/MountWizzard4/files/7111957/ASCOM.RemoteAccessServerException.1804.506310.txt)

**Comment by mworion** [comment]
Hi Marc,
thanks for testing. So far MW4 does not throw any error more.  You could just press abort on image windows to stop. As the ALPACA server is responding without any error, MW4 keeps waiting for the response (or error). So hardly anything to do about it.  I've seen you opened an issue on ASCOM Remote. So hopefully this will be sorted out soon. 

I added the focuser interface already, so a manual focus could be done. I has not to be perfect to do a model, as the solver normally tries to find the center itself (BTW: some focus routines perform on the base on source extraction, which is also the base for a solver). So good from eye is good for modeling.

I put the autofocus on the wish list....

What about the filter topic ?

Michel

**Comment by mhambuch** [comment]
Hi Michel, Yes there is nothing more you can do for the imaging. It is now proper as it does not crash anymore when alcapa has the out of memory. For the filter, i maintained their names on the alcapa server side setup, those a shown in mw4, so perfect. I just found it strange at the beginning that the number starts at 0, but yet i know.All fine on my side, ill close the issue.For the focuser, you are right, a manual focusing does it even if it is not always easy to check the number of pixel displayed. Maybe there are some open source for this. Lets see if other users propose that addon.Many thanksMarc
-------- Message d'origine --------De : Michael ***@***.***> Date : 05/09/2021  18:33  (GMT+01:00) À : mworion/MountWizzard4 ***@***.***> Cc : mhambuch ***@***.***>, Author ***@***.***> Objet : Re: [mworion/MountWizzard4] Image does not show (#174) 
Hi Marc,
thanks for testing. So far MW4 does not throw any error more.  You could just press abort on image windows to stop. As the ALPACA server is responding without any error, MW4 keeps waiting for the response (or error). So hardly anything to do about it.  I've seen you opened an issue on ASCOM Remote. So hopefully this will be sorted out soon.
I added the focuser interface already, so a manual focus could be done. I has not to be perfect to do a model, as the solver normally tries to find the center itself (BTW: some focus routines perform on the base on source extraction, which is also the base for a solver). So good from eye is good for modeling.
I put the autofocus on the wish list....
What about the filter topic ?
Michel
