### ISSUE TITLE
V2.0.1: "Avoid meridian Flip when starting" is not working

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#177]
Hi Michel,

just creating a new model. The mount was pointing to west and first point was east. The mount started with a flip though the option "avoid Flip" was checked. It was simply ignored.

The model build started approx. 21:09. The log is huge since MW is running continuously. 

Cheers
Rüdiger

[mw4-2021-09-04 - Copy.zip](https://github.com/mworion/MountWizzard4/files/7112232/mw4-2021-09-04.-.Copy.zip)

**Comment by mworion** [comment]
Hi Rüdiger,
checked the log. Perhaps there is a misunderstanding how this function works: It is a sorting of points before starting the model run and not an optimization during model run.
Normally MW4 would start on the east side:

![Bildschirmfoto 2021-09-06 um 17 43 25](https://user-images.githubusercontent.com/6632980/132240803-63cba5f9-1bd5-4261-bae3-7fb4fddc9dc8.png)

If the mount points west (like in the image, that's a pity. If you check avoid flip and generate points again, than you get a sorting which starts west first like this:

![Bildschirmfoto 2021-09-06 um 17 43 34](https://user-images.githubusercontent.com/6632980/132240904-8798f8b7-5bdc-4c04-87fb-2b43eac078db.png)

If you finished a model run which started on east and ended in west and build another model afterwards, the order of the model points in hemisphere did not change and therefore the process will start on east. You have to "generate" the build points again to get the sorting right. My guess is that in your case it happened exactly like this.

Does this interpretation makes sense ?
Michel

PS: Perhaps I could try to automate some of the steps if possible.

**Comment by Ruediger3** [comment]
Hi Michel,

Now I have understood how it should work. 

This is only useful, when you re-generate it automatically on every model generation. In my case I have a mixture of generated and manual added points, due to the obstructed FOV. Hence I cannot use this function, since I only load my point spread.

This is not a big issue. I was only confused since I expected another function. 

Only one idea: Maybe it is possible to renumber the points on start in general to do all the optimization? Like minimum slew paths, flips and probably dome?

Thanks!
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
The function does also work if you load a point spread. Generating also means loading the points from file. This item has a generate button as well, so it hat the same capabilities. So if you press generate on file points and have avoid flip and the sorting will be done.
Michel

Von meinem iPad gesendet

**Comment by Ruediger3** [comment]
Ok, than it is strange, since I exactly did that. It was not a intermediate start or something like that. I had hot the button "show points" and started immediately. 
I will retest to make sure that the mount was already pointing to east when loading the point spread.

I have installed the latest beta for test.

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
I now build a beta2 with #177 and #178 improved for your tests.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

many thanks. I can confirm it works as you have described it. 
Either the mount is already on the appropriate site, or hit show points again. Than it gets properly numbered. 

Thanks for clarification :)

Cheers
Rüdiger
