### ISSUE TITLE
MW4 in ubuntu virtual box on dome windows PC

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#18]
SInce Alpaca camera connection does not work, I am installing VirtualBox with Ubuntu 18.04.4
From there I would like to install MW4 and run it from Linux.
Is this a viable option?
I do need some help, because I have no experience with Linux and all the command-line instructions that are used here.
Arie

**Comment by ACMBakx** [comment]
Ubuntu is up and running in virtualbox.
Installed Phyton. Installed MW4. Needed manually to install PIP3 and PIP.
Ubuntu terminal showed me the syntax how to install these.
Did all kinds of fuzzy installs in terminal to try to get INDI installed and the server running.
Finally installed KSTARS and EKOS to get this done. No clue how else to start the INDI server.
The mount connects straight away via IP address.
Cannot get anything else connected in MW4. No camera and no dome.
How to install a solver?

**Comment by mworion** [comment]
Hi Arie,
As solver I would recommend ASTAP. If you search for it you find an installer for the database as well as for the solver as DEB package. Just download and right click should ask for installing. Defaults will be OK.
For INDI server I would recommend INDI Web Manager. Once installed (pip3 install indiweb) it will start the server on boot an configured by ip:8624.
Hope this helps.
Michel

**Comment by mworion** [comment]
Arie,
from your feedback in 10micron forum I guess you stay with ASCOM on windows. I close this point. If there are some questions left, please let me know. Thanks for trying !
Michel
