### ISSUE TITLE
Use mount‘s park positions

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#182]
Hi Michel,

Maybe you have seen the thread in 10M forum about parking the scope face down. I am doing that too.

https://www.10micron.eu/forum/viewtopic.php?f=2&t=1620

Currently these special park positions can only be used, when using the hand box, since MW is using its own park positions. 

It would be great, if you could park the scope to the stored positions too. 

Maybe this is already possible but I have not found out how to do. 😎

Many thanks!
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
I do not know any command or way to move the mount below the horizon limits, which this feature needs to do. I have to check, how this works in the handpad, but there from my point of view no way to make this happen.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I have done following:

1. Move the scope into final position below limits (face down)
2. Store position as custom park
3. Set park position to this parkposition

When ever you send "park" it uses the chosen park position. This works from all applications which send "park" command via ASCOM. e.g. NINA.

The scope slews first to alt/az "over" the final park, waits a second and then moves the tip towards the floor into this "forbidden" position. Works actually flawless. 

So to send a simple "park to set position" should do the work.

Cheers
Rüdiger

**Comment by mworion** [comment]
Seems to be easy. Let‘s give it a try.

**Comment by Ruediger3** [comment]
Yep, I think just a button "Park to mount's PP" should do the job. :)

**Comment by Ruediger3** [comment]
Me be here: 
![2021-09-13_16h01_20](https://user-images.githubusercontent.com/65772654/133097716-42195f12-85a6-4efc-8202-80e8d07bd105.png)

**Comment by Ruediger3** [comment]
Yet another idea: if it is possible to select the mounts different parkpositions via native protocol, the button can be a drop down field to select default or P1 to P5.
That would cover even more use cases.

Rüdiger

**Comment by mworion** [comment]
Rüdiger,
Your request is already build in. If you set your custom position for park and press park on the main screen, MW4 will already do the trick. The positions in Tools are additional points (where you could just drop any actual position in). This position has to be reachable (and has the constraints). I just tried it and it works.
Michel

**Comment by Ruediger3** [comment]
Great! I will test as soon as weather allows it!

Thanks!
Rüdiger

**Comment by Ruediger3** [comment]
Tested and it works perfectly.
Many thanks!
