### ISSUE TITLE
Option for DAT during model build

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#183]
Hi Michel,

I am missing the option to enable/disable Dual Axis Tracking while modelling. I had noticed it was disabled during modelling and wanted to enable it, but I cannot find the option anymore, since 10M advised to keep it on during model build.

Please help me where to find ... THX!

Rüdiger

**Comment by mworion** [comment]
Rüdiger,
I removed this option, as MW4 clears the model before modeling anyway. So if no model present -> DAT does nothing special as there is no special correction possible. Hope this makes things a little easier.
Michel

**Comment by Ruediger3** [comment]
Thanks Michel,
I was searching for ages now 😂

Main switch I was a aware off.

If you have removed the option, I would prefer not to switch it off by default. Please don't alter setting, though you are right in argumentation. But following it, it also makes no sense to switch it off.

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
fully agree. I removed all things already for 2.1 release and perhaps do it in a device release 2.0.4 as well as 2.1 will take some time.
Michel

**Comment by mworion** [comment]
Rüdiger,
pls: check 2.0.4b. There is not much testing for it.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

many thanks!
I will test as soon weather allows, since it cannot be tested in dry run.

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
DAT stays active while build. Many thanks!
Cheers
Rüdiger
