### ISSUE TITLE
Fits Header: Add location and FL

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#184]
Hi Michel,

I am just supporting Han to improve a new feature on ASTAP. He had requested a data set of images and we noticed that no location is stored in the fits header. Also noticed that focal length is also not there.

Would it be a big effort to add this?

Thanks!
Rüdiger

**Comment by Ruediger3** [comment]
Also one feedback from Han;

_The date has a Z in the format. Should not be there but I can remove or ignore it:

     DATE-OBS= '2021-09-12T20:55:58Z' / Time from UTC is ISO format_

**Comment by mworion** [comment]
Hi Rüdiger,
no, not a big effort to add this data as it is anyway available. For the format of the date-obs I look the spec for the correct FITS entry up (I just pushed it in without long thinking as is was an ISO format).

**Comment by Ruediger3** [comment]
Many thanks. Much appreciated!
Rüdiger

**Comment by mworion** [comment]
As FITS standard does not have such Keywords, I would use the Keywords used in other context:

Latitude: 'SITELAT', Logitude: 'SITELON', format is 'sDD HH SS' with s is '+' or '-'

Any obstacle to that ?

**Comment by Ruediger3** [comment]
Perfect! Example below.
Rüdiger

![2021-09-14_17h13_19](https://user-images.githubusercontent.com/65772654/133284590-2dd7eb95-af3d-4135-b7d3-e962abf10a93.png)

**Comment by mworion** [comment]
Rüdiger,
pls: check 2.0.4b. There is not much testing for it.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

many thanks!
I will test as soon weather allows, since it cannot be tested in dry run.

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
works perfectly! Many thanks!
Rüdiger
