### ISSUE TITLE
Analysis window: Window position out of screen limits

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#187]
Hi Michel,

when I open Analysis Window, it gets open out of range. Only the small window frame is visible. Any attempt to reset window position fails. Only solution is to minimize and maximize again to get it positioned correctly and accessible.

Cheers
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
tested it with actual config file and with empty config. In both cases the windows opens in correct size in the middle of the screen. Could you post the config file which cause the trouble to check ?
Michel

**Comment by Ruediger3** [comment]
Good Morning Michel,m

sure I can. Also here an Image what is happening. You see the Analyse window completely moved to the left out of the screen. Only a thin line is visible. 

Also attached the cfg as zip.

Thank you!
Rüdiger

![2021-09-14_07h58_33](https://user-images.githubusercontent.com/65772654/133203217-f0eb81ce-cca3-4df3-82c5-f05cc788e659.png)

[CDK.zip](https://github.com/mworion/MountWizzard4/files/7159206/CDK.zip)

**Comment by mworion** [comment]
Still checked the code, there is actually nothing in to reduce size of windows or to move it out of to the left. 
How does this happen ? Two screens setup?

**Comment by Ruediger3** [comment]
It was used on multi screen setup and then moved it to NUC which runs with RDP only.

**Comment by mworion** [comment]
OK, will introduce a robustness topic in 2.1

**Comment by Ruediger3** [comment]
Many thanks!
Rüdiger
