### ISSUE TITLE
Help with Drivers and Set Up in MW4

### ISSUE THREAD

**Issue by PwrHsePro** [mworion/MountWizzard4#188]
I have about 80 hours in trying to help a school system set up their observatory... I, of course am donating this time, and its an hour drive each way from my home to this observatory... and time is running short...

Every company I go to to help get things set up, after they confirm the item is working, points me at you... theMW4 folks... to figure out how it is supposed to work with your software.

The problem items include, but may not be limited to:

Boltwood/Clarity II
Pier-Tech Roll-Off-Roof and Electronic Pier

Both of these work on their own, and according to MW4, show Green in ENVIRON and DOME... unfortunately, in MW4, the Environ tab when open, in large font says, "Offline Mode" and the roof and pier don't budge...

I am happy to schedule some time for someone to TeamViewer in like Diffraction Limited did for me last week... I'd be happy to take off work to facilitate this. 

Thank you in advance for your efforts,
Jeff

**Comment by mworion** [comment]
Hi Jeff,
sure, we could arrange a teamviewer session where I could try to help in setting up the system. As I'm still very busy on work saturday or sunday would be the best solution. You are on central time correct ?
Michel

**Comment by PwrHsePro** [comment]
Excellent!

Yes,  we are Central time, and weekends can work for me too... we do have a number of public events over the next few weeks, but I'd like to try to work around them...

Maybe you could suggest a few dates and times we could narrow it down?

Clear Skies!
Jeff

![20210920_170753](https://user-images.githubusercontent.com/90519146/134325777-54593558-62f9-439a-a72e-ae70fd7a633f.jpg)
![20210920_170734](https://user-images.githubusercontent.com/90519146/134325779-add6792c-6dc7-4091-87a2-45b330d1c7c0.jpg)
![20210920_170656](https://user-images.githubusercontent.com/90519146/134325782-7a49e3b8-bd0c-43bd-ba75-546e3d00912e.jpg)
![20210920_164232](https://user-images.githubusercontent.com/90519146/134325785-29c7da58-3330-4f5d-9e80-0dfdc3638600.jpg)
![20210920_164129](https://user-images.githubusercontent.com/90519146/134325788-900c13b2-1799-435f-9fba-2821defca794.jpg)

**Comment by mworion** [comment]
Hi Jeff,
I tried to do some preparation. From what I get, you need help in setting up the BoltWood Weather station in MW4 as well and the RoRo feature (open/close) from dome settings. And perhaps some other hints for MW4. Anything I miss ? If so, we don't need to be there during night (which might be tricky du to the 8h time difference). Sat or sun this weekend (and perhaps the next as well I could try to arrange, ideally around 8pm to 11pm Munich time which should be noon to 3pm your time. What do you think ?
Michel

**Comment by PwrHsePro** [comment]
I agree...We dont need a night time, but will.make what ever hours that are convenient for you work...Can we start with 8pm your time 12 noon my time on Saturday?I think youve covered current issues...It looks like the Environment (Boltwood/Clarity) connects as does the Dome (Pier-Tech Roll Off and electronic pier) but neather do anything qhen manipulatedClear Skies!Jeff
-------- Original message --------From: Michael ***@***.***> Date: 9/22/21  13:22  (GMT-06:00) To: mworion/MountWizzard4 ***@***.***> Cc: PwrHsePro ***@***.***>, Author ***@***.***> Subject: Re: [mworion/MountWizzard4] Help with Drivers and Set Up in MW4 (#188) 
Hi Jeff,
I tried to do some preparation. From what I get, you need help in setting up the BoltWood Weather station in MW4 as well and the RoRo feature (open/close) from dome settings. And perhaps some other hints for MW4. Anything I miss ? If so, we don't need to be there during night (which might be tricky du to the 8h time difference). Sat or sun this weekend (and perhaps the next as well I could try to arrange, ideally around 8pm to 11pm Munich time which should be noon to 3pm your time. What do you think ?
Michel

**Comment by mworion** [comment]
Jeff,
yes. Ideally a temviewer session. Let's see how far we get.
Michel

**Comment by PwrHsePro** [comment]
Looking forward to our meeting!

**Comment by mworion** [comment]
Hi Jeff, 
not really. I saw that you are using a BoltWood weather station. There is a ASCOM driver for getting this data from the file you showed. This driver is downloadable from [https://ascom-standards.org/Downloads/ObservingConditionsDrivers.htm](url) (Boltwood Weather driver). Perhaps you have gotten a newer one, but I tried this and it was able to read a test file. This we need to be installed if you did now have done it anyway. 
See you in about 10 hours! You could contact me directly for the TeamViewer session details: michael@wuertenberger.org
Michel

**Comment by mworion** [comment]
Closing the issue, we stay in contact.
Michel

**Comment by PwrHsePro** [comment]
Thank you!Clear Skies!Jeff
-------- Original message --------From: Michael ***@***.***> Date: 9/26/21  03:29  (GMT-06:00) To: mworion/MountWizzard4 ***@***.***> Cc: PwrHsePro ***@***.***>, Author ***@***.***> Subject: Re: [mworion/MountWizzard4] Help with Drivers and Set Up in MW4 (#188) 
Closing the issue, we stay in contact.
Michel
