### ISSUE TITLE
2.1.0b0

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#189]
Hi Michel,
there is an error in cmd window on start:

![2021-09-22_21h11_37](https://user-images.githubusercontent.com/65772654/134409094-6f93aeb4-a66b-434a-88b0-7b9dfb54d8ce.png)

Also when whirling around the sphere in satellite window MW crashed. This was not repeatable and there is no entry in the log.

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
I keep it, but there is rather any chance to find out what happened.
Michel

Von meinem iPad gesendet

**Comment by Ruediger3** [comment]
Just crashed to desktop again. I will try to find out what is triggering the crash.

**Comment by Ruediger3** [comment]
Here the logfil
[mw4-2021-09-22.log](https://github.com/mworion/MountWizzard4/files/7213375/mw4-2021-09-22.log)
e.

**Comment by mworion** [comment]
Still no clue, but v2.1.0b1 had an additional entry for robustness for OLE. hope this helps.

**Comment by Ruediger3** [comment]
Unfortunately not. Still the same error.

**Comment by mworion** [comment]
Closing this as it will be followed by https://github.com/mworion/MountWizzard4/issues/190
