### ISSUE TITLE
Getting some errors in the Mac terminal

### ISSUE THREAD

**Issue by Raddock** [mworion/MountWizzard4#19]
Image downloads are stalling, even with 4x4 binning. It's giving C++ Errors in the console. Some images do download, but then there are stalls. Here's my latest log and errors.
[Archive.zip](https://github.com/mworion/MountWizzard4/files/4467637/Archive.zip)

**Comment by mworion** [comment]
Hi Andrew,
uploaded 0.150.0. This has change behavior in keeping connection to Indi server. I tested it with ASI178 and did 4000 images without problems, but it has less pixels. 
The C++ Errors did they happen, when you leave MW4 or during runtime as I don't see anything in the log.
Michel

**Comment by Raddock** [comment]
I believe those C++ errors happen when leaving the application. I saw those errors on the version prior to .149. In .149 and now .150 I don't see the errors any more.

**Comment by mworion** [comment]
OK, makes sense, because I changed the shutdown behavior. This should prevent seeing these errors.

**Comment by mworion** [comment]
Hi Andrew,

closing this. If you have with the actual 0.150.5 new issues with entries in the Mac terminal, please open a new one.

Michel
