### ISSUE TITLE
2.1.0b1: Crash on device connect

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#190]
Hi Michel,

when hitting connect, MW crashes to desktop. 
Log attached.

Rüdiger
[mw4-2021-09-22.log](https://github.com/mworion/MountWizzard4/files/7214072/mw4-2021-09-22.log)

**Comment by Ruediger3** [comment]
Downgraded to 2.0.4: works

**Comment by Ruediger3** [comment]
Hi Michel,

sorry I do not understand your comment.
This crash is different. The first crash is in Satellite window when moving the sphere and this is a crash on ASCOM device connect.
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
from MW4 logs, there is nothing I could see in both cases. Issue 189 with the message on the terminal windows leads to win32 integration (which is only used when using ASCOM devices), the second issue 190 is direct related to ASCOM use. Rollback to 2.0.4 fixes the problem in both cases. ASCOM Initializing is the part I tuned performance. Therefore I put the issues together. Did you have some message in the terminal window in issue 190 as well? Perhaps same message? As I do not see the crash when connecting ASCOM devices on windows, could you point to a special driver? There are COM drivers and dotNET driver and COM Servers (Drivers which are built as .EXE). This might help.
Many thanks,
Michel

**Comment by mworion** [comment]
Rüdiger,
2.1.0b2 is online
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

The error in command and crash is fixed. That.
Another error is coming in this and beta before when calculating satellites:
![image](https://user-images.githubusercontent.com/65772654/134554731-6fc155d5-8cc7-4cf9-96ab-ac12ec084e2a.jpeg)

**Comment by Ruediger3** [comment]
Sorry, I have to correct my self. It only worked one. Now MW crashes on ASCOM connect again.

**Comment by Ruediger3** [comment]
Hi Michel,

I got the trouble maker! It ts the connection to skymeter for some reason. Currently it is not plugged in via USB. Even if no device is connected and I want to change it to disabled since it is not connected MW crashes.

Please see here what I mean:
![2021-09-23_19h36_32](https://user-images.githubusercontent.com/65772654/134556630-5a771c0d-bb2f-4d2e-8acc-91afdd57778a.png)

**Comment by mworion** [comment]
OK this helps,
I made some tests, too: There is a leftover message in terminal window. This warning I know, nothing serious, working to eliminate this. 
To the ASCOM.OCH.HUB: if I run ObservingCondistion Hub Tester from ASCOM suite (without running MW4), the tester crashes as well. Could you check this please ?
Michel

**Comment by Ruediger3** [comment]
No problem there (see below). I also use it with NINA. Also no issue. Only MW reacts allergic.
![2021-09-23_20h12_42](https://user-images.githubusercontent.com/65772654/134561411-8e59a974-180d-40f6-a7e8-952c35922ce8.png)

**Comment by mworion** [comment]
Reinstalled ASCOM, now I see the Observation Conditions Hub. An I get MW4 to crash. So I could work now.

**Comment by mworion** [comment]
Hi Rüdiger,
2.1.0b3 should solve the issue
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
i can confirm. Its fixed. Many thanks.
Rüdiger
