### ISSUE TITLE
Slew path in Southern Emisphere

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard4#192]
hi Micheal,

not even sure if this is a bug. When I generate model points for a golden spiral, the slew path always  crosses the meridian from one side to another when going from one point to the next. And it loose a lot of time slewing.
I remember that in the Northern Emisphere these path  were optimized, potentially doing W and then E.
Attached a picture of the slew path I get in the Southern.
![modelbuild](https://user-images.githubusercontent.com/38842860/135723702-38a4e540-c627-46e0-94df-d5b5dd3d8778.png)

Best,
Ferrante

PS: I've two more question but will use a different ticket.

**Comment by mworion** [comment]
Hi Ferrante,
I checked V2 and it does not behave different between N or S hemisphere. With default sorting you get the image you show:

![Bildschirmfoto 2021-10-02 um 19 08 44](https://user-images.githubusercontent.com/6632980/135726066-356a404a-3617-4742-986e-9457cebf5000.png)

with sorting N/S you get is split between both piersides:

![Bildschirmfoto 2021-10-02 um 19 08 52](https://user-images.githubusercontent.com/6632980/135726077-0ce29f42-e416-467d-aefa-4af5c50fc151.png)

Michel

**Comment by fenriques** [comment]
thanks Micheal. I was not aware of this feature, it helps a lot reducing time for modelling.
