### ISSUE TITLE
'Disable dual axis tracking during model build' . Default value

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard4#193]
When installing MW4, the 'disable dual axis tracking during model build' is checked by default. 
10Micron reccomends to leave dual axis tracking when building a model. Maybe this option should be unchecked by default.

Ferrante

**Comment by mworion** [comment]
Hi Ferrante, 
I removed this option in version 2. It stays as you set it. Only for polar align it is switch off be firmware.
Michel

**Comment by fenriques** [comment]
wow. I was far behind, will update to last version.
Thanks
