### ISSUE TITLE
Single axis tracking during model build causes infinite slewing loop. Not able to reproduce it.

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard4#194]
When building a model with single axis tracking, after slewing to a new point of the model, the mount doesn't engage tracking anymore.  It stops slewing but doesn't beep and the status is 'slewing'.
This never happens when dual axis is used.

This is not happening for all points, so it's not a real issue. But maybe there's a reason for that.

Thanks
Ferrante

**Comment by mworion** [comment]
Hi Ferrante,
could you post the log file? Otherwise it's hard to find the problem.
Michel

**Comment by fenriques** [comment]
hi Michael,
here's the log from last night session, Used both single and dual axis tracking so you'll find them mixed up in the log file.
As I was using and old version, could be solved in a more recent one.
Ferrante

[mw4-2021-10-01.log](https://github.com/mworion/MountWizzard4/files/7272041/mw4-2021-10-01.log)

**Comment by mworion** [comment]
Hi Ferrante,
thanks for the log. 
What I see many connection issues with INDI as well with the mount -> bad ethernet connection or wireless connection ?
There is an issue which is not related to the modeling stop, which is in actual version solved.
Still I hardly could see any relation between Dual Axis Tracking and the problem. Might that others influence this. So I would recommend to update to v2.
Michel

**Comment by fenriques** [comment]
ok, thanks. I already updated to v2. 
I will try to reproduce the issue (if any) in the next days.

ferrante
