### ISSUE TITLE
MW4 crashes after an image capture

### ISSUE THREAD

**Issue by ghost** [mworion/MountWizzard4#195]
- MW4 versions : 2.0.5 and 2.1.0b5 (both show the defect)
- CPU : Intel(R) Core(TM) i3-8130U CPU (64 bits)
- OS flavour : Ubuntu 20.04.3 LTS (64 bits), running the Mate desktop environment.
- Devices : a GM2000 mount and a ZWO ASI 120 MM camera, both connected through a remote indiserver.
- Scenario : After MW4 recognises the devices (the Mount, Camera and Solver buttons are green), I open the Image window to capture a 5 s exposure image. The capture goes well, the image frame is displayed inside the window, and the various fields (left of that window) are correctly fullfilled. Then, as soon as I clicked on any MW4 window (Image, Main, Message or whatever), MW4 crashes by closing immediately all MW4 windows.
If I re-run MW4, no more image capture is possible unless I restart the indi camera server.
This behaviour is fully reproducible within my environment.
Note : If I click inside opened MW4 window prior the image is captured, I do not see any issue. From my point of view, the display of the captured image creates the crash conditions.
In the /var/log/kern.log, I see a SegFault trace in a QT5 library that may be related.
Attached are the MW4 log file (trace level) and the kern.log trace.
[2021-10-11T15-05_kern.log](https://github.com/mworion/MountWizzard4/files/7323750/2021-10-11T15-05_kern.log)
[2021-10-11T15-05_Trace_MW4.log](https://github.com/mworion/MountWizzard4/files/7323751/2021-10-11T15-05_Trace_MW4.log)

**Comment by mworion** [comment]
Hi, 
thanks for reporting, I don’t see that on Mac or windows. Would you mind to test v2.0.2 and v2.0.3 as I think, the first one should work an the step to 2.0.3 changed something. If you could confirm this, it would help a lot.
Michel 

Von meinem iPad gesendet

**Comment by jmichelet** [comment]
Hi Michel,
Thank you for your response.
As you have predicted, v2.0.2 works correctly, while 2.0.3 crashes. In the very same conditions as previously, of course.
So for the time being, I will obviously keep on running the v2.0.2 flavour.
Jacques

**Comment by mworion** [comment]
Hi Jacques,
v2.0.6 and v2.1.0b6 should be OK now.
Michel
