### ISSUE TITLE
New color schemes

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#198]
Upgraded to .13
Sorry to report that in the Light Day theme the red grid in the Imaging window is not shown when selected.
When I change color scheme the message window is cleared.
Going back to Main Theme still messages are cleared.

Graphically looking good.

Arie

**Comment by mworion** [comment]
Arie thanks for looking onto it.
I tried now to improve the visibility (grid was still there...)
Regarding the Message window: When changing the color it will be cleared (as I could not change the text color for existing text). Other possibility: keep it in the old color scheme.
Any opinion ?
Michel

**Comment by ACMBakx** [comment]
I took a better look at the imaging window in Light Day.
Indeed the grid is still there, but in Image Grey (my default) it is black against a black background. :-(
When I select one of your rainbow/candy colors for the image it becomes visible indeed.
Can't you keep the grid and cross hair just red in all schemes?

I think a lot of mobile users will appreciate the Red Night Theme.
Is it possible to show the HC window with Red characters?
Those are still Blue and White, whereas everything else is turned Red.


Clearing the message window is not a big issue, as long as the user is aware of it.
It does fill again with new lines as MW4 continues.

Arie

**Comment by mworion** [comment]
Arie,
What do you mean with HC?

**Comment by ACMBakx** [comment]
Sorry,
The Hand Controller

**Comment by ACMBakx** [comment]
![MW4RedScreen](https://user-images.githubusercontent.com/59890758/139598393-432d5bed-53f1-4a1f-8398-dd6b43c1c50b.JPG)

**Comment by ACMBakx** [comment]
![MW4LightDayScreen](https://user-images.githubusercontent.com/59890758/139598524-64ddb181-8dda-498a-914e-83d18b31f7ee.JPG)

**Comment by mworion** [comment]
Hi Arie,
I had to rewrite the keypad complety as I used the original webpage from the mount. In v2.1.0b14 I have an implementation. Please check also the functions of the keypad. Good point about the new implementation is that also the RPi3/4 users will have a keypad available.
Michel

**Comment by ACMBakx** [comment]
Tested it.
Seems to be working OK. Virtual Keypad also OK.
Including the dome showing in the simulator.

MW4 is getting better and more inclusive everytime
Arie

**Comment by mworion** [comment]
Thanks for testing, closing the issue
