### ISSUE TITLE
Random crashes when leaving MW4 alone during image

### ISSUE THREAD

**Issue by Raddock** [mworion/MountWizzard4#20]
Not sure what's causing this, but here's the latest log if it shows something. During an image session, while MW4 is regularly updating environmental data, it randomly crashes. Not sure what's causing this, as usually I'm away from the computer and notice it's crashed when I come back.

[mw4-2020-04-14.log.zip](https://github.com/mworion/MountWizzard4/files/4479083/mw4-2020-04-14.log.zip)

**Comment by mworion** [comment]
Hi Andrew,

from the log I see:
- MW4 started 2 times
- In both cases MW4 was closed with save/quit
- I do not see in the log a broken sequence.
- I do see a reconnect error to the camera -> tried a fix with 0.150.1
- I see one connection error on the physical side (IP connection) which say's the the host closed the connection (means the Indi server).

I try to keep MW4 now open for many hours with an ASI178 connected, we'll see.

Michel

**Comment by Raddock** [comment]
Strange, these crashes happen about once or twice a night. But having said that, I managed to run all night after the above crash and there were no more crashes. However I did see a message in the log about not being able to get data from the camera, but then it continued showing captured images. Anyhow, I thought I would attach another log so you could see the message. It would be towards the end of the log. Thanks for all your help Michel.

[mw4-2020-04-14.log 2.zip](https://github.com/mworion/MountWizzard4/files/4481190/mw4-2020-04-14.log.2.zip)

**Comment by Raddock** [comment]
So, it's strange on my end. I have all the equipment wired right now. But my iMac Pro which I run KStars and MW4 on has both ethernet and WIFI. They connect simultaneously. I don't know how the computer determines which connections to go over WIFI or ethernet, but when I run a program like LAN scan, it shows some connections over WIFI and some over ethernet. I might just turn off WIFI on the computer and see if I can have everything going through ethernet.

**Comment by mworion** [comment]
I have a Mac Pro and as soon as I go via LAN I disable the WiFi. Never had good results letting the Mac deciding what to do.

**Comment by Raddock** [comment]
I ran over LAN during the last session. I think this was 0.150.2. It was a perfect run with no issues or disconnects. I didn't see any devices disconnect in the status window. I'll have another clear night next week and will try the latest version. I have not seen another crash, and woke up in the morning to MW4 still running. So I'll close this issue.
