### ISSUE TITLE
cannot upload earth rotation data

### ISSUE THREAD

**Issue by vich4man** [mworion/MountWizzard4#205]
**Describe the bug**
I have problems with uploading earth rotation data to the mount via MW4.
When I try the upload I get the error message "Not running windows - upload not possible"

Needless to say that I am running Windows, 10u updater for FW V3.0.8 is installed.
I have this problem with both mounts of our observatory (GM3000 and GM4000), and I tried it with three different PCs, all do not work.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
See logfile below

[mw4-2021-12-03.log](https://github.com/mworion/MountWizzard4/files/7652230/mw4-2021-12-03.log)

**Comment by mworion** [comment]
Hi Stefan,
this was a tricky one on my side. It's related to the python comparison. And the message is misleading. It should have said: "no automation installed". 

v2.1.5 will fix this behavior.

Michel
