### ISSUE TITLE
MW4 v2.1.5 Problems uploading DeltaT and Satellite resp.

### ISSUE THREAD

**Issue by Attalar** [mworion/MountWizzard4#206]
Hi Michel,

I have found gitHub. We may continue here :-)

I have the same problem as described by Stefan (vichman).

[mw4-2021-12-08.log](https://github.com/mworion/MountWizzard4/files/7675708/mw4-2021-12-08.log)
![Screenshot_1](https://user-images.githubusercontent.com/95751837/145202669-f46c314a-e356-4db5-ae4b-fd71b39dc172.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/95751837/145202071-8f2718d1-54b1-47c3-9d24-ff435639d704.jpg)

**Comment by mworion** [comment]
Hi Stefan, Michael,

this was a hard one and I only found it because both of you had exactly the same issue: it is related to the german language setting of your windows. I work in English (as most of the other users) and I did not see it until I switched. So I will build a beta 2.1.6b0 for this.

@Any other English native user (having set windows to English) and using python 64bit: Could someone check this beta as well If I broke the English part ? So far in my setup switched back to English MW4 with the bugfix is still working, but I cannot test 100%.

Michel

**Comment by Attalar** [comment]
OMG - I have not thought about that kind of problem at all. THX Michel for ur great work!!!

**Comment by Attalar** [comment]
I updated to version 2.1.6b0 and tried it out.
The updater starts but when it chooses the finals.dat it stops working (this time without creating a new subfolder).
![Screenshot_1](https://user-images.githubusercontent.com/95751837/145356820-4441995b-7879-42a9-98da-32350d6f940b.jpg)


I then tried to upload comets and there also is the same stoppage but before choosing a file. 
Also the updater does not accept the downloaded comets-file as it seems to be the wrong file-type ?

![Screenshot_2](https://user-images.githubusercontent.com/95751837/145357376-d8ee0d4d-c82f-4f28-b4c5-cbf00c020a1e.jpg)


Thrid I tried to upload space stations data. Here the same. The updater stops working also before choosing the downloaded file. (That file can be uploaded manually but not automatically).

![Screenshot_3](https://user-images.githubusercontent.com/95751837/145357767-fe23e260-f008-4f30-9783-91690f462c0b.jpg)

Here is the log-file:
[mw4-2021-12-09.log](https://github.com/mworion/MountWizzard4/files/7683277/mw4-2021-12-09.log)

Sorry to make you work so much on this... :-(

**Comment by mworion** [comment]
Hi Michael,
closing without action. I worked through. To solve this problem correctly I would have to check all languages and their internal ID for buttons. This is a no go for me. The solution is easy but hard: set windows language to English.
Sorry to say. As soon as the automation library I use could handle this, I will reopen it and work with it.
Michel

**Comment by Ruediger3** [comment]
Hello Michel,

we have to be careful only to set the language to English, but to keep Time, Date, Numbers format and Currency set to German, because when changing it to US I experiences other software to fail. Especially when working with CSV files or decimal numbers. Also time format is very critical. So switching the language, but only the language, is possible, 

Cheers
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
I agree. To be honest I only change the language and keep all other topics to German in my setups. 
Michel

**Comment by Ruediger3** [comment]
A workaround could be to jump to the appropriate control / field by sending a specific amount of "Tab" keys. The number is language independent. It is only defined by the control order. This could be a fall back.

**Comment by mworion** [comment]
I though about this, but if you recompile the EXE, you could choose the order of tabs. If Somebody change this, I searching for a bug again. Not stable enough.

**Comment by Attalar** [comment]
Hi Michel,

I totally understand that you won't fix this when the solution is that simple.
I switched the language (only) to English and tried it again. This time the freeze comes a little bit later while trying to load the tai-utc.dat. But it still freezes.

![Screenshot_1](https://user-images.githubusercontent.com/95751837/145774083-4e44c9fa-bd78-415c-a407-7cfca3bda2c0.jpg)

Log-file:
[mw4-2021-12-13.log](https://github.com/mworion/MountWizzard4/files/7701950/mw4-2021-12-13.log)

**Comment by mworion** [comment]
Hi Michael,
yes there is still an issue for whatever reason. I build during the weekend 4 additional test instances (win32 and win64 both with QCI Updater and Tenmicron_v2 updater). Testing in these instances successful hopefully give another beta for testing the next days.
Michel

**Comment by Attalar** [comment]
Hi Michel.

I am really sorry that I bother you with this :-(
I really appreciate your efforts

**Comment by mworion** [comment]
All good. You're welcome. Might take some time...

**Comment by Attalar** [comment]
Hi Michel,

I updated to 2.1.7b0 and tried it out but it still freezes while trying to open the tai-utc.dat. :(
Language turned to English (U.S.)

Sorry :(

![Screenshot_1](https://user-images.githubusercontent.com/95751837/146145564-abfef9fa-da45-44f9-a688-7f91b441b80e.jpg)
[mw4-2021-12-15.log](https://github.com/mworion/MountWizzard4/files/7717392/mw4-2021-12-15.log)

**Comment by mworion** [comment]
OK, sorry to hear that. So as I see the window of the updater shows another set of headline texts. My guess is that we have two versions of tenmicron_v2.exe. The one which came with 2.16.x firmware versions and the one with 3.x firmware.
I'll check this tonight.

**Comment by Attalar** [comment]
in the 2.16.13 version that I run the updater is named "GmQClv2.exe". I copied the file and renamed it to tenmicron_v2.exe

**Comment by mworion** [comment]
OK, then please go back to the old original name. This will probably fix the issue.

**Comment by Attalar** [comment]
Yes!!! That was it!!! Problem solved at least for me :-)

**Comment by mworion** [comment]
Great, closing your point and see if Stefan is also happy with it. Otherwise opening for him a new one as it might be a different problem.

**Comment by vich4man** [comment]
Hi Michel,

as discussed in the 10u forum, it does not work for me, unfortunately, when running German language.
In English everything is fine.

Here the log file when it failed (German language).
[mw4-2021-12-16.log](https://github.com/mworion/MountWizzard4/files/7735558/mw4-2021-12-16.log)
Thanks for looking into it.

Stefan
