### ISSUE TITLE
Kmtronic Relay Log windows

### ISSUE THREAD

**Issue by mducatmisathodotcom** [mworion/MountWizzard4#207]
Hello Michel,
Since 2.1 I got a little problem with Kmtronic Relay.
As soon the kmtronic is connected, the log windows fills up with messages about the successful relay connection...
Merci...

Michel-d.

[mw4-2021-12-13.log](https://github.com/mworion/MountWizzard4/files/7702601/mw4-2021-12-13.log)
<img width="804" alt="Capture d’écran 2021-12-13 à 10 32 11" src="https://user-images.githubusercontent.com/96048732/145787293-640f7fc1-c558-4c09-9507-9951cf070fbd.png">
<img width="800" alt="Capture d’écran 2021-12-13 à 10 32 19" src="https://user-images.githubusercontent.com/96048732/145787350-c6517d11-d6e4-4e6b-9e58-9b263ef299ba.png">

**Comment by mworion** [comment]
Hi Michel,
I will hopefully release a beta 2.1.7b0 tonight, where you could test the KmTronic relay working correctly. Please check the connection status and connect / disconnect it also on it's connector to see if the status is correct.
Michel

**Comment by mworion** [comment]
2.1.7b0 is online now

**Comment by mducatmisathodotcom** [comment]
Hello Michel,
I just test 2.1.7b0 and now, the KmTronic relay is working fine: on, off, pulse ---> OK and no fill up messages...
Thanks Michel !
Michel-d

**Comment by mducatmisathodotcom** [comment]
Hello Michel,
I just test 2.1.7b0 and now, the KmTronic relay is working fine: on, off, pulse ---> OK and no fill up messages...
Thanks Michel !
Michel-d

**Comment by mworion** [comment]
Great, closing the issue
