### ISSUE TITLE
MW4 - Virtual KeyPad does not connect

### ISSUE THREAD

**Issue by mhambuch** [mworion/MountWizzard4#21]
Hi, i have installed MW4 on a W10 environment with Alpaca. The App works fine with the only exception of the virtual keypad that keeps trying to connect. The IP is correct 10.0.0.197 but it uses port 8000 and i dont know where this comes from. The virtual keypad is not defined as device in MW4 nor in on the ASCOM remote server.

Get this error in MW4

 js: WebSocket connection to 'ws://10.0.0.197:8000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED 

This is the original 10Micron virtual keypad config 

![image](https://user-images.githubusercontent.com/63575440/80001336-88ae5300-84be-11ea-8c90-e6b3754c6c35.png)

**Comment by mworion** [comment]
Marc,

Two points: You have to enable web services in your physical or the 10micron virtual keypad (under settings / network). A good test ist to use a Webbrowser and enter the ip of your mount in the address selector. If you see the keypad, then your are done. 

I discovered the situation even still it is enabled if you have the physical handed connected (I have a GM1000), you don’t get connection on the browser (and the MW4) side.

Michel

**Comment by mhambuch** [comment]
Hi Michel, that was it, thx. I have another question, other subject, on the mount tab there is a field "DeltaT expires", in my case framed in red as expired since 24.11.2019. I dont understand this, i have a gps (MGbox V2) connected physically to the mount control box. From the Mgbox i get gps, time, refraction data (according to my understanding...) So what does this expiration mean and what should i do ? Under local data on the keypad i have "use gps data" set to on, "boot gps syn" also set to On and GPS_UTC diff shows 18s

**Comment by mworion** [comment]
Hi Marc,

DeltaT has nothing to do with actual time. It’s a table which contains a list of DeltaT’s for UTC to TAI time, but more important earth rotation data. This alters over time and will be calculated and offered for download from different source. With the 10micron updater you could program it to the mount. This has to be done about once a year. It’s not critical if you are overtime, but astronomical calculations in the mount become larger errors over time.

BTW: if you still have MW3 installed, the is an automation routine build in to update this values. I cannot do this va commands, so MW3 calls the 10micron updater for you and does all the stuff.

Michel

**Comment by mhambuch** [comment]
Many thanks for the explanations
