### ISSUE TITLE
Beta 2.2.b2: NINA as camera connect fails

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#210]
Hi Michel,

I have tried to connect NINA but it fails. 
Log attached, 

Cheers
Rüdiger

[mw4-2022-01-09.zip](https://github.com/mworion/MountWizzard4/files/7835783/mw4-2022-01-09.zip)

![2022-01-09_20h32_59](https://user-images.githubusercontent.com/65772654/148698020-f7d410cf-81da-46cc-99cf-224fed34f962.png)

**Comment by Ruediger3** [comment]
Also tested on a second device and same result. MW4 cannot connect NINA camera.

**Comment by Ruediger3** [comment]
Hi Michel,

root cause identified. You have to enable the server in NINA, which is not enabled by default.
![2022-01-09_22h01_38](https://user-images.githubusercontent.com/65772654/148700895-c40580ab-7552-445d-9813-2e64f841a629.png)

**Comment by Ruediger3** [comment]
Maybe you can add this info to the documentation.

Cheers
Rüdiger

**Comment by mworion** [comment]
Good point, I used beta and had this setting on
