### ISSUE TITLE
Beta: 2.2.0b2 erratic errormessage when setting gain value with NINA controlled camera

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#215]
Hello Michel,
I cannot set gain, when the camera is connected as NINA controlled. I guess I have to manage that via NINA (as default gain), but the error message is confusing. Any way to control it via MW? This might be a trap, when you rely on the settings made in MW e.g. having set gain = 100, but actually shooting in gain = 0 since this is the default in NINA.
Same with offset.

Rüdiger

![2022-01-11_20h50_10](https://user-images.githubusercontent.com/65772654/149012014-69ec3df6-b007-4f27-8016-3bf66eae8d82.png)

**Comment by Ruediger3** [comment]
I have tried several ideas, but you can only change offset and gain when disconnecting the camera in NINA and reconnect it with different default settings, but I have not found any way to change the settings without interruption. This is problematic, since you interrupt the cooling process. Is there any way to send required gain and offset from MW?

Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
thanks for the feedback. During the upcoming weekend I try to disable all UI elements, which are useless during App controlled and check the implemented API‘s.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
this makes definitely sense, but how to control gain and offset? 

Rüdiger

**Comment by mworion** [comment]
Rüdiger,

the way for MW4 is: If device is NINA controlled (camera), you only could change Exposure Time and Binning. These are the minimum parameters for NINA API to work. No property else will be read or set nor does the connection state be changed from MW4 side. So everything set in NINA should stay. I checked this now with the simulator and it does in the next beta.  In this case I remove all GUI elements nor be there. 

If MW4 controlled the full API (which is not that much more) including the connection state is handled through MW4. I will look, if Gain and Offset could be changed through API, a first try failed.

Michel

**Comment by Ruediger3** [comment]
Thanks for the update.

**Comment by mworion** [comment]
Rüdiger,
the actual beta should be ready for having the topics solved. The NINA only as well as the MW4 controlled setup. 
Actually NINA has a bug on the API as it does not change cooler temp when set (SGPro does).
Michel

**Comment by mworion** [comment]
Hi Rüdiger, anything new with the latest beta ?
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
sorry some delay. I had to fix the the update problem first (clean, updateBeta script).
Now the the fields are greyed out. So the initial problem is fixed.

But I have to admit, I am still trying to figure out the advantage of using the cam connected via NINA, since I cannot change any setting like gain as long as it is connected in NINA. If I want to change it, I have to disconnect the camera in NINA too. Hence it is less complicated to connect it directly in MW4. Maybe I am overlooking something, but where is the advantage? 

Cheers
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
if you use NINA controlled device, you could work in NINA as you want. And you have to setup your settings there as well. MW4 only sends commands to take an image. The only parameters are bin, exptime, subframe. No connect or disconnect through MW4.
if you choose a device through NINA in MW4, MW4 is handling connection and all settings which could be handled remotely. This is in case of NINA very limited (GAIN is possible). SGPro offers more settings to be influence.

Other advantages: NINA might use a native driver, which MW4 couldn't. You could prepare your imaging setup direct for later and focus. MW4 will not interfere in the NINA controlled mode.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,
here this is not working as you describe it. The settings in NINA for taking an image are not used when MW4 triggers a shot. Whenever MW4 triggers the shot, NINA uses the default connection values, but not the currently set parameters. 
e.g. to change gain you have to disconnect the cam, change default value and reconnect the cam. Ba that you interrupt the cooling. 

The driver point is valid.

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Also I have just done a dry run test with the ASCOM camera simulator and it failed. 
I can take the image in NINA but when I try to expose from MW it stays infinitely at "Expose 1".

Log attached....

Rüdiger



![2022-01-22_21h26_47](https://user-images.githubusercontent.com/65772654/150654350-85b569c0-24b6-434c-bf31-f22036168f14.png)
![2022-01-22_21h27_11](https://user-images.githubusercontent.com/65772654/150654364-6bbff2eb-820f-4226-b1ac-24b55e8b259d.png)
[mw4-2022-01-22.log](https://github.com/mworion/MountWizzard4/files/7919231/mw4-2022-01-22.log)

**Comment by mworion** [comment]
Gotcha,
beta v2.2.0b9 will fix this.
Michel

**Comment by Ruediger3** [comment]
Installed, Now the image process finishes, but no image shown. blank black screen.

![2022-01-22_22h17_10](https://user-images.githubusercontent.com/65772654/150655736-7fc0a3ad-de57-4afc-afa2-2081ac94c272.png)
![2022-01-22_22h17_57](https://user-images.githubusercontent.com/65772654/150655763-aea55b99-5f7c-4371-b0bd-b620f7d8b657.png)

**Comment by Ruediger3** [comment]
Hi Michel,
I have restarted MW and took again a shot and now it is displayed. Nothing changed. Looks like a hick-up.
I will continue testing...

**Comment by Ruediger3** [comment]
Hi Michel,

found following behavior:

1. The gain set in "Equipment" -> "Camera" -> "Camera Settings" -> "Default Gain" is taken
2. This can be switched without disconnecting.

I think it is a good idea to put it in the docu. Otherwise people try to set the gain in image tab which will fail.

Rüdiger


![2022-01-22_22h42_23](https://user-images.githubusercontent.com/65772654/150656459-9303a14c-40e3-46be-b9ec-bac7d3255cc5.png)

**Comment by mworion** [comment]
Rüdiger good point, I will add this.
Was it in the remote controlled mode? I ask, because GAIN setting should be able to set in MW4 with NINA if you select the device MW4 (not remote controlled)
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

this was in NINA controlled mode. I have just tested MW controlled mode where you can set the Gain. But again the Gain from NINA is taken and not that from MW. Please see screen shot.

More over i have Identified another issue: When selecting the Simulator MW throws an error, since NINA does not connect fast enough. It takes up to 15s to fire up the ASCOM Simulator due to the large resolution. After 15s MW gets the connection.


![2022-01-23_14h52_41](https://user-images.githubusercontent.com/65772654/150681919-b73ba067-f7b8-456a-ae55-6d72f80c0d96.png)

[mw4-2022-01-23.log](https://github.com/mworion/MountWizzard4/files/7920617/mw4-2022-01-23.log)

**Comment by mworion** [comment]
Ok I increase the timeout as it's limited to 10s now.
For the gain setting, this might be an issue on NINA's interface. There are some more as well.
Michel

**Comment by Ruediger3** [comment]
Ok, do you get in touch with NINA guys?
If this is a bug, maybe we should open a new issue to follow up?

Rüdiger

**Comment by mworion** [comment]
Actually I talked Stefan. The remote interface is a copy (not really) of the SGPro REST API. He did not implement all devices (only camera) nor all items for the camera. So setting gain will be not possible, as the REST API does not deliver the list auf possible gain settings and does not accept the parameter when doing image.
He is open to accept work on a plugin, which enables NINA to access many remote commands, but this is still open.
Michel

So next beta (next minutes) reflects checking if gain values are delivered (showing them) and if not removing the input field as well.
Michel

**Comment by Ruediger3** [comment]
Ok, but this actually means that both modes are more or less identical. You have to control the camera from NINA. 
Rüdiger

**Comment by mworion** [comment]
That's basically the result. In SGPro you could do more things and hopefully NINA implements the REST Pluging to offer more functions.
