### ISSUE TITLE
Plate Solving ASCAP

### ISSUE THREAD

**Issue by mhambuch** [mworion/MountWizzard4#22]
Hi Michel, I could test MW4 last night, very good!

I have one issue with plate solving that systematically fails.

Here what I see. This has been done this morning; image window; open FITS from last night and click on solve. I see a little pop up screen for less than one second and then get the error message back. CCD and mount are not connected, i guess this is fine.

![img](https://user-images.githubusercontent.com/63575440/80179044-f746fa00-85ff-11ea-8ddf-098d07d89d63.gif)

Within ASCAP it always defaults the Field Height Image Field with 0,48degrees. That then fails as the correct value is 0,95. When  I change in ASCAP to 0,95 and start the solving in ASCAP it works. When i set it to auto and leave ASCAP, go to MW4 load the FITS and ask to solve i have the error message. 

![img2](https://user-images.githubusercontent.com/63575440/80179647-4fcac700-8601-11ea-9fa8-6aa7dbac78f1.gif)

**Comment by mhambuch** [comment]
![IMG3](https://user-images.githubusercontent.com/63575440/80180063-2cece280-8602-11ea-9f58-9a14e6e458e1.gif)

**Comment by mhambuch** [comment]
wrong button... closed the issue while editing it ....

**Comment by mhambuch** [comment]
If you need the FITS i can provide it I didnt find a way to attach it it only allow image files

**Comment by mhambuch** [comment]
pixel size is 2,4 and i was binning 2x2

**Comment by mworion** [comment]
FITS file would be good. If FITS does not work, just ZIP it and try it again. Will have a look this evening.

Michel

**Comment by mhambuch** [comment]
Hi Michel, here is the fits, thanks a lot


[2020-04-23-19-53-23-exposure.zip](https://github.com/mworion/MountWizzard4/files/4528412/2020-04-23-19-53-23-exposure.zip)

**Comment by mworion** [comment]
Thanks Marc,

found the issue. I missed the binning parameter in size calculation. The solving used the wrong scale hint -> no solution. You have to make a new image to test it.

Michel

**Comment by mhambuch** [comment]
Thanks Michael,

Just for my understanding, i now run the mw4 update script to get the latest version with the bug fix or do you publish new releases  regularly with several improvements/bux fixes?

Envoyé de mon iPad

**Comment by mworion** [comment]
Marc, 

within MW4 under settings/misc there is an internal updater. If you enable the online connection (just above in case you did not already do it) there should be the hint in Message window that there is a new version available. Just press install, wait for finish you could watch it in the message window and restart MW4. Then it's done. Normally you don't need the scripts for updating, it's just for fallback.

Michel

**Comment by mworion** [comment]
Marc please use 0.150.8 as there might be another issue introduce with the changes.

**Comment by mhambuch** [comment]
Thanks for having notified
-------- Message d'origine --------De : Michael <notifications@github.com> Date : 25/04/2020  12:28  (GMT+01:00) À : mworion/MountWizzard4 <MountWizzard4@noreply.github.com> Cc : mhambuch <mhambuch@laposte.net>, State change <state_change@noreply.github.com> Objet : Re: [mworion/MountWizzard4] Plate Solving ASCAP (#22) 
Marc please use 0.150.8 as there might be another issue introduce with the changes.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mworion/MountWizzard4/issues/22#issuecomment-619357289",
"url": "https://github.com/mworion/MountWizzard4/issues/22#issuecomment-619357289",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
