### ISSUE TITLE
Goto RA/DEC no function

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#220]
Hi Michel,

for me goto RA/DEC is not working anymore. It has no function. If I enter the coords in VHC it works. No message in the message window.

Log attached.

Rüdiger

![2022-02-09_20h02_07](https://user-images.githubusercontent.com/65772654/153272152-cc359a6a-65d3-49a9-bf25-618deb715f87.png)
[mw4-2022-02-09.log](https://github.com/mworion/MountWizzard4/files/8035512/mw4-2022-02-09.log)

**Comment by mworion** [comment]
Sorry, changed the format with ':' and did not accept them afterwards.
Is fixed in next beta.

**Comment by Ruediger3** [comment]
Hi Michel,
Goto Alt/AZ is also not working :(

Rüdiger


![2022-02-13_12h07_41](https://user-images.githubusercontent.com/65772654/153750422-78bc5ce3-92b6-4184-9aa4-9133bbdb79df.png)
![2022-02-13_12h08_49](https://user-images.githubusercontent.com/65772654/153750423-10d88d4b-5d80-4244-8c23-fd88a307a42c.png)
![2022-02-13_12h08_55](https://user-images.githubusercontent.com/65772654/153750424-7d211f1f-bfba-4d19-b65f-ece99df36b0c.png)
(

**Comment by mworion** [comment]
Rüdiger,
the text is a fault. there should be the values in it. 
I tested Az 90 and Alt 5 and it worked. I fixed the text and it should work now.
If you set the value exact to the horizon limit, the command protocol does not accept the target of the same value.
Michel
fixed in next beta

**Comment by Ruediger3** [comment]
Hello Michel,

the limit is set to -3. So limit is not the issue. It was also working when entering it into virtual key pad (VKP). The mount was slewing to 90/5. But it not from MW.

Rüdiger


![2022-02-13_20h56_01](https://user-images.githubusercontent.com/65772654/153772413-f2184929-4757-4422-9686-5531ccd415dd.png)
