### ISSUE TITLE
Raspi 64 bit - Binning/Gain/Offset issues

### ISSUE THREAD

**Issue by mads0100** [mworion/MountWizzard4#221]
When I change the binning in MW4, it updates the INDI driver, but doesn't update the info for solving... result is failures.

The offset/gain options are greyed out and do not allow you to change those settings.

**Comment by mworion** [comment]
Hi Chris, as always: could you provide a log? Ideally in trace mode.
The Gain / Offset options are greyed out if the driver does not provide some data for it to choose from. Unfortunately every driver does is different. 
Binning is strange I have to look into it.
Michel

**Comment by mworion** [comment]
Hi Chris,
anything about a log?
I checked this with an INDI setup and ASTAP. Solving performance is directly linked to search radius.
I tested ASTAP on Debian [https://www.hnsky.org/astap.htm](url) (Download the star database as well)
I did not have any performance issues (despite the fact that a full blown MAC has more performance than a RPI4)

Testing with the INDI simulator, Gain and Offset is available. I could check if the driver of your cam supports this via INDI remote if I could check the MW4 log (trace mode). See video on RPI4 with INDI CCD Simulator (6000x8000 pixel) and ASTAP bin 1 and bin 2
Michel

[https://www.dropbox.com/s/c55pb9cg22sosrb/Bildschirmaufnahme%202022-02-12%20um%2015.07.31.mov?dl=0](url)

**Comment by mads0100** [comment]
I figured out what was wrong. ASTAP CLI isn’t quite ready for 64 but based on the threads on their forums. But, the installer for the full package fixed my issues. 

I have a zwo2600mc. I’ll give binning a try now that the solver is working again. 

Sent from my iPhone

On Feb 12, 2022, at 08:11, Michael ***@***.***> wrote:

﻿
Hi Chris,
anything about a log?
I checked this with an INDI setup and ASTAP. Solving performance is directly linked to search radius.
I tested ASTAP on Debian https://www.hnsky.org/astap.htm (Download the star database as well)
I did not have any performance issues (despite the fact that a full blown MAC has more performance than a RPI4)

Testing with the INDI simulator, Gain and Offset is available. I could check if the driver of your cam supports this via INDI remote if I could check the MW4 log (trace mode). See video on RPI4 with INDI CCD Simulator (6000x8000 pixel) and ASTAP bin 1 and bin 2
Michel

https://www.dropbox.com/s/c55pb9cg22sosrb/Bildschirmaufnahme%202022-02-12%20um%2015.07.31.mov?dl=0

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mads0100** [comment]
Gain and offset are - for me and I can’t type in those boxes. 

Sent from my iPhone

On Feb 12, 2022, at 08:26, Chris Madson ***@***.***> wrote:

﻿I figured out what was wrong. ASTAP CLI isn’t quite ready for 64 but based on the threads on their forums. But, the installer for the full package fixed my issues. 

I have a zwo2600mc. I’ll give binning a try now that the solver is working again. 

Sent from my iPhone

On Feb 12, 2022, at 08:11, Michael ***@***.***> wrote:

﻿
Hi Chris,
anything about a log?
I checked this with an INDI setup and ASTAP. Solving performance is directly linked to search radius.
I tested ASTAP on Debian https://www.hnsky.org/astap.htm (Download the star database as well)
I did not have any performance issues (despite the fact that a full blown MAC has more performance than a RPI4)

Testing with the INDI simulator, Gain and Offset is available. I could check if the driver of your cam supports this via INDI remote if I could check the MW4 log (trace mode). See video on RPI4 with INDI CCD Simulator (6000x8000 pixel) and ASTAP bin 1 and bin 2
Michel

https://www.dropbox.com/s/c55pb9cg22sosrb/Bildschirmaufnahme%202022-02-12%20um%2015.07.31.mov?dl=0

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mads0100** [comment]
I will. 

Sent from my iPhone

On Feb 12, 2022, at 08:40, Michael ***@***.***> wrote:

﻿
Could you post the log? sounds strange with regard to gain and offset

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
