### ISSUE TITLE
Multiple silent crashes

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#222]
Hi Michel,

I have experienced multiple silent crashes when switching between the tabs. MW just closes all windows. This happened a few times now. I have attached one log, but I don't see any hint there.

Also I have two log files from MW exceeding 9 GB (!)

Cheers
Rüdiger

[mw4-2022-02-10.log](https://github.com/mworion/MountWizzard4/files/8047188/mw4-2022-02-10.log)

**Comment by mworion** [comment]
Rüdiger,
could you describe more, what happened. I would like to build a test automation against it.
Large log files are cause by intensive tracing. 
Michel

**Comment by Ruediger3** [comment]
Well, it happened always when I was quickly jumping between the tabs. I had switched the tabs, before the could load completely. That made it crash four or five times. Unfortunately more details I can not tell.

**Comment by Ruediger3** [comment]
The huge cannot be opened by Notepad++ anymore, since they are too big. Also zip was not really sufficient
![2022-02-11_16h41_47](https://user-images.githubusercontent.com/65772654/153622303-ce9b5afa-e931-4129-b431-632663c87d62.png)
.

**Comment by Ruediger3** [comment]
Maybe it makes sense to have a max log file size and MW4 starts a new log when reached?

**Comment by mworion** [comment]
Hi Rüdiger,
good point, moving to a rotating file with max size 100MB
Available next beta. For the crashed I try to install an automated test. We'll see how far I get.
Michel

**Comment by mworion** [comment]
Rüdiger,
I really can't find this crash. Ideally you could observe carefully, what happens on your side. I try to make this test on windows as well, right now only on MAC. The mount will be connected and MW4 is set to online during this run

[Bildschirmaufnahme 2022-02-11 um 21.04.05.mov.zip](https://github.com/mworion/MountWizzard4/files/8051344/Bildschirmaufnahme.2022-02-11.um.21.04.05.mov.zip)

Michel

**Comment by Ruediger3** [comment]
I will try to get more infos, but it just closed. No error, no log entry. This is hard to tackle.

**Comment by Ruediger3** [comment]
Hi Michel, 18 just crashed again, but this time I git an error in the log. I was clicking on the model tap. MW was immediately closed. Here it starts:

[2022-02-12 15:02:15.070][E][    loggerMW.py][  43] [STDERR] Traceback (most recent call last):

Rüdiger

[mw4-2022-02-12 - Copy.log](https://github.com/mworion/MountWizzard4/files/8053781/mw4-2022-02-12.-.Copy.log)

**Comment by mworion** [comment]
That might be a good hint. As I did not change anything on my side, I suspect the update of matplotlib library. If you don't ride, I rollback the lib to the previous stage and build a v19 for longer testing. V19 is now online
Michel
