### ISSUE TITLE
NINA controlled camera: Wrong scalling when Bin !=1

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#223]
Hi Michel,

just tried "NINA controlled" camera for the first time life. If MW is set to Bin>1 the scaling is wrong. with Bin=2 only the top left quadrant is shown. Please see screenshots below.

Rüdiger

![NINA](https://user-images.githubusercontent.com/65772654/153653452-e81108d9-6f57-4ee2-9b8e-052c5fce881e.png)

![Bin2_2](https://user-images.githubusercontent.com/65772654/153653484-9d4c2d28-966b-4a3e-9b3d-d7bbeada2fa4.png)

![Bin1_1](https://user-images.githubusercontent.com/65772654/153653507-9e924ffc-d671-4d86-9767-b0690a434f4a.png)

**Comment by mworion** [comment]
Rüdiger,
I learned that the API interface between SGPro and NINA is different in bin calcs although they promised to have the same.
Will be corrected in next beta
Michel

**Comment by Ruediger3** [comment]
Many thanks!

**Comment by mworion** [comment]
v2.2.0b18 is online with fixes for NINA, RA/DEC
