### ISSUE TITLE
M1 Mac install not working

### ISSUE THREAD

**Issue by His-Holy-Noodliness** [mworion/MountWizzard4#224]
Used MacOS scripts to install on a Macbook with M1 processor, I get a run log indicating some architecture issues, I can't post now as I deleted already, but if it's helpful I could get that again of course, I am guessing (I don't know much about how pip works) that some of the dependencies have no ARM package available yet, or that the install scripts are mis-selecting the architecture of the installed package. Would be great if this could be made to work, but it's really not important more of a convenience so I could use my macbook for modelling if desired, albeit this is a pretty fringe usage since I can't imaging anyone then uses one for acquisition, and the windows or linux scope-top machine which will be acquiring the images can be connected to via remote desktop or VNC to use it for the model build anyway.

**Comment by mworion** [comment]
Hi,
installing MW4 on a Mac M1 is simple, Willem-Jan made a short blog on it:
[https://www.astroworldcreations.com/blog/apple-silicon-and-legacy-command-line-software](url)
The basic start is that you need to work with Rosetta as native M1 packages for python are still rare. But He said it works flawless.
Hope this helps,
Michel

**Comment by His-Holy-Noodliness** [comment]
Ah excellent thanks, I am new to macs and had assumed the rosetta stuff all happened automatically, I'll take a look at that.
