### ISSUE TITLE
Image Binning bug on Mac

### ISSUE THREAD

**Issue by Raddock** [mworion/MountWizzard4#23]
Michel I've come across a new bug introduced in the version between 0.1.5. and the current. I have always had my camera set to bin 3x3 since the files are so large, 50 megapixel in size. Their large size takes about 9 seconds to download over my LAN network, and longer to MW4 for some reason. This makes it prohibitive to use 1x1 binning with my camera. 

So today, I updated to the latest version, and started a model, I noticed my screens were not getting plate solved. The images also looked very small in the image window. Also, after a good polar align, the images that were plate solving had as much as 800 error in pointing. It turns out that binning is not working properly. With the binning set to anything different from 1x1 the images get cropped to a small size, not binned. So at 1x1 you see the full image, at 2x2 you see less of the full image, and so on to 4x4 where there is so little image left, that platesolvign no longer works.

I've attached screenshots of my MW4 settings, the log, and some of the images that were captured during the model making showing sizes for Bin 1x1, 2x2, and 3x3 so you can see the difference. I did not reposition the telescope during this time, so the 3 images are the same field, and you can see what was happening when they got cropped, and not properly binned.

I have to use dropbox for the images because the fits are too large.
https://www.dropbox.com/s/46w2l6tpmbc6xdp/MW4%20Binning%20Bug.zip?dl=0
![Screen Shot 2020-04-23 at 9 10 55 PM](https://user-images.githubusercontent.com/5283143/80260465-980fd680-864d-11ea-8445-f14fc7b4b127.jpg)
![Screen Shot 2020-04-23 at 9 11 22 PM](https://user-images.githubusercontent.com/5283143/80260468-9b0ac700-864d-11ea-9d29-532c9adef6c7.jpg)
![Screen Shot 2020-04-23 at 9 11 43 PM](https://user-images.githubusercontent.com/5283143/80260470-9ba35d80-864d-11ea-9b91-73fb5b9a1543.jpg)

[mw4-2020-04-23.log](https://github.com/mworion/MountWizzard4/files/4531749/mw4-2020-04-23.log)

**Comment by mworion** [comment]
Found the issue. I worked on the Alpaca side. For unknown reasons INDI and ALPACA drivers behave different when calculation the Frame when binning is more than 1. So correction should be in 0.150.8.
Sorry about this regression.

**Comment by Raddock** [comment]
Thanks, this appears to be fixed now.
