### ISSUE TITLE
Auto Solve and Model Making does not work

### ISSUE THREAD

**Issue by Enno1971** [mworion/MountWizzard4#232]
Hello, unfortunately the Auto Solve and thus also the Model Maker does not work on my German Windows 10. Here is the error message (once with manual Solve and then Autosolve) Manuel Solve works fine
[mw4-2022-04-16.log](https://github.com/mworion/MountWizzard4/files/8500736/mw4-2022-04-16.log)
)

**Comment by Enno1971** [comment]
Hello, I would like to use MW4. Is there a tip? I've already reinstalled it. No success.

**Comment by mworion** [comment]
Hi Enrico,
yes I'm from Germany.For using the v2.2.2, just use the internal updater under settings/misc
.
Michel

**Comment by Enno1971** [comment]
Danke, teste ich gleiche bei entsprechendem Wetter

Grüße Enrico

Von: Michael ***@***.***>
Gesendet: Mittwoch, 20. April 2022 18:49
An: mworion/MountWizzard4 ***@***.***>
Cc: Enrico Köhlmann ***@***.***>; Author ***@***.***>
Betreff: Re: [mworion/MountWizzard4] Auto Solve and Model Making does not work (Issue #232)


Hi Enrico,
yes I'm from Germany.For using the v2.2.2, just use the internal updater under settings/misc
.
Michel

**Comment by Enno1971** [comment]
Hello, I imported version 2.2.3 today. Unfortunately no change. Same error - too bad. How can I help you with the solution (e.g. Teamviever session)? Greetings and many thanks from Enrico

Von: Michael ***@***.***>
Gesendet: Mittwoch, 20. April 2022 18:49
An: mworion/MountWizzard4 ***@***.***>
Cc: Enrico Köhlmann ***@***.***>; Author ***@***.***>
Betreff: Re: [mworion/MountWizzard4] Auto Solve and Model Making does not work (Issue #232)


Hi Enrico,
yes I'm from Germany.For using the v2.2.2, just use the internal updater under settings/misc
.
Michel

**Comment by mworion** [comment]
Hi Enrico,
I would propose a TeamViewer session next weekend Sat ?
Michel

**Comment by Enno1971** [comment]
Gladly, what time?

Grüße Enrico Köhlmann

Automatisch vom Handy diktiert, daher nicht frei von Fehlern.
________________________________
Von: Michael ***@***.***>
Gesendet: Sunday, April 24, 2022 8:43:01 PM
An: mworion/MountWizzard4 ***@***.***>
Cc: Enrico Köhlmann ***@***.***>; Author ***@***.***>
Betreff: Re: [mworion/MountWizzard4] Auto Solve and Model Making does not work (Issue #232)


Hi Enrico,
I would propose a TeamViewer session next weekend Sat ?
Michel

**Comment by Enno1971** [comment]
Hallo,

hast Du einen Zeitvorschlag für Samstag für mich?


Grüße

Enrico Köhlmann

Enrico Köhlmann, An der Schule 7, DE-06198 Salzatal OT Lieskau,
Verkehrspilot CPL(A)/IR JAR-FCL mit ATPL
Freelance Commercial Pilot Licensed JAR CPL(A)/IR with ATPL
Lizenz.- Nr. 5086

Email: ***@***.******@***.***>

Mobil:       +49 171 36 222 90

-----------------------------------------------------------------------------------------------------------------
In dieser eMail enthaltene Informationen beruhen auf sorgfaeltiger Recherche. Dennoch laesst es sich nicht ausschliessen, dass eine Information im Einzelfall unzutreffend ist. Wir bitten daher um Ihr Verstaendnis, wenn wir keine Gewaehr fuer die Richtigkeit der Informationen uebernehmen und jede Haftung ausschließen. Sollten Sie feststellen, dass eine Information unzutreffend ist, bitten wir um Rueckmeldung.



Von: Michael ***@***.***>
Gesendet: Sonntag, 24. April 2022 20:43
An: mworion/MountWizzard4 ***@***.***>
Cc: Enrico Köhlmann ***@***.***>; Author ***@***.***>
Betreff: Re: [mworion/MountWizzard4] Auto Solve and Model Making does not work (Issue #232)


Hi Enrico,
I would propose a TeamViewer session next weekend Sat ?
Michel

**Comment by mworion** [comment]
Hi Enrico,for some reasons I do not see my response I made. What about this 14:00 or 15:00 and using a simulator?
Michel

**Comment by Enno1971** [comment]
Ok 15 Uhr wäre super. Kannst Du mich unter +491713622290 anrufen?

**Comment by mworion** [comment]
Ok, rufe an.

**Comment by Enno1971** [comment]
super, muss die Kamera angeschlossen sein?

**Comment by mworion** [comment]
Nein, ich würde es mit dem https://sourceforge.net/projects/sky-simulator/ <https://sourceforge.net/projects/sky-simulator/> probieren, sofern Du auf Windows / ASCOM arbeitest. Wenn Du noch Zeit hast, gerne installieren, der Simulator generiert ein Bild passend, der Ablauf danach sollte der gleiche sein wie in einer realen Kamera.

**Comment by Enno1971** [comment]
mache ich. Zugriff per Teamviewer?

**Comment by mworion** [comment]
ja gerne, Du kannst mir die credentials per sms schicken. Normalerweise sollte dann auch Audio mit Teamviewer funktionieren.

**Comment by Enno1971** [comment]
bitte senden mir mal Deine Handynummer an 01713622290

**Comment by Enno1971** [comment]
Hier die File https://visuplus-my.sharepoint.com/:f:/p/e_koehlmann/ElIwK-5XiJxHgHj9JTNt_qUB3qDnsNUovI9pUE-TemgT9w?e=zsogcX

**Comment by Enno1971** [comment]
und die Logs https://visuplus-my.sharepoint.com/:f:/p/e_koehlmann/Ev-pZvEfk4ZJlNEmva4-TWABundfJcgrYagSXLGUS8ALIA?e=2yAmL0

**Comment by mworion** [comment]
Hi Enrico,
v2.2.4 should fix your problem as I removed a cause of a race condition for file handling.
Michel

**Comment by Enno1971** [comment]
Vielen Dank. Ich werde das sobald das Wetter passt mal testen.

Grüße Enrico

Von: Michael ***@***.***>
Gesendet: Sonntag, 19. Juni 2022 17:13
An: mworion/MountWizzard4 ***@***.***>
Cc: Enrico Köhlmann ***@***.***>; Author ***@***.***>
Betreff: Re: [mworion/MountWizzard4] Auto Solve and Model Making does not work (Issue #232)


Closed #232<https://github.com/mworion/MountWizzard4/issues/232> as completed.
