### ISSUE TITLE
Almanac Moon phase always half moon

### ISSUE THREAD

**Issue by aphelyon-net** [mworion/MountWizzard4#233]
Unsure if I've missed a setting but the image graphic for the moon phase always appears to show half moon phase.
The illumination otherwise looks correct for the location.

<img width="529" alt="Screen Shot 2022-04-20 at 8 33 14 pm" src="https://user-images.githubusercontent.com/69456746/164231326-3358dd10-921e-4d4a-bce1-ddbd8b06230a.png">

**Comment by mworion** [comment]
That's definitely wrong. I'll have a look to the drawing issue.

**Comment by aphelyon-net** [comment]
Updated and confirmed working. Thanks for the fast resolve.
