### ISSUE TITLE
Mount Simulation View not updated for Southern Hemisphere observer

### ISSUE THREAD

**Issue by aphelyon-net** [mworion/MountWizzard4#235]
I just noticed that the graphical representation of the mount position appears to be only showing the northern hemisphere position.
In my case of being in the southern hemisphere, the graphical position should be reversed.
In the attached picture the mount is currently positioned near the South celestial pole towards IC2944 target.
Thanks

<img width="798" alt="Screen Shot 2022-04-21 at 7 23 33 pm" src="https://user-images.githubusercontent.com/69456746/164448287-977e9c52-57eb-4972-9226-84ff27a2b6ee.png">

**Comment by mworion** [comment]
Sorry to hear.
I checked it and I turn the mount if I set the latitude to southern hemisphere, but so far I hardly get any feedback if there are any problems with it. I have another user in NewZeeland, but there MW4 runs so far as well as Tony in Chile. In any case, please check things and report back. It would be helpful to get more detailed pictures (not overlapped).
Michel

**Comment by aphelyon-net** [comment]
Hi Michel, 
Do you mean to manually set the Latitude rather than have GPS update the mount position?
In park position here you can see that the graphic is pinting north rather than south when in parked position.
I wonder if the is an issue with the firmware and updates returned by ascom? 
I'm currently on firmware 3.0.8

-------------------------------------------------------------------------------
Upgrade notes for 10micron mount software version 3.0.9
-------------------------------------------------------------------------------

Improved logging.

* Bugs *

When the location was updated with the GPS module, the southern hemisphere
state was not correctly updated when a southern latitude was selected. This
has been corrected.

![Screen Shot 2022-04-22 at 8 39 40 am](https://user-images.githubusercontent.com/69456746/164574018-8218f6b4-d2a0-4f5a-a757-42919f259c8c.png)

**Comment by mworion** [comment]
Hi it was probable an initialization problem at startup of MW4.
v2.2.3 should fix this. If you change hemisphere you have to reopen the mount simulator window.
Michel

**Comment by aphelyon-net** [comment]
Thanks, I can confirm this is working now.
