### ISSUE TITLE
ASTAP Failed - ASI 6200 MM PRO

### ISSUE THREAD

**Issue by rkas12** [mworion/MountWizzard4#236]
Hello,

I wanted to start building a model for my 10 micron mount with my full frame ASI 6200 MM camera. I was unsuccessful since ASTAP failed every time to solve. Worth mentioning that usually ASTAP works like a charm with my setup. In addition, while loading manually an image taken via MW4 and the plate solving works perfectly ;(

In the settings, I made sure to have the correct values, i.e. focal length, aperture, increase radius up to 180, etc. Further, I put the work file under "my document" to avoid conflicts in W10.

I would appreciate your kind advice. 

Best regards.

PS : MW4 is an incredible tool, very well done !

**Comment by mworion** [comment]
Hi,

sorry to hear, would you mind to post the log file here in GitHub and probably the zipped fits file as example, too ? If the file size of the image is too large, you might use the dropbox link as well: https://www.dropbox.com/sh/5q9jcvdq2tf2o0l/AAAbrVhoaWAAgQz3AdlE777fa?dl=0
Michel

**Comment by rkas12** [comment]
Dear Michel, 

Thank you for your quick reply, much appreciated. 

Image example : [https://www.dropbox.com/s/5oog415482a2zij/image-001.fits?dl=0](url)

As for the log, sorry for the newbie question, where can I retrieve it ? I have under settings "standard" selected, but I do not have any log file under the work file.

Thank you for your help, Michel.

Greetings,
Aygen

**Comment by mworion** [comment]
Augen,
you will find the log file in your work folder. Named: mw4-yyyy-mm-dd.log. If you try the next time, you could set logging to debug (settings / misc) tab.
The config file you will find in config folder and has extension *.cfg
Michel

**Comment by rkas12** [comment]
Michel,
Thank you - I found it ! Please find the log : https://www.dropbox.com/s/x4jfzinicg3cexc/mw4-2022-04-23.log?dl=0[](url)
I have already changed the logging level to debug.
Best regards,
A.

**Comment by mworion** [comment]
Aygen,
I tried the image with the MW4 default settings and it failed whereas ASTAP manually solved correctly. ASTAP showed 13 degrees RA off (which is a lot). Default search radius set by MW4 is only 10 degrees, which explains the fail. If you increase the search radius in ASTAP driver setting to 30 degrees like:

![2022-04-24-18-37-20-Setup_driver_for_astrometry](https://user-images.githubusercontent.com/6632980/164991415-8bf81ad3-8125-429e-a4fe-698d2b5195fd.png)

MW4 solves with ASTAP, too with the same solving result.
Please give it a try.
Michel

**Comment by rkas12** [comment]
Evening Michel,

Thank you for your time and your feedback. 

Yesterday, I did increase the radius up to 180. It failed in MW4 whereas it worked both by loading manually the image in MW4 (and solve it) and by going through ASTAP itself directly. 

Tonight should be good enough to run some tests. I will keep you posted about the outcome. 

Otherwise, should it fail again, is there a way in MW4 to load images manually, solve them and then export the overall results into the mount ? 

Thank you again for your kind help and all the best,
Aygen

**Comment by mworion** [comment]
Aygen,
If you have to increase the radius to 180 something is strange. If you have a rough estimation where the mounts points to, it should be less. If you need more than 90 I would wonder why. Please check if ASTAP times out and increase the timeout setting accordingly.
Unfortunately there is no way to do it manually. But we'll find out what the reason is and sort it. If you do another test, please set debug level to trace and post the log file afterwards.
Michel

**Comment by rkas12** [comment]
Michel,
Great news, I just ran a small model (22 points) and did work perfectly (plate solving, modeling, etc.). 
Thank you for your very nice followup ! 
Shall we close the thread ?
Many thanks and best regards,
Aygen

**Comment by rkas12** [comment]
Michel,
A side question if I may : is there a way to keep the existing model while adding points (without starting from the scratch) ?
Best regards,
A.

**Comment by Ruediger3** [comment]
> Michel, A side question if I may : is there a way to keep the existing model while adding points (without starting from the scratch) ? Best regards, A.

Hi Aygen,
happy to read that it works for you now. Coming to your idea to have an incremental model approach. This is not a good idea, because the different model parts are taken under different environmental conditions, so the model might become corrupted. 

Better do it in one glitch. Actually it does not take much more time. For me 92 points take only around 40 minutes, which can be done during sun set. No imaging time is lost. 

CS
Rüdiger

**Comment by mworion** [comment]
Hi Aygen,
I agree with Rüdiger, but still there is the technical possibility in doing two separate model an adding them.

**Comment by rkas12** [comment]
Thank you for everything Michel ! You rock !!!!

I wish you an excellent start into the new week.

Aygen
