### ISSUE TITLE
GM2000HPS - Startrails after polar align and model Build

### ISSUE THREAD

**Issue by GsellAstrophotography** [mworion/MountWizzard4#240]
Hello Together,

I bought a new GM2000HPS. Now I tried to get everything to work.

My steps were:
1. Small Model
2. Polar Align
3. redo Steps one and two
4. After I got a Polar error of 20 Arcseconds I wanted to test with some 5 minute Pictures. But all of them had elongated stars. I will send the Log file (first one)

Then I made a Polar alignment with Sharpcap and wanted to create a new model. (I also updated the MC4 with the autoupdater)
Unfortunately the Model Creator always stopped after the first star and didn't do anything else then. 
I tried everything. Shut down everything, restart and so on.
But then it only created a model under conservative setting (before it worked with every setup)
I 

I will attach the Log files. Perhaps you can help me.

My setup is a GM2000HPS and a Orion UK ODK12 with 2040mm focal length.

CS Christia
[mw4-2022-05-18.log](https://github.com/mworion/MountWizzard4/files/8757019/mw4-2022-05-18.log)
[mw4-2022-05-17.log](https://github.com/mworion/MountWizzard4/files/8757020/mw4-2022-05-17.log)
n

**Comment by mworion** [comment]
Hi Christia,

thanks for the logs and sorry about your experience. There is an service release 2.2.5 out which fixes your problem (model setup with other than conservative). This happened in special cases, but should be now more robust. As you are using ASTAP, please make sure that you are roughly polar aligned with your actual focal length or increase the FOV setting in ASTAP driver from 10 to 30 degrees (to allow more deviation). I would recommend enabling Dual Axis Tracking during imaging run with you focal length. Depending on your ASI Camera (my guess is a newer with large sensor), ASTAP only needs 1500 pixel each side. So go for bin2 or bin3 might be helpful to lower the download speed and increase robustness.

After you updated, please set logging Leven (under log/ misc) to debug to ge more information about possible problems next run.

Hopyfully 2.2.5 is the way to go for you.
Michel

**Comment by GsellAstrophotography** [comment]
Hallo Michael,

danke sehr, ich werde es testen :)
