### ISSUE TITLE
Creating Model with ASCOM and ASTAP

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#243]
Hi Michel
I started to use your MW app with my GM1000HPS, to begin I use the mount, the simulatorV2 for the camera, MGbox,  the PC, 
i have every thing green solver is ASTAP, I tried Astromety.net but I miss the lib. and I am not enough inside to understand the whole picture...Later...When I run a model the plate solving never complete but the process continue, is it normal with the simulator of the camera ? Is ASTAP ok as a solver ?  Thanks a lot and thanks.   George

_Originally posted by @georgesblum in https://github.com/mworion/MountWizzard4/discussions/96#discussioncomment-2907399_

**Comment by mworion** [comment]
Hi Georges,

I made an issue out of it. We are going to sort your problem out. As you are using Windows as your operating system, could you please post the log here in the issue (just drag the *.log file to the webpage). An attachment for email does not work. Then I will have a look to your setup and then wo move further on.

Michel

**Comment by mworion** [comment]
Hi Georges,
I publish a new 2.2.7 this evening. Probably this also addresses your issue as well.
Michel

**Comment by georgesblum** [comment]
Hi Michael,
i upgraded to 2.7 / i am going to send you the logs but i think i have an issue with the mount, unfortunately, the famous code error 00.20.00.00.16/00, so i am waiting to get the grid filter from Baader, i am not to shure the logs are helpful for you ? are you still willing to get them ?  king regards Georges

**Comment by mworion** [comment]
sure, at least I will have a look to it and see what happened.

**Comment by mworion** [comment]
so following the issue were our log files are in

**Comment by georgesblum** [comment]
[mw4-2022-06-13.log](https://github.com/mworion/MountWizzard4/files/8936173/mw4-2022-06-13.log)
[mw4-2022-06-14.log](https://github.com/mworion/MountWizzard4/files/8936174/mw4-2022-06-14.log)
[mw4-2022-06-18.log](https://github.com/mworion/MountWizzard4/files/8936175/mw4-2022-06-18.log)
[mw4-2022-06-19.log](https://github.com/mworion/MountWizzard4/files/8936176/mw4-2022-06-19.log)

**Comment by georgesblum** [comment]
[mw4-2022-05-16.log](https://github.com/mworion/MountWizzard4/files/8936180/mw4-2022-05-16.log)
[mw4-2022-05-17.log](https://github.com/mworion/MountWizzard4/files/8936181/mw4-2022-05-17.log)
[mw4-2022-05-18.log](https://github.com/mworion/MountWizzard4/files/8936182/mw4-2022-05-18.log)
[mw4-2022-05-20.log](https://github.com/mworion/MountWizzard4/files/8936183/mw4-2022-05-20.log)
[mw4-2022-05-21.log](https://github.com/mworion/MountWizzard4/files/8936184/mw4-2022-05-21.log)
[mw4-2022-05-25.log](https://github.com/mworion/MountWizzard4/files/8936185/mw4-2022-05-25.log)
[mw4-2022-05-28.log](https://github.com/mworion/MountWizzard4/files/8936186/mw4-2022-05-28.log)
[mw4-2022-06-04.log](https://github.com/mworion/MountWizzard4/files/8936187/mw4-2022-06-04.log)
[mw4-2022-06-06.log](https://github.com/mworion/MountWizzard4/files/8936188/mw4-2022-06-06.log)
[mw4-2022-06-07.log](https://github.com/mworion/MountWizzard4/files/8936189/mw4-2022-06-07.log)
[mw4-2022-06-08.log](https://github.com/mworion/MountWizzard4/files/8936190/mw4-2022-06-08.log)
[mw4-2022-06-09.log](https://github.com/mworion/MountWizzard4/files/8936191/mw4-2022-06-09.log)
[mw4-2022-06-10.log](https://github.com/mworion/MountWizzard4/files/8936192/mw4-2022-06-10.log)

**Comment by georgesblum** [comment]
Could you got the files Michael ?

**Comment by mworion** [comment]
yes, as soon as you are „online“ with the mount again, we‘ll sort the topic‘s I‘ve seen.
