### ISSUE TITLE
Unable to solve with ASTAP

### ISSUE THREAD

**Issue by Fukinagashi** [mworion/MountWizzard4#244]
I'm unable to solve old images (already successfully used for modelling) with ASTAP. This happens both with v2.2.2 and v2.2.6. Tried to widen the ASTAP search field without any result. As a consequence modelling does not work anymore.
The error is Solving error: none.

**Comment by mworion** [comment]
Hi,
could you post the fits file? You need to zip it and then just drag it in your reply on the webpage with in this issue.
There is something in the FITS header which does not match for some reason.
Michel

**Comment by Fukinagashi** [comment]
Here is the zipped file (the one created by MW4)
[image-010.zip](https://github.com/mworion/MountWizzard4/files/8928875/image-010.zip)
.

**Comment by mworion** [comment]
I combine both issue as they have the same reason. I will publish 2.2.7 this evening which will address the issue. As summary: The change is related to newer ASTAP versions. ASTAP writes a text file in FITS header format where it stores its results. There were COMMENT cards which describe additional informations out of the solver process. This comments were cutted in the past. Han corrected this by adding a CONTINUE card for upcoming lines. Unfortunately I did not catch these cards. This should be addressed with 2.2.7 now.
Michel

**Comment by hdiessner** [comment]
Awesome! Weather looks like I will be able to test the new release tonight :) Thank you once again, Michel :)

**Comment by mworion** [comment]
So 2.2.7 is published. Hopefully after my tests this will make it.

**Comment by hdiessner** [comment]
For me, it's working now! I am running my polar alignment routine right now and everything works great! Thank you, Michael :)

**Comment by hdiessner** [comment]
First model successfully  created with 30  pictures taken and successfully plate solved, after little bit of optimizing I now have a first model with 22 Model terms and an Expected RMS of 1.8" - not too bad I think for the first Alignment Model with MW4 :)

**Comment by mworion** [comment]
Great new, have fun.


Von meinem iPad gesendet

**Comment by Fukinagashi** [comment]
Working for me too!

**Comment by mworion** [comment]
Great to hear.
