### ISSUE TITLE
MW2.2.7: No model creation is triggered after last exposure

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#246]
Hello Michel,
long time no hear. I hope you are fine!

Yesterday I faced an issue while building a 96 point model. 

1. During model build the processed / solved point was always 2 points behind the current one. The points 2 steps behind were marked with yellow and hook.

2. After the last point was exposed it was not handed over to ASTAP and model build was not triggered. I had to press "End" button and then the model was created without the last point. It looks like there is an index has an offset by 1.

Thank you!

Cheers
Rüdiger

![mw4-2022-07-02 - Copy zip](https://user-images.githubusercontent.com/65772654/177035397-ebd07b7d-e8ff-4cde-ae2a-3925fe7a6cae.gif)

**Comment by Ruediger3** [comment]
Hi Michl,
I see the gif is removed. Please advice how to attach the log file. I get always "Something went really wrong" Error.

**Comment by Ruediger3** [comment]
At this moment MW got stuck and I had to press "end" to initiate model creation:


![IMG_1657](https://user-images.githubusercontent.com/65772654/177036759-d5373669-7cae-40ca-9220-44ff979069bf.PNG)
.

**Comment by mworion** [comment]
Hi Rüdiger,
I'm fine, hope you are doing well, too.
I checked the log and saw that after point 27 in the model build a manual exposure was triggered. This caused and queuing error and caused the model run expect more things to come. In future this will stop a model run immediately. I hardly understand, why a manual trigger could happen, as I tried to disable these functions during a model run. Could you remember, what you did during this time? But anyway I have to find out why this happens.

![Bildschirmfoto 2022-07-03 um 13 38 30](https://user-images.githubusercontent.com/6632980/177037832-9a834420-0ceb-4e70-bb80-ea5136978952.png)

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

many thanks - just recovering from COVID, but almost fine again thanks vaccination.

I cannot remember triggering a manual exposure during model run. I did one single exposure before model creation to test whether it is dark enough to solve. The rest of the time I had the tablet on the couch table and I was watching MW doing its job. That is very strange.  

Could it be, that NINA was doing something with the camera since I use NINA as Server?

Rüdiger

**Comment by mworion** [comment]
Rüdiger,

Good to hear that your are „back“. I would not guess that NINA is involved as the log only tells about UI clicks in MW4. 
So I checked disabling Exposures during model run. This is not implemented for the Imaging window, just you can’t change the points during run.
So I added this function to v3.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

many thanks! For me this is absolute fine. Since I know now what has caused the hick-up I can take care. 

Enjoy your Sunday!
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,

I have re-done last night exact the same as the night before. No error. Everything worked as expected. So I guess either I have made something stupid or it was an unique event. 

Thanks!
Rüdiger
