### ISSUE TITLE
MW4 not connecting to mount from Eagle

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#247]
Dear Michel,

I am currently helping another Dutch 10Micron owner setting up his observatory. He is has a GM2000HPS and is using an Eagle to run all his software. The 10Micron virtual keypad connects fine to the mount and so does my MountMonitor (in native LX200 mode). MW4 connects fine to all ASCOM drivers, so that works fine as well, but no connection is made to the mount using the same IP-address as the virtual keypad and MountMonitor.

![afbeelding](https://user-images.githubusercontent.com/66182061/177370176-887f23a9-617a-4077-991d-3925aa678f0e.png)

Attached is a run from yesterday.
[mw4-2022-07-04.log](https://github.com/mworion/MountWizzard4/files/9047846/mw4-2022-07-04.log)

Installation was done using the MW4_install.bat file. We have been testing MW4 2.2.7 and 2.2.0.

We would appreciate any hints that could lead to a successful connection.

Thanks in advance and
with kind regards,
Nicolàs

PS: a TeamViewer connection is possible, please contact me privately if you wish to do so.

**Comment by mworion** [comment]
Hi Nicolas,
Hopefully a simple fix:
Normally I write the address without '0', so 192.168.1.99, but this should not matter.
And I checked it: On Mac it really does not matter at all, but on windows it does. So please remove the leading '0' from the IP address and it should work.
Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

thank you so much, indeed it works!:

![afbeelding](https://user-images.githubusercontent.com/66182061/177483525-89e04c21-b33c-40ce-b483-ef014f180e76.png)

It is a Python-thing, in combination with Windows, so not a pure Windows thing. My MountMonitor has no issue at all using leading zero's in the connection, even under Windows.

Anyway, it is not a MW4-issue, but maybe it would be good to have this explained in the tool-tip of the address-field?

Nicolàs
