### ISSUE TITLE
I cannot download MW4

### ISSUE THREAD

**Issue by alanrock24** [mworion/MountWizzard4#256]
When I click on the link for the zip files so I can download MW4, I get a 404 error. How can I download the software? (WIndows)

**Comment by mworion** [comment]
Hi sorry about a wrong link, you should be able to download it from
[https://github.com/mworion/MountWizzard4/tree/master/support/2.0](url)
Michel

**Comment by mworion** [comment]
Please see also my post in the 10micron forum for the new installer.
Michel

**Comment by alanrock24** [comment]
Thanks. All the links on the page with the instructions, from “Example setup for rig” on down are also broken: https://mworion.github.io/MountWizzard4/install/index.html <https://mworion.github.io/MountWizzard4/install/index.html> and click on any of the links on the bottom left. They all seem to be broken,
Thanks,
Alan

**Comment by mworion** [comment]
Hi Alan,
thanks for the hint. Looking fort that.
Hope you did get set install script and it worked.
Michel

**Comment by alanrock24** [comment]
Hi Michel,
Yes, thanks, I did get it installed. Now I’m just trying to learn it—may brain hurts!!
Thanks again,
Alan

**Comment by mworion** [comment]
Good to hear,
if you need help, please let me know.
Closing the issue.
Michel

**Comment by alanrock24** [comment]
II cannot seem to get the terrain image to load. Although I put the terrain.jpg file in the config directory, it doesn’t want to load. I am wondering ig I have installed it incorrectly. Does this screen shot help?

**Comment by mworion** [comment]
Alain,
if you don‘t see the terrain image, please post the MW4 log file (just drop it to your response in the webpage - reply via email does not work with attachments) as there might be a format issue with the image. Hope I could see something in it.
Michel

> Am 24.08.2022 um 01:22 schrieb alanrock24 ***@***.***>:
> 
> ﻿
> II cannot seem to get the terrain image to load. Although I put the terrain.jpg file in the config directory, it doesn’t want to load. I am wondering ig I have installed it incorrectly. Does this screen shot help?
> 
> 
>
