### ISSUE TITLE
Cannot install due to dependency version mismatch

### ISSUE THREAD

**Issue by ghulands** [mworion/MountWizzard4#26]
Hi,
I tried to install the latest master and got the following error.

error: PyQt5 5.14.2 is installed but PyQt5==5.14.1 is required by {'mountcontrol', 'indibase'}

**Comment by mworion** [comment]
Hi,
I see the point and you're right. Please install MW through pip and PyPi online. Github Master is always development and might be not OK. But thank to you test I saw that the build jobs see your issue as well, but report green for whatever reason. I have to check this.
Michel

**Comment by mworion** [comment]
Added an explicit check fro dependencies on GitHub actions. So if badges show package build failing, install from master will fail as well. Hope this helps for future.

Closing the issue.
Michel
