### ISSUE TITLE
Issue with software update

### ISSUE THREAD

**Issue by mhambuch** [mworion/MountWizzard4#27]
Hi Michael, I wanted to install the latest version, hit the install button as a new version is available. Button turns blue but nothing gets installed, respectively it stays blue forever

![img](https://user-images.githubusercontent.com/63575440/81298289-db6a3c00-9074-11ea-8cb8-866537fd38cb.gif)
![img2](https://user-images.githubusercontent.com/63575440/81298297-de652c80-9074-11ea-9b7f-00f15163ec45.gif)

**Comment by mworion** [comment]
...could you post the log file ? This would help a lot !

Michel

**Comment by mhambuch** [comment]
Hi Michael, i will .... but where is the log file ?

**Comment by mworion** [comment]
Got it. 

There is no need for renaming as Github normally accepts *.log files directly. 
There are some minor issues not related to update. These will be fixed in the next version.

Question: the timestamps of the images and the log file are different. Normally I see the output of the message window in the log, but that's only be done of you had the message window open. I changed this now. Please open the message window before trying to update and send the log again.

Michel

**Comment by mhambuch** [comment]
Hi Michael, just restarted the process.

![img](https://user-images.githubusercontent.com/63575440/81472128-34151280-91f6-11ea-8052-515d24f2a8ef.gif)

[mw4-2020-05-09.log](https://github.com/mworion/MountWizzard4/files/4603328/mw4-2020-05-09.log)

**Comment by mhambuch** [comment]
the message windows blocks on "building wheels for collected packages"

**Comment by mworion** [comment]
There is a timeout set for ever running processes during install. This might be to short especially for windows computers as it might take there extreme long. 
I release the next versions with extended timeout. This start from 0.150.12 on. Until then, please use the provided script (MW4_Update.bat). it should do the same trick.

Michel

**Comment by mhambuch** [comment]
Thx Michel, the update script also fails, i havent found its log file.

below what i could copy from the window



copying astropy\wcs\include\wcslib\prj.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\include\wcslib\spc.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\include\wcslib\spx.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\include\wcslib\tab.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\include\wcslib\wcs.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\include\wcslib\wcserr.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\include\wcslib\wcsmath.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\include\wcslib\wcsprintf.h -> build\lib.win-amd64-3.8\astropy\wcs\include\wcslib
  copying astropy\wcs\tests\extension\wcsapi_test.c -> build\lib.win-amd64-3.8\astropy\wcs\tests\extension
  running build_ext
  running pre_hook from astropy.modeling.setup_package for build_ext command
  running pre_hook from astropy._erfa.setup_package for build_ext command
  building 'astropy.compiler_version' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\astropy
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Windows\System32\venv\include -Ic:\users\mhambuch\appdata\local\programs\python\python38\include -Ic:\users\mhambuch\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcastropy\_compiler.c /Fobuild\temp.win-amd64-3.8\Release\astropy\_compiler.obj
  _compiler.c
  astropy\_compiler.c(58): warning C4005: 'COMPILER': macro redefinition
  c:\users\mhambuch\appdata\local\programs\python\python38\include\pyconfig.h(126): note: see previous definition of 'COMPILER'
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Windows\System32\venv\libs /LIBPATH:c:\users\mhambuch\appdata\local\programs\python\python38\libs /LIBPATH:c:\users\mhambuch\appdata\local\programs\python\python38 /LIBPATH:C:\Windows\System32\venv\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit_compiler_version build\temp.win-amd64-3.8\Release\astropy\_compiler.obj /OUT:build\lib.win-amd64-3.8\astropy\compiler_version.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\astropy\compiler_version.cp38-win_amd64.lib
  _compiler.obj : warning LNK4197: export 'PyInit_compiler_version' specified multiple times; using first specification
     Creating library build\temp.win-amd64-3.8\Release\astropy\compiler_version.cp38-win_amd64.lib and object build\temp.win-amd64-3.8\Release\astropy\compiler_version.cp38-win_amd64.exp
  Generating code
  Finished generating code
  building 'astropy.convolution._convolve' extension
  creating build\temp.win-amd64-3.8\Release\astropy\convolution
  creating build\temp.win-amd64-3.8\Release\astropy\convolution\src
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Windows\System32\venv\lib\site-packages\numpy\core\include -IC:\Windows\System32\venv\include -Ic:\users\mhambuch\appdata\local\programs\python\python38\include -Ic:\users\mhambuch\appdata\local\programs\python\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcastropy\convolution\src/convolve.c /Fobuild\temp.win-amd64-3.8\Release\astropy\convolution\src/convolve.obj -UNDEBUG
  cl : Command line warning D9025 : overriding '/DNDEBUG' with '/UNDEBUG'
  convolve.c
  c:\users\mhambuch\appdata\local\temp\pip-install-gyr_zhvm\astropy\astropy\convolution\src\convolve.h(44): fatal error C1083: Cannot open include file: 'numpy/ndarrayobject.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for astropy
  Running setup.py clean for astropy
Successfully built mountwizzard4
Failed to build astropy

**Comment by mworion** [comment]
I still learning what might happen. For some reason satrapy wants to compile. I've never seen that. I have a Win10 machine just for testing. I did manually up / downgrades. Installed with script. It never happen.

Could you explain a little about your equipment and how you installed MW4?

As experiment you could create another work folder, install pretty clean with the install script, run MW4 just once without doing something  and then copy the config folder from your older work folder to it. This copies all your settings.

Michel

**Comment by mhambuch** [comment]
Hi Michel, 

I reinstalled from scratch on my W10 environment 

1 Python installed using the link from the instruction. Strangly it is a 64bit version but when i look at the installed result it say 32bit

![Python](https://user-images.githubusercontent.com/63575440/81494292-10120980-92a8-11ea-8d4b-d84c928042f6.gif)

![PythonCheck](https://user-images.githubusercontent.com/63575440/81494300-1a340800-92a8-11ea-9df3-750164d2c2e3.gif)

**Comment by mworion** [comment]
basically it’s not really relevant, which python version 32 or 64 bit is installed for MW4. just 32 Bit allows also the use of ASCOM, as many drivers only support 32 bit and you can’t mix it. As you have 32 bit installed, the check against it might be wrong, but for MW4 it’s anyway ok.

Des the overall system run now ?

**Comment by mhambuch** [comment]
Hi Michel, no the install script just runs 2s and stops, on the window that openes i have the messages as above. Is there a log file i could attach?

**Comment by mworion** [comment]
Normally there should be a file install.log in the same directory. If the script is that fast, a virtualenv is already in the directory (is there a folder called venv existing?). If so, that would explain:
- If you had python 64 bit already installed (at the beginning), the venv is 64 bit. 
- If you removed python 64 bit and installed 32 bit, in the venv still resides 64 bit as it is not installed new.
- Please use a new work directory.
No other clue to the situation.
Michel

**Comment by mhambuch** [comment]
Hi Michel, tried all i could think of, reinstalled Python (32bits) new work directory, it still does not install anything, the script if over in 2s. As i really would like to use MW4 we may try teamviewer when you have time, i will of course pay for your time. Marc

**Comment by mhambuch** [comment]
there is a venv folder in the python library (under lib). This venv folder is created while installing python and is then there when i execute the install script. I have deleted the entire python folder before reinstalling python (after proper deinstallation  from the application app in windows10)

![venv](https://user-images.githubusercontent.com/63575440/81506031-f8607280-92f3-11ea-8402-945352182e43.gif)

**Comment by mworion** [comment]
Hi Marc,
let' try to find a schedule for a TeamViewer. If you don't mind it would be Tuesday evening as I'm on work. Definitely never would take money for helping. Does Tuesday 20:00 in the evening work for you ?
Michel

**Comment by mhambuch** [comment]
Hi Michel, great thank you very much, Tuesday 20:00 is fine. I will give it another try to solve it and let you now. Marc

**Comment by mhambuch** [comment]
I Michel, i didnt manage to solve the issue so if still ok we can plan a teamviewer this evening 8pm. How should i pass you the credentials of my pc not so secure to post it here ?

my mail is mhambuch@laposte.net

Thanks

**Comment by mworion** [comment]
Marc, 
you could send me a PM with teamviewer credentials to michael@wuertenberger.org
Michel
