### ISSUE TITLE
NINA timeout

### ISSUE THREAD

**Issue by gpassera** [mworion/MountWizzard4#281]
**Describe the bug**
The camera is a Moravia G2-8300 which if used with NINA is seen correctly and works using the native (Moravian) 64-bit drivers. If I use NINA as  interface in Mountwizzard I have a timeout as per attached log. I also tried to define the direct link of the ASCOM driver which works in NINA  but doesn't work in Mountwizzard. I enclose the log of attempts from last night. Some idea? Thank you

[mw4-2022-10-18.log](https://github.com/mworion/MountWizzard4/files/9821420/mw4-2022-10-18.log)

**Comment by mworion** [comment]
Did you enable NINA server? Otherwise NINA will not respond to MW4 requests. You will find the enable here:
![Bildschirmfoto 2022-10-19 um 21 50 42](https://user-images.githubusercontent.com/6632980/196790072-cb2a01a9-2d41-415f-9354-b548a6067be4.png)
Hope this helps.
Michel

**Comment by gpassera** [comment]
Michael

Thank you for your answer
No, the server was not active. Sorry.
This evening I will try again.

I close the Issue.
Thank you

**Comment by gpassera** [comment]
Solved, not an issue.
