### ISSUE TITLE
Plate solving with ASTAP fails with the recent version of ASTAP

### ISSUE THREAD

**Issue by razvan-astro** [mworion/MountWizzard4#282]
A few weeks ago I was using MW4 2.2.7 with ASTAP v2022.09.10 and all was fine (like before).

A few days ago I upgraded ASTAP to v2022.10.19a and at the next imaging session in the field last night, all attempts to plate solve failed with the error below.

[2022-10-22 23:29:06.155][C][       tpool.py][ 103] fn: [solve], file: [tpool.py], line: 97 fn: [solve], file: [astrometryASTAP.py], line: 235 fn: [solve], file: [astrometry.py], line: 156 fn: [solve], file: [header.py], line: 272 fn: [solve], file: [header.py], line: 690 fn: [solve], file: [card.py], line: 206 fn: [solve], file: [card.py], line: 503 fn: [solve], file: [verify.py], line: 73 fn: [solve], file: [card.py], line: 1111 fn: [solve], file: [card.py], line: 818 fn: [solve], file: [card.py], line: 1191  - excType: [<class 'astropy.io.fits.verify.VerifyError'>], excValue: [CONTINUE cards must have string values.]

I installed the previous ASTAP and plate solving worked correctly again. I have not changed any settings neither before the problem, nor after it. Nor did I make any library updates.  The camera is a ZWO ASI2600MC Pro. I still have the captured images if needed.  The computer is a PL Eagle4 running Windows10.

The exception is thrown by https://docs.astropy.org/en/stable/_modules/astropy/io/fits/card.html Not sure what triggered the problem and whether it's something new or the latest ASTAP caused it to surface. I thought you may want to know. Log excerpt below. 

Thanks and please let me know if any additional information can help.

[mw4-2022-10-22 (github).log](https://github.com/mworion/MountWizzard4/files/9847986/mw4-2022-10-22.github.log)

**Comment by mworion** [comment]
Hi Razvan,
sorry to hear. I had a similar report and made 2.2.7 for it and it was solved. To find out,
please post the full log as I check them automatically and please have a look after a false solve in your /temp folder in your work dir. There should be a file temp.wcs. Please post this file as well.
Michel

**Comment by razvan-astro** [comment]
Hi Michel,

Attached are the requested files.  In mw4-2022-10-22.log you will see the first model I aborted just after starting it ( I don't remember why). The second attempt ran with all the stars. Unfortunately didn't notice the plate solving failures as after starting the model building, I went to help a friend with his setup. 

[mw4-2022-10-22.log](https://github.com/mworion/MountWizzard4/files/9864870/mw4-2022-10-22.log)

Also attaching temp.wcs (from which I removed SITELAT and SITELON; also renamed to temp.wcs.txt to be accepted by Github) but I don't think it will help because it shows the last plate solve of the _successful_ model build which I ran about an hour later after I reverted to the earlier ASTAP. I can say this based on the timestamps. I didn't know temp.wcs would have been useful, otherwise I would have saved it. 

[temp.wcs.txt](https://github.com/mworion/MountWizzard4/files/9865034/temp.wcs.txt)

I'm also attaching the log (mw4-2022-10-23.log) from this separate build. By then the UTC day had changed as my local time now is EDT.

[mw4-2022-10-23.log](https://github.com/mworion/MountWizzard4/files/9864891/mw4-2022-10-23.log)

Something I did try on that night after noticing the model failures: I opened ASTAP (the new one) and loaded one of the images that failed to solve, then attempted to solve it there. It was successful. This suggests an integration problem rather than a solving problem. 

In case it's useful, I'm also attaching the FITS header from the first image which failed to solve (again, with SITELAT and SITELON removed). 

[image-001.fits.header.txt](https://github.com/mworion/MountWizzard4/files/9865055/image-001.fits.header.txt)

Thanks again for looking into it.

**Comment by razvan-astro** [comment]
If you cannot reproduce the error, I don't want to add a burden for you since there's already a newer version of ASTAP and if it's a persistent problem with it, others will encounter it as well so you'll get more data; in my case it will be a while until I can get out again (the camera's cooler stopped working on the same night and needs a warranty repair). 

Let me ask something else, something more general, though: is it possible with MW4 2.2.7 to trigger plate solving based on the existing saved images (which I still have) by invoking a particular method (even if the functionality is not exposed in the UI)? That is, to jump directly into the workflow at that point. Then I can try on my end. 

Thanks.

**Comment by mworion** [comment]
Sure you could do, please open the image window, there you could load any FITS image and plate solve it. So for test it's exactly the same procedure.

**Comment by razvan-astro** [comment]
Excellent, so I did that test on the same computer with the images taken in the field from the first session when plate solving failed. 

- the error was reproducible with ASTAP v2022.10.19a. The earlier v2022.09.10 as well as the newer v2022.10.22 work fine (the latter is good news).
- I compared temp.ini and temp.wcs between v2022.10.19a and v2022.10.22. They were identical (except for the ASTAP version string that appears in the PLTSOLVD field (which also means that ASTAP successfully solved the image even when that exception occurred. This matches my experience in the field when loading the FITS file directly into ASTAP worked).
- I had TRACE logging in MW4 in both tests. I'm attaching the log in case you see something. There are two separate launches of MW4, the first one when ASTAP v2022.10.19a was installed and the second one after installing v2022.10.22. I closed MW4 in between the tests. The FITS image was the same. 

Now, based on the fact that the error no longer occurs with the latest ASTAP, I would suggest to close the bug. I hope it does not re-occur. I've attached the log just in case it helps with understanding the cause or dealing with a possible re-occurrence. 

Thanks.

[mw4-2022-10-29.log](https://github.com/mworion/MountWizzard4/files/9892657/mw4-2022-10-29.log)

**Comment by mworion** [comment]
Hi Razvan,
closing the issue. Still the reason is exactly the difference of this file. Could you post both files ? I would like to check, why the satrapy library handles this different.
Thanks for this precise analyses from your side.
Michel

**Comment by razvan-astro** [comment]
Attaching the two temp files (with SITELAT and SITELONG removed from temp.wcs). These are from the attempt with ASTAP v2022.10.19a (as mentioned, the files were identical when I tried with v2022.10.22 on the same image). If you are still interested, I can share the v2022.10.19a installer (I wouldn't ask you to spend the time, just saying in case you want). 

[temp.ini.txt](https://github.com/mworion/MountWizzard4/files/9895991/temp.ini.txt)
[temp.wcs.txt](https://github.com/mworion/MountWizzard4/files/9895996/temp.wcs.txt)

**Comment by mworion** [comment]
Hi Razvan,
thanks for the files. For your informations: it was a little bit difficult to find out and the message of the library was misleading. Problem with the ASTAP version was that Han had a line 1 character longer as allowed in FITs Text file. When parsing the string, astropy expects instead of longer lines a new line starting with CONTINUE, which was not there. Han seems so fix that in later releases. For a possible 2.2.8 I made a workaround dropping two long lines.
Michel

**Comment by razvan-astro** [comment]
Thanks for looking into it! At least we know the nature of the problem causing that surprising error message, should they happen again elsewhere.
