### ISSUE TITLE
Cannot start MW4 2.2.7, log reports EphemerisRangeError

### ISSUE THREAD

**Issue by yzhzhang** [mworion/MountWizzard4#286]
Hi,

I noticed today that after restarting my PC, I cannot start MW4 2.2.7. After hitting MW4_run.bat, the blue MW4 welcome screen flashed, but then disappear and nothing show up. Looking at the log (attached), it reports some EphemerisRangeError. Can you help checking what's wrong on my side, and advise how to proceed? Thanks!

Yizhou

[mw4-2022-12-15.log](https://github.com/mworion/MountWizzard4/files/10233520/mw4-2022-12-15.log)

**Comment by mworion** [comment]
Hi Yizhou,

the ephemeris file has end of life.
Please replace the de421_23.bsp file under /data with the zipped one under [https://www.dropbox.com/s/glqx2zgz21pjy ... p.zip?dl=0](https://www.dropbox.com/s/glqx2zgz21pjy1l/de421_23.bsp.zip?dl=0).
I will do an update in v2.2.8!

see entry in [https://www.10micron.com/forum/viewtopic.php?f=18&p=15720&sid=b88855ae23872e222cdd494886848b99#p15720](url) in 10micron forum.
Michel

**Comment by yzhzhang** [comment]
Thanks! Seems working!

**Comment by mworion** [comment]
Yes, still ephemeris has some end of life in.
