### ISSUE TITLE
Polar alignment problem slewing incorrectly

### ISSUE THREAD

**Issue by abdiastroboy** [mworion/MountWizzard4#289]
**Describe the bug**
When trying to use polar alignment feature after building a model the selected star is confirmed however the mount slews diametrically opposite. However in HEMIS in the normal mode the selected star correctly gets slew to. The work around is to slew to the star from the hand controller which works everytime.

**To Reproduce**
Steps to reproduce the behaviour:
Build a 12 point model
Go to hemis
polar align option window
select star for example sirius
it then confirms sirius but slews completely wrong

**Expected behavior**
to slew to Sirius with a small offset which then allows polar alignment by centring star in crosshair

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10
Mwz 4 beta 7
Gm 1000 micron 
southern hemisphere

Logs attached
[mw4-2023-01-07.log](https://github.com/mworion/MountWizzard4/files/10366296/mw4-2023-01-07.log)

**Comment by mworion** [comment]
Hi abdiastroboy,
Thanks for the logs. This was a fault 1. order from my side (ra in degrees instead of hours). I had this right in v2, but due to refactoring error this was in since the beginning of v3. Thanks for finding out. In beta it should be fixed.
Michel

**Comment by mworion** [comment]
beta8 with the fix in online now.

**Comment by abdiastroboy** [comment]
ok excellent i’ll try tonight , its clearOn 8 Jan 2023, at 04:39, Michael ***@***.***> wrote:﻿
beta8 with the fix in online now.
