### ISSUE TITLE
What is this information line?

### ISSUE THREAD

**Issue by mhambuch** [mworion/MountWizzard4#29]
Hi Michael, this not an issue but a question. What is the meaning of this line, especially the number? Tried yesterday to make a first model and had here values above 10. Thanks

![Img](https://user-images.githubusercontent.com/63575440/82644411-8fd99580-9c11-11ea-9a0c-db8819d11b49.png)

**Comment by mworion** [comment]
Marc,
the number (at least will stay in the beta status of MW4) tell you how many parallel threads are running at the same time. This gives some hints how busy the system is and if there might be some bottleneck (mostly I/O related). values below 20 are ok. Values up to 10 are normal when starting or doing things. If you are in steady state, just main window open it should be max 2-3.
This might not relate to any cpu load !
Michel

**Comment by mhambuch** [comment]
Thanks a lot Michel
