### ISSUE TITLE
Issues with photometry

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#290]
When using the "Image" button, in particular, the associated window and operations of the image processing. 

I found when you load a FITS file, the image loads and can be solved. The issue is with the other tab assessments i.e. HDR, Tilt square, Tilt triangle etc.
Here, they do not load or appear once the image is solved. I found if I clicked the "Photometry" box, these all loaded correctly and I could see the results in their separate tabs but if I untick then reapply the Photometry tick, all the results disappeared and would not respond. If I opened another image file, the image would load and display correctly but the other assessing tools would be blank (even with Photometry ticked) and the window would respond as "Not responding" for several seconds.

Just to note, the FITS file was not captured via MW4 v3beta, it was captured with Voyager and opened with MW4.

My version of Python is 3.9

**Comment by mworion** [comment]
I tested this with standard FITS files (still not all done by MW4 and it worked. So I need a log file from you to check:
Please enable Loglevel to "Debug" under update / logging.
Try to load the image and enable / disable photometry.
You will find the log in your work dir / subdirectories log
Please drop it here.
Please ZIP the FITS File which does not work
Please drop it here as well.
Many thanks.
Michel

**Comment by rprangley** [comment]
Hi Michel,

My apologies for the delay. Please find attached two .zip folders you seek containing two screenshots, two fits files and two log files.

[MW4_Debug.zip](https://github.com/mworion/MountWizzard4/files/10444030/MW4_Debug.zip)

**Comment by rprangley** [comment]
Here is the other .zip folder with the second fits files.

Best Regards,

Rowan
[MW4_Debug_2.zip](https://github.com/mworion/MountWizzard4/files/10444037/MW4_Debug_2.zip)

**Comment by rprangley** [comment]
HI Michel,

Just to note, the images were taken with a QHY268C. Could the bayer of the image cause an issue?

Best,

Rowan

**Comment by mworion** [comment]
Hi Rowan,
the hint with bayered images was a good hint. In overall tricky. As result the following:
1: In the fits file there is the hint that the camera uses a BayernPattern, but under FITS Keyword "FILTER" (which is strange), missing the right keyword "BAYERPAT" and in addition not hint which pattern is used anyway. So debayering is not really possible. So voyager should change this. I see no other imaging app which does this in this strange way.
2: Even though MW4 tries to analyze this image anyway. First with the large size, analyzing could take up 15-60 seconds (the timeout will come). So the missing response might be one of this behavior.
3: Still if you wait long enough, MW4 will throw a failure as this data really could not be analyzed as there is no fitting PSF function.
4: If you manually enter the right keyword for the pattern and define the right pattern, which is btw. most probable "GBRG", MW4 had a bug in calculating the image size, which I have to fix and will be published in the next beta (3.0.0beta10) later.

With doing this all and waiting 15s, you will get all the informations:
![Bildschirmfoto 2023-01-18 um 20 54 53](https://user-images.githubusercontent.com/6632980/213281361-fc24bc9d-25ba-4bac-a801-2273758ee549.png)
![Bildschirmfoto 2023-01-18 um 20 55 01](https://user-images.githubusercontent.com/6632980/213281371-784e6020-e9ae-4042-8f88-41fdf64f8f0a.png)
![Bildschirmfoto 2023-01-18 um 20 55 17](https://user-images.githubusercontent.com/6632980/213281385-3e8ade3b-bde3-408e-8ff0-b4aaa4d4cac2.png)

One remark: On these large image chip cameras analyzing as well as modeling could be done more easy and faster if you are using binning. you don't need more that 1500 pixels to do this job.

Michel

**Comment by rprangley** [comment]
Thank you Michel! I will test this.

Just to check, is the keyword you have entered under "Filter",  "Matrix__"?   Or is this where you type "GBRG" or the applicable bayer filter orientation?

Best,

Rowan

**Comment by mworion** [comment]
… you have to add a new FITS header  keyword named. BAYERPAT with a value of GBRG

Von meinem iPad gesendet

**Comment by rprangley** [comment]
Thank you Michel!

I appreciate your time and feedback helping me with this!

This can be marked as "closed".
