### ISSUE TITLE
Problem with dome simulator

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#291]
Another issue I found - which is probably an issue caused by me not MW4 - is finding the 3D dome simulator viewing window. Following your previous instructions using MW4 v2, I found the 3D dome window but in the beta version, I cannot find it nor when I click or double click the "dome" indicator, the 3D dome simulator does not appear.

Am I doing this wrong? 
Is it possible to assign an actual button to launch the 3D dome simulator?

**Comment by mworion** [comment]
Hi,
this is simple, there is a button already there at top level. You only get it of the mount is connected (otherwise the positions as well as the location of the mount is not available).
Once the mount status moves to green and everything works, the text changes from Mount to Mount3D. If you press this button (only possible when Mount3D as text), the the simulator window opens.

![2023-01-10-14-14-12-MountWizzard4_-_v3 0 0b9](https://user-images.githubusercontent.com/6632980/211574945-57c6e5ca-2223-4bd6-b355-4192bfd06a79.png)

Hope this helps.
Michel

**Comment by rprangley** [comment]
This is perfect Michel. Thank you!
