### ISSUE TITLE
GUI for Mount On / Off

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#292]
The location of the "mount on" and "mount off" buttons have moved to another tab. This one is not a big issue but it did stall me till I found it's new location.
Will these buttons return to their original position or back to the initial start-up screen? It's not a big issue for me but the thinking on the MW4 v2 user journey, it was a single click to start the mount and now it's multiple clicks.

Happy to learn your feedback to my comments and thank you for your time. If any of these are known issues or are not applicable, please ignore my above comments.

**Comment by rprangley** [comment]
Cheers Michel! The "mount on with MW4 startup" is excellent. I've adopted this method
