### ISSUE TITLE
Delta T expiration difference

### ISSUE THREAD

**Issue by nocturnalguy** [mworion/MountWizzard4#293]
Delta T expiration indication ( 2022-11-03) in MW4 v3.0.0b9 does not match the indication of the 10micron control box update indication (2023-11-03). See attached screenshot

Martin

![Delta T expiration_230109](https://user-images.githubusercontent.com/122407767/211672664-93b51c39-2c05-4cac-b1b3-11e8d82ab157.PNG)

**Comment by mworion** [comment]
Hi Martin,
simple to explain: MW4 shows the downloaded data inside the mount. The window to the left shows the data of the 10micron updater program available. This is not the data from the mount !

My guess is that the updater program take the data and tries to give a prognosis, how it would be, but finally the relevant topic is, what the mount reports back in terms of expire date. And this value is consistent to what MW4 shows.

![Bildschirmfoto 2023-01-11 um 16 52 35](https://user-images.githubusercontent.com/6632980/211853421-24c50c28-ab97-48a0-bf86-5f97e7ce475d.png)

Hope this helps.
Michel

**Comment by nocturnalguy** [comment]
Hi Michel, thank you for the clarification
Martin

________________________________
Von: Michael ***@***.***>
Gesendet: Mittwoch, 11. Januar 2023 12:56
An: mworion/MountWizzard4 ***@***.***>
Cc: nocturnalguy ***@***.***>; Author ***@***.***>
Betreff: Re: [mworion/MountWizzard4] Delta T expiration difference (Issue #293)


Hi Martin,
simple to explain: MW4 shows the downloaded data inside the mount. The window to the left shows the data of the 10micron updater program available. This is not the data from the mount !

My guess is that the updater program take the data and tries to give a prognosis, how it would be, but finally the relevant topic is, what the mount reports back in terms of expire date. And this value is consistent to what MW4 shows.

[Bildschirmfoto 2023-01-11 um 16 52 35]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6632980%2F211853421-24c50c28-ab97-48a0-bf86-5f97e7ce475d.png&data=05%7C01%7C%7C19a8d4f1f11d4eb6e07f08daf3ec7015%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638090494056185911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vf1s7eQwcWZr9OLMkKBRjWiJIFh04YoFKLRyo3FSakg%3D&reserved=0>

Hope this helps.
Michel

**Comment by mworion** [comment]
Ok, closing it
