### ISSUE TITLE
MW4 instantly crashes

### ISSUE THREAD

**Issue by nocturnalguy** [mworion/MountWizzard4#296]
As soon as MW starts, all its windows open, but in less than a second MW crashes/dissapears.
Tried reinstaling Python and MW and nothing changed.
Had no problems the day before. Did not update anything.
Windows 11 and MW 3.0 b9 and b10.

[startup-2023-01-22.log](https://github.com/mworion/MountWizzard4/files/10473758/startup-2023-01-22.log)
[mw4-2023-01-22.log](https://github.com/mworion/MountWizzard4/files/10473759/mw4-2023-01-22.log)

Cheers
Martin

**Comment by mworion** [comment]
Hi Martin,
there is a discussion ongoing in a used external library so far with no clue which might be related to this topic. It's something to openGL, but I do not know.
From my point I cannot see anything in the logs (other that the exit code which states a memory violation - an this hardly related to a python script which does not access memory directly).
But anyhow: please delete the file 'profile' in you work dir and rename 'config.cfg' if you have used this profile or also delete this file. Then start again. At least you get a clean startup, which should conclude your situation. After that, you could reload your last used profile again.
Hope this helps.
Michel

**Comment by nocturnalguy** [comment]
Hi Michel
I first deleted both files you mentioned but had no success.
Luckily after I deleted all files (images) in the image folder, MW started working again.
Cheers
Martin

**Comment by mworion** [comment]
Martin,
strange as there is no relationship between MW4 and the images as soon as you delete the profile files.
Do you know if you had the image window open the last time MW4 started and which image you have loaded ? But as I said not relationship there.

We can keep this thread for further communication, but I close the issue with won't fix as I do not know what to de.

Michel

**Comment by nocturnalguy** [comment]
Michel,
I usually do not use the image window open, but I am not 100% if last time it may have been open by mistake.
Yes, that was reaally strange, but luckily it worked out, maybe it was just coincidence as I first tried deleted the files you mentioned but had no success till I restarted my PC and then just to free up some hdd space I deleted all the image files.
Cheers
Martin

**Comment by mworion** [comment]
Martin, thanks for the feedback. If you experience this again, please try to „freeze“ the setup -> log files, config folder, last image used. My hope is that if I start in the same environment I could see this with a debugger.
Anyway have fun using MW4,
Michel
