### ISSUE TITLE
Problems loading Python on pc

### ISSUE THREAD

**Issue by magsterone** [mworion/MountWizzard4#297]
So here is the sequence so far;
--I tried the YouTube video directions and when I d/l the zip file and try to open the pya file I get a request from windows for an app to open it with?!
--ok, I am preparing to dash into traffic. ;). I am a Mac guy who only uses a pc for this hobby/obsession.  When I open terminal I get c:\users\magst    How do I go about this?
--I get python3startup.pyz is not recognized as an internal or external command, operable program or batch file
--I got a new result, python was not found; run without arguments to install from the Microsoft store, or disable this shortcut from settings> manage app execution aliases
--I am running and dodging traffic now and I am losing my mind.  I remember why I have Macs now.  I downloaded python 3.10.9 and now I get “invalid syntax”  ;)

Would love to use this program but will be unsure of mental status when resolved. ;)

**Comment by mworion** [comment]
Hi,
made an actual video step by step using new python install and mw4.
[https://www.dropbox.com/s/yha8f0thf7vnwtr/install.mov?dl=0](url)
You find the docs (updated) here: 
[https://mworion.github.io/MountWizzard4/install/index.html](url)
if there is any problem, please take the mw4-yyyy-mm-dd.log file and post it here. These are located in workdir (if v2.x) or subfolder /log in workdir.
If you have python 3.10 installed you could not install v2.x (as it is limited to python 3.9 max and the script will install v3 beta instead.
Hope this helps.
Michel

**Comment by magsterone** [comment]
When select either link I get the following:

No results matched your search.

You could search [all of GitHub](https://github.com/search) or try an [advanced search](https://github.com/search/advanced).

**Comment by mworion** [comment]
Sorry, I missed the formatting. The links are working now. Please redownload startupScripts.zip

**Comment by magsterone** [comment]
I appreciate your help in this but I think I have confused you.  I use a pc for this program not a Mac.  I made the comment about “this is why I own a Mac" due to the difficulties to me me of using pc’s.  Can you send a link to video for installing on a pc.  Sorry for the confusion.

Joe

**Comment by mworion** [comment]
Hi Joe,
no problem, here the video for windows. It's realtime. Please download the actual files.
The video shows also the location of the log files I need if there is going something wrong.

Michel

https://www.dropbox.com/s/8weivv8xfmn319i/install_windows.mov?dl=0
