### ISSUE TITLE
Unable to install MW4 v3

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#298]
Dear Michel,

Today I tried to install v3 of MW4, but got a "failed to install" message. The log file is attached.

Nicolàs

[mw4-2023-01-29.log](https://github.com/mworion/MountWizzard4/files/10529914/mw4-2023-01-29.log)

**Comment by InFINNity-Deck** [comment]
Hi Michel,

issue solved! I was running Python 3.8.2, which should be fine according to the documentation. I have upgraded to 3.10.9 and now works just fine (after correcting the environmental vars to make Path point to the new Python folder).

Will run it if we ever get some clear skies again!

cheers,
Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,
python 3.8 should be ok. But after searching I found that you have to use 64 bit python as a library dropped 32bit support.
Michel
