### ISSUE TITLE
Direct Refraction Update Source from Environment Data in v3

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#299]
Dear Michel,

Running v3 of MW4 I found a difference in how Refraction Update Source from Environment Data is shown in the Environ-tab. In 2.2.9 the data that comes directly from the mount is shown as Direct, but in v3 this seems not to be working and I need to connect to my MGBox using ASCOM to see the data, which is then shown as Sensor while the fields under Direct remain empty.

![afbeelding](https://user-images.githubusercontent.com/66182061/215335557-b886d620-d61d-4db5-8b43-446bf7f7f6b4.png)

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,
yes there were some updates in UI as it was a little bit confusing. Did you enable the direct driver? I have the same setup (MGBox) directly attached:

![2023-01-29-15-12-01-MountWizzard4_-_v3 0 0](https://user-images.githubusercontent.com/6632980/215335872-20b0bc97-ec7e-4f55-87bc-25c0bb99a965.png)
![2023-01-29-15-12-40-MountWizzard4_-_v3 0 0](https://user-images.githubusercontent.com/6632980/215335880-bd3f25ba-c4eb-4891-9691-de78744465cf.png)

Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

thanks for your swift answer. Found the Direct-setting, works as always (now also have the MeteoBlue data):

![afbeelding](https://user-images.githubusercontent.com/66182061/215336106-56b1fe10-0844-4f05-ac2f-5fb548366597.png)

Nicolàs

**Comment by mworion** [comment]
OK good. Please check direct as well and choose auto (no tracking or continuous) for enable refraction update. The status button on top tells you exact how refraction update is working (regardless which source if known to MW4).
