### ISSUE TITLE
Satellite Module: float division by zero

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#30]
When selecting database and and object a 'Division by Zero' is thrown in cmd window. See screen shots.
Active.txt and visuals.txt get updated and contain valid data. They are also attached.

![2020-05-22_15h23_16](https://user-images.githubusercontent.com/65772654/82673828-b237d700-9c42-11ea-982f-5cd77a4358d7.png)
![2020-05-22_15h24_47](https://user-images.githubusercontent.com/65772654/82673854-b9f77b80-9c42-11ea-91cf-e401ebc1a9d6.png)
![2020-05-22_15h24_53](https://user-images.githubusercontent.com/65772654/82673857-bc59d580-9c42-11ea-9e3d-d451f56d2edb.png)
[active.txt](https://github.com/mworion/MountWizzard4/files/4668337/active.txt)
[visual.txt](https://github.com/mworion/MountWizzard4/files/4668338/visual.txt)

**Comment by mworion** [comment]
Rüdiger,

I think I found the problem: Your PC is set to German, right ? The library has a problem parsing the TLE strings when not set to English. If you could give it a try, you're welcome, but I wait now for the response of Brandon, who is maintainer of the skyfield package.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,
yes, you were right! Switching to US solved it, but this is no persistent solution, since all the other applications do not work anymore :(
![2020-05-22_16h13_45](https://user-images.githubusercontent.com/65772654/82676950-823f0280-9c47-11ea-96c8-bd3eab2f99db.png)

**Comment by Ruediger3** [comment]
Hi Michel,
0.150.17b1 works with German separator.
Thank you!

**Comment by mworion** [comment]
I built a 0.150.17b1, which should be able to run with German setting. It would be nice to give it a try.
Michel

**Comment by mworion** [comment]
Actually reproducible.

**Comment by Ruediger3** [comment]
Are you sure about 17b since we have been already at 20b?
Not visible for installation yet

**Comment by mworion** [comment]
Hi Rüdiger,
are you willing to make a counter test now ? if so please go to the non functioning v0.150.20.
Check if it's still broken.
Close MW4.
Open power shell
goto your work directory
go to  virtual environment with command:

venv/Scripts/activate

- prompt should change to heading (venv) ....

install new library with command

pip install https://github.com/brandon-rhodes/python-sgp4/archive/master.zip

close powershell and start MW4 v0.150.20 again. This should do the trick. 

Please let me know if you do so.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I can confirm this works. I had to manually install sgp4.
Do I have to that anytime I install an update?

Thanks Rüdiger

BTW: there is also an issue with the first pass. It is always in the past (red box)


![2020-05-28_19h37_08](https://user-images.githubusercontent.com/65772654/83174384-9f2d7700-a11a-11ea-9142-a20142d08acf.png)

**Comment by mworion** [comment]
Thanks for testing,
Brandon will release the new library when we sign it off (what we will do now). from That point on I will release 0.150.21. Then it's done.
I've seen the point with the first pass. I played around. I this version I will have a better selection !
Michel

**Comment by Ruediger3** [comment]
Thanks Michel for your great support!
