### ISSUE TITLE
Meteoblue not showing correct local date?

### ISSUE THREAD

**Issue by aphelyon-net** [mworion/MountWizzard4#300]
Just installed Version3. 
I've configured the metoeblue api to test. It appears that it's showing as of local time, but UTC is not matching?

![Screen Shot 2023-01-30 at 12 49 45 am](https://user-images.githubusercontent.com/69456746/215341973-1832c974-114b-43b4-b6f3-3526b4af1d3c.png)

Meteoblue is reported days as 30Jan onwards.

<img width="506" alt="Screen Shot 2023-01-30 at 12 52 04 am" src="https://user-images.githubusercontent.com/69456746/215342094-2a0922f1-04c5-4a6d-a067-034e4d99121f.png">

**Comment by mworion** [comment]
Hi,
there is a small issue about changing UTC / Local as it will update only on startup correctly (setting under settings/user Interface).
Actually the json used by MW4 looks different. Which data are you showing?
Michel

**Comment by aphelyon-net** [comment]
Im using the https://my.meteoblue.com/packages/basic-1h?apikey=XXXXXXXXXXXX&lat=-31.7885&lon=117.329&asl=297&format=json

I tried using just apikey, then daily. Also tried local time. 

Im not sure if this should be showing daily , or hourly. It seems to also be showing times 12hours earlier as the first entry, where Id expect closet rounded down start time on first load, then populating time from thereon.
![Screen Shot 2023-01-30 at 7 42 52 am](https://user-images.githubusercontent.com/69456746/215362739-3a83e0e1-02ba-4318-b3ca-97fb5dfe1d11.png)

**Comment by mworion** [comment]
MW4 is using a different api (always asking for UTC), which should be ok. In your case (seeing set to local time) the purple line is correct highlighted.
You're point about what should be the start is valid, but meteoblue does only 2 times a day a calculation. So MW4 does only retrieve this data 2 times a day. For a simpler processing, MW4 builds the GUI each time it collects the data. Meteoblue does also send a complete set (beginning with 00:00 UTC) in any case, so I do not cut out data sent from meteoblue just for transparency reasons.
I think about moving the cursor and position regularly to a better position. let's see.
Michel

**Comment by aphelyon-net** [comment]
OK thanks for reviewing that. It would be good if somehow we could see 6hours from the current date. Not sure if it can't be done dynamically.. if a reload button would suffice what would recalc and display from the current hour and display the future 12hours or something similar.

**Comment by mworion** [comment]
You have a scrolling of the data anyway for the next 3 days in that list. 
If I find a solution for dynamic scrolling...

**Comment by aphelyon-net** [comment]
Oh! Indeed yes :) I didn't see a scrollbar, but using my mouse I see that works thank you.
I leave this then to your discretion whether to deem this as requiring an update or not

**Comment by mworion** [comment]
Good point about the scroll bar. I put it onto the todo list.
Michel

**Comment by mworion** [comment]
Next release there will be some scroll bars in it.

![2023-02-01-19-45-38-MountWizzard4_-_v3 0 0](https://user-images.githubusercontent.com/6632980/216147365-647a06b6-531f-4da9-aa20-1a1e79c4746a.png)

Michel

**Comment by mworion** [comment]
Hi,
if you install 3.0.1a1 you should be able to test the scroll bars.
(Internal Updater, write 3.0.1a1 in available version text field and click start updater)
Michel

**Comment by aphelyon-net** [comment]
Fantastic, thanks. Will continue testing and report if any other issues found.
