### ISSUE TITLE
Flats Generator won't turn on when Flip Flat "Light On" button is clicked: Accessories > Cover > ASCOM  - Device found - ASCOM.Giotto.CoverCalibrator 

### ISSUE THREAD

**Issue by rprangley** [mworion/MountWizzard4#303]
**Describe the bug**

**New PrimaLuceLab Giotto flat panel and Alto 3 Motor in MW4: Light will not turn on.**

Setting the ascom driver under in MW4: Accessories > Cover > ASCOM  - Device found - ASCOM.Giotto.CoverCalibrator  connects through matched ports and a green MW4 connect colour is displayed.

Once connected, I attempt to turn the flat panel on by clicking the Flip Flat "Light On" button under the "Imaging" tab. The flat panel does not turn on.

To test proper operation of the flat panel; after disconnecting the driver form MW4 I then connected via PrimaLuceLab "PLAY" app and also via Voyager (separate instances and not at the same time). Both programs successfully turned on and off the light of the Giotto Flat Panel.

To note, I've noticed that the Giotto-Alto motor driver can only be used by one standalone program at a time. Multiple instances of connecting the driver to another program i.e. PrimaLuceLab "PLAY" app and MW4 does not work.

I have not tested the Flip Flat "Open", "Close" and "Stop" buttons as of yet due to bad weather. I'll test these soon.

Please find attached the log file.  

[MW4 Log.zip](https://github.com/mworion/MountWizzard4/files/10608520/MW4.Log.zip)

MW4 version is the recent v3.0 release.

Best Regards,

Rowan

**Comment by mworion** [comment]
Hi Rowan,

thanks for the report. This is a bug. Will be fixed in the next service release. Open and close should work, but please check. Unfortunately the interface for ASCOM is different to the ALPACA (I do not know why).

Michel

**Comment by mworion** [comment]
Hi Rowan,
if you install 3.0.1a1 you should be able to test the fix.
(Internal Updater, write 3.0.1a1 in available version text field and click start updater)
Michel

**Comment by rprangley** [comment]
Hi Michel,

Thank you!

I'll test this - along with the open/close operation - and will report back asap.

Best,

Rowan

**Comment by rprangley** [comment]
Hi Michel,

MW4 v3.0.1a1 successfully installed.

I can confirm cover will open, stop and close successfully using each applicable button.

Unfortunately, the flat panel will not turn on using the assigned buttons.

To note, the PrimaLuceLab Giotto firmware version is 1.3.1

I've tested this using PrimaLuceLab "Play app, v1.5.3" and the flat panel turns on and off.

I've seen that when MW4 connects successfully and you go to the assigned imaging tab, the "intensity" identifier box has a "-" visible. Could this be the issue? As in, MW4 auto sets the brightness level to "0" and since I cannot assign or toggle the brightness level manually, the Giotto flat panel stays at "0" and reports visually no brightness?

Could a manual value be added so the user can control brightness to a set level? 

At your service. 

Best Regards,

Rowan

**Comment by mworion** [comment]
Rowan,
I cannot test the driver without hardware, but I changed the settings of values. If I receive a brightness value from the driver, you could click on the value and change it.
This was true for INDi and should work for ASCOM as well.
I put it in 3.0.1a2. You give it a try.
Michel

**Comment by rprangley** [comment]
Hi Michel,

Sorry for my delay - I had to finish an acquisition before updating to v3.0.1a2

I'm please to confirm the 1a2 version update was successful.

I've completed a test and am excited to confirm that the brightness values from the driver are received to MW4 and as such, the Giotto flat generator turns on! 
From my test, the light must be turned on before brightness values can be changed, i.e. from 51 to 100. Once values are changed, brightness increases with nominated values.
Great outcome!

Many thanks for addressing this Michel!

Best Regards,

Rowan

**Comment by mworion** [comment]
Great to hear!
Yes. You have to turn it on. This is a glitch in ASCOM Interface specification as you don't have a property to set brightness.
Michel
