### ISSUE TITLE
Can't install MW4 on RPi4 Ubuntu 22.04

### ISSUE THREAD

**Issue by orfest** [mworion/MountWizzard4#304]
I can't install MW4 after trying all possible installation options. Please help.

Device: Rpi4 4GB
OS: Ubuntu 22.04

I have a very old installation which doesn't start because `ephemeris segment only covers dates 2018-12-27 23:58:51Z through 2023-01-07 23:58:51Z UT` and want to install a new version. Especially interested in 3.0.0, but any version will do.

Installing MW4 3.0.0 is not supported according to https://mworion.github.io/MountWizzard4/install/mw4.html
Tried 2.0 install scripts for Ubuntu and Mate, and they both fail.

`PyQt5-5.15.8.tar.gz` cannot be installed. This version of `PyQt5` goes into an infinite loop, consumes all RAM and eventually dies.
Don't see how to use one of the precompiled wheels.

[install.log](https://github.com/mworion/MountWizzard4/files/10687784/install.log)

After some hacking made the old installation of MW4 launch. Started the update to MW4 3.0.0 and it tries to collect the same `PyQt5` package, which is impossible.

When I try to collect older versions of `PyQt5` they complain about the `sip` package and I can't workaround that.

Not MW4 not supporting Python3.10 creates a mess, because Ubuntu 22.04 has given up on Python3.9, even package `python3.9-venv` no longer exists. Installed that from the `deadsnakes` ppa.

**Comment by mworion** [comment]
Hi orfest,
the v2 version could be updated with:

Please replace the de421_23.bsp file under /data with the zipped one under [https://www.dropbox.com/s/glqx2zgz21pjy ... p.zip?dl=0](https://www.dropbox.com/s/glqx2zgz21pjy1l/de421_23.bsp.zip?dl=0). See also 10micron forum
https://www.10micron.com/forum/viewtopic.php?f=18&t=1887

Actually the underlying external frameworks do not support aarch64. MW4 is prepared for that, but not these frameworks. So actually I'm sorry about this as I did also not manage to build the headers myself.

The release notes and the hint in 10micron forum show the unfortunate situation:
https://mworion.github.io/MountWizzard4/changelog/changelog.html#version-3-0.

Michel

**Comment by orfest** [comment]
Thank you, for the prompt response.
Updating the ephemeris helped indeed.
Then I'm stuck with `2.2.0`. Let's hope the dependencies get an update and become `aarch64` compatible again.

**Comment by mworion** [comment]
The actual version 2 is 2.2.9. So if you use the internal updater and enter in the text field 2.2.9, you will get the latest updates / fix if necessary. If everything works, keep the actual one.
