### ISSUE TITLE
Almanac Local time

### ISSUE THREAD

**Issue by aphelyon-net** [mworion/MountWizzard4#305]
It appears that the Almanac moonrise, moonset time is back to front for the rise/set times?

![Screen Shot 2023-02-12 at 4 10 22 pm](https://user-images.githubusercontent.com/69456746/218300158-1a090163-66be-4e2b-9401-594cf487e53b.png)

The current settings for my location with lat/long are:
![Screen Shot 2023-02-12 at 4 17 49 pm](https://user-images.githubusercontent.com/69456746/218300366-d50d9b11-51dd-4e7a-baf2-838d8350442c.png)

**Comment by mworion** [comment]
You're right. I checked the spec and the text fields for displaying type are mixed up.
Solved from 3.0.1a3 and the next official service release.
Michel

**Comment by aphelyon-net** [comment]
Thank you, installed 3.0.1a3, and confirmed is working/fixed.
