### ISSUE TITLE
MW4 won't boot mount on application startup or via dedicated button

### ISSUE THREAD

**Issue by rprangley** [mworion/MountWizzard4#306]
**Describe the bug**

Hi Michel,

I hope you don't think me a bug for hassling you with reports!

I noticed this bug last night while I was testing the Flip-Flap on/off but thought it was just a glitch. Starting things up tonight, the following occurred:

When launching MW4, the mount would not wake via WOL. I tried the dedicated "On" button within MW4 and still, mount would not wake/turn on.

Please find attached the log file from this evening test. Here, MW4 was launched and the dedicated "On" button several times. To wake the mount, I used another software called "WakeMeOnLan" and this woke the mount straight away. You will see in the log where MW4 connects to the mount. 
I used MW4 "Off" button to turn the mount off, followed by consecutive MW4 "On" button presses which yielded no results.

[mw4-2023-02-12.log](https://github.com/mworion/MountWizzard4/files/10715918/mw4-2023-02-12.log)

To confirm equipment; 10 Micron GM3000HPS  v3.0.8
IP and MAC address are the same in WakeMeOnLan and MW4.

MW4 v3.0.1a2

Sorry for the hassles.

Best Regards,

Rowan

**Comment by mworion** [comment]
Rowan,
not bothering at all. Did it work at some point in time? If not there are some glitches, which could appear in using WOL. So far I do not see any fault in the log.
Please have a look to https://www.10micron.com/forum/viewtopic.php?f=2&t=1578&p=13354&hilit=wol#p13354, which could show you some hint. That's the reason, why MW4 could be configured in multiple ways. 
In addition, if the mount computer was switched of from power supply, WOL does not start, as the MAC table might be lost in your switch.
The best way might be that you start with an IP address broadcast, which matches your subnet. 
Hop this helps.
Michel

**Comment by rprangley** [comment]
Good Morning Michel,

Many thanks for the link! Amending MW4's broadcast address worked; following the information in the link you provided, I changed this to 192.168.1.255

WOL via the dedicated "on" button worked as did WOL via starting a new launch of MW4.

Many thanks for your help!

Best,

Rowan

**Comment by mworion** [comment]
Ok, closing.
