### ISSUE TITLE
Mount address can be DNS as well

### ISSUE THREAD

**Issue by d33psky** [mworion/MountWizzard4#308]
**Describe the bug**
Minor regression: previous versions of mw4 accepted DNS addresses for the mount, this appears to no longer be the case.

**To Reproduce**
Use a DNS hostname as address for the mount.

**Expected behavior**
A connection to the mount address is made.

**Screenshots**
log says 'Mount  setting error  'gm2000hps' does not appear to be an IPv4 or IPv6 address

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - MW4 3.0

**Comment by mworion** [comment]
Sorry the check goes wrong. Fixed from 3.0.1a4 and available in next service release.
