### ISSUE TITLE
ASTAP: Application path is hard coded

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#31]
MW4 fails to find ASTAP if not installed in standard path, but somewhere else, since the path is hard coded.

**Comment by mworion** [comment]
Hi Rüdiger,
in 0.150.17b3 you should be able to config the path. please test !
Michel

**Comment by Ruediger3** [comment]
Hello Michel,

it is not working as expected. You can only change maximum up into the root of the drive, but you cannot change drive itself. See screenshot. It is only switching to root C:\

Workaround: You have to type in the other drive, then “chose”, then go back, browse through the directories. (see second screenshot).

 

Solving fails with following error: “Solving error: astap error” (see third screenshot).

 

Thanks

Rüdiger

 

 

 

Von: Michael <notifications@github.com> 
Gesendet: Sonntag, 24. Mai 2020 14:59
An: mworion/MountWizzard4 <MountWizzard4@noreply.github.com>
Cc: Ruediger3 <r.proske@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [mworion/MountWizzard4] ASTAP: Application path is hard coded (#31)

 

Hi Rüdiger,
in 0.150.17b3 you should be able to config the path. please test !
Michel

**Comment by mworion** [comment]
Hi,
v 0.150.17 should show an extended selection and checks online if valid selection are made in colors.
Michel

**Comment by Ruediger3** [comment]
Looks better, but still issues:
I selected the proper folder, but it shows in red and disables ASTAP.
As well the ASTAP.exe as the index G17 and G18 is in the same folder hnsky.

![2020-05-24_20h13_12](https://user-images.githubusercontent.com/65772654/82761489-1f8e6800-9dfb-11ea-8aee-0367be41dbb0.png)
:

**Comment by mworion** [comment]
Could you post the log ? I my windows environment (did not have a second drive), I see it enabled.

**Comment by mworion** [comment]
Copied astap folder to a network drive and renamed it. When selecting it works....

**Comment by Ruediger3** [comment]
Maybe case sensitive?
![2020-05-24_20h35_37](https://user-images.githubusercontent.com/65772654/82761931-236fb980-9dfe-11ea-9230-f70772630cd9.png)

**Comment by mworion** [comment]
If the exe file is written with upper letters, that might be the point

**Comment by Ruediger3** [comment]
here the log file...
[mw4-2020-05-24.zip](https://github.com/mworion/MountWizzard4/files/4674165/mw4-2020-05-24.zip)

**Comment by mworion** [comment]
logs are good, found an issue, quick fix in 0.150.19. Hope this works.

**Comment by Ruediger3** [comment]
Now it looks fine. It works as expected 😀👍
Thanks Michel for the quick help!
Please close the issue.
