### ISSUE TITLE
Cannot get MW4 to start after installing using startup.pyz

### ISSUE THREAD

**Issue by StratocasterBk** [mworion/MountWizzard4#310]
**Describe the bug**
I've tried multiple times to get startup.pyz to get MW4 going but it fails each time.  
**To Reproduce**
1. Downloaded appropriate installation files
2. Downloaded and installed Python3 version  (3.10.10)
3. Run "startup.pyz" as in your video

**Expected behavior**
I expect MW4 to start as per your videos.

**Screenshots**
[Terminal Saved Output 1.pdf](https://github.com/mworion/MountWizzard4/files/10937072/Terminal.Saved.Output.1.pdf)
[mw4-2023-03-09.log](https://github.com/mworion/MountWizzard4/files/10937074/mw4-2023-03-09.log)
[Python version.pdf](https://github.com/mworion/MountWizzard4/files/10937096/Python.version.pdf)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 10.15.7 (Catalina)
 - Browser [e.g. chrome, safari] Safari

**Smartphone (please complete the following information):**
N/A

**Additional context**
I'm sure this is not a bug but rather my doing something wrong.  I would be grateful for your help.

**Comment by mworion** [comment]
Hi,
strange result. I develop on a Mac and using python 3.10.10 as well without this problem.
Would you mind to install ffmpeg on your computer as well? See [https://www.hostinger.com/tutorials/how-to-install-ffmpeg](url), and restart the script again ? Probably you need to reinstall MW4.
Michel

**Comment by mworion** [comment]
Sorry again a more precise topic:
[https://stackoverflow.com/questions/75043231/upgrade-to-opencv-python-4-7-causes-import-error](url). So your situation looks like this issue. Do you have the intrusion to upgrade the OS anyway (as it is a little older)?

**Comment by StratocasterBk** [comment]
Danke Michel,

Will do.  FYI I un-installed Python 3.10 and installed 3.9 in its place.  Will try it all again with ffmpeg.

Oh just saw your second email.  I cannot update the system on this iMac as it is from 2013 and Apple won’t let me do so.  Am waiting for the M3 iMac to replace this computer in the Fall(?). But fortunately I also have an M1 Air, so I will try again on that computer.

Not the first time I’ve had an issue like that;  had a similar one with SBIG drivers which they recognize.  Can’t do what Apple won’t allow…!

Thanks,
Stan

PS ich heise Stanley Fertig aber bin ich nicht fix und fertig…!
Ich hatte deutsch gelernt seit 30 jähren aber seit langem habe ich nicht deutsch gesprochen und ich habe alles vergessen.
Ich bin der Vater von VIVA-TV!

**Comment by mworion** [comment]
Hi Stan,
no problem. If you move to the M1 Air, please use Rosetta emulator to get things done, see [https://www.astroworldcreations.com/blog/apple-silicon-and-legacy-command-line-software](url). If you want to keep the iMac, ill could do a special build for you, which might actually be compatible, but as Apple dropped support for Catalina I expect more of these issues upcoming.
I'll let you know how to get it.

Aber nein, das Deutsch ist immer noch sehr gut. 
Viele Grüsse
Michel

**Comment by mworion** [comment]
Ok, please try a new install of MW4 with the command

python3 startup.pyz --update-beta

This should work now.

**Comment by StratocasterBk** [comment]
In the gym, will try when i get back.  Thank you Michael!-stanSent from my iPhoneOn Mar 10, 2023, at 3:18 PM, Michael ***@***.***> wrote:﻿
Ok, please try a new install of MW4 with the command
python3 startup.pyz --update-beta
This should work now.

**Comment by StratocasterBk** [comment]
That did it Micahel, success!!  Woo-Hoo!

Big thank you for all you’ve done for us 10µ owners, and for me.

Cheers,
Stan


—
Stanley Fertig
20 Henry Street, PH3S
Brooklyn, NY 11201
***@***.***

**Comment by mworion** [comment]
Hi Stan,
traveling next week to New Jersey on a business trip cross US. I wonder where do you shoot images out of the light of New York without getting too much light pollution.
Good to hear that it worked. I keep that in the next service release as official, but I as soon as I have to support python 3.11, I have to drop Catalina support. Unfortunately this does not fit together.
Michel

**Comment by StratocasterBk** [comment]
Thank you again Michel!!  You are awesome!  Again, I’m well familiar with Apple dropping support for legacy platforms, went through that with SBIG.

For next week, first of all be aware that the weather will be bad Monday and Tuesday—rain and some snow.  Not enough to create a real problem but the skies will not be clear at all.  Wednesday and Thursday should have fairly clear skies and mild temperatures.  Then bad weather again starting Friday.   In the Spring it often rains in this part of the world.

For astrophotography I personally go 3 hours north of the city to a small mountain range/ski resort region called the Catskills.  My NYC astronomy club (aaa.org <http://aaa.org/>) goes there on New Moon weekends in the warmer weather.  In  NJ, we also sometimes go to a good site which I’ve been to called Jenny Jump—here’s the link attached.  JJ is managed by the United Astronomy Clubs of New Jersey (http://www.uacnj.org <http://www.uacnj.org/>).

Depending where and when you will be, I think Jenny Jump is the best bet.  Of course my club also has a group of formidable astrophotographers led by Stan Honda (www.stanhonda.com <http://www.stanhonda.com/>) who specialize in light-polluted astrophotography from the city:  https://aaa.org/event/urban-astrophotography-deep-sky-imaging-2023/2023-03-16/  

Incidentally I host our club’s podcast, AAASKY (www.AAASKY.nyc <http://www.aaasky.nyc/>).  I haven’t even used my 10µ yet—it’s new, sitting in my garage at my house in the Catskills, alongside a CDK telescope also in its crate from AGO Optical (http://agoptical.com <http://agoptical.com/>), in my opinion the best telescope maker in the US.  All that waiting for me to construct my Exploradome observatory, which I cannot start until the frozen ground thaws in April-May!!  I once started writing a humorous story about astrophotography in the Catskills where all the equipment and software fight with each other (I was using a Meade LX200 12”, which isn’t really built for photography), entitled “In Space No One can Hear you Swear”!!

Let me know if there’s anything I can do to help you.

Cheers,
Stan

**Comment by mworion** [comment]
Stan, 
many thanks for all the hints!
Michel
