### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mbalkham** [mworion/MountWizzard4#311]
**Describe the bug**
not used MW4 for a while. Now it wont start. Brings the flash screen up and gets half way through initialising before closing

**To Reproduce**
1. resart computer
2. CLick on MW4
3. wait a few mins for it to crash and close

**Expected behavior**
MW4 would open and run

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise
 - Browser chrome

**Additional context**

**Comment by mworion** [comment]
Please have a look to [https://www.10micron.com/forum/viewtopic.php?f=18&t=1887](url) as ephermeris might be outdated to solve your issue. If you provide a log I could check this.
Hope this solve your problem.
Michel
