### ISSUE TITLE
URL for Finals changed

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#313]
Hello Michl,

it looks like the URL for the finals.data at iers.org has changed. The old URL path /data/finals.data doe not work anymore.
the new one is https://datacenter.iers.org/products/eop/rapid/standard/finals.data

Please see screenshot below.

Cheers
Rüdiger

![2023-04-05_17h20_43](https://user-images.githubusercontent.com/65772654/230127692-8760b355-d570-465e-ae0f-1ea6aa735860.png)

**Comment by mworion** [comment]
Hi Rüdiger,
you're right, I've seen this, too. Already prepared for the next release.
Michel

**Comment by Ruediger3** [comment]
Many thanks and a nice evening!
Rüdiger

**Comment by mworion** [comment]
3.1.0b6 released

**Comment by Ruediger3** [comment]
Hi Michl,

tested and works fine. Thank you!

Cheers
Rüdiger
