### ISSUE TITLE
Increas precission of "Defined positions"

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#314]
Hi Michl,

currently the "defined positions" are stored with one decimal. For telescopes with long focal length this is not precise enough. The precision is less than the FOV. Is it possible to increase precision of these stored positions?

Thank you!
Rüdiger

![2023-04-05_18h02_49](https://user-images.githubusercontent.com/65772654/230138321-90d86bba-e2be-4de8-84ad-049feb3f2ef8.png)

**Comment by mworion** [comment]
Rüdiger,

sure, I'll add a decimal. In the next release it will be visible.

Michel

**Comment by Ruediger3** [comment]
Many thanks for the quick change, appreciated!
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michl,

thanks for implementing. I will test precision physically as soon as the weather allows.

Thank you!
Rüdiger
