### ISSUE TITLE
Toggle between UTC and "Local Time" fails (version 3.1.0b5)

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#315]
Hi Michl,

I experienced a strange behavior with the setting of time format. Toggling between UTC and local time, changes the time format sometimes, sometimes not, sometimes not for all variables. This is very strange. Please see the attached screenshot. Here the values are even mixed. 

All Screenshot were taken when set to local. Almanac just randomly displays UTC/local. 

Greetings
Rüdiger

![2023-04-05_19h15_17](https://user-images.githubusercontent.com/65772654/230155036-78f2debe-e9e1-4249-a10c-2984d98eadfb.png)
![2023-04-05_19h15_44](https://user-images.githubusercontent.com/65772654/230155095-3f04387a-4e15-4a0d-9af1-9794495c8284.png)
![2023-04-05_19h16_04](https://user-images.githubusercontent.com/65772654/230155174-d64a08f3-5427-450a-9a57-64ef626b7507.png)
![2023-04-05_19h18_18](https://user-images.githubusercontent.com/65772654/230155637-dadf5d0c-fb4b-4af4-9277-d3b368c53b2b.png)

**Comment by mworion** [comment]
Rüdiger,
thanks for the hint, will be solved next release

**Comment by mworion** [comment]
3.1.0b6 released

**Comment by Ruediger3** [comment]
Hi Michl,

installed b7 and it looks fixed now. Many thanks :)
Rüdiger
