### ISSUE TITLE
No update of Asteroids, Comets and Space Stations to mount

### ISSUE THREAD

**Issue by vich4man** [mworion/MountWizzard4#316]
Since recently I am not able to update asteroid, comet and space station data in my 10u mount via MountWizzard any longer.
I do not know if this is related to an update to MountWizzard or to an update of the 10u updater SW, as I had not been using the update feature in MW for a quite a while, and have updated both 10u and MW versions since.

This is what happens:
- When updating asteroids, comets or space stations via MW the 10u updater opens, but gets stuck while searching for the appropriate files quite soon. To me it looks as the script that MW is running does not match the UI of the updater. See screenshot example (when unsuccessfully trying to upload the data of "ZTF". I abandoned it after several minutes).
- deltaT (Earth Rotation data) can be updated without issues

Running latest 10u firmware (3.1.10) on GM3000 and GM4000 (same behavior), MW4 V3.1.0 (fresh install) on Windows 10 Pro (German language version).
I attached a screenshot and a log file.

[mw4-2023-04-21.log](https://github.com/mworion/MountWizzard4/files/11300079/mw4-2023-04-21.log)
![Screenshot](https://user-images.githubusercontent.com/95504176/233757426-72b1266c-4b01-459d-a70a-04a8406de1e5.jpg)

Thanks.

**Comment by mworion** [comment]
Hi
you are right, it's about matching UI strings of the 10micron updater and the windows versions. Unfortunately there were no ID's to UI objects which identify item uniquely.
I have to search for strings in object descriptions and these vary between windows versions and language settings.
I checked my setup (win10 Home, German language), which works (same updater, same firmware, same MW4 version), which does work fine.
If you would like, please do me a favor and set language to English in your setup and restart MW4 and check it again.

Another question to your screen shots. When I open the updater manually, I see in the update selection in total 5 checkboxes equally line by line.
In your screen shot I only see 4 entries whereas 1 line seems missing (4th one). Could you check how this menu looks if it is not hidden by the next menu ?

Many thanks.

Michel

![Bildschirmfoto 2023-04-23 um 11 46 24](https://user-images.githubusercontent.com/6632980/233832355-39d1f827-a7ca-4bb8-b5bb-7c2cf1d5f68f.png)

**Comment by vich4man** [comment]
Hi Michel,

thanks for looking into this.

I might have found the root cause.
The 10 micron control box updater window looks for me indeed like this:
![NoAdmin](https://user-images.githubusercontent.com/95504176/233851341-e74b60d4-e3d2-4652-9ebd-c013ad2aa346.jpg)
It has been like this for a while (I do not know since which update), apparently there is one line missing causing the MW4 script to fail.

I tried different things (uninstall, re-install, etc.), and I also ran the updater **with admin rights** (the standard user has no admin rights for security reasons).
And when running the updater **with admin rights** the UI looks OK (!):
![Admin](https://user-images.githubusercontent.com/95504176/233851339-17d22190-5f11-4e78-be08-3e902277d23c.jpg)

Apparently the updater has a bug when it is run without admin rights.
I will send an email to 10u to make them aware of this issue.

Best,
Stefan

**Comment by mworion** [comment]
Hi Stefan,

I run the updater without admin rights and it works ok. Something strange. Keep the issue open until we found out what really makes the difference for others as well.

Michel

**Comment by vich4man** [comment]
Hi Michel,

I was in contact with 10u by email. They confirmed that this is a bug in the updater SW and will correct it in an upcoming update.

CS
Stefan

**Comment by mworion** [comment]
Hi Stefan,
thanks for the update.
Michel
