### ISSUE TITLE
Watney Solver cannot be used under Win10

### ISSUE THREAD

**Issue by astroalex80** [mworion/MountWizzard4#317]
Dear Michel,

installed Watney on my Win10Pro Notebook. Really like it as seems to do very fast blind solving even without providing any imaging data. However, not getting it to run in MW4 as the field unter Settings>Devices is not turning green.

Below the sequence out of the log file.
[2023-05-26 16:35:29.089][I][      watney.py][ 256] No index files found
[2023-05-26 16:35:29.090][I][      watney.py][ 258] Watney OK, app: [F:\MountWizzard4\watney-cli/watney-solve.exe], index: [F:\MountWizzard4\watney-index]
[2023-05-26 16:35:29.090][D][  plateSolve.py][ 332] Framework: [watney], True, False
[2023-05-26 16:35:29.090][U][     mainApp.py][ 371] Message window: [Driver - WATNEY enabled - plateSolve]

Have provided the right path information and the index files are existing. 
Do I have to put them elsewhere?

(FYI, When hoovering over the "folder astronomy index" textbox on the Watney tab it says "path to astap star database". sure this is just a typo and not causing the error). 

Thanks in advance and kind regards,
Alex

**Comment by mworion** [comment]
Hi Alex, 
as the log says, the index files are not present. MW4 tries to check the number of files needed for a correct install. There might be some subdirs in your folder for different FOV, so you have to select further.
In case of my screenshot you need to select a dir ending with -v3.
MW4 checks the presence also during selection. You should see a red frame in case MW4 does not see the index files.

![Bildschirmfoto 2023-05-27 um 18 32 56](https://github.com/mworion/MountWizzard4/assets/6632980/49d4c215-c0bd-46a3-8aee-12479e2d4ee6)

I checked it and with present index files Watney works at least in my setup.
BTW: which MW4 version do you use. Your remark about the textbook is about the tooltips and not related to any function. I correct this entry next service release. Thanks for the hint.

Hope this helps.

Michel

**Comment by astroalex80** [comment]
Dear Michel,

thanks for your reply. Managed to select the index files properly ;-) 
However, solving still fails. Watney Desktop app is blind solving the image within a few seconds. When calling why MW4 an timeout is occuring (180 degrees - all sky and timeout 240 seconds).

Could you please give it a try to solve the image via MW4? As its too large (51 MB) to be uploaded here directly please take following download link from my online storage: [https://hidrive.ionos.com/lnk/sLyzRYXv](url)

The picture is all but good -  weak signal, few stars, no tracking but however it is solvable.


As you asked, I m having MW4 v3.1.0 installed. 

Also noticed, when loading an XISF file in the imaging tab solving with Watney is not possible because Watney is not supporting XISF.

Thanks for checking.

Kind regards,
Alex

**Comment by mworion** [comment]
Hi Alex,
tried it. 

First: there is no meta information at all in the file (RA / DEC). That's bad as you normally should know at least where your mount is pointing to. Otherwise you need very much time.

I used ASTAP blind solve and it took 65s to solve it.

Watney Online did not accept this files for whatever reason.

Watney did not solve after 300s for whatever reason. It just times out. From the aster solve I would guess that you need the Passes 10-11 (built using 640, 905 stars per square degree) database. But I'm not sure as I do not have information about your optical train.

You're right. I can load XISF files, but the solver accesses the original file. If it does not support XISF, solving will fail.

Hope this helps.
Michel

**Comment by astroalex80** [comment]
Thanks Michel. Strage enough Watney Desktop appilcation is solving it in seconds.
However its not a proper image anyway. 
My image train is an 355mm / 1535 mm Newtonain with an QHY268M (IMX571).

As figured out thanks to your help how to properly setup the index files, issue closed :-)

Kind regards,
Alex

**Comment by mworion** [comment]
You‘re welcome!

Von meinem iPad gesendet
