### ISSUE TITLE
UPBv2: Multible issues (INDIGO)

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#32]
Hello Michel,

I have tested features of UPBv2 via INDIGO and found following issues (v 0.150.17b1):

1. Variable power port is not correct (see screenshot).
2. Power port names are not forwarded.
3. Power values are not displayed (screen screenshot) 
4. Ports cannot be switched.

At that point I have stopped testing since there seems to a serious issue.

Thank you !
Rüdiger

![2020-05-23_14h05_49](https://user-images.githubusercontent.com/65772654/82730243-9abe2400-9cfe-11ea-9670-7c352dad1306.png)

![2020-05-23_13h53_30](https://user-images.githubusercontent.com/65772654/82730186-3b601400-9cfe-11ea-92b9-35606db08b2e.png)

**Comment by mworion** [comment]
Hi Rüdiger,

0.150.29b1 should support UPB, UPBv2, UniHedron SQR for INDIGO. Should be available tonight.

Michel

**Comment by Ruediger3** [comment]
Hello Michel,

unfortunately it is not working. Please see update on issue #33 
https://github.com/mworion/MountWizzard4/issues/33

Thank you!

Cheers
Rüdiger

**Comment by mworion** [comment]
OK then closing this one an follow up in #33
