### ISSUE TITLE
unable to update from v2 to 3.1 and bring settings etc over from v2

### ISSUE THREAD

**Issue by morrienz** [mworion/MountWizzard4#320]
follow on from discussion on 10micron forum.

Thanks so much for the latest  suggestions Michel.

I uninstalled all python versions ( 3.9 32 bit and 3.10 64 bit) and both launchers. Successful

I reinstalled python 3.10 64 bit. Successful

I reinstalled mw4 v3.1 into empty work folder. Successful and it ran at end of install.

I copied over only config folder from old v2 MW4 folder to mw4 v3.1 folder and restarted mw4 3.1. As before the run failed.

I have attached here the config folder contents, and the log file, all in a zip file.

Thanks for your help again
Chris 
[files.zip](https://github.com/mworion/MountWizzard4/files/11957124/files.zip)

**Comment by mworion** [comment]
There some issues to fix about robustness. Still in progress how to transfer maximum amount setting which could be reused.

**Comment by morrienz** [comment]
good idea to keep this open thanks Michel. I never did get it to fully transfer everything across to v3
Chris.

**Comment by mworion** [comment]
Chris,
once the v3.2b1 is published, please give it a try for a test (please make sure that you don't loose you actual install as it is beta). It's the maximum I could do with reasonable effort.
Michel

**Comment by morrienz** [comment]
I'll try that Michel. Do you mean try it by copying over the config folder from my V2 install to my Vb.2b1 folder, or did you mean try an internal update from v2 to v3.2b1?

Thanks,
Chris

**Comment by mworion** [comment]
Chris,
I try to figure out, what the best way for the test is and let you know.
Michel

Von meinem iPad gesendet

**Comment by morrienz** [comment]
Hi Michel, Im setting up a new windows machine with mw4 in it, is it ok to install python 3.11 or must it be 3.10? after i installed python 3.11 when i did the cmd virtualenv --version  i get back "'virtualenv' is not recognized as an internal or external command, operable program or batch file.". does that mean ive done something wrong? Chris

**Comment by mworion** [comment]
Python 3.11 will not work as it is not supported from all libraries. Ideally you take 3.10.11 64 bit.
Michel

**Comment by morrienz** [comment]
ok, thanks. ill uninstall and install 3.10

**Comment by morrienz** [comment]
Hi Michel, Do i have to do anything after install of python to get virualenv setup? after 3.10.11 python64 bit  install which cmd python --version confirms, (I ticked the box to create python path in the installer screen), when I then try virtualenv --version I get that same error message as before. I think MW4 is wonderful and I thank you a lot for it, but I am sorry to say that I really find the whole installation process for mw4 on windows very complicated and messy even after doing it a number of times, and that is with me being a software developer for many years. Can you not get us a simple one click windows installer for mw4 that installs everything we need? Even if it was just for the windows platform I think that would make lot of MW4 users very happy.
