### ISSUE TITLE
MW cannot connect anymore to latest nightly NINA

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#322]
Hello Michel,

I have just noticed, that MW cannot connect to the latest NINA V3 nightly 23. The server functionality was outsourced into a plug-in „SGP Server“. But even when installing and enabling it, no connection is possible.

![image](https://github.com/mworion/MountWizzard4/assets/65772654/c9a046a2-1a91-4309-b94a-ed8441dfb475)

I will attach the log in a second step.

Can you please have a look?

Thank you in advance!
Rüdiger

[mw4-2023-08-18.zip](https://github.com/mworion/MountWizzard4/files/12384069/mw4-2023-08-18.zip)

**Comment by Ruediger3** [comment]
Added Log

**Comment by mworion** [comment]
Hi Rüdiger,
I installed NINA nightly. And for some reasons when server enabled NINA does not how any webpage at all. You could check this by calling the webpages for SGP with your browser. NINA refuses all connections.
I thinks it's good that SGP Server is now in a plugin. I do not understand, why Stefan Berg added this many versions of context sensitive URL as SGP does exactly supports only on of them and NINA did it the right way in 2.x. As they changed to 3.x nightly they did not respect the case sensitive SGP implementations. 
So from my side I'm stuck as NINA does not respond even from Browser side.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

Are you raising a Bitbucket issue as MW author? I will chim in too. But I think it is better you raise it as developer.

CS
Rüdiger

**Comment by Ruediger3** [comment]
Update:
Created Bitbucket Issue: https://bitbucket.org/Isbeorn/nina/issues/1246/server-api-not-working-even-with-plugin

**Comment by Ruediger3** [comment]
Hi Michel,
can you please have a look on BB issue?
Ruediger

**Comment by Ruediger3** [comment]
Hello Michel,
I could connect locally, but still no success from MW. 

![2023-08-20_15h45_48](https://github.com/mworion/MountWizzard4/assets/65772654/dbc2c9c6-42b4-4de7-bd5d-01ee9a5aeda1)

**Comment by mworion** [comment]
Hi Rüdiger,
Stefan did some changes in x.4 version of the Plugin. I will release 3.1.1b0 for you for testing. Normally NINA should work then.
Michel

**Comment by mworion** [comment]
Rüdiger, 
3.1.1b0 is uploaded, please give it a try
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
I will test in 1,5 hours and provide feedback. 

Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
I have updated and tested. It works again. Many thanks for the quick help.

Viele Grüße und schönen Abend
Rüdiger
