### ISSUE TITLE
3.x installation routine failure

### ISSUE THREAD

**Issue by WTRVGL** [mworion/MountWizzard4#323]
Haven't used the 2.x version in a while and that didn't seem to be launching for some reason.

Decided to reinstall MW4 3.x using the new installation script but it seems to crash every single time on this line in the logs:

`[2023-09-03 22:06:01.419][I][    startup.pyz][  61]   WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe`

Don't have VS installed and I hope this isn't a requirement (didn't find anything about it in the documentation) since I'm running this on an Eagle with limited disk space.

Log:
[mw4-2023-09-03.log](https://github.com/mworion/MountWizzard4/files/12507892/mw4-2023-09-03.log)

**Comment by WTRVGL** [comment]
Seems to be happening as well when trying a fresh download of 2.x

**Comment by mworion** [comment]
Hi, 
I checked the log. The installer is OK, but a library seemed to drop support for windows 32 bit and / or python 3.8. The installer now does trying to compiler all sources itself, which normally does not work as you don't have a compete c development suit installed (and it is not intended anyhow)

So if this is your first install, please install python 3.10.11 64bit and do another run of the installer. 

Hope this helps.

Michel

**Comment by WTRVGL** [comment]
Using Python 3.10.11 64bit fixed this issue. 

Thanks!
