### ISSUE TITLE
Windows Startup scripts not Visible

### ISSUE THREAD

**Issue by h2ologg** [mworion/MountWizzard4#324]
**Describe the bug**
When using the link [https://github.com/mworion/MountWizzard4/blob/master/support/3.0/startupPackage.zip](url) to obtain the MountWizzard 4 download there is nothing but a RAW download/view. This is also true for 2.0.

**To Reproduce**
1.Click the link for both 3.0 and 2.0

**Expected behavior**
Should be info as shown in documentation for Installation including a download button.

**Screenshots**
![image](https://github.com/mworion/MountWizzard4/assets/48735466/6cf68ec6-c9c0-4d5d-8151-9a2002af429e)
**Desktop (please complete the following information):**
Windows 11

**Additional context**
I've attempted this in both Chrome and MS edge Same result.

Thanks for checking/fixing!

I have MW4 working on two other computers and enjoy/ proud of its functionality.  This is a new computer build.

**Comment by mworion** [comment]
Hi,
for some reason GitHub changed behavior. I did a try and if you follow this link:
https://github.com/mworion/MountWizzard4/blob/master/support/3.0/startupPackage.zip
and click RAW, it will download a ZIP file. In my case it was name true.zip (I do not know why). If you unzip this file, you see the installer....
Hope this helps.
Michel

**Comment by h2ologg** [comment]
Thank you Michel,I’ll give it a whirl and if doesn’t work I’ll report back. Many, many thanks for an amazing indispensable program. It makes 10micron mounts more premium than they already are. Best,DanOn Sep 4, 2023, at 11:42 AM, Michael ***@***.***> wrote:﻿
Hi,
for some reason GitHub changed behavior. I did a try and if you follow this link:
https://github.com/mworion/MountWizzard4/blob/master/support/3.0/startupPackage.zip
and click RAW, it will download a ZIP file. In my case it was name true.zip (I do not know why). If you unzip this file, you see the installer....
Hope this helps.
Michel

**Comment by h2ologg** [comment]
Hi Michel,Curios...When I attempt to download the RAW it downloads a file named startupPackage.zip for both 3.0 &2.0  both are non functional as an installer (Both zipped and unzipped).  The command screen blinks and returns to the original state.  Hoping you can run the installer and see what's up.  I have command line verified python 3.10.11 installed.  The startup package doesn't install the usual files I have on two other computers.  I'm struggling.Thanks for giving this your attention.Dan Bartlett
    On Monday, September 4, 2023 at 12:11:23 PM PDT, Dan bartlett ***@***.***> wrote:  
 
 Thank you Michel,I’ll give it a whirl and if doesn’t work I’ll report back. Many, many thanks for an amazing indispensable program. It makes 10micron mounts more premium than they already are. 

Best,Dan

On Sep 4, 2023, at 11:42 AM, Michael ***@***.***> wrote:



﻿


Hi,
for some reason GitHub changed behavior. I did a try and if you follow this link:
https://github.com/mworion/MountWizzard4/blob/master/support/3.0/startupPackage.zip
and click RAW, it will download a ZIP file. In my case it was name true.zip (I do not know why). If you unzip this file, you see the installer....
Hope this helps.
Michel

**Comment by mworion** [comment]
Dan,
I put the installer to dropbox, hope this helps:
https://www.dropbox.com/scl/fo/msc4h987y55mt9249cmbo/h?rlkey=6e3v2sucp8gbqibd83mlyi3ni&dl=0
Michel

**Comment by h2ologg** [comment]
Thank you Michael!
I fell back to MW3 and was missing your 4.0.  Truly feel that 4.0 is a marvelous piece of software.  Love the DSO modeling ability (great for quick set up remote site work especially useful for low altitude comets and slow to download full frame  cameras).  The functionality of 4.0 is amazing!
Thank you for spending so much of your time.Dan 

    On Thursday, September 7, 2023 at 02:58:46 AM PDT, Michael ***@***.***> wrote:  
 
 


Dan,
I put the installer to dropbox, hope this helps:
https://www.dropbox.com/scl/fo/msc4h987y55mt9249cmbo/h?rlkey=6e3v2sucp8gbqibd83mlyi3ni&dl=0
Michel

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by mworion** [comment]
Hi Dan,
did it work out ?
Michel

**Comment by h2ologg** [comment]
Hi Michel,Just another zip file to the startup.   I’ve given up.  I will continue to use MW3 on the new computer.  Appreciate the assistance  Best,DanOn Sep 11, 2023, at 12:12 PM, Michael ***@***.***> wrote:﻿
Hi Dan,
did it work out ?
Michel

**Comment by mworion** [comment]
Dan, 
not happy seeing you getting back to MW3. I understand, that you have problems getting the installer script to be able to start with MW4. The file you need is called startup.pyz and it's a python script like MW4 is.
I checked the dropbox link downloaded starupPackage.zip and unzipped it, there I found the startup.pyz file, which does the install and everything else.

If you are still interested I could offer a joint team viewer session, to check what I could improve to make things more easy and find out, what causes the problem.

Michel

**Comment by h2ologg** [comment]
Hi Michel.  It's now working!  I uninstalled Python 3,10 trashed the old MW4 and reinstalled both anew.  Works like a charm!  Back to tracking satellites when I'm in the city and cometswww.astrobin.com/users/h2ologg/ when I'm at the cabin in June Lake California USA.  

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Dan Bartlett's gallery

Astrophotography by Dan Bartlett on AstroBin
 |

 |

 |

All thanks to your splendid software and GM1000 & 200hps mounts.  Again your DSO modeling tracks were a life saver for remote imaging setup prior to C/2023 P1's rising.  Amazing tool!  Thanks for extending your reach to help.Regards,Dan
    On Sunday, September 17, 2023 at 08:48:05 AM PDT, Michael ***@***.***> wrote:  
 
 


Dan,
not happy seeing you getting back to MW3. I understand, that you have problems getting the installer script to be able to start with MW4. The file you need is called startup.pyz and it's a python script like MW4 is.
I checked the dropbox link downloaded starupPackage.zip and unzipped it, there I found the startup.pyz file, which does the install and everything else.

If you are still interested I could offer a joint team viewer session, to check what I could improve to make things more easy and find out, what causes the problem.

Michel

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |
