### ISSUE TITLE
Envornment data: Dew point and humidity reversed in direct sensor data

### ISSUE THREAD

**Issue by Yazracor** [mworion/MountWizzard4#328]
**Describe the bug**
I have connected a MGBoxv2 to the 10Micron Mount via serial and to the computer via USB/ASCOM. In the sensor tab, under "direct", humidity and dew point are reversed. In the "sensor" tab, it shows correctly.

**To Reproduce**
Connect an MGBox to a 10Micron mount. Use "direct" sensor data.

**Expected behavior**
Show the correct sensor data.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mworion** [comment]
Hi
thanks for the hint, service release 3.2.1 will fix this.
Michel
