### ISSUE TITLE
Openweathermap shows incorrect air pressure

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#329]
### Discussed in https://github.com/mworion/MountWizzard4/discussions/327

<div type='discussions-op-text'>

<sup>Originally posted by **Jojo1703** October  1, 2023</sup>
Hello,

I have activated weather data from Openweathermap with a valid API code in MW4. Unfortunately, incorrect air pressure is displayed in the Environment window. In the debug I also see an incorrect specification of longitude and latitude. Here is the excerpt from Debug:

[2023-09-30 22:42:05.304][D][onlineWeather.p][ 258] http://api.openweathermap.org/data/2.5/forecast?lat=51.47&lon=0.00&APPID=d81e8ba30be0ef53f958a5228cc2fc21

I don't know where the incorrect entries of "lat" and "lon" come from. My correct data would be "lat=51.20" and "lon=7.36". Can I enter this somewhere and change it?

Bye
Jurgen</div>

**Comment by mworion** [comment]
Hi Juergen,

I used the forecast API of openweathermap. Since there might be up to 3h difference between now and their regular updates, I changed interface to another API (which is also be used by NINA I guess). Should from v3.2.2 on similar. Please delete openweathermap.data file before testing again.

Michel

**Comment by Jojo1703** [comment]
Hi Michel,

great, it works now. Thanks for your help,

Bye
Jurgen
