### ISSUE TITLE
Update MW 4 from 3.2.2 to 3.2.3 fails

### ISSUE THREAD

**Issue by Jojo1703** [mworion/MountWizzard4#332]
Hi Michael,
I updated MW 4 from 3.2.2 to 3.2.3. The update process went through without an error message but now MW4 no longer starts. I did this on 2 Windows 10 Pro PCs and MW4 no longer works on both of them. Attached is the last LOG file. Is there an explanation?

Greetings
Jurgen
[mw4-2023-10-12.log](https://github.com/mworion/MountWizzard4/files/12887616/mw4-2023-10-12.log)

**Comment by mworion** [comment]
Jurgen,to make them run again, please try the following steps:- only delete the openweathermap.data file and restart- if you profile has a specific name (not “config”), please delete the file “profile” under config folder and MW4 should restart, then loading you original profileUnfortunately I on a business trip and cannot check in detail, but I will be back saturday.MichelAm 12.10.2023 um 18:47 schrieb Jojo1703 ***@***.***>:﻿
Hi Michael,
I updated MW 4 from 3.2.2 to 3.2.3. The update process went through without an error message but now MW4 no longer starts. I did this on 2 Windows 10 Pro PCs and MW4 no longer works on both of them. Attached is the last LOG file. Is there an explanation?
Greetings
Jurgen
mw4-2023-10-12.log

**Comment by mworion** [comment]
Hi Jürgen,
I will release a v3.2.4 which should be more robust against the openweathermap API. Sometime there were missing ID's (e.g. no rain).
So update to 3.2.4 will do the trick. Please report back, if you observe missing values in some circumstance.
Michel
