### ISSUE TITLE
3.2.2: ASTAP D80 databse not recognized

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#335]
Hello Michel,

it looks like that the D80 database is not properly recognized. please see screen shot.
ASTAP: 2023.10.14

Cheers
Rüdiger

![2023-10-17_17h36_37](https://github.com/mworion/MountWizzard4/assets/65772654/72d209f7-8e07-4558-b8bb-2f756b58de48)
![2023-10-17_17h38_24](https://github.com/mworion/MountWizzard4/assets/65772654/13b33668-286e-407e-986d-56a4b935c2d1)

**Comment by Ruediger3** [comment]
Thanks Michel,
I had been testing the D80 for Han for a couple of weeks now. A week ago or so he released it. I only noticed since I have removed D50 which I had as Backup.

Rüdiger

**Comment by mworion** [comment]
Rüdiger,
you could check v3.2.4b1 for testing.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

it works now :) Thank you!

Rüdiger
