### ISSUE TITLE
PegasusAstro UPBv2 wrong entities mapping using Ascom

### ISSUE THREAD

**Issue by hdiessner** [mworion/MountWizzard4#336]
The Mapping of some entities between the Pegasus Astro UPBv2 and MountWizzard using Ascom seem to be wrong.
See Screenshot attached:
![image](https://github.com/mworion/MountWizzard4/assets/30579383/1e2d05ea-46b4-4ab5-9cce-4df0922341fe)

**UPBv2 - "Power Hub"**
MW4 - "Power Ports": "Power" Buttons are working, but no Display of "Current"

**UPBv2 - " USB Hub"**
MW4 - "USB Ports":
- USB1 - powers USB4 on UPBv2
- USB2 - powers USB5 on UPBv2
- USB3 - powers USB6 on UPBv2
- USB4 - powers Dew A on UPBv2
- USB5 - powers Dew B on UPBv2
- USB6 - powers Dew C on UPBv2

All Display Values are unavailable on MW4 in sections "Consumption" and "Adjustable output"

Versions used:
Python: 3.10.11
Script Version 3.2
MW4 3.2.4
PegasusAstro Unity Platform v1.11.2039.91

For reference: when the UPBv2 is controlled via N.I.N.A. the mapping of all entities seems to be ok.

**Comment by mworion** [comment]
Herwig,
thanks for the report. I did not catch that Pegasus made a new driver setup and software. As I used my Pegasus UPBv2 through Indi, I did not catch the difference. NINA is using a native driver to enable all functions as ASCOM with the switch interface was lagging.
So it will be more a feature request (I would put it on the list) to implement a native driver as well.
Michel
