### ISSUE TITLE
Image Solve Failures on Polar Align

### ISSUE THREAD

**Issue by Altair8861** [mworion/MountWizzard4#337]
**Describe the bug**
When selecting 9 point alignment model and executing, mount correctly cycles through points but none of exposures solve using ASTAP

**To Reproduce**
Focus scope using Bahtinov mask, Luminance Filter
Launch MW4
Connect to camera
Verify focal length
Go to Modeling Tab->Generate Build Points and select 9 points
Within Modeling Tab select Model Build and Program->Run

**Expected behavior**
After running 9 point alignment model, 0 points in model. Checking Message Tab all points failed (screenshots below)

**Screenshots**
![ASTAP and Camera Active](https://github.com/mworion/MountWizzard4/assets/110138869/37cbc59d-3c36-4869-bc4c-9ad35610d1bf)
![ASTAP Setup](https://github.com/mworion/MountWizzard4/assets/110138869/968cb2d4-b9ad-431d-8125-5c555aea5600)
![Image Settings 2](https://github.com/mworion/MountWizzard4/assets/110138869/c7f4b9f6-9bdf-42f2-afc7-0db92f03e54d)
![Message Window 2](https://github.com/mworion/MountWizzard4/assets/110138869/c591c7f9-6137-43e9-b771-ef67ae599660)

**Desktop (please complete the following information):**
Windows 11
MW4 3.2.4
ASTAP 2023.11.17 D50 database

**Additional context**
Initial failure was using previous ASTAP and S17/H18 database, updated to latest ASTAP 2023.11.17 and D50 database. Solving still failed.

Loading image files into MW4 and solving with ASTAP appears to work. Also able to capture and solve images in NINA using ASTAP. Performed Autofocus in NINA and re-ran MW4, images still fail to solve.

**Comment by Altair8861** [comment]
Ok, these were found under Windows_Scripts->Log.

The November 28 file should be the failure, the September 24th file should have been a success.

Other than moving the mount physically, no other changes I can recall.

[mw4-2023-09-24.log](https://github.com/mworion/MountWizzard4/files/13520281/mw4-2023-09-24.log)
[mw4-2023-11-28.log](https://github.com/mworion/MountWizzard4/files/13520282/mw4-2023-11-28.log)

**Comment by Altair8861** [comment]
Attached are images from the failed align last week. Looking at them, it appears they are blank frames. Tuesday night will be clear, should be able to make another attempt.
[Nov228_fail.zip](https://github.com/mworion/MountWizzard4/files/13554977/Nov228_fail.zip)

**Comment by Altair8861** [comment]
Here is the debug log from a few moments ago - the camera is shooting but not recording.

Focus was done with a Bahtinov mask using NINA to control the camera. Worked fine.
[mw4-2023-12-06.log](https://github.com/mworion/MountWizzard4/files/13574615/mw4-2023-12-06.log)

**Comment by mworion** [comment]
Hi,
checked the log, is says error code 2 from ASTAP, which means not enough stars found, which fits to the observation of black frames. I checked them with Pixinsight, there is nothing in. The header data in the file seem to be OK.
Michel

**Comment by mworion** [comment]
That looks strange. 
As you are using NINA as well, the ideal config together with MW4 would be:
- Enable API server in NINA
- Set Camera to NINA controled
- Connect all devices you in NINA (at least Camera, Mount)
- Do things within MW4 as it uses the camera through NINA
Actually with the ASCOM driver the image content is black, which leads to an incompatibility issue.
Please keep in mind that the camera could not be connected to NINA and MW4 at the same time. As there is a resource conflict (even if you are using Native driver in NINA).
So either you connect in MW4 and disconnect in NINA before (and vice versa) or you are using the camera from MW4 through NINA, which mean that only NINAcontrols the camera.
Hope this helps.
Michel

**Comment by shine1532** [comment]
I have the same problem from yesterday. I have been using it without any problems for a few years, but after updating to the latest version, the same problem as Altair8861 has been occurring since yesterday. I've been using NINA with MW4. 
Even when only MW4 - v.3.2.4 is running without running the NINA program, the image data taken by the camera does not appear on the imaging screen at all.
Can you explain more about "enable API server in NINA. Set camera to NINA controlled"?

**Comment by mworion** [comment]
Hi,
In nightly it is a separate Plugin, whereas in official 2.x build you find it under system tab in NINA.
![Bildschirmfoto 2023-12-14 um 17 57 37](https://github.com/mworion/MountWizzard4/assets/6632980/055f41af-4887-440b-99a6-b642320859f2)
But anyhow I published a 3.2.5, which should be better.
Michel

**Comment by shine1532** [comment]
Thank you, Michael!
After upgrading to 3.2.5, it works again.
MW4 is a really cool integrated system. I would like to take this opportunity to say thank you very much.
Young

**Comment by mworion** [comment]
Thanks for the feedback.
