### ISSUE TITLE
Connect to NINA-Camera fails (MW V3.2.6b12, NINA 3.0 BETA 003=

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#343]
Hello Michel,

I have the problem, that I cannot connect anymore camera to NINA though SGP Plugin is active and running.

Maybe I am making something wrong. The log is not very talkative here. 

Thanks in advance!
Rüdiger

<img width="961" alt="2024-01-10_16h28_15" src="https://github.com/mworion/MountWizzard4/assets/65772654/670f13a0-1fd9-4dd4-9e2d-59537c384288">
[mw4-2024-01-10.zip](https://github.com/mworion/MountWizzard4/files/13889733/mw4-2024-01-10.zip)

**Comment by Ruediger3** [comment]
Fell back to version 3.2.5 and it can connect the camera.

**Comment by mworion** [comment]
Sorry, this happened when trying to search for some ip routes for a two network solution.
3.2.6b12 will be available soon and solves it.
Michel

**Comment by mworion** [comment]
...sorry v13 available now...

**Comment by Ruediger3** [comment]
Thanks! It works again :)

Have a nice evening!
Rüdiger

**Comment by Ruediger3** [comment]
Fixed in b13

**Comment by Ruediger3** [comment]
fixed in b13
