### ISSUE TITLE
Integration with NINA

### ISSUE THREAD

**Issue by gpassera** [mworion/MountWizzard4#347]
Hi Michel

Is there any way to have MW4 as a plugin for NINA, just to use it before any session avoiding using 2 different programs but integrating one inside the other?

Thanks

Giuseppe

**Comment by mworion** [comment]
Hi Giuseppe,

Unfortunately there is no way to make this integration. MW4 is written in python whereas NINA ist written in C. But there is a plugin by George in NINA, which does at least all necessary things as well.

Michel

**Comment by gpassera** [comment]
Michel
Thank you for your super fast answer.
I lnow the plugin from George but I prefer your program( nothing bad of
course about George’s plugin).
Ok tomorrow morning I’ll close the issue.
Thanks and regards
Giuseppe


Giuseppe Passera
www.giuseppepassera.com


Il giorno mer 14 feb 2024 alle 21:24 Michael ***@***.***> ha
scritto:
