### ISSUE TITLE
Wait after slew not working

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#349]
Dear Michel,

I am currently modelling with my GM3000HPS and set the "Mount wait time while modelling" to 5s, but imaging is still done as soon as the mount indicates the tracking state.

I did restart MW4 after I set the value to 5s and it shows this setting upon restart.

Is there another setting required to let MW4 wait?

Nicolàs
PS: I am using MW4 3.2.5

**Comment by mworion** [comment]
Hi Nicolas,
I will add another time for waiting explicitly. With the mount it is a little complicated. You have multiple wait times:

1.) Mount setting inside the mount computer: visible on Mount Page under Mount computer Settings. This is the internal settling time. Whenever a slew command is issued (from whatever source (driver, MW4, Handpad) and whatever use case, the mount computer will wait this time before showing the status slew finished. In this case exposing will immediately start after the mount signal received. So you experience tracking state the same time as expose start. But still you will have a defined settling time ! This might be your case

2.) Adding times during modeling: visible under mount settings. These are valid only while running a modeling session. After pier flip... will add a specific settling time on top of the basic settling time of the mount computer in a situation when MW4 know about a pier flip. The mount state will change immediately after basic settling time to tracking, but MW4 will show this state after this additional wait time. Exposing will start immediately after you will see tracking state in MW4.

3.) New: Adding a wait time during modeling before exposing. This will add another wait time after the mount and MW4 tells tracking. So you will experience this time delay between tracking state shows up and camera starts expose.
Does this makes sense ?
Michel

**Comment by InFINNity-Deck** [comment]
Dear Michel,

thanks! It is indeed method 3) I was looking for as with a heavy set-up like mine the mount still moves a bit within the first 5 seconds after status is set to tracking.

But if I understand you well method 1) already does this, but then on the mount side. I presume you use the :SstmNNNNN.NNN# command for that? If so there is no need to implement method 3), although it may be more clear to the user as he/she will actually see the tracking state change and x seconds later that the exposure starts (this is why I thought that the delay did not work).

Nicolàs

**Comment by mworion** [comment]
Nicolas,
You could check v3.2.6b17 now as a try out. If that helps, I keep it. Unfortunately my rig is disassembled, so I cannot test physically.
Michel

**Comment by mworion** [comment]
...and yes, It's the command I used...

**Comment by InFINNity-Deck** [comment]
Hi Michel,

thanks for your quick response and beta-version. I installed it and found the two settings:

![afbeelding](https://github.com/mworion/MountWizzard4/assets/66182061/518f040e-a619-4f11-b712-f042da917d07)

As you can see I deliberately tested them with large values. I noticed the following:
- when restarting MW4 the two values get exchanged, so now we see 60s and 20s, after save and restart it is 20s and 60s.
- method 1) appears not be working on my mount. I tested this with MountMonitor and the Virtual Keypad. As soon as the RA/DEC values on the keypad show that the slew has (more or less) ended, the status goes to tracking (as indicated by the star-symbol and shown by MountMonitor) and MW4 continues, even though it should wait a minute (tested it with each field set to 60s, both times with a full restart of MW4).
- The new method 3) works like a charm (apart from above bug in saving). It works with the 60s in the "Additional wait time before exposure" field.

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,
I mixed the settings when persist them. Bug on my side. Will be corrected. I will add some message in the status as well to make it more clear. 
Please have a look to 3.2.6v18. There the mount setting should also work, there might be another bug in.
Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

you're swift as always, thanks a lot! First opportunity for me to test it will be Friday. Currently the weather turned for the worst, so mount and scopes are wrapped up in an additional cover and the dome is locked to resist upcoming high winds.

Nicolàs

**Comment by InFINNity-Deck** [comment]
Hi Michel,

just now I tested v3.2.6b18. The settings are now correctly stored and retrieved and the "Additional wait time before exposure works as expected". The other option "Additional wait time after wait time, slew and settle" does not seem to work at all. While running MW4 I also tried to force this setting by sending #:Sstm60.000# to the mount using FoxTerm. The mount responds with a 1 (I received that in FoxTerm), indicating the command was successfully received, but wait time was not affected. It seems that the mount does not handle the command correctly or not how we think it should work.

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,
I will check the other option as soon as my rig is back in operation. So far I could not test.
Michel

**Comment by InFINNity-Deck** [comment]
Dear Michel,

your bot woke us up... ;-)

Did you have any chance to check the remaining issue?

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,
same observation with the mount internal command. I will do some logs for 10micron and send them a ticket.
Closing this remaining part.
Michel
