### ISSUE TITLE
MountWizzard4 Wont Start

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#352]
### Discussed in https://github.com/mworion/MountWizzard4/discussions/351

<div type='discussions-op-text'>

<sup>Originally posted by **jameshawks60** March 30, 2024</sup>
Hello All,

I have tried installing MW4 but it just wont start. Here is the error code that is returned from the log:

> [2024-03-30 17:55:09.342][E][    loggerMW.py][  46]          class MyApp(QApplication):
> [2024-03-30 17:55:11.045][H][      loader.py][ 296] ----------------------------------------------------------------------------------------------------
> [2024-03-30 17:55:11.061][H][      loader.py][ 297] mountwizzard4    : 3.2.5
> [2024-03-30 17:55:11.061][H][      loader.py][ 298] platform         : Windows
> [2024-03-30 17:55:11.061][H][      loader.py][ 299] sys.executable   : c:\MountWizard\venv\Scripts\python.exe
> [2024-03-30 17:55:11.061][H][      loader.py][ 300] actual workdir   : c:\MountWizard
> [2024-03-30 17:55:11.061][H][      loader.py][ 301] machine          : AMD64
> [2024-03-30 17:55:11.061][H][      loader.py][ 302] cpu              : Intel64 Family 6 Model 92 Stepping 9, GenuineIntel
> [2024-03-30 17:55:11.061][H][      loader.py][ 303] release          : 10
> [2024-03-30 17:55:11.061][H][      loader.py][ 304] python           : 3.9.0
> [2024-03-30 17:55:11.061][H][      loader.py][ 305] python runtime   : 64bit
> [2024-03-30 17:55:11.061][H][      loader.py][ 306] PyQt5 / Qt       : 5.15.9 / 5.15.2
> [2024-03-30 17:55:11.061][H][      loader.py][ 307] node / hostname  : ASTROPHOTO / ASTROPHOTO
> [2024-03-30 17:55:11.061][H][      loader.py][ 308] run as admin     : yes
> [2024-03-30 17:55:11.061][H][      loader.py][ 309] ----------------------------------------------------------------------------------------------------
> [2024-03-30 17:55:11.076][I][      loader.py][ 332] Using existing: [de440_mw4.bsp]
> [2024-03-30 17:55:11.092][I][      loader.py][ 332] Using existing: [visual.txt]
> [2024-03-30 17:55:11.092][I][      loader.py][ 332] Using existing: [CDFLeapSeconds.txt]
> [2024-03-30 17:55:11.107][I][      loader.py][ 332] Using existing: [tai-utc.dat]
> [2024-03-30 17:55:11.107][I][      loader.py][ 332] Using existing: [finals2000A.all]
> [2024-03-30 17:55:11.139][I][      loader.py][ 332] Using existing: [finals.data]
> [2024-03-30 17:55:11.170][I][      loader.py][ 332] Using existing: [mountwizzard4.pdf]
> [2024-03-30 17:55:11.201][I][     profile.py][ 189] Config file c:\MountWizard\config\config.cfg not existing
> [2024-03-30 17:55:11.357][I][     obsSite.py][ 142] Timescale is using downloaded version
> [2024-03-30 17:55:23.400][D][    startup.pyz][  77] Exit code:[3221225477], message:[], success:[False]

When I analyze the dmp file it has the following information:

> SYMBOL_NAME:  Qt5Core+1d69db
> MODULE_NAME: Qt5Core
> IMAGE_NAME:  Qt5Core.dll
> STACK_COMMAND:  ~17s; .ecxr ; kb
> FAILURE_BUCKET_ID:  INVALID_POINTER_READ_c0000005_Qt5Core.dll!Unknown
> OS_VERSION:  10.0.19041.1
> BUILDLAB_STR:  vb_release
> OSPLATFORM_TYPE:  x64
> OSNAME:  Windows 10
> IMAGE_VERSION:  5.15.2.0
> FAILURE_ID_HASH:  {e187daa5-db35-d98d-1840-c9f4590b5968}

With it being an invalid read in the Qt5Core.dll I am assuming the issue is with PyQt5. I have tried a fresh install of Python (various versions from 8.2 to 10) and of MW4 using v2 install and v3.

Any thoughts or help would be greatly appreciated. 
</div>

**Comment by mworion** [comment]
Hi James,

I did a privat build for you. Some remarks to limit variances:
- Please install latest available python 3.10 version.
- Please do a new install (to be sure that newest libraries are loaded)
- Please only use the v3 installer
- The version I build is 3.2.6a1. It contains the latest pyqt5 bugfix library
- You could install this with the command, if you have downloaded the v3 installer 

``` 
python startup.pyz -v 3.2.6a1
```

Hope this helps.
Michel

**Comment by jameshawks60** [comment]
Michel,

I will do this tonight, just wanted to let you know I got you message.

**Comment by jameshawks60** [comment]
Michel,

The same thing happened. Here are the MW4 log file and dmp file analysis. 

[mw4-2024-04-03.log](https://github.com/mworion/MountWizzard4/files/14845366/mw4-2024-04-03.log)
[dmp file analysis.txt](https://github.com/mworion/MountWizzard4/files/14845374/dmp.file.analysis.txt)

**Comment by mworion** [comment]
Hi James,
I cannot figure out, what the problem with Qt5 lib is. I did e retest with python3.10 like you on windows10 64 bit. No issue in my test setup.
I have two steps in mind:
- first I build you another version 3.2.6a2 (install it like the other), which removes the Windows Automation capabilities. Reason: Last entries of log and some hints in crash dump show this. Please give it a try.
- second: I am anyway on the path of migrating to Qt6 (but this might take some more time). And hopefully the issue on the Qt lib is solved in their version 6.
- Michel

**Comment by jameshawks60** [comment]
Michel,

I appreciate all the help. The same thing happened again. Here are the files for your reference but don't spend anymore time on this. I will wait for the upgrade to Qt6 or a new mini-pc.

[dmp file analysis.txt](https://github.com/mworion/MountWizzard4/files/14895984/dmp.file.analysis.txt)
[mw4-2024-04-07.log](https://github.com/mworion/MountWizzard4/files/14895986/mw4-2024-04-07.log)

**Comment by mworion** [comment]
James,
if you could do me a favor: I made an early build 4.0.0a0 based on PyQt6 for you. Could you check if the problem still exists ? Please use a clean installation. The package itself also has many changes in is not tested for general use.
Michel

**Comment by jameshawks60** [comment]
Michael,

[2024-04-15 03:54:53.540][I][    startup.pyz][  64] ERROR: No matching
distribution found for mountwizzard4==4.0.0a0

Just let me know when you have it uploaded and I will try again or if the
build number is incorrect.


Thank You,
---
James Hawks
602-369-0690

**Comment by mworion** [comment]
James,
upload went wrong from CI (missed to install twine...) It's online now. Version is 4.0.0a0
Sorry for the inconvenience.
Michel

**Comment by jameshawks60** [comment]
Michael,

No problem, and there is nothing you need to apologize for. I
appreciate all the time and help.


Respectfully,
---
James Hawks
602-369-0690

**Comment by jameshawks60** [comment]
Michael,

It did not crash this time but it still would not start. Error log
attached. Here are the last few lines:

[ 289]
----------------------------------------------------------------------------------------------------
[2024-04-16 03:24:47.590][I][    startup.pyz][  64] Traceback (most recent
call last):
[2024-04-16 03:24:47.590][I][    startup.pyz][  64]   File
"c:\MountWizard\venv\lib\site-packages\mw4\loader.py", line 48, in <module>
[2024-04-16 03:24:47.590][I][    startup.pyz][  64]     setupLogging()
[2024-04-16 03:24:47.590][I][    startup.pyz][  64]   File
"c:\MountWizard\venv\lib\site-packages\mw4\base\loggerMW.py", line 124, in
setupLogging
[2024-04-16 03:24:47.590][I][    startup.pyz][  64]     timeTag =
datetime.datetime.now(datetime.UTC).strftime('%Y-%m-%d')
[2024-04-16 03:24:47.590][I][    startup.pyz][  64] AttributeError: module
'datetime' has no attribute 'UTC'
[2024-04-16 03:24:47.699][D][    startup.pyz][  77] Exit code:[1],
message:[], success:[False]


Thank You,
---
James Hawks
602-369-0690

**Comment by mworion** [comment]
James,
found the issue, v4.0.0a1 hopefully does the trick.
Michel

**Comment by mworion** [comment]
James, great to hear. Please watch out, when official beta is available. Still your alpha should be able to work, but as I said right now untested.
Closing the issue.
Michel

**Comment by mworion** [comment]
James,
this happens if you start solving during a running solve process. Please post the full log for reviewing the history. Made a quick test and it behaves exactly that way in my test setup.
Michel
