### ISSUE TITLE
Image zoom setting when looping images during polar alignment.

### ISSUE THREAD

**Issue by WillB-2024** [mworion/MountWizzard4#353]
Hi Michel

In MW4 when looping images continuously (Expose N) to carry out an assisted polar alignment is there a user setting that maintains the current user set zoom ratio for as long as continuous images are downloading?

I find that as each image is downloaded using continuous exposures (Expose N) and the Crosshair display set to visible, the image zoom ratio reverts back to full frame with each new image, irrespective of the state of the checkbox for “Lock aspect” under the Image View group of the Imaging window.

I managed to carry out a polar alignment eventually by taking single images, adjusting the zoom ratio then manually adjusting the mount by guesswork, taking another single image and repeating until the polar alignment was completed.

The observatory monitor was just too far away to be seen easily from the mount and the image scale too small to accurately adjust the mount alignment without a large zoom factor applied, and that was not possible under Expose N looped exposures.

The camera used was a QHY268M and the QHY ASCOM driver, 100mm, f/5.8 quadruplet refractor of 580mm focal length at 2.6 arc sec/pixel binned 2x2, Windows 11.

The mount is now permanently pier aligned in the observatory and a sky model in place (10u 2000 HPS 11 Combi) with a PA inaccuracy of ~35 arc sec, so this is not urgent, but I would appreciate any hints on how to keep the chosen zoom ratio maintained when using Expose N continuous looped exposures for the next time I build a new model and make any adjustments to the polar alignment.

Kind regards.
William.

**Comment by mworion** [comment]
Hi William,
the function you described should work since version 3.2.0 ongoing.

https://github.com/mworion/MountWizzard4/assets/6632980/b999b3a6-3a08-40f6-b4c8-7ad3a8e176ab

Michel

**Comment by WillB-2024** [comment]
Thank you for the quick reply Michel.

I did not know that I was running the standard distribution of MW4, v3.1.0.

Updated MW4 today using the automatic updater to v3.2.25 and can now hold the zoom ratio during Expose N sequence so I should be good to go the next time I carry out a polar alignment.

Mit freundlichen Grüßen

William.
