### ISSUE TITLE
Version 0.150.19 no startup

### ISSUE THREAD

**Issue by TomBootz** [mworion/MountWizzard4#36]
I updated to version 0.150.19 from 0.150.15. MW4 will not start up now. 

Relevant cut from syslog is follows:

May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]: Traceback (most recent call last):
May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]:   File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 418, in <module>
May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]:     main()
May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]:   File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 361, in main
May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]:     locale.setlocale(locale.LC_ALL, 'en_US')
May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]:   File "/home/tom/MW4/venv/lib/python3.7/locale.py", line 608, in setlocale
May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]:     return _setlocale(category, locale)
May 27 10:34:47 tom-x570-aorus-master-1 MountWizzard4.desktop[3580]: locale.Error: unsupported locale setting

System:
Ubuntu 18.04.4 LTS, Python 3.7.6

Tom

**Comment by mworion** [comment]
OK,
was because of a workaround on windows for German locale setting due to a faulty library.
0.150.20 should fix this. Please update via the MW4_update script.
Michel

**Comment by Ruediger3** [comment]
Update on Window to .20 and now the Satellite bug is partially back. Transition are not calculated and errors are thrown in cmd window. Also satellite window is empty again.

![2020-05-27_21h44_17](https://user-images.githubusercontent.com/65772654/83065666-28ce3d80-a064-11ea-97b4-cd7e1b881df5.png)
![2020-05-27_21h46_02](https://user-images.githubusercontent.com/65772654/83065677-2b309780-a064-11ea-8e42-3ad278c92a78.png)

**Comment by TomBootz** [comment]
Very good. .20 fixed my issue. Thank you!

**Comment by Ruediger3** [comment]
Fixed yours, crashed mine .🤔

**Comment by mworion** [comment]
Rüdiger,
could you send me some informations about you windows version, the install.log and the laguage settings? I would like to reproduce this behavior in a vm.
Many thanks !
Michel

**Comment by Ruediger3** [comment]
Windows 10-64 Built 1903
Windows display language: EN
Region: Germany
Regional Format: Germany

MW4 version: 0.150.20b1 

I have no install.log in any folder. :(
Where should it be?

![2020-05-28_17h03_08](https://user-images.githubusercontent.com/65772654/83158479-1eb04b80-a105-11ea-9528-348ba73126d9.png)
![2020-05-28_17h04_49](https://user-images.githubusercontent.com/65772654/83158680-5b7c4280-a105-11ea-8eb4-c83dfa810db2.png)

**Comment by mworion** [comment]
Hi Rüdiger,
got it. Could reproduce it now. 
The install.log would be in the working folder top level, when used the install script (but a newer one). Never mind, I could reproduce it. I close the point here as it was for Ubuntu and work in the original one.
Michel
