### ISSUE TITLE
Platesolve with ASTAP, missing mount point coordinates in FITS

### ISSUE THREAD

**Issue by stefanZbinden** [mworion/MountWizzard4#361]
MW4 latest version 3.2.6

A long time ago, when NINA still was in 2.x version, I was using the camera with NINA (in server mode)
At that time I never had a problem with plate solving because NINA was putting the mount RA/DEC into the FITS header and ASTAP was very fast. MW4 was really fast building a mount model.

Since NINA version 3.x I am no longer able to use the camera with NINA (no server mode???) therefore I have to use the mw4 internal imaging stuff.
Unfortunately mw4 is not putting the mount point coordinates into the FITS header. Therefore a blind solve takes a long time and sometimes fails.

What is the reason not writing the mount point coordinates into the header? Yes, it can be completely wrong but in all other cases it helps for plate solving.

Maybe that I am missing a configuration step ....

Many thanks and my best regards
Stefan

**Comment by stefanZbinden** [comment]
Uups, it may be not a bug. Sorry! It's my first time opening an issue ....

**Comment by mworion** [comment]
Hi Stefan,
The server mode is a separate plugin you could install in NINA. This might be the simple solution for you. When using the camera directly, MW4 puts the coordinates to the FITS Header itself. To check if there is an error, would you mind to post the log here (just drop it on this webpage) ?
Michel

**Comment by mworion** [comment]
Stefan, it's the following Plugin:

![Bildschirmfoto 2024-08-01 um 17 00 43](https://github.com/user-attachments/assets/56ca7bf7-d924-4030-b215-b1b88fd9ff9d)

Michel

**Comment by stefanZbinden** [comment]
Perfect! Many thanks!
As soon as there will be a clear night I will provide you with all the necessary info!
For me it is important that your tool is working as expected. It's a great thing!!!!!!!!

My best regards
Stefan

**Comment by mworion** [comment]
You’re welcome !

**Comment by stefanZbinden** [comment]
Hi Michel

Finally I found time to make a test during a perfect night, no moon, no clouds and dark.
Here the description of my test:
1. I built a model with the 10micron NINA plugin. I got a RMS of 4.9 arcsecs and I was able to take 5 minute subs without guiding. So I am pretty sure that I did it right.
2. For the test I was deleting the model -> no model active
3. I started mw4. The camera was attached through NINA. (SGP Plugin). ASTAP has been setup the right way because I did not have problems during plate solving in NINA.
4. I generated a 9 point model program.
5. After completion I got a horrible result. Only 4 positions were plate solved and the RMS was far away from 5 arcsecs. The altitude pointing was about 3 degrees away and the Polar Align Error was 140356 arcsecs off. These results are completely wrong!

I know at least two other colleagues who have similar problems.

I attach the log file and the result of NINA model and a picture of mw4.
The images you may find on my dropbox: https://www.dropbox.com/scl/fo/0yu6mksuspq3zxhthinrl/AF8XBquKGp1wdFr19ygp0lI?rlkey=ljvxcyu2rty2dun18a14ig26a&dl=0
There is absolutely no problem to plate solve these images. ASTAP can do it in less than 0.5s.
![IMG_4868](https://github.com/user-attachments/assets/c40e5f65-0e73-472b-bd02-08b370aac1ff)
![IMG_4869](https://github.com/user-attachments/assets/09b350b0-ed83-489f-948c-87399140d681)
[mw4-2024-08-10.log](https://github.com/user-attachments/files/16595395/mw4-2024-08-10.log)

My best regards
Stefan

**Comment by stefanZbinden** [comment]
Hi Michel

Puhh! Obviously there is a problem. I am happy to hear that. I don't like to file an issue then it can also be a user problem.

English is not my native language but I will try to explain my observations.

I NEVER had a problem with ASTAP. If there is a mount pointing coordinate in the fits header (more or less precise) ASTAP solves in less than a second. Incredible fast! I never had to change any parameters.
I started changing FOV/timeout the first time together with mw4. When I was first using mw4 (an older version) I had plate solving issues when I attached the camera through ASCOM directly to mw4. If I attached the camera through NINA I never observed any issues (older version). One time I had a problem but I forgot to attach the mount to NINA. So I assumed that there was no mount pointing coordinate in the fits header. (After attaching the mount the problem was solved)
When I take pictures through mw4 (manually, latest version) the plate solve takes a very long time. I found out, that there is NO mount pointing coordinate in the fits header. Look at the first Pixinsight picture with the fits header tool. So I was happy that you told me to use the SGP plugin for NINA. If you try to solve the provided images on my dropbox you will see that ASTAP solves VERY fast, but mw4 has a lot of trouble. However the mount pointing coordinate is in the fits header. Therefore I had to assume that the problem could be in mw4.

According to some forums where people had similar problems (also a Swiss and a German colleague) I changed then the FOV/timeout to 180/90s. But this does not really help.

If I set the FOV/timeout to 180/90s and if there are more or less precise mount pointing coordinates inside the fits header ASTAP solves very fast. The FOV does not have any impact. If the coordinate is missing this parameter change is necessary and the solve takes a long time... (it can also fail).

These are my observations. I hope you under stand my way of trying to find out what's going wrong. Do you have access to my email address? If yes, we can also communicate in German which would be easier ... Just an idea!

Many thanks for having an eye to my problems ...

My best regards
Stefan

**Comment by stefanZbinden** [comment]
Hi Michel

Sorry I forgot to answer the first question: Right now the FOV is set to 180 degrees (because of suggestions out of the community). At the beginning the parameters were standard but then I never got a successful plate solve... (latest version)

Normally plate solving takes less than a second ... There is no popping up window ...

My best regards
Stefan

**Comment by stefanZbinden** [comment]
I told you some rubbish .... I just tried to plate solve one of the 9 images through mw4. Load file and press solve.
If I set FOV to 30 it solves without a problem if the FOV is set to 180 it takes a long time ... 30s but the plate solve was successful.

Hmmmm I will try it again with FOV set to 30.

Maybe that I was hunting a ghost ....???? As soon as there are clear skies I will try it again ...

My best regards
Stefan

**Comment by mworion** [comment]
Hi Stefan,wir können hier auch gerne mal etwas in Deutsch besprechen. Ich bleibe normalerweise auf englisch, um alle in der Diskussion zu beteiligen.Aber zu Deiner Einschätzung:- Es gab einmal das Thema, dass NINA keine Header geschrieben hatte, da wurde von mir der All Sky nachgerüstet.- Prinzipiell braucht MW4 keine Koordinaten, wenn es selbst Bilder macht, weil die Koordinaten der Montierung ohne hinbekannt sind -> Mittlerweile sollte ich die reinschreiben, muß aber nochmal nachschauen.- Ich werde All Sky auch wieder herausnehmen, nachdem NINA die Koordinaten schreibt. Wenn das notwendig wäre, ist ein anderes Problem vorher zu lösen. Ich hatte noch nie in einem Erstsetup mehr wie 10 Grad FOV benötigt, um mit ASTAP zu lösen.- Bei MW4 gibt es noch ein Problem, wenn die Solving Zeit mehr als 2x die Aufnahme und Slewing Zeit ist -> da bekomme ich einen Überlauf und verwerfe Bilder -> das macht so keinen Sinn. Das ist aber mit dem Verzicht auf ALL Sky ohnehin extrem unwahrscheinlich.- …und da gab es noch Unterschiede zwischen NINA 2.x und 3.xIn Summe aus meiner Sicht:- MW4 mit Kamera direkt sollte funktionieren mit FOV <=30 Grad- MW4 mit NINA ebenso.- Die Modell mit NINA und MW4 unterscheiden sich nicht wirklich.Danke für’s testen!MichelPS: Es wird hoffentlich bald eine 4.0 beta geben, wo MW4 die neue Firmware 3.1.15 ff unterstützt. Dort werde ich den Ablauf zu NINA nochmal überarbeiten.Am 13.08.2024 um 19:36 schrieb stefanZbinden ***@***.***>:﻿
I told you some rubbish .... I just tried to plate solve one of the 9 images through mw4. Load file and press solve.
If I set FOV to 30 it solves without a problem if the FOV is set to 180 it takes a long time ... 30s but the plate solve was successful.
Hmmmm I will try it again with FOV set to 30.
Maybe that I was hunting a ghost ....???? As soon as there are clear skies I will try it again ...
My best regards
Stefan

**Comment by stefanZbinden** [comment]
Hi Michel
Last week I had the possibility to test mw4 together with SGP plugin and NINA.
It worked after I changed the FOV of ASTAP back to 30 degrees. There were no timeouts or bad plate solves.
I generated a 30 point model.
As a next step I will try again to connect the camera via ASCOM directly to mw4. Sorry these tests need time. If we have a clear night I like to take images ...

My best regards
Stefan

**Comment by mworion** [comment]
Hi Stefan,
great to hear. I will add an quick patch for manual imaging (through MW4) in 3.2.7b2
Michel

**Comment by stefanZbinden** [comment]
Hi Michel
Are you waiting for any response?

**Comment by mworion** [comment]
Hi Stefan,
the bot is automatically. I would close the issue if you did not have any further uses with it after the patch.
Michel

**Comment by stefanZbinden** [comment]
Hi Michel
Ok, no problem! At the moment I am using the camera together with NINA and it works perfect also with the latest 3.2.6 version. However as soon as you provide the new beta version I will also try to use the camera directly attached to MW. Thanks for the great communication!
Stefan
