### ISSUE TITLE
Have I installed the wrong version?

### ISSUE THREAD

**Issue by nickym998** [mworion/MountWizzard4#363]
Hi,

Apologies in advance, I really do not know how to use Github and find it really confusing.  I have installed MW4 on a Windows 11 Pr, Intel N100 Beeline mini S PC.  I have used Mount wizzard for years but recently bought new computer and had to setup from scratch.

When MW4 launches, I get the following splash screen and it reports the machine as AMD64. Is this correct for an Intel based machine?
<img width="712" alt="Screenshot of Google Chrome at 13 Aug 2024 at 16_56_30" src="https://github.com/user-attachments/assets/d76826a7-ce45-42b0-af69-a32f9f4d0e34">

Thanks in advance

Nick

**Comment by mworion** [comment]
Hi Nick,
everything went fine. AMD64 stands for all Intel based CPU's with 64 bit (Including AMD as well - I do not know why this was defined that way).
When running MW4 it should report version 3.2.6, which is the latest version.
Hope this helps.
Michel

**Comment by nickym998** [comment]
Thank you, sorry for noob question!

Thank you also for this software, I use it every time

**Comment by mworion** [comment]
Hi Nick, thanks for the feedback. Michel
