### ISSUE TITLE
Measuring not working

### ISSUE THREAD

**Issue by aphelyon-net** [mworion/MountWizzard4#364]
Unsure if this is 10micron issue with latest firmware revisions, or in MW4
I'm using the latest 3.2.6 version. 
Measuring no longer displays or shows graphs?

![Uploading Screenshot 2024-08-15 at 9.55.29 pm.png…]()

**Comment by mworion** [comment]
Hi, your upload did not finish.
I checked it, should work. Did you enable a driver for that ?
![Bildschirmfoto 2024-08-15 um 16 25 19](https://github.com/user-attachments/assets/69961a23-0842-4ea0-bd56-4dbbca74e59c)

![Bildschirmfoto 2024-08-15 um 16 26 18](https://github.com/user-attachments/assets/7e7f3483-20b2-4491-9244-964ed696ba68)
Hope this helps
Michel

**Comment by aphelyon-net** [comment]
Oh thank you, can confirm yes that worked. I had somehow missed this , feel free to delete this issue.
