### ISSUE TITLE
MW4 does not get images from SGPro

### ISSUE THREAD

**Issue by Cent74** [mworion/MountWizzard4#365]
Hi there,

My camera is controlled via SGPro. When I take a "Expose 1" image in MW4, SGpro successfully takes the image and writes it to the MW4 folder.

However, the image does not appear in the MW4 "Imaging" window. The last error I see in the trace log is:

_Verification reported errors:
HDU 0:
    Card 34:
        Card keyword 'STRSZ1x1' is not upper case._

It worked for me in the past, but not anymore even though I'm not aware of any changes to my system (except an update of SGpro to the latest version).

Many thanks in advance for any advice!
[mw4-2024-08-17.log](https://github.com/user-attachments/files/16644109/mw4-2024-08-17.log)

Uli

**Comment by mworion** [comment]
Hi Uli,
sorry to hear. It might be that SGPro did add some Header info in the FITS file and the used library does a hard compliance check.
To find out and to do a workaround on MW4 side, could you ZIP and post this Image from SGPro here ?
All attempts to provoke this header entry fails.
Many thanks.
Michel

**Comment by Cent74** [comment]
Hi Michel,

I tried loading another image taken with the new SGpro version, and it worked. The image was displayed immediately.

However, when I then click "Expose 1", SPpro takes another picture, and the status windows above "Camera" in MW4 says "exposing" -> "download" - "saving" and stays there. The load button in Image is grayed out and the image window is not updated. If I then close the image window and reopen it, the new image appears. But I don't see image statistics under "statistics and formulae", nor does modelling work - it just hangs at the first image.

I'll attach one of the .fit files.

Many thanks for your support and best wishes,
Uli


[2024-08-17-09-00-46-exposure.zip](https://github.com/user-attachments/files/16644183/2024-08-17-09-00-46-exposure.zip)

**Comment by mworion** [comment]
Hi Uli,

I made a beta build for you: 3.7.0b0 (could be installed through mw4 when enabling beta or any other method). This will bring you relaxed header checking. From what I can see is that many of the astronomy community sees header entries with lower cases as "wrong". The new entry is defined and by SGPro only. So from my point of view, they should correct this.
I did now a warn only and silent fix for that (going for upper case change).

Please report back if that works now.
(my old SGPro license - 3.x - does not write this entry)

Michel

**Comment by Cent74** [comment]
Thanks Michel for the fast reply. Just to double check, I don't see a 3.7 beta, only a 3.2.7 beta. Is this the one you mean?
Uli

<img width="395" alt="image" src="https://github.com/user-attachments/assets/9b51a9e3-9980-4d68-bbee-ae27230e601f">

**Comment by mworion** [comment]
Sorry it will be a 3.2.7b0

**Comment by Cent74** [comment]
Yes, it works!!
So many thanks for your great support and the fantastic software you're writing!
Best wishes, Uli

**Comment by mworion** [comment]
Closing it. solved with next release.
