### ISSUE TITLE
Updates are not working

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#367]
### Discussed in https://github.com/mworion/MountWizzard4/discussions/366

<div type='discussions-op-text'>

<sup>Originally posted by **Jojo1703** August 17, 2024</sup>
Hello,
I have the problem that no more updates are being sent to the mount (GM3000). Satellites, comets, asteroids are not working. The earth rotation data cannot be updated either, see attachement. Version MW4 is the latest 3.2.7b0, mount is 3.1.10.
Everything was working properly a few months ago.
Is there a solution?
Regards
Jurgen
![leap](https://github.com/user-attachments/assets/93f8d360-f161-4db2-a058-6b4523d36bd3)
![Satupdate](https://github.com/user-attachments/assets/24214606-29ac-4cf8-b65d-788ee3fa5148)
</div>

**Comment by Jojo1703** [comment]
[mw4-2024-08-18.log](https://github.com/user-attachments/files/16649029/mw4-2024-08-18.log)
![satupaster](https://github.com/user-attachments/assets/ed47392f-82fb-4ded-9683-e4d8414051aa)

![astercomet](https://github.com/user-attachments/assets/21d36832-d3c9-4d75-af92-2e54d39a6af9)

Hello Michel,

thank you very much for your help.
The Earth Rotation Update now works again, I don't know why but OK.
What doesn't work are the other updates for satellites, asteroids and comets. For example, if I select satellite, the update window for asteroids suddenly appears, but it gets stuck. For example, if I select update for asteroids, the window for comets appears and then hangs, see pictures.
Regarding your further question about the firmware: do you mean the mount update? I still have 3.1.10. I don't see any other possible version in the 10Micron forum either.

greeting
Jurgen

**Comment by mworion** [comment]
Hi Jurgen,

I went back and forth. Still I see now the issue like you (TLE and comets running now). I have no clue what's happening in windows which leads to this way. In my setup (and I will offer a 3.2.7b1 for that later this evening), in asteroids it's opening the file selection, but speed is really, really slow. 

What you could do: Interfere manually in the updater by selecting the "minorPlanets.mpc" file and finishing the dialog manually. This let's you update the data as the prep was already done.

With (hopefully) the upcoming firmware 3.1.15 ff (whenever 10micron will use them), I switch from this automation way to a direct communication to the mount. Hopefully from then on, these thing will be much easier (as 10micron offer also the web interface for manually choosing the files).

So from my knowledge there is no way for further improvements possible.
Michel

**Comment by Jojo1703** [comment]
Hi Michel,
I was able to update my mount to 3.1.15 and now the updates for satellites, comets and asteroids seem to work, some of them run automatically.
But what surprises me is that, for example, a very old Epoch appears at ISS, see picture. However, a current file can be seen in the work/data directory.

greeting
Jurgen


    Am Sonntag, 18. August 2024 um 19:01:02 MESZ hat Michael ***@***.***> Folgendes geschrieben:  
 
 


Hi Jurgen,

I went back and forth. Still I see now the issue like you (TLE and comets running now). I have no clue what's happening in windows which leads to this way. In my setup (and I will offer a 3.2.7b1 for that later this evening), in asteroids it's opening the file selection, but speed is really, really slow.

What you could do: Interfere manually in the updater by selecting the "minorPlanets.mpc" file and finishing the dialog manually. This let's you update the data as the prep was already done.

With (hopefully) the upcoming firmware 3.1.15 ff (whenever 10micron will use them), I switch from this automation way to a direct communication to the mount. Hopefully from then on, these thing will be much easier (as 10micron offer also the web interface for manually choosing the files).

So from my knowledge there is no way for further improvements possible.
Michel

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
  

|  | Virenfrei.www.avast.com |

**Comment by mworion** [comment]
Hi Jurgen,
attachments of Email with reply are not included in the issue thread. You have to drop them on the web page. So I cannot see the image.
Michel

**Comment by Jojo1703** [comment]
Hi Michel,
I was able to update my mount to 3.1.15 and now the updates for satellites, comets and asteroids seem to work, some of them run automatically.
But what surprises me is that, for example, a very old Epoch appears at ISS, see picture. However, a current file can be seen in the work/data directory.

greeting
Jurgen
![satupdate alt](https://github.com/user-attachments/assets/45099471-ddee-4869-ab2d-a165a5d47490)

**Comment by mworion** [comment]
Jurgen,
strange. 
Please close MW4, delete the file "stations.txt" in your work/data folder and restart MW4 again.
Michel

PS: Could you post the log file? You set MW4 to online, does it have also internet connection ?

**Comment by Jojo1703** [comment]
Hi Michel,

success with Satellite Stations but e.g. 100 brightest doesn´t work. Only old datas are shown, see picture

![brightsat](https://github.com/user-attachments/assets/62857ef2-d6a8-4833-9def-1d595ac0869c)

and Yes I have always internet connection.

[mw4-2024-08-20.log](https://github.com/user-attachments/files/16679127/mw4-2024-08-20.log)

Bye
Jurgen

**Comment by mworion** [comment]
Hi Jurgen,
it seems that the file entries in work/data went somehow corrupt. Please all "*.txt" files in this data folder as they will be newly generated then.
Michel

**Comment by Jojo1703** [comment]
Hi Michel,

I have deleted all *.TXT files but without success with updates. 
I have installed your new version 3.2.7b1 and then everything is OK. All updates were good.
Thanks again,

Jurgen

**Comment by mworion** [comment]
Jurgen,
happy to hear. I do not know why. I leave it at this point. If anything happens again, please reopen the issue.
Michel

**Comment by Jojo1703** [comment]
Hi Michel,

for your information, the updates don't always work, only sometimes, strange.
Something else, see picture: do you know which serial number has to be entered here?

![serial](https://github.com/user-attachments/assets/49620d1c-c1c8-45c0-a1fb-713cfaa4d29d)


greeting
Jurgen

**Comment by mworion** [comment]
Jurgen I do not enter or see any serial number.
As you are on 3.1.15, would you mind to give an early v4.x a chance ? 
You have to be on python 3.10 or later. If you would like to stay also with 3.2.7 this is the right way.
Please give me a hint. v4x handles the updates directly without any use of updater if you could see the web interface (please open a browser and enter the ip of the mount)
![Bildschirmfoto 2024-08-22 um 18 46 57](https://github.com/user-attachments/assets/186831f0-822e-4a7b-99bf-4e5a3d0bb5ec)
You might have to enable in the keypad the web services:
![Bildschirmfoto 2024-08-22 um 18 49 14](https://github.com/user-attachments/assets/b4f8081b-aeb6-447e-88a0-a2c8bbafc25e)
![Bildschirmfoto 2024-08-22 um 18 49 23](https://github.com/user-attachments/assets/a6dddd63-328a-48eb-a2d4-df59f5a11fe7)

Michel

**Comment by Jojo1703** [comment]
Hi Michel,

I have already used the update via the web interface but it behaved the same as with MW4. 
Unfortunately I don't understand what you mean by version v4.x

greeting
Jurgen

**Comment by mworion** [comment]
Hi Jurgen,
interesting. If you are saying it behaved like MW4, what do you mean. 

My experience is that the 10micron updater (exe for windows, which you get if you install a new firmware) works, but automation of this process through MW4 sometimes sucks due to the “old way” of doing automation.

On the Web interface I saw sometimes glitches that the service went down after some time and you have to reboot the mount computer to restart the webservice for these updates again.
Both ways in firmware 3.1.15 are completely different ways to upload datan to the mount.

Different topic: actual MW4 version uses the first way of automating things to the mount, the next version of MW4 will make heavy use of the web interface. This means MW4 will download select and filter files from various sources and transfers them directly to the mount. You won’t see the web interface nor you need any other browser window. And downloading and transferring a set of asteroid data to the mount will take only a few seconds. But this way relies on a good working web interface on the mount side. Question would be if you are willing to test this.

Michel

**Comment by Jojo1703** [comment]
Hi Michel,

what I meant by the same behavior on the web interface/MW4 is that the updates sometimes work for both, sometimes not.
The web interface doesn't always work for me either; it can't be started after entering the IP.
Of course I'm willing to do further tests if you tell me exactly what to do.

greeting
Jurgen

**Comment by mworion** [comment]
Hi Jurgen,
thanks for the willingness to test (it is still an alpha !!!).
Prerequisite is python 3.9 - 3.12 on the computer (if you are willing to keep 3.x, please use python 3.10)
Choose a new workdir.
Copy the startup.pyz into the new work folder
Install alpha with 
```
python startup.pyz --version 4.0.0a19
```
to install the alpha.
After that you could copy the config folder in your new working dir to avoid typing all data.
Starting is the same like old version, just
```
python startup.pyz
```
There will be still many thing to be changed, but it should hopefully work out of the box. Interesting will be the test for satellite, asteroids, comets and IERS deltaT data.

Michel

**Comment by Jojo1703** [comment]
Hi Michel,

I tested it, all updates work as expected, excellent work.

 I noticed 2 things:

1. I miss an update option to see the well-known asteroids again, such as Ceres, Vesta, Pallas etc. How can they be restored? They were originally stored in the mount.

2. the virtual keypad doesn't look as nice as before, see picture.

![key](https://github.com/user-attachments/assets/d28f0e69-bf1a-4003-b4b4-97edc096fb6c)


greeting
Jurgen

**Comment by mworion** [comment]
Jurgen,
yes, thats not finally worked through. the keypad i will check, should be not altered.
Michel

**Comment by Jojo1703** [comment]
Michel,

I just see that the Keypad is like before 

Jurgen

**Comment by Jojo1703** [comment]
Michel,

I looked for asteroids again and found that the known brighter asteroids are not included in the Searching Asteroids lists, see the current visibility from today in the picture. I can't find these, for example IRIS or PALLAS, in any of the asteroid data lists offered by MW4.

Are there other lists?

Jurgen

![ast](https://github.com/user-attachments/assets/886d19ba-c378-4b79-bc35-46d56bc92b67)

**Comment by mworion** [comment]
Hi Jurgen,I try to add an online search as well to MW4. So hopefully this makes the difference.Stay tuned.MichelAm 31.08.2024 um 21:03 schrieb Jojo1703 ***@***.***>:﻿
Michel,
I looked for asteroids again and found that the known brighter asteroids are not included in the Searching Asteroids lists, see the current visibility from today in the picture. I can't find these, for example IRIS or PALLAS, in any of the asteroid data lists offered by MW4.
Are there other lists?
Jurgen
ast.JPG (view on web)
