### ISSUE TITLE
camera exposure is not finite

### ISSUE THREAD

**Issue by michael-jon** [mworion/MountWizzard4#369]
**Describe the bug**
When using MW4, I try to take either a single exposure image or looping exposures.  The image doesn't change, and I am finding in the main screen the "exposing" message is constantly on.

**To Reproduce**
1. Start up MW4. Mount (GM2000 Combi) and Camera (QHY294M) turn green (camera is controlled by NINA).
2. Start modeling and bring up image tab, set exposure for both single and exposure N to 5.000 s
3. Push Exposure N, Main screen shows "exposing" and image does not change even if I manually move mount to determine if it is taking multiple images.

**Expected behavior**
I expected a new image every 5 seconds so I could use control pad to move stars into "bullseye"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by mworion** [comment]
Hi michael-jon,
could you paste the log file as well in this thread. Many thanks.
Michel

**Comment by michael-jon** [comment]
[mw4-2024-09-06.log](https://github.com/user-attachments/files/17006500/mw4-2024-09-06.log)
[mw4-2024-09-09.log](https://github.com/user-attachments/files/17006501/mw4-2024-09-09.log)
[mw4-2024-09-10.log](https://github.com/user-attachments/files/17006502/mw4-2024-09-10.log)
[mw4-2024-09-13.log](https://github.com/user-attachments/files/17006503/mw4-2024-09-13.log)

Thank you for responding to my post/question. It took me a couple of days to figure out where the logs were saved and how to post them to this forum, so I am sorry for taking a few days to respond.  Thank you for any help you can offer me.
Best, mj

**Comment by mworion** [comment]
Hi Michael-Jon,
no worries and sorry from my side as I did not say anything where to find the logs.
I had a first look to the log (still need some more time as I came back from vacation the evening)
- I see some timeouts in the communication to NINA. I guess you are running now v3 actual build correct (for checking the setup)
- I also recognized that you chose a setup to solve the image after the download. Did you intend this ?  
-> Please uncheck this option in case or config a valid plate solver e.g. ASTAP as you might not have configured one already.
- In some cases NINA reports camera busy. I currently do not know why. This I have to evaluate why NINA sends this.

Michel
