### ISSUE TITLE
Times Expired (not an issue)

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard4#37]
hi Michel,
I noticed that MW4 is warning me about internal time table expired. Is there a way to update through MW4?
I didn't find any clue in the 10Micron user manual not in the handset, so doing that using MW4 would be great.
Best,

Ferrante
![Screenshot from 2020-05-29 08-26-47](https://user-images.githubusercontent.com/38842860/83229366-29f88b00-a188-11ea-8dcc-69f904b20a8a.png)

**Comment by mworion** [comment]
Hi Ferrante,

The DeltaT expires is not extreme critical, but the mount becomes more inaccurate. Unfortunately there is no way to update this value except the 10micron (Windows) updater itself. There is no command protocol doing that. I asked 10micron for opening this with a protocol, but so far I can’t do anything about it. So the way is to install the QCI Updater, download the files from internet an program them to mount.

Michel

**Comment by fenriques** [comment]
Thanks Michel. I updated the data from the firmware updater as you suggested. Everything worked out fine.
