### ISSUE TITLE
Camera never completes exposure 

### ISSUE THREAD

**Issue by nickym998** [mworion/MountWizzard4#370]
Hi,

I am running Mount wizzard 4 3.2.6 on a windows 11 PC. I have used this for a long time but have recently switched to a new PC from a windows 10 machine. My camera is an ASI 1600 MM-cool which works fine but not under mount wizzard.  The camera connects via ASCOM 6.2 in the settings tab without issue.  When I start a modelling run, the camera begins exposure but never finishes the shot and I have to cancel the modelling run.  The camera also does not work if I use the imaging tab and try to take a single exposure. I then open NINA and connect to the same ASCOM driver and the camera functions perfectly.

Any ideas?

kind regards

Nick

**Comment by mworion** [comment]
Hi Nick,

sorry to hear. Would you mind to post a log file and switch to the actual beta version which is 3.2.7b2. For updating check show beta in the updater tab.

Michel

**Comment by nickym998** [comment]
Thanks Michel,

The update to beta seems to have solved the problem.  I will also attach logs.

many thanks

Nick
[mw4-2024-11-11.log](https://github.com/user-attachments/files/17775567/mw4-2024-11-11.log)
[mw4-2024-11-12.log](https://github.com/user-attachments/files/17775572/mw4-2024-11-12.log)

**Comment by mworion** [comment]
Hi Nick,
thanks for the logs. It seems (out of the logs) you had a similar problem, for which I made the beta. Please let me know whenever you run into problems again and reopen the issue again. I will release this beta if there is no further problem upcoming.
Michel
