### ISSUE TITLE
Unable to update MW4 from 3.2.6 to 3.2.7

### ISSUE THREAD

**Issue by WillB-2024** [mworion/MountWizzard4#371]
Hi Michael.

This is non-urgent as I can work around by deleting the MW4 program folder and manually downloading the latest version when necessary and I have no pressing need to update MW4 at this time but is a mystery why I can't update MW4 from inside MW4 itself.

**Describe the bug**
On the observatory PC it is not possible to update MW4 except by deleting the startup folder and manually installing the latest version.

**To Reproduce**
1. Open MW4.
2. Click on Settings tab.
3. Click on Update, Logging tab.
4. Click "Enable download data and program files".
5. Check Updater display, Actual version = 3.2.6, Available version = 3.2.7.
6. Click "Start Updater" button.
7. MountWizard4 Updater window appears with "Update to version: [3.2.7]" displayed.
8. Click "Start Update" button.
9. MountWizard4 Updater window immediately closes and MW4 launches back to the "Update, Logging" tab with the original version 3.2.6 still installed as the actual version.
10. See attached error log created with Trace enabled.

**Expected behaviour**
On my other non-observatory PC MW4 Update works as expected.

**Desktop (please complete the following information):**
 - OS: Windows 11 PRO 24H2.
 - OS Build: 26100.2314.
 - OS Experience pack: 1000.26100.32.0.
 - OS Region: English UK.
 - Browser: Edge.
 - Browser version: 131.0.2903.70.

Hardware: OnLogic Helix 511 Industrial PC.
CPU: Intel Core i5-12600HL (Alder Lake) 2.7-4.5Ghz 12 Core Processor.
RAM: 32Gb DDR5 4800.
Primary Hard Drive: Transcend 1TB PCIe M.2 2280 NVMe.
Secondary Hard Drive: Transcend 1TB M.2 SATA SSD.

**Python version current: 3.9.13.

**Other Python versions tried: 3.10.11.

**Additional context**

The only AntiVirus and Firewall on this machine is Windows Defender and I have tried running the MW4 Updater with Windows Defender disabled and Windows UAC switched off but no change to the behaviour.

Kind regards.

William.

[mw4-2024-11-27.log](https://github.com/user-attachments/files/17935979/mw4-2024-11-27.log)

**Comment by mworion** [comment]
Hi Will,
everything is OK. If you have actually no other application using python so far, you could try 

```
python startup.pyz --clean
```

and try updating or downgrading again. It looks like a case that MW4 is also installed as system package a not only as user package in the virtual environment residing in "venv" folder. If you are updating MMW4 in this case, it updates correctly the user package, but still the system package has priority and throws an error. The command above cleans up the system package. Therefore I asked if you have some other python apps installed (beside MW4 any version), because their system packages would be deinstalled as well.

Hope this helps.

Michel

**Comment by WillB-2024** [comment]
Hi Michael.

Thanks for the quick reply.

I ran the python "startup.pyz --clean" command from the MW4 directory but after that MW4 would not start at all.

I suspect that this problem may have been caused by installing Python and MW4 over a Microsoft Remote Desktop link and not while logged in as the local user of the observatory PC so last night I went out to the observatory and logged in locally, after backing up the MW4 config folder I deleted the installed Python platform, deleted the MW4 folder, removed the environmental path registry entries for Python and carried out a fresh install of Python 3.10.11 and MW4 v3.2.7.

After that I copied back the backup MW4 Config folder and started up MW4 again, this time I could roll back to MW4 v3.2.6 via the Updates and Logging tab and then after a reboot could update to v3.2.7 again, after which I ran a small "Golden Spiral" model of 25 points and polar aligned, followed by a full 96 point "Golden Spiral" model that resulted in a reported 23 arc-second Polar alignment error and 5 arc-second Otho align error, which is excellent for my needs.

So please mark this issue report as closed and if the problem reappears when you release MW4 v3.2.8 I'll get back in touch.

Thanks again Michael...

William.
