### ISSUE TITLE
Ideas fo analyse window

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#38]
Hi Michel,
here are 3 ideas / questions:

1. Is it possible to load a model from the mount and store it on disk, so it is available in the analyses window? At least for some functions?

2. Is it possible to change the file selector for loading a model. Very often I am looking for the latest or second latest model. Hence it would be nice that you could sort for date.

3. Is there any explanation for the model prefixes?  "m-allign", "m-file", or "m-none"

**Comment by mworion** [comment]
Hi Rüdiger,

To your questions see below:

> Am 29.05.2020 um 15:55 schrieb Ruediger3 <notifications@github.com>:
> 
> 
> Hi Michel,
> here are 3 ideas / questions:
> 
> Is it possible to load a model from the mount and store it on disk, so it is available in the analyses window? At least for some functions?
> 
> 
Yes / No: the data you could get from the mount model you see under ManageMount Model Tab in the main window. Problem: The model in the mount when retrieved does not give you all the context (like pier side etc)

Thats the reason why I store this context as model file including the information I get from the mount.
> Is it possible to change the file selector for loading a model. Very often I am looking for the latest or second latest model. Hence it would be nice that you could sort for date.
Sure.

> Is there any explanation for the model prefixes? "m-allign", "m-file", or "m-none"
> 
> 
The prefixes tell you which type of model build you used from build points align stands for alignment points, file for loaded from file etc.

**Comment by Ruediger3** [comment]
Hi Michel,

thanks for the lighting fast reply. :)

1. that's what I had (unfortunately) expected. :(
2. the opportunity to alternate the sort order would be a great help
3. That is quite strange, since I never changed the way I create a model, but I have all these pre-fixes in my list. Would be great to have a short note in the help documents which explains the meaning. 

Again tank you for your great support.

**Comment by mworion** [comment]
Hi Rüdiger,

v0.150.23b2 should have a reverse ordering and I changed prefix top postfix, so order will be date / time newest first.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,
just installed and tested. Perfect! Thanks a lot. This is very helpfull.
Cheers
Rüduger
