### ISSUE TITLE
Negative Lateral Offset value

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#41]
Hi Michel,

thanks for implementing the Lateral offset for me, that makes quite a difference. A positive value is in the direction as in the new image in MW4, but I can imagine that there are users that have the imaging scope on the other side, therefore requiring a negative offset, but currently it is not possible to enter a negative value (for me the current situation is fine, so no rush from my side ;-)).

best wishes,
Nicolàs

**Comment by mworion** [comment]
Fixed in 0.150.25b1
