### ISSUE TITLE
No automatic connect to devices

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#43]
Hi Michel,

I identified a serious problem: When starting MW4 it automatically connects the devices e.g. camera. But this could be fatal if you try to start MW during an imaging session, when these devices are already connected (esp. camera, MGPBox) and lead to crashing the complete session, due to mutual access to devices. I have not found any way to start MW4 and prevent it from connecting. Hence I could not start MW anymore for the complete night. 

So I would appreciate if there would be an option to define auto connect [yes | no].

Thank you!

**Comment by ACMBakx** [comment]
I have to connect to my camera every time  I start MW. Go to the setup menu and clik ok.
It does not auto connect. Same for my dome. The scopedomedriver is started but I have to connect just like the camera. Everything else goes on green straightaway.
 Actually I prefer not to auto connect any devices for reasons mentioned by Ruediger.

**Comment by mworion** [comment]
OK I really like ASCOM as it does dot allow connect clients multiple times.
I give it a try.

**Comment by mworion** [comment]
Hi Arie, Rüdiger,
the special treatment of ASCOM devices is in 0.150.25b5:
automatic -> obvious
if not automatic, you could connect disconnect all drivers manually. Even in automatic mode.
If done this for all ASCOM driver in parallel I do not want to treat them individually
Please test and give me a feedback.
Michel

**Comment by ACMBakx** [comment]
Tried it and seems to work as requested.
Thank you Michael.
Arie

**Comment by Ruediger3** [comment]
Also tried and works as expected. Great!
Thank you very much - this helps a lot :)
Rüdiger
