### ISSUE TITLE
Update to 0.150.25b6 fails 

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#45]
Hello Michel,
since last night the update fails. See screenshot. 
Thank you!
![2020-06-03_08h59_05](https://user-images.githubusercontent.com/65772654/83605702-a7514080-a578-11ea-8366-60db90aaa179.png)

**Comment by mworion** [comment]
..should be OK by now...

**Comment by Ruediger3** [comment]
works again after refactored unit tests
