### ISSUE TITLE
Updated from 0.150.24 to 0.150.25ax will not start

### ISSUE THREAD

**Issue by TomBootz** [mworion/MountWizzard4#47]
Hi Michel;

I upgraded from 0.150.24 to 0.150.25a (something) don't recall what it said but is was NOT from the Beta line. MW4 will no longer start.

Relevant syslog below:
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]: Traceback (most recent call last):
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 44, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     from mw4.mainApp import MountWizzard4
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mw4/mainApp.py", line 28, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     from mountcontrol import qtmount
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/qtmount.py", line 31, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     import mountcontrol.mount
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/mount.py", line 29, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     from mountcontrol.firmware import Firmware
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/firmware.py", line 27, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     from mountcontrol.convert import valueToInt
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/convert.py", line 26, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     import skyfield.api
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/skyfield/api.py", line 13, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     from .iokit import Loader, load_file
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/skyfield/iokit.py", line 17, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     from .jpllib import SpiceKernel
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/skyfield/jpllib.py", line 6, in <module>
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]:     from jplephem.exceptions import OutOfRangeError
Jun  6 20:44:29 tom-x570-aorus-master-1 MountWizzard4.desktop[3118]: ModuleNotFoundError: No module named 'jplephem.exceptions'

System OS: Ubuntu 18.04.4 LTS

Clear skies
Tom

**Comment by mworion** [comment]
Hi Tom,
this was an alpha release, which you should not be able to see at all. 
To get your environment running again please change with terminal in your working directory and:

source ./venv/bin/acitvate
pip install jplephem --upgrade
pip install mountwizzard4==0.150.25b7
deactivate

Michel

Please report if that fixes your problem.

**Comment by mworion** [comment]
Addition: Brandon, who maintains skyfield will fix the issue in his next release. Until then I put in a workaround, once installed 0.150.25b9 or later.

Michel

**Comment by TomBootz** [comment]
MIchel;

I seem to have a problem finding that version:

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mountwizzard4==0.150.25b7 (from versions: none)
ERROR: No matching distribution found for mountwizzard4==0.150.25b7

Tom

**Comment by mworion** [comment]
Tom,

normally you should have MW4 in a virtual environment and therefore this should be writable. Actually is 0.150.25b9. This should be visible as I counter checked it from ubuntu right now as well.
Michel

**Comment by TomBootz** [comment]
OK got this far:

Installing collected packages: mountwizzard4
  Found existing installation: mountwizzard4 0.150.25a6
    Uninstalling mountwizzard4-0.150.25a6:
      Successfully uninstalled mountwizzard4-0.150.25a6
Successfully installed mountwizzard4-0.150.25b7

Still doesn't start up, let me check syslog.

**Comment by TomBootz** [comment]
Syslog:

Traceback (most recent call last):
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 44, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     from mw4.mainApp import MountWizzard4
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mw4/mainApp.py", line 28, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     from mountcontrol import qtmount
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/qtmount.py", line 31, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     import mountcontrol.mount
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/mount.py", line 29, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     from mountcontrol.firmware import Firmware
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/firmware.py", line 27, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     from mountcontrol.convert import valueToInt
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/mountcontrol/convert.py", line 26, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     import skyfield.api
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/skyfield/api.py", line 13, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     from .iokit import Loader, load_file
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/skyfield/iokit.py", line 17, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     from .jpllib import SpiceKernel
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:   File "/home/tom/MW4/venv/lib/python3.7/site-packages/skyfield/jpllib.py", line 6, in <module>
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]:     from jplephem.exceptions import OutOfRangeError
Jun  7 09:24:41 tom-x570-aorus-master-1 MountWizzard4.desktop[5449]: ModuleNotFoundError: No module named 'jplephem.exceptions'

**Comment by TomBootz** [comment]
Ah didn't see your comment about ...b9. Installed that and it is working now. 

Thank you!
Tom

**Comment by mworion** [comment]
Great to hear, OK closing this point now.
