### ISSUE TITLE
ASCOM Support for "Obeserving waether conditions Hub"

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#48]
Hello Michel,
since integration for INDIGO will definitely take some more time, would it be possible to integrate ASCOM direct support for "Observer weather conditions hub" so SQM and MGPBox could be connected?

Thank you in advance!
Cheers Rüdiger

PS: I closely follow the current activities related to dome control with Nicolàs. Take your time to finish this first. This has definitely more important.

**Comment by mworion** [comment]
Support added in 0.150.28 for sky meter and sensor weather

**Comment by mworion** [comment]
Any news if this works in your environment ?

**Comment by Ruediger3** [comment]
Hello Michel,

sorry for the delay. I was totally focused on the FW testing...

Just made a first test and it looks good. I get the data. Only with temperatures there is a small mix-up. It looks like that "Temperature" is taken for both Temperatures (also for Sky Temperature) though it is a different value coming from other device.
Please see screen shot. I hope I could make my point clear.

I have not included UPB in the environment hub data, since I i get more precise data from MGPBox.

![2020-07-19_18h31_19](https://user-images.githubusercontent.com/65772654/87880021-a2dccc00-c9ee-11ea-8b7e-c43f092a4a0c.png)

**Comment by mworion** [comment]
Rüdiger,

that's OK, because the SQM does not read sky temperature, but environment temperature, so I set the readout to temperature. The SQM driver does not provide the sky temperature, but temperature property.

Michel

**Comment by mworion** [comment]
...is now online...

**Comment by Ruediger3** [comment]
Hi Michel,
This is not a good idea, since thr SQM is contained in a sealed plastic pipe, which heats up - up to more than 20°C over ambient temperature. This value should be clearly separated and definitely not used for any calibration or post procession.

**Comment by mworion** [comment]
Rüdiger,

you are right. I just show this number, MW4 does not process anything (beside measuring it). Other frameworks show this number, so nothing bad happens. I could not be used.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,
Showing the value was not the issue, but as you can see on the screenshot, the value is copied and used for sensor data, instead of using the correct temp of the observation hub. 
If it would be only displayed then you were right, but it is overwriting the needed temperature.
