### ISSUE TITLE
Improvement suggestions UI (0.150.25b10)

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#49]
Hello Michel,

the new Icon set is very nice, but sometimes on a big screen hard comprehend.
Here are 2 improvement suggestions:

1. Align labels left, because centering the cell content makes the UI too tattered. The human eye has no chance to find anchor points and align the information. 

![2020-06-07_17h02_26](https://user-images.githubusercontent.com/65772654/83972613-6b540d80-a8e1-11ea-8c6b-f0d9cb48206a.png)

2. The text in disabled fields is not readable. It is too dark.

![2020-06-07_17h04_14](https://user-images.githubusercontent.com/65772654/83972681-d43b8580-a8e1-11ea-8573-10504feae1b1.png)

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
One more suggestion: mount control uses same error symbol for different directions. that is misleading. Better would be an arrow in the matching direction or no symbol at all. 

![2020-06-07_17h18_38](https://user-images.githubusercontent.com/65772654/83972904-2630db00-a8e3-11ea-8077-bd2c84b5e684.png)

**Comment by mworion** [comment]
Hi Rüdiger,
I made a quick ...b11 release. The first point were only 2 styles changed and I removed the misleading icons until I find better ones
Michel
