### ISSUE TITLE
MW4 device settings do not switch to Alapaca when selected to do so.

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#5]
I installed MW4 on my in-house laptop as per recommended procedure.
Only ASI1600 camera to connect physically.
Installation went without a problem.
MW4 starts up and runs update too.
In sett/config - devices I can select the dome driver only to switch to alpaca.
Other devices only show disabled and indi. No alpaca. Not even after selecting alpaca in the setup.
Camera is connected ok, because SGP and CCDCile can make contact and asco- rest shows green buttons.
Image downloads are really slowthrough alapaca by the way.
From 1-2 sec to 15-18 sec with ASI1600 and ASI071

Unless I can connect through alpaca I cannot do a test of MW4.

Just installed MW4 on my dome computer.
Same result.
All equipment is up and running, but MW4 sees only the dome as a Alpaca device.

![MW4Alpaca1](https://user-images.githubusercontent.com/59890758/72533671-d428e380-3875-11ea-8909-a962bb7c1da0.JPG)

[mw4-2020-01-16.log](https://github.com/mworion/MountWizzard4/files/4071799/mw4-2020-01-16.log)

rgds
Arie

**Comment by mworion** [comment]
Hi Arie,

good to hear that installing went OK. I have to look into, what’s happening. As I said the first test I try to get the dome working, because we than could check if the geometry calculations are going well. I check and write later.

Michel

**Comment by mworion** [comment]
Other devices still in 0.146b5 are not finished beside dome. So this will take some more time to implement. I currently doing implementation on the camera side as it is the next step for modeling.

Michel
