### ISSUE TITLE
Feature Request: FL and Profilename displayed in "Model Build File Analyses" window

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#51]
Hi Michel,

thanks for the new version! Excellent work! Very much appreciated!

While testing, I found myself in a situation, where I miss some information.
I wanted to compare some stored models. But I had the problem to identify which model file belongs to which profile. I create for three different scopes different models, so I had to open one after the other, to find the specific ones or even to read the models in Notepad.

So may I suggest following ideas:
- Include profile name in stored file model file
- display FL in the analyses window
- display profile name in analyses window

Again, great job and this is only making something very good, maybe again even a bit more better :)

Thanks a lot!
Rüdiger

**Comment by Ruediger3** [comment]
Maybe also a good idea is to have a dedicate sub directory for each profile and defaulting to the appropriate sub folder.

**Comment by mworion** [comment]
The idea of adding the profile is interesting, other information to the model file makes sense, too.
Try to implement this.

Adding dedicated subfolders according to profile names lead right now to a too complicated and not backward compatible design.

Michel

**Comment by Ruediger3** [comment]
Thanks Michel, that will definitely help to identify the appropriate profile resp. the telescope.
