### ISSUE TITLE
Unreadable text in file open dialog

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#52]
Hello Michel,

in the file open dialog when right click, the option menu is not readable, since the text is too dark.
Please see screenshot.

Thank you!
Rüdiger

![Dialog-right-click](https://user-images.githubusercontent.com/65772654/84594489-e1f98980-ae52-11ea-9604-546afc3bbdfa.png)

**Comment by mworion** [comment]
Normally I should have disabled the context. But anyway, I changed it for the next version.
Michel
