### ISSUE TITLE
Almanac: Twilight Phases not poppulated

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#53]
Hello Michel,

in Almanac, the "Twilight phases upcoming night" is not populated by default when opening. You have to change Timezone from local to UTC an back to get data calculated.
Might be better to populated it by default with the chooses time zone.

Also the main window is empty. "Twilight phases per year" is a black empty area, Not sure how to use it.

Thank you!
Rüdiger

**Comment by mworion** [comment]
Status was: mount has to be connected. 
Changed the behavior: now it works without running mount.
Michel

**Comment by Ruediger3** [comment]
Perfect. works with 0.150.26b1 as expected.
Thanks  a lot!
