### ISSUE TITLE
Hemisphere: Switchting between Built and Horizon mask freezes App for a while

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#54]
Hello Michel,

in Hemisphere Window, when switching between "Normal", "Edit Built points" and "Edit Horizon Mask" freezes the app between 3 to 10 seconds.

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
can't see that right now. Could you make a clean run (delete log file), run and test it and post a log file ?
Michel

**Comment by Ruediger3** [comment]
Sure, please find log file attached. 
Thanks!

[mw4-2020-06-14.log](https://github.com/mworion/MountWizzard4/files/4777004/mw4-2020-06-14.log)

**Comment by mworion** [comment]
Rüdiger,

reason for this (which I don't see on Mac) is I switch odd dual axis tracking as well in hemisphere when enabling slew function there. As you might have not connected the mount in the test, MW4 waits until timeout for the mount communication (which is 3 s. 
Please test:
- if the situation is still there when mount connected
- if the situation is still there when disable dual axis tracking while model build is disabled.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

Sure I will test and revert back as soon as weather gets better, since electronics is not connected.

But wouldn't it make sense to avoid communication with mount here, since usually you design your horizon mask and point spread in advance during day, when the is usually never connected? All these activities belong to the preparation acitivities or bad weather periods. Same as we had with the Almanac. These tools are extremely useful for planning before you fire up your system. 🤔

Thank you!

**Comment by Ruediger3** [comment]
Solved in 0.150.26b2. Switches quickly forth and back now.

Thanks!

Cheers
Rüdiger
