### ISSUE TITLE
Almanac: 2 Improvement sugestions

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#56]
Hello Michel,

I really do enjoy the Almanac. It is a very useful deature, but there are two things which are confusing to me:

1. In the right list the entries for "Darkness" is missing. You dont know where "astronomical Twilight" ends, and this is the most important information.

2. The yearly graph should be in the same time zone as the list. UTC is of course fail safe towards DST and similar things, but it forces you always to recalculate the times on the fly. Hence it would nice to align the graphic with the time zone chosen.

Thank you in advance!

Cheers
Rüdiger

![2020-06-16_10h56_42](https://user-images.githubusercontent.com/65772654/84755269-bcd75900-afc1-11ea-855d-6f7f0b8b42e8.png)

**Comment by mworion** [comment]
Rüdiger,

Point 1: could it be the case that your lat is not defined (as not connected to mount) and is set as default to Greenwich? If so, there is no dark.

Point 2: makes much work as I have to recalculate the positions (list is easy as just defining the time zone). I put it on the wish list.

Michel

**Comment by Ruediger3** [comment]
Hello Michel,

1. No, the location is set properly (see screen shot)

I guess, darkness is not show, since currently there is none. But at least there should be an entry like: N/A or "--" to make that clear.

2. Second the diagram is not correct, since there is no astronomical darkness in the time period in the circle). Looks like it uses a wrong location.
Time zone could be easily adjusted with just shifting the the diagram along y-axes with an hourly offset.

Cheers
Rüdiger


![2020-06-18_12h39_09](https://user-images.githubusercontent.com/65772654/85011270-92bc9d00-b161-11ea-91ab-e4d0917c43f3.png)

**Comment by mworion** [comment]
Hi Rüdiger,

point with the graphics valid. With you lat, there is right now no darkness. And you‘re right, when no Location is there, you will see „—-„

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

thank for the reply. 

I meant with "--" these should be displayed if there is no darkness at you current location and time. So it makes absolutely clear, that it wont be dark tonight.
And if there is darkness. then there should be a lines about Darkness.
I would suggest to make it clear what is really meant:

Always to use the point of time when something starts
e.g the list could look alike (all start times). By that all intervals are well defined.:
Civil Twilight
Nautical Twilight
Astronomical Twilight
Dakrness
Astronomical Twilight
Nautical Twilight
Civil Twilight

**Comment by mworion** [comment]
Hi Rüdiger,

I will go to an online version as calculation of world wide timezones, north / south hemisphere etc. Is simply too much to do. I will tale like for the Environment my online source. Not that nice, but OK.
Will be present in next version

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

For me ok since I am stationary, but keep in mind that there are a bunch of people who are mobile or have no internet at their observatory or location. At least you should keep MW's basic functions available offline. 

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Yet another point which you should consider: you are transferring user information to a third party service provider which raises legal issues. You need explicit confirmation of the users within EU in respect to GDPR.

**Comment by mworion** [comment]
Hi Rüdiger,
not all could be done offline. But as you said the overview is prepared before, that's online, the timing calculation stays offline capable.

Right now I do not transmit any user data to a provider. Still there is the point that I load a webpage. There is no capability to store data from web locally as I do not have a local cache for it (make life offline harder). But I will add the hint of what could happen if you are online in the doc's and tooltips and you have to explicit enable the online mode. If you do not get online, you won't have any connection.

Michel

**Comment by Ruediger3** [comment]
Hello Michel,

Nicolàs has a ready to use script even for offline use. I think he will happily share it. I think this should de easily to be integrated. So no need to re-envent the wheel ;)

http://www.dehilster.info/astronomy/astronomical_twilight.php

**Comment by mworion** [comment]
Hi Rüdiger,
I tried to switch now to a local time only solution. You could give it a try it's:
0.150.26a1
As you normally not see alpha in the internal installer, you have to enter the version in the installer field manually.
Good point: you have DST and all other parts in. 

Michel
![Bildschirmfoto 2020-06-21 um 10 11 23](https://user-images.githubusercontent.com/6632980/85219890-a0636400-b3a7-11ea-92d1-6c1ec66cf71e.png)

**Comment by Ruediger3** [comment]
Hi Michel,

that sounds really great! Just tried to install, but get an error.

![2020-06-21_10h37_23](https://user-images.githubusercontent.com/65772654/85220398-61371200-b3ab-11ea-9d86-9357397288cd.png)

**Comment by Ruediger3** [comment]
After renaming the file I get the next error:
![2020-06-21_10h44_51](https://user-images.githubusercontent.com/65772654/85220519-52049400-b3ac-11ea-9635-df4126d97dbb.png)

**Comment by Ruediger3** [comment]
Here the log file. Tried to rename the complained files. But was not successful. 
Please find attached log-file.

[mw4-2020-06-21.log](https://github.com/mworion/MountWizzard4/files/4809206/mw4-2020-06-21.log)

**Comment by mworion** [comment]
OK
thanks to windows! The reason is that windows keeps the files locked for whatever reason (this does not happen on ubuntu and Mac). So the solution would be to do in manually:
Change to work dir

venv/Scripts/activate
pip install mountwizzard4==0.150.26a1
deactivate

and then start with the run script again. This should do the trick. 
Just for information: when this might happen with an official release, there is the update script available as well. But this is not build for updating alpha or beta versions.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

sometimes I use the update script, but I was looking for an option to pass a version ID to it. Now I know, it is not possible. But I will keep the "trick" above.

the graphic looks fine to me!

One minor suggestion: labeling of the x-axis: this is a bit hard to read. I would label every second month 1st and joust with month's short name "Feb", "Apr", "Jun" and so on. The grid I would keep month wise. So there is no need to have daily dates. What could be also improve could be a mouse over / mouse tooltipp
![2020-06-21_15h08_20](https://user-images.githubusercontent.com/65772654/85225465-d584ac00-b3d1-11ea-9916-01f49a6a6f6d.png)
 showing the actual date you are currently pointing at at. The deluxe version could be when pointing at one of the "event" lines to show date and time as mouse tool tip. but this only nice to have, but would add additional value.

One question: If there is "darkness" is there an addition line and time displayed in the table section shown?

But the rest looks pretty nice to me. Thanks a lot for this offline version. Very much appreciated your work and sorry for all the extra work I produce. Just trying to support.

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,

the list to the right is the list the library brings up. There are only events when happen real, not the ones which exist, but don't happen. As it is an external library I'm not gonna change it.
Try to finalize the tooltip. The X axis I could change. Still some work as the exact day is always in the middle ! So the whole chart moves a little bit per day.
Mouse over is hard to implement. I would omit this part.

Michel

PS: It's not a good idea changing files in venv manually.

**Comment by Ruediger3** [comment]
That's all fine to me. Thanks a lot!

**Comment by mworion** [comment]
The final landing zone:

![Bildschirmfoto 2020-06-21 um 15 54 26](https://user-images.githubusercontent.com/6632980/85226368-82155c80-b3d7-11ea-96ca-26651e488ca9.png)

Michel
