### ISSUE TITLE
Tried to install MW4 on MacBook

### ISSUE THREAD

**Issue by ACMBakx** [mworion/MountWizzard4#6]
I have an old MacBookPro (mid 2009) with OSX 10.11.6 on it.
To try to take a sneak peek at MW4 I wanted to install it on my Mac.
That's all INDI, so should not be a problem. I used the cloudmasters.eu suite years ago.
Installed Pyhon 3.7.1. (for OSX 10.9 and later) and ran the MW4 install script.
After installation ran run script and get a error message that some module is written for OSX 10.12 and later. So this was a unsuccessful attempt. My MBP is to old for this . . . . . maybe I am too?
 :-)
Just to let you know.

**Comment by ACMBakx** [comment]
Last login: Sat Jan 18 14:28:25 on ttys000
MacBook-Pro-van-Arie:~ arie$ /Users/arie/Desktop/MAC_Scripts/MW4_Run.command ; exit;
Traceback (most recent call last):
  File "./venv/lib/python3.7/site-packages/mw4/loader.py", line 35, in <module>
    import PyQt5.QtCore
ImportError: dlopen(/Users/arie/Desktop/MAC_Scripts/venv/lib/python3.7/site-packages/PyQt5/QtCore.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Users/arie/Desktop/MAC_Scripts/venv/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/arie/Desktop/MAC_Scripts/venv/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proces voltooid]

**Comment by mworion** [comment]
Hi Arie,

oh that’s a good point I have to add to the documentation. Some of the frameworks need 10.12 or later. I can’t do anything about this.

I uploaded a new version, where dome slew should work. Still the Alpaca part for camera is not finished. The download time look not that good as you state. Hopefully they get it improved soon (at least I read about it)

If you have a chance to test the dome (therefore you only need to setup the dome driver), you open the hemisphere window and double click in the chart. This is a traget point for slewing. if you accept, MW4 will slew dome and mount there. If you enabled the geometry correcting in setting / dome tab, it should be ok. Any deviations, please let me know.

Michel

**Comment by ACMBakx** [comment]
Michel.

I shall test it a.s.a.p. in my dome and give you feedback.

Arie

**Comment by ACMBakx** [comment]
What I see is that MW4 now takes the easy route by slaving the dome-driver to the mount. You can tell by the RED letters "Scope Sync ON" in the dome driver window. This is what I do currently when using MW3. But I have to set some 30s settling time for the mount, to allow the dome to catch up at high azimuth. Low azimuth is not so much a problem.

[1st testrunMW4&scopedome.zip](https://github.com/mworion/MountWizzard4/files/4082965/1st.testrunMW4.scopedome.zip)

Like that the calculations are done by the dome driver. Which is not a problem of course all beit that you need to get confirmation from the dome that it really has finished its slew before taking an image again. You  notice that the dome sometimes slews in 2 steps. At high alt the dome is turning sometimes in the opposite direction to line up the slot. These slews take a long time. When the mount does a flip to cross the meridian, the dome tries to chase it and goes often in the wrong direction. All this can be prevented like SGP does it, First send the dome to the required azimuth and then send the mount to follow. This means that MW has to do the calculation. This is not happening at the moment,
In MW4 I still cannot alter the geometry settings. They are in blue but I cannot change them.

Hope this helps for a first step.

**Comment by mworion** [comment]
Hi Arie,

thanks for the video, it helped a lot. Please update to 0.146b5 (you have to enable beta releases in updater by checking the box). There should be no slaving. I just send two slew commands: one for the mount, one for the dome and MW will wait for both to end. MW4 will know in advance on which pier side the mount will be and calculates the correction for dome azimuth (hopefully correctly). How both devices reach their targeted position, MW4 does not care.

With 0.146b5 you should be also able to change the settings.

Michel

**Comment by ACMBakx** [comment]
Michel,

I run the update script and do not see a button for beta releases

Arie

**Comment by ACMBakx** [comment]
Found te button, but the INSTALL button remains black.
Actual version        0.145
Available version  [e connections a]  ??  I can not edit this line.
Should there be a path set to your repository?

**Comment by mworion** [comment]
Arie, there might be a misunderstanding. I meant the update inside MW4, attached a picture showing that:
![Bildschirmfoto 2020-01-21 um 21 54 29](https://user-images.githubusercontent.com/6632980/72842479-ba820480-3c98-11ea-93b7-88a7b2186e78.png)
Michel

**Comment by ACMBakx** [comment]
Hi,
I found this button. Available version is empty (fragment of text). Button INSTALL is dark.
I click the Beta button. Nothing happens. Still no version available.
Save&Quit MW.
Run update script.
Run run script.
Not updated.
Arie

**Comment by mworion** [comment]
OK strange. Last question: Is the checkbox online above the installer checked as well ? If no, please check it, than the button should be available. Otherwise please post a log file for further investigations.
Michel

**Comment by ACMBakx** [comment]
MW keeps on presenting surprises for me!
Found the button. Shows now version 0.146b to be available.
See attached.
Press button INSTALL. It lights up bright blue, but nothing happens still.
![MW4Updater](https://user-images.githubusercontent.com/59890758/72920222-28860480-3d49-11ea-8c4f-9af594397667.JPG)
[mw4-2020-01-22.log](https://github.com/mworion/MountWizzard4/files/4099005/mw4-2020-01-22.log)
Ran update.bat a few times while MW was running and not running.

Arie

**Comment by mworion** [comment]
Arie,
thanks for the log it makes things easier to debug. Has nothing to do with MW4. First for some reason the package manager found older version on the internet. I don't know why. I uploaded just for the sake of being consistent a new version 0.146 plain (which should be usable from the internal updater as well from the manual part (which btw does not install betas). I checked it and at least in my test environment i could make this update.
You could enable the message window (Button Message) on main window to follow the update process when doing it internally. There might be the rare situation that the first try end with an error, but you see that and just a second chance will do it.
It the log I see an error when accessing the work directory. That's not good. MW4 should install without admin rights and running as well without it. For some reason some directories are not accessible. Could you check permissions or did you do some part of the installation as admin ?
Michel

**Comment by ACMBakx** [comment]
Update was ok this time. I set the dome and mount dimensions as I usually do.
Watch the video. The slews of both mount and dome run nicely simultanios, but the calculations are slightly off. Here you have some homework to do, :-)
[bandicam 2020-01-23 14-54-34-488.zip](https://github.com/mworion/MountWizzard4/files/4103437/bandicam.2020-01-23.14-54-34-488.zip)
[Uploading mw4-2020-01-23.log…]()

**Comment by mworion** [comment]
Hi Arie,

thanks for testing and the feedback. the video helps. unfortunately the log file is not readable, but this does not matter,

Some things changed:

I definitly had a bug in calculation the GEM Offset as I store the specific mount geometry and just calculate the resulting value. My guess is, that you measured (as in other programs) the distance GEM point (cross point ra/dec) to center of OTA (0.26m). As I intended to make life easier, I though measuring just the OTA radius and getting the rest for free was not a good idea. My fault was to add the GM2000 distance GEM point to OTA plate, which lead to a bigger number in your case. This cause a major error.
-> I went back to the traditional GEM - OTA distance and dusted the image and texts as well. So it should be like all other programs now.

I wonder the 0.85m for you dome radius. I looked for small domes myself, never found it. Is this number right= ScopeDomes I’ve seen start from 1m radius. Why I am asking: With the big scope in a small dome, the correction reacts very sensitive on these numbers.

Another question: the offset north, east, vertical are measured from the center of your base pate of the mount where it is attached to the pier. 

When I reviewed many use cases I’ve seen, that some users have domes, where the radius changes over height. Do you have such a setup as well ?

In any case I made all the correction and fixes to v0.147.1. I added some logging for geometry a well. So whenever you have the time and mood to test again, please update, set logging to deep debug. Im case of problems, please post log and the video (which really helped a lot)

Michel

**Comment by ACMBakx** [comment]
Michel,

I think you nailed it!

Just ran a quick test. No logs no video's.
Impressive accuracy and behavior.
Also near and at the zenith.

Maybe it would be nice that as soon as the mount is un-parked the sync function would start.
It now starts at the first slew to a point.
Same as when you park the mount again. But maybe other users may not like this.

I tried to fool MW4 by manually positioning the dome in a wrong position. But he recovers very well from that.
I had to increase the dome radius to 1 m. Now the accuracy is even better.
SGP and the Scopedomedriver work best with 85cm. Don't ask me why.
I usually have to play a bit with the GEM numbers to get the best fit.

My dome is indeed tight. Only 2m in (outer)diameter.
With the Esprit100 it offers enough space, but with my 10"lacerta newton it is very tight.
The telescope is very close to the roof (and shutter motor).

I will produce a proper (deep)log and video at a later stage.
But for now I congratulate with the result.

**Comment by mworion** [comment]
Arie,

thanks for the quick testing. To explain: I don't have a sync function implemented. I only slew the dome when i issue a slew command when explicit slewing the mount or during modeling process. 

I would assume that you have a sync anyway when using SGPro. 

And to be honest: when I issue the slew commands, I know where the mount will go before really starting the slewing of mount and dome. If SGPro or another software will issue a mount slew command I cannot step in and sync.

The radius should be the real one. Hopefully just measuring the distances and putting them in should result automatically in the optimal sync. I've seen some different implementations of how to calculate the deviations, some of them might be simpler, but approximations. I did it the hard way using plain straight forward 3d transformations for each element. So from mathematics it should be ok. Intension was to be able to show up a virtual 3d model of the mount geometry like it is done in APCC.

As soon as we are sure that we fixed this problem, watched the video and checked the logs, I will close the issue.

Michel

**Comment by ACMBakx** [comment]
[MW4Test 2020-01-26 15-02-48-277.zip](https://github.com/mworion/MountWizzard4/files/4113588/MW4Test.2020-01-26.15-02-48-277.zip)
[MW4Test-2020-01-26.log](https://github.com/mworion/MountWizzard4/files/4113589/MW4Test-2020-01-26.log)

As promised the log and a video.
Dome setting: Radius set at 100cm and GEM hight at 12cm. Gem offset at 24cm The rest at zero.
These work best for my situation.
Tried to connect the camera as well. All green, but imaging hangs. Also with Simulator camera selected.
Hoped to run a small model. A failed image and failed solve would hopefully be ignored and skipped..
But MW stops after the 1st slew and waits indefenitely. Solve time-out was set at 30s.
I am sure you are working on this. Or I am overlooking a setting (as usual)

Arie

**Comment by mworion** [comment]
Hi Arie,

thanks for continuously test with patience :-)
The camera could not work at all. Still working on it, but will take some time as I have right now limited time due to my job. 
What I have seen in the video, at that i would like to understand, that I loose connection to dome (at least the button gets red from time to time. That's not good. I will do another release to get some more logging -> 0.147.3

Michel

**Comment by ACMBakx** [comment]
Yep, everytime when the dome finishes the slew, it disconnects. Then it quickly reconnects to ascom rest.

If you could find a way to connect the camera and manage to transfer the image data quickly, you have a winner. MW is becoming more versatile than just a model builder.

Would it be very difficult to put the dome slewing into mw3. That would satisfy a lot of ascom users. But I guess that is not a priority right now.
Kay has presented you with a lot of homework already.

Glad to help.
Arie

Verstuurd vanaf mijn iPad

**Comment by mworion** [comment]
OK, that's strange. As I only could check it with the dome simulator I don't see this behavior. What I did in 0.147.3 is to extend the timeout to 5 sec. But anyway, next time with the changed logging I should clear it up. As long as I don't have to first device on Alpaca up and running without problems, I will do the next one. If you don't mind post the log of the alpaca server as well.
Camera I should be able to manage, the speed is related to the actual transfer, but I've read that the would like to improve this situation, too.
Michel

**Comment by ACMBakx** [comment]
![MaximDL_Scopedome](https://user-images.githubusercontent.com/59890758/73197988-9740d480-4132-11ea-9083-3a2bd64516d5.JPG)
I think I solved the issue with the disconnecting dome.
I recalled a reference made to ACP. I tried MaximDL a while ago and had dome connecting issues. Then I found out that I needed to set a certain tick in the Scopedome driver. (see attached)
With that set, there was no issue wit the dome anymore.
Up till today I had this option unselected. MaximDL is removed from my computer.
I started a testrun with the option unchecked and as expected the dome disconnected everytime after a slew. I stopped, changed the setting in the Scopedomedriver and restarted the testrun. As by magic the problem had disappeared.
It appears there is more happening under the hood of the Scopedomedriver than just setting aasynchronous model. What it is exactly you will have to ask the developer Jacek Palek at info@scopedome.com
Arie

**Comment by mworion** [comment]
Close it right now. When having the camera working, starting a new issue, if upcoming or reopen if issues with the dome happen.

**Comment by mworion** [comment]
Arie,

v0.148.2 should be able to connect to the ascom camera and do a picture. It's not ready, but you could check download speed. Please also update to the latest ASCOM ALPACA server (which has also some updates).

Hope you're equipment is save because of the thunderstorm coming soon.

Michel
