### ISSUE TITLE
Unable to select model, load/save preferences, or quit

### ISSUE THREAD

**Issue by Raddock** [mworion/MountWizzard4#60]
Hi Michel, I was having trouble with the last working version connecting to INDI devices, so I updated to the latest version 0.150.29. I'm unable to load or save settings in the main window. I'm also unable to generate any model points, load an existing model, etc. No button presses seem to work on these panels. But I can change devices in device settings. The Pegasus UPBV2 is updated to firmware 1.5, but seems to report lots of debug errors to the messages window. See attached log.  I cannot save or quit, so I have to quit Pyton from the apple menu. The interface (only parts of it) seem to not be accepting mouse clicks. I did mange to save a working copy on my laptop, but thought you should know there are issues with this version. I have even reinstalled it from scratch in a new directory, with the same issues appearing. Thanks for your time.

[mw4-2020-08-05.log](https://github.com/mworion/MountWizzard4/files/5025943/mw4-2020-08-05.log)

**Comment by mworion** [comment]
Hi Andrew,

the extensive logs of UPBv2 are normal and don't show any problematic topics. It's massive, because you set logging in EKOS / KStars to debug and in MW4 you enables show INDI messages. You could revert to any old version by entering the version number in the update field.

The behavior is related to Qt5 framework update 5.15 which I tested in my setup and works with windows, but has troubles with some OS X installations.

Michel

PS: uploaded 0.151.0 which should solve the issue

**Comment by Raddock** [comment]
Hi Michel, This brought back all buttons and model loading. However the model making process stops always at the last star after solving, then does not upload the model into the mount. This is the same for 3 star models, or 50 star models. 

I must have turned off logging in order to stop the UPB because these logs I attached don't show the modeling process. But there is one error or two in them which might be related or not.

[mw4-2020-08-08.log](https://github.com/mworion/MountWizzard4/files/5045227/mw4-2020-08-08.log)

[mw4-2020-08-07.log](https://github.com/mworion/MountWizzard4/files/5045220/mw4-2020-08-07.log)

**Comment by mworion** [comment]
Hi Andrew,

if you want to stop logging UPB (which is done by EKOS), you have to disable debug in EKOS. If you want to reduce log load in MW4 from this source, please disable message out in the Indi UPB driver settings.

I don't see any issue in the log, but not much in. Last night I did 3 times modeling with the same software on my Mac and saw no issues. I used ASTAP for solving.

Michel

**Comment by Raddock** [comment]
Worked perfect tonight with V 0.151.2. Thanks!
