### ISSUE TITLE
Satellite Window: Many errors displayed in log window

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#62]
Hi Michel,

I installed the latest version and I get a lot messages in log window while refreshing the satellite tracks. 

BTW: could not update from within application. I had to use update batch. 

Cheers
Rüdiger

[mw4-2020-08-09.log](https://github.com/mworion/MountWizzard4/files/5048270/mw4-2020-08-09.log)

![2020-08-09_21h24_01](https://user-images.githubusercontent.com/65772654/89740214-166e7800-da87-11ea-946d-f62842aa6849.png)

**Comment by mworion** [comment]
Rüdiger,

0.150.2 should fix this

**Comment by Ruediger3** [comment]
Hi Michel,
fix confirmed. Thx!
Cheers
Rüdiger
