### ISSUE TITLE
Flip Flat

### ISSUE THREAD

**Issue by mhambuch** [mworion/MountWizzard4#65]
Hello Michael, i just invested in a Flip Flat device (i guess there is only one from Alnitak) and saw that there are some control buttons. Currently only indi is proposed, i use ascom via alpaca. Maybe you could add this communication channel in a future release, would be nice if i could at least open / close the cover from mw4. Thanks for considering.  
Marc

**Comment by mhambuch** [comment]
No ascom driver for this device so the request does not make sense. I will try to use indi.

**Comment by mhambuch** [comment]
Reopened the issue just to ask if there is an other way to control the flip flat device as indi is not supporting w10. ?

**Comment by mworion** [comment]
Marc,

with ascom 6.5 there is a cover device available. If you have a ascom driver (which should be the case) I will integrate this device. 

Michel

**Comment by mhambuch** [comment]
Hi  Michael, thanks a lo. Yes i have the new ascom 6.5 installed as well as alpaca.
Can you guide me to access this ascom cover driver?
Marc

**Comment by mworion** [comment]
Marc:

Got it implemented in MW4. Only point so far: I could test it with the ASCOM simulator, but as I also have an Alnitak FlipFlat I see that there is no compliant ASCOM6.5 cover driver available from OPTEC. We both should address this.

Michel

**Comment by mhambuch** [comment]
Thanks a lot Michel. I guess the only way is to contact Optect, i will contact them unless you you want to address it differently.
Nice WE
-------- Message d'origine --------De : Michael <notifications@github.com> Date : 06/09/2020  13:18  (GMT+01:00) À : mworion/MountWizzard4 <MountWizzard4@noreply.github.com> Cc : mhambuch <mhambuch@laposte.net>, State change <state_change@noreply.github.com> Objet : Re: [mworion/MountWizzard4] Flip Flat (#65) 
Marc:
Got it implemented in MW4. Only point so far: I could test it with the ASCOM simulator, but as I also have an Alnitak FlipFlat I see that there is no compliant ASCOM6.5 cover driver available from OPTEC. We both should address this.
Michel

**Comment by mworion** [comment]
I wrote them as customer an email. Please do so as well.

Von meinem iPad gesendet

**Comment by mhambuch** [comment]
just did it. thx

-------- Message d'origine --------De : Michael <notifications@github.com> Date : 06/09/2020  14:42  (GMT+01:00) À : mworion/MountWizzard4 <MountWizzard4@noreply.github.com> Cc : mhambuch <mhambuch@laposte.net>, State change <state_change@noreply.github.com> Objet : Re: [mworion/MountWizzard4] Flip Flat (#65) 

I wrote them as customer an email. Please do so as well.



Von meinem iPad gesendet

**Comment by mworion** [comment]
We'll see. I close this point an we could reopen that once we could test.
Michel

**Comment by mworion** [comment]
Hi Marc,

That’s the response I get:

Hello Michael,
We have an ASCOM and Alpaca ICovCal driver in progress. I don't have a solid ETA other than fairly soon. Ongoing effects from Covid lockdowns have caused major issues with our planned release schedule. In the meantime is there a reason that the current integrations no longer work for you?
Regards,
Daniel Van Noord
Optec, Inc.

BTW. On SGPro forum as they also updated to ASCOM6.5 the were loosing FlipFlat functions, too and need a new driver. This should make things run better.

**Comment by mhambuch** [comment]
Hi Michel,
I got this reply from Jeff. Very responsive, sounds good.Marc
-------- Message d'origine --------De : Jeff Dickerman <jeff@optecinc.com> Date : 06/09/2020  19:32  (GMT+01:00) À : mhambuch <mhambuch@laposte.net> Objet : RE: Flip Flat Ascom 6.5 

Hi Marc,
 
Thanks for your note.  Yes, we are working on a major update for the Alnitak drivers to include ASCOM and Alpaca for cross-platform compatibility.
 
Hope to have something in early October.
 
                Thanks again,
                
                Jeff.
 
 









Jeff Dickerman
–
President, Sales & Support
199 Smith Street - Lowell, Michigan  49331 - U.S.A.
Toll-free:  888-488-0381 - Office: 616-897-9351 - Fax: 616-897-8229




 
 
 
 


From: mhambuch <mhambuch@laposte.net> 
Sent: Sunday, September 6, 2020 8:48 AM
To: Jeff Dickerman <jeff@optecinc.com>
Subject: Flip Flat Ascom 6.5


 
Hi Jeff, 

 


I just bought a flip flat device which i find very good. Now as many amateurs, I would like to automate my imaging session. This includes the creation of flats under the same condition as the imaging session which makes the creation of
 flats after each session interresting. I would like to ask you if you could envisage to provide an ascom 6.5 driver for your device?. This would be very helpfull for many people I guess. I hope you find this question worth a thought. 


 


Greathings from France


 


Marc

**Comment by mworion** [comment]
Hi Marc,

I got a beta version of the ASCOM6.5 driver. You could use the FlipFlat with that, but is still buggy.

Michel

**Comment by mhambuch** [comment]
Hi Michael,Great! Thanks a lot i will test it asap. You have the FlitFlat device as well right? My entire hardware setup is currently dismantled as i am setting up a fixed observatory.  Keep you posted. Nice WE
-------- Message d'origine --------De : Michael <notifications@github.com> Date : 29/11/2020  13:32  (GMT+01:00) À : mworion/MountWizzard4 <MountWizzard4@noreply.github.com> Cc : mhambuch <mhambuch@laposte.net>, State change <state_change@noreply.github.com> Objet : Re: [mworion/MountWizzard4] Flip Flat (#65) 
Hi Marc,
I got a beta version of the ASCOM6.5 driver. You could use the FlipFlat with that, but is still buggy.
Michel
