### ISSUE TITLE
Camera not integrating when dome is active

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#66]
Hi Michel,

just tried to run a model build, but found out that when the dome is connected the camera won't integrate and MW4 stalls. As soon as I disable the dome the integration works and MW4 continues.

A log file is attached showing that MW4 has an issue with the shutter status. My dome is only automated in slewing, the shutter goes manual and has no switches and is thus not interfaced.

Nicolàs

[mw4-2020-09-12.zip](https://github.com/mworion/MountWizzard4/files/5213199/mw4-2020-09-12.zip)

**Comment by mworion** [comment]
Nicolas,

reason for that was adding shutter function to dome. Unfortunately your dome driver does not support shutter status. Second problem was that I cannot review in advance if a driver supports a property. So this raised exceptions which did MW4 stop working. I put a workaround for catching this exception and disabling shutterstaus.

Next beta should work.

Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

My driver is LesveDomeNet and should support shutter status. But as I have not yet implemented this in the dome there is no electronics for it attached to the interface board. I have posted a question regarding this on the LesveDomeNet group to see if I need to add some wiring to get this working. For imaging I use SGP and that has no issue with the dome as it is.

I will leave this issue open for the moment until I have response from the LesveDomeNet group.

Thanks for creating a workaround in the next beta, will test it as soon as it becomes available.

Nicolàs

**Comment by InFINNity-Deck** [comment]
Just had response from the LesveDomeNet programmer. Apparently the CanSetShutter should be read first before querying the shutter status:

> The application program is normally aware of this Capability by reading a property CanSetShutter and shouldn't read Shutter status
> If it does, LesveDomeNet will raise an error when trying to read Shutter status.

Nicolàs

**Comment by mworion** [comment]
Nicolas,

OK, good hint. I will add the CanSetShutter property reading and we could check if that work. But anyway the workaround should do the trick as well.

Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

just started MW4 0.152.0b6 and all goes fine, we can close this issue.
Once again thanks!

Nicolàs
