### ISSUE TITLE
Beta versions won't install

### ISSUE THREAD

**Issue by InFINNity-Deck** [mworion/MountWizzard4#67]
Hi Michel,

if I try to install a beta version through the MW4 GUI it does not pass the install. Trying to run MW4 after this results in nothing. I have to either re-install MW4 or to run the updater batch file to get MW4 back alive again.

Nicolàs

**Comment by mworion** [comment]
Hi Nicolas,
there are some situations where the internal update has to update libraries which are in use during installation. On windows this might be much more (cached ?) than on MAC. The normal way is to use the batch updater to clean up. If that works, that would be the correct way. Reinstall should not be used if not explicitly necessary.
Could you feedback if the batch updater worked?

The batch updater is not intended to update to betas (as it is for regular users). If you want to manual install a dedicated version, please use from the actual worker the terminal:

venv/Scripts/activate
pip install mountwizzard4==<exact version number>
whereas the next beta is: 0.152.0b4

Michel

**Comment by InFINNity-Deck** [comment]
Hi Michel,

just tried that, so first double clicked the venv/Scripts/activate.bat file then gave the command "pip install mountwizzard4==0.152.0b3" as version b4 was not yet available. This did, however, not work, probably because I opened a DOS-terminal in the wrong location. So opened a new CMD box and gave the following commands:

>cd venv/Scripts
>activate
>pip install mountwizzard4==0.152.0b3

And that did work! :-)

Looking forward to b4!

thanks!
Nicolàs
