### ISSUE TITLE
Dome doesn't wait for slew during model build

### ISSUE THREAD

**Issue by ghilios** [mworion/MountWizzard4#68]
Waiting for dome slew during model build doesn't quite work unless the target azimuth is strictly less than the current azimuth.

The bug is here: https://github.com/mworion/MountWizzard4/blob/master/mw4/logic/dome/domeAscom.py#L97

Basically, "(azimuth - self.targetAzimuth) < 0.1" is not adequate for testing for slew completion. Using abs is quite a bit better, but also incomplete since 359.9 and 0 will be missed.

A correct fix here would look something like the below, which will always return a value between 0 and 180 so you can compare. Another issue to be aware of here is that not all domes can slew to such precision, so the tolerance should be configurable. For example, Nexdomes up until the very latest firmware (from a few months ago), could only slew to integer precision, so "< 0.1" would be a very long wait

```
def mod_distance(x, y, m):
   diff = abs(x - y)
   diff = abs(diff % m)
   return min(diff, abs(diff - m))

hasReachedTarget = mod_distance(azimuth, self.targetAzimuth, 360) < 0.1

**Comment by mworion** [comment]
Hi,
thanks for the hint. Put your solution in (in alpaca as well).
0.152.0b5 is uploaded and have this fixed.
Michel

**Comment by ghilios** [comment]
Awesome thanks! I'll verify with my next clear night
