### ISSUE TITLE
170.3: Tooltips wrong in "Manage Models: Model Positions"

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#71]
Hi Michel,
noticed the tool tips are dummies in mentioned window. Please see screenshot.
Thanks!
![2020-10-15_08h26_40](https://user-images.githubusercontent.com/65772654/96085100-94ecf900-0ec0-11eb-8d60-968ce4e0a64c.png)

**Comment by mworion** [comment]
will be in 0.170.4
