### ISSUE TITLE
Hemisphere Window: Polar Diagram

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#72]
Hi Michel,

a short question to polar diagram in "Hemisphere Window";
This function is disabled now for a long time, since it is not implemented. Any chance to get it done in near future? If not, I would suggest to remove it. 
Personally I think it would be great to have a spherical view to toggle with plane view currently implemented, since the distribution looks completely different and sometimes you got mislead by the plane projection.

Thank you in advance!

**Comment by mworion** [comment]
Hi Rüdiger,

I did some early preparations for bringing this back. I made a beta for that, revising all hemisphere handling. Still the CPU load might increase. Could you have a look to the usability and the speed (load) in version 0.170.5b1

Michel

**Comment by Ruediger3** [comment]
Hi Michel.
thanks for the Beta. I have installed it. For me there is no difference in speed to before, but I have a very powerful workstation.

2 Things I have noticed:

1. Last point in horizon mask drops to zero, though you have made some code changes for that. My be it needs review. After the last point the mask drops to 0 degree altitude and does not close the 360 degree. Please see screenshot at the right.

2. What would be a could idea when auto creating the point grid to stay away from the horizon line a few degree. There should be a kind of safety distance, because if these limits are heated up building roofs, it might cause seeing effects (what it was in my case). May be any option "Distance to horizontal line in degree" would be a good idea?

Thank you very much for all your efforts!

Cheers
Rüdiger

![2020-10-19_08h35_23](https://user-images.githubusercontent.com/65772654/96410321-02fa2e80-11e7-11eb-8efb-51692f485172.png)

**Comment by mworion** [comment]
Hi Rüdiger,
1. is already addressed. Might be the case if you have an file with that point in it (I did it in the past for getting the polygon). If you clear the horizon and start with a single point in the middle, you could see that.
2. good idea. still so the generation of the horizon mask is the critical point. I thought about having some automatics there as well, but this might take some time.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

to 1: To be honest, I do not want to delete the Horizon mask. This was exactly created with the mount and cross hair eye piece. It looks simple and humble. but it is very precise. Maybe I can edit the file itself. This is easier.
[Horizon.txt](https://github.com/mworion/MountWizzard4/files/5400869/Horizon.txt)

to 2: great. Looking forward to 👍 

Cheers
Ruediger

**Comment by mworion** [comment]
Had a look to the file. Everything is OK. I just draw the pink line to far. This is changed now. There were no points.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

thanks for checking. 👍

**Comment by mworion** [comment]
0.170.5 in online which should correct the graphics (and remove unnecessary logging in some areas)

**Comment by Ruediger3** [comment]
Hi Michel,

installed and drawing is now OK. Thanks!
We should keep this issue open, until polar diagram is implemented. 

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,

should be OK. I will not implement all visuals from Alt/Az diagram to polar.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

looks really good. It helps a lot to get a realistic impression of the points' distribution at the sky. Great!
Thanks a lot! 

Issue closed :)

**Comment by Ruediger3** [comment]
PS: It has just helped me to identify 3 "blind" spots in the model :) great feature.
