### ISSUE TITLE
Can't run a sequence?

### ISSUE THREAD

**Issue by mads0100** [mworion/MountWizzard4#73]
Attached as requested.  I can connect my gear, take an individual frame and platesolve it, but when I hit 'run' for model building it doesn't seem to do anything.  There is an error in the log that I don't understand.  Hopefully it helps.

Chris

Log attached. 
[mw4-2020-10-10.log](https://github.com/mworion/MountWizzard4/files/5398373/mw4-2020-10-10.log)

**Comment by mworion** [comment]
Hi Chris,

thanks for the log. Please update to 0.170.5, which is online now. One ASCOM error has now a workaround. After the last start of MW, the ASCOM driver acted correctly, but there was no try after.

Michel

**Comment by mads0100** [comment]
Wilco.  Thank you!

**Comment by mworion** [comment]
Closing it as long as there are no new feedback. Hope it's fixed now.
Michel
