### ISSUE TITLE
Feature Request: Safty distance to horizon limits

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#74]
Hi Michel,
as discussed in the other issue, I carve out the feature request for a safety distance to horizontal limits when auto generating a point cloud. I have noticed that the points getting very close to it.
Please find attached an example.
Feature request: To have an option to set a minimum distance in degree to the horizon limits. 

Thank you!

Cheers
Rüdiger

![2020-10-25_18h36_52](https://user-images.githubusercontent.com/65772654/97114487-0f075400-16f1-11eb-9249-65f7bd9445e4.png)

![2020-10-25_18h40_22](https://user-images.githubusercontent.com/65772654/97114600-c734fc80-16f1-11eb-856e-faee5d69b7bf.png)

**Comment by mworion** [comment]
Hi Rüdiger,

with the intermediate version 0.190.2 this feature is in. Please feed back.

Michel

**Comment by Ruediger3** [comment]
Hello Michel,
this version is not generating any points at all. Even the points from my point spread before are vanished. Regardless whether I activate safety margin or not. Screenshot and log attached.

Cheers
Rüdiger

[mw4-2020-11-01.log](https://github.com/mworion/MountWizzard4/files/5471614/mw4-2020-11-01.log)

![2020-11-01_20h40_42](https://user-images.githubusercontent.com/65772654/97812598-98cf9800-1c82-11eb-8318-5d37804f4a22.png)

**Comment by mworion** [comment]
Rüdiger,

for some reasons it's related to you last checkbox meridian limits. The logic was wrong. fixed in 0.190.3

Michel

**Comment by Ruediger3** [comment]
Udated to 1.90.3 and still not working. Same - empty :(

**Comment by mworion** [comment]
Don't see this in my environment. Have a look to it.

**Comment by Ruediger3** [comment]
Thx!

**Comment by mworion** [comment]
Rüdiger,
0.190.4 works in my environment.

![Bildschirmfoto 2020-11-02 um 20 57 03](https://user-images.githubusercontent.com/6632980/97913002-fb419a80-1d4d-11eb-99b7-8c48647ea6c3.png)

Hopefully in yours as well. Michel
Hop

**Comment by Ruediger3** [comment]
Hi Michel,

1.190.4 does not start at all. Splash screen shows and gets closed immediately without any screen.
Fell back to 1.190.0 which works. Please find attached logfile.

Thank you
Cheers Rüdiger


[mw4-2020-11-02.log](https://github.com/mworion/MountWizzard4/files/5477740/mw4-2020-11-02.log)

**Comment by Ruediger3** [comment]
Tried to generate a new log file by updating from 190.0 -> 190.4. But no log was created. Splash was closed without any log.

**Comment by mworion** [comment]
Rüdiger, 
you did not tell that updates .2, .3 did not work.
Out of the log file: 
1. Your first attempt to install via internal updater was really quick after my upload. The package was not available on the server.
2. With the second one you already had some tasks running -> need for update manually. 
3. But then I see 0.190.3 starting, which is strange if you updated manually.

I did an upgrade on win10 from 0.190.3 to 0.190.4 and needed step 2 as well. But 0.190.4 is running on this machine well.

Ideally I would make a clean install in a new work dir and copy you configuration into it. As I don't take care about securely handling configuration during up and downgrade as long as we have no first official release, this might lead to some hickups.
Michel

**Comment by mworion** [comment]
Important: please delete the "config.cfg" and "profile" file as there are the problems with compatibility.

**Comment by Ruediger3** [comment]
Hi Michel,

.2 I told (2nd post)-> did not work
.4 tried as advised -> did not start
.3 tried while downgrading -> did start, but points were not created
.4 went back to last well known version 190.0

I will stay with 190.0 since I do not want to reinstall or delete my configs. 

Cheers
Rüdiger

**Comment by mworion** [comment]
Ok understood.
Michel

**Comment by mworion** [comment]
sorry wrong button

**Comment by Ruediger3** [comment]
Updated to 190.4 and renamed config folder.  Tried to start MW. But again only splash flickering and closing. 
So not related to config.

**Comment by Ruediger3** [comment]
A complete fresh install of 190.4 does not start neither.

**Comment by mworion** [comment]
Rüdiger,
many many thanks for trying again. Your observations are not reproducible. A fresh install with the script should work. I tried it on different systems, any thoughts what might gone wrong? I did a win10 install with python 3.8.6 64bit like yours.
Please let me know how I could help.
Tonight I release 0.191.0, which sorts (hopefully) the dome and all other open part out.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
sorry for yesterday, but I was very frustrated :(
Re-Installed everything from the scratch. Downloaded Zip and started "MW4_install.bat".
Then I tried to run MW, but same result. The "run.log" is empty. "Install.log" find attached below. 
190.0 - .3 run fine except the reported issues.

Cheers
Rüdiger

[install.log](https://github.com/mworion/MountWizzard4/files/5482031/install.log)

**Comment by Ruediger3** [comment]
Here are some hints:
![2020-11-03_16h07_15](https://user-images.githubusercontent.com/65772654/98003161-b1f55780-1dee-11eb-9995-acc7a0ee2da3.png)

**Comment by Ruediger3** [comment]
The folder "numpy" is missing too.

**Comment by mworion** [comment]
The runtime error seem to be related to a the bumpy library, which has a problem with the used version 1.19.4.
I will revert this back to 1.19.3. Still we could give this a try, but the 1.19.4 library works on my windows10 without problems.
So MW4 0.191.0 (don't get mixed up with bumpy numbers) will support the older one. I countercheck this right now.

**Comment by mworion** [comment]
Rüdiger,

0.191.0 is uploaded and installs und runs hopefully correct now.

Michel

**Comment by Ruediger3** [comment]
Made a fresh install and it it works. But if I try to load any of many profiles, it is not showing any points any more. When removing config folder and start again, it works.
It looks like the profiles are working up to 190.3 cause trouble with .4 onward.

**Comment by Ruediger3** [comment]
I even cannot load the horizon mask:
[2020-11-03 19:34:35.486][I][     mainApp.py][ 458] Message window: [Horizon mask [DCRP] cannot no be loaded]

**Comment by mworion** [comment]
Hi Rüdiger,
could you post a "config" file, which does not work, the "profile" file and a related horizon mask. I would like to understand what's happening there. Config structure is not changed at all.
You definitely have a beer at my expense !
Michel

**Comment by Ruediger3** [comment]
Please find the config folder attached. Just downgraded to 190.0 and the configs work again. It is definitely related to the version.

[config.zip](https://github.com/mworion/MountWizzard4/files/5483763/config.zip)

**Comment by mworion** [comment]
Rüdiger,
for not showing the point -> bug if no meridian limits are set - this is the case only if no mount is connected -> fixed 0.191.1
Horizon file and Build file could be loaded directly...
Michel

**Comment by Ruediger3** [comment]
Bingo! It works! Great! Time for a second one :P

**Comment by mworion** [comment]
had a beer, too.

**Comment by Ruediger3** [comment]
Yea, this was a hard earned beer :D
