### ISSUE TITLE
Wrong tooltips in Tools window

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#77]
Hi Michel,
you may have a look on the tool tips:

![2020-11-03_22h05_37](https://user-images.githubusercontent.com/65772654/98040700-fb5e9a80-1e20-11eb-8b71-f6c793487e34.png)

**Comment by mworion** [comment]
Rüdiger,

will be in 0.200.0 where the asteroid upload functionality (for windows only, because of the need of using the 10micron updater).

Michel

**Comment by Ruediger3** [comment]
Thanks! Fixed and closed. 👍
