### ISSUE TITLE
0.200.0 Manage Model -> Model Positions: Strange Grafic

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#78]
Hello Michel,
when multiple clicking in "Model Positions" on "error values" I get every click one graphic more.
Probably I do something wrong, but it is a little bit wired.

Cheers
Rüdiger

![2020-11-05_18h52_38](https://user-images.githubusercontent.com/65772654/98285304-a8acec00-1fa2-11eb-96c8-a3b23d07827b.png)

**Comment by mworion** [comment]
Never seen this. Could you explain, how you made it ?
Michel

**Comment by Ruediger3** [comment]
Just double clicking the Field "error values". Each DC produces a new pair of bar graphs.

![2020-11-06_11h06_09](https://user-images.githubusercontent.com/65772654/98355551-92467500-2022-11eb-8a62-e9489c80f8be.png)

Also DC the bar graph it self throws errors:
![2020-11-06_11h05_40](https://user-images.githubusercontent.com/65772654/98355640-b43ff780-2022-11eb-9076-0664ade99a2c.png)

And more errors:

![2020-11-06_11h13_34](https://user-images.githubusercontent.com/65772654/98355660-befa8c80-2022-11eb-8428-64bc43b1784a.png)

**Comment by Ruediger3** [comment]
Fix confirmed in 210.0
Thank you!
