### ISSUE TITLE
Feature Request: Support for ASCOM Observation Conditions Hub

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#79]
Hello Michel,

since most of the environment sensors use COM interfaces they can only used by one application at a time.
There fore I can ether connect MW or Imaging SW to it - but never at the same time. 
Since I use in NINA ASCOM observation condition hub to gather all information from different sources (E.g. MGPBox, SQM, UPP and online weather) it would be great, if I could connect this hub from MW too. So all resources could be used at the same time without any HW conflict.
Thanks

Cheers
Rüdiger

![NINA](https://user-images.githubusercontent.com/65772654/98286125-cd559380-1fa3-11eb-8c18-7bd936195fa4.png)

![ASCOM_OCH](https://user-images.githubusercontent.com/65772654/98286442-4fde5300-1fa4-11eb-8cf1-3900cce56593.png)

**Comment by mworion** [comment]
Hi Rüdiger,
this is already done. You could select this hub for the use ins skymeter and sensor at the same time. There is no dedicated device for it, but if you set a device using this hub, the device driver grabs the necessary data from the hub.
Michel

![Bildschirmfoto 2020-11-06 um 16 35 51](https://user-images.githubusercontent.com/6632980/98384504-2417a780-204e-11eb-98ee-a725ebf8939a.png)

**Comment by Ruediger3** [comment]
Hi Michel,
I cannot select the ASCOM Hub under "Sensor". Only the MGPBox is shown. Probably because both both driver register as environment. Please see screenshot. Thx!

![2020-11-06_19h19_53](https://user-images.githubusercontent.com/65772654/98401007-479a1c80-2065-11eb-90f1-4c76a1861819.png)

**Comment by Ruediger3** [comment]
Got it. Classic case of PICNIC. Problem In Chair, Not In Computer :)
But it does not take all values: E.g. wind, rain, and more are not taken from HUB. But this is minor.

Thanks!

**Comment by mworion** [comment]
Rüdiger,
the following steps:
![Bildschirmfoto 2020-11-06 um 19 25 22](https://user-images.githubusercontent.com/6632980/98401391-e4f55080-2065-11eb-9543-1cdb83ff776e.png)
The hub should be available for selection.
Michel

**Comment by mworion** [comment]
Ok, good you got it.
Yes, the sensor is limited right now for the MBOX part, but as you tell it would make sense to tale the others as well if available. Think about it.

**Comment by mworion** [comment]
should show now all field for sensor in 0.211.0

**Comment by Ruediger3** [comment]
Hi Michel,

just checked with simulator and it works fine.
I will check with real sensor as soon as possible, since the gear is in the house due to bad weather. If there is any problem I will reopen the issue, though I think it works as expected. 

Thank you very much for your great support!

CS
Rüdiger
