### ISSUE TITLE
Some minor issues in MountWizzard4 GUI

### ISSUE THREAD

**Issue by kaythriemer** [mworion/MountWizzard4#8]
Hi Michel,

first of all a big compliment for MountWizzard4.
During todays test I found some minor issues in the GUI.

* If I go to "Model Points" and open the "Hemisphere" Window I have the issue, that every mouse click on a up or down arrow (e.g. Points) results in two steps.
E.g. I want to increase the golden spiral from 50 to 75 point and I press once on the up arrow, it will be decreased  to 75 and than to 100. 
If the Hemisphere Window is closed. The behaviour is as expected.

* The Polar Diagram in Hemisphere Window is not shown if I activate this option.

* Sometimes an empty tooltip box appears, e.g. if you move the mouse over the "Mount", "Environ",... Tabs or every "white" text in the Mount area, e.g. "HA", "RA",... "Local Sidereal Time",...

* there are also some wrong "mouse over" message texts. E.g. if you move your mouse to "WakeOnLan" to "ON"/"OFF" the wrong text is shown. There are many others, if you want I can summarize the findings.

* Mount-> Parking/Emergency stop -> "Mount Park" Button : wrong text, I think, it should be "Switches the parking state on and off..."

Thank you.
Take care.

Kay

**Comment by mworion** [comment]
Hi Kay,

thanks for the kind feedback. To your issues:

> If I go to "Model Points" and open the "Hemisphere" Window I have the issue, that every mouse click on a up or down arrow (e.g. Points) results in two steps.
E.g. I want to increase the golden spiral from 50 to 75 point and I press once on the up arrow, it will be decreased to 75 and than to 100.
If the Hemisphere Window is closed. The behaviour is as expected.

Never saw that, because I'm on MAC. There it's not the case, but I could reproduce it like you explained on Ubuntu. Have to check why.

> The Polar Diagram in Hemisphere Window is not shown if I activate this option.

True. I removed it temporarily. I did some performance optimization for drawing (cpu usage went down from 70% to 8%), but it is complicated tweaking of matplotlib. Having two diagrams with moving points at the same time caused to much troubles. I'll recap that later on, but i should remove the entry.

> Sometimes an empty tooltip box appears, e.g. if you move the mouse over the "Mount", "Environ",... Tabs or every "white" text in the Mount area, e.g. "HA", "RA",... "Local Sidereal Time",...

Issue of the framework. You have the mouse over a widget (which is the case for showing up a tooltip), but it is empty. I have to find out how I could address this.

> there are also some wrong "mouse over" message texts. E.g. if you move your mouse to "WakeOnLan" to "ON"/"OFF" the wrong text is shown. There are many others, if you want I can summarize the findings.

That would be great to let me know. It's always a bunch of work and I miss often changes on this side.

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
here my summary.

Following tooltips are probably not correct.

* Mount 
 -> "Parking/Emergency stop" 
  --> "Mount Park" (Switches the parking state on and **off** ...)

 -> "Status and settings from mount computer"
 --> "DeltaT expires" typo in text
 --> "WakeOnLan" wrong text
 --> "Connection is" wrong text
 
* Environ 
 -> Moon phase 
  --> xx % -> typo in text

* Model Points 
-> Generate model points as grid 
 --> AltMin wrong text
 --> AltMax wrong text

-> Generate model points equally distributed 
 --> Points wrong text
 --> green tick is missing on "Generate Golden Spiral"

-> Generate model points from tracks
 --> TimeShift wrong text

-> Auto sort points
 --> No Sorting wrong text

* Model Build
-> Alignment info from mount computer
 --> Stars  wrong text
 --> PosAngle  wrong text
 --> Altitude Pointing  wrong text
 --> Azimuth Pointing wrong text


* Manage Model
 -> Optimize actual model
 --> Show error values in polar plot: wrong text


* Satellite
 -> Satellite data file
  --> "drop down list" typo  in text  (shoufl --> should)

 -> TLE satellite data calculation
  --> unfortunately all fields containing the same text

* Sett./Conf.
 -> Imaging
 --> Actual parameters 
  ---> Resolution shows "Configuration of settings"
  ---> FOV shows "Configuration of settings"
  
-> Mount /WeatherAPI
 ---> OpenWeatherMap API Key shows "Configuration of settings"
 ---> Computer on rig -> MAC Address shows "Configuration of settings"

-> Dome / Cover
 --> all values showing "Configuration of settings"

-> ParkPositions
  ---> all values showing default texts

-> Misc/Audio
--> Internet online connection
--->  online and update data files if necessary : wrong text

--> Update
---> Actual Version showing "Configuration of settings"
---> Available Version showing "Configuration of settings"
---> Release/Beta/Alpha  wrong text

--> Firmware data
  ---> all values showing "Configuration of settings"

--> Logging 
---> Info/Debug/Deep Debug  wrong text

--> Play audio signals
 ---> Modeling finished wrong text
 ---> Image save wrong text 
 ---> image solved wrong text

I understand, that keeping the tooltips up to date is a huge work and it is not funny.

Kay

**Comment by mworion** [comment]
Kay,

no worries. If you fall over some more, please report back. Beside you first topic (double steps when increasing the number of points), other parts should be fixed in 0.147.2

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
thanks for the very fast deployment of version 0.147.2 .
I have already updated and will collect other findings.

Kay

One thing I found this morning: the tooltip for the Keypad has the same text as Satellite.
It is very pleasant, that the empty tooltip boxes are not occurring anymore.

**Comment by mworion** [comment]
Kay,

> If I go to "Model Points" and open the "Hemisphere" Window I have the issue, that every mouse click on a up or down arrow (e.g. Points) results in two steps.
E.g. I want to increase the golden spiral from 50 to 75 point and I press once on the up arrow, it will be decreased to 75 and than to 100.
If the Hemisphere Window is closed. The behaviour is as expected.

with 0.147.6 the issue about double up when pressing should be solved. I don't see it anymore on ubuntu. If you could verify, please close the issue and open new ones if necessary.
Michel

**Comment by kaythriemer** [comment]
Hi Michel,
now it works with version 0.147.6 also in Ubuntu, one klick on an up/down arrow decreases/increases the value one step.

Thank you for your support.
Kay
