### ISSUE TITLE
Push satellites' data

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#81]
Hi Michel,

is it planned to push also the satellite data to the mount analog to asteroids and comets?

Cheers
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
different way: you could select and program directly a satellite (including viewing the path and starting track). So why downloading the database as MW4 could handle this remotely ?
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
yes, but when doing simple visual observing with some guests I use the hand pad only to operate the mount. No PC at all. It is even not wired. It would be nice if we could keep our mounts updated with MW as central tool. 

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
implemented, see 0.220.0

**Comment by Ruediger3** [comment]
Hi Michel,

looks also very good and I will test it ASAP, but depends on the weather. Thank you very much!

Cheers
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,

just tested and it works, but the log window shows some warnings. 
This is also coming with the other programming actions. 

Cheers
Rüdiger


![2020-11-20_15h30_45](https://user-images.githubusercontent.com/65772654/99811548-9c4d9500-2b45-11eb-903f-64fad1a570f9.png)

**Comment by mworion** [comment]
Hi Rüdiger,
OK we are back to the problem of windows, which does a difference between 32 bit and 64 bit. Windows on the drivers side cannot mix 32 and 64 and this will stay in future. I did not check the updater base. But as you discovered it is 32 bit. So my recommendation (and I have to state this much more) to stay on windows on a 32 bit python version (also because not all ASCOM drivers support 64bit). I will check this this weekend and report back.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
j.f.y.i.: all my applications (e.g. NINA) and as consequence all my ASCOM drivers are 64BIt or at least 32/64 Bit (e.g. ZWO) compatible,

Thanks for looking into it.

Cheers
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,
after some hours I seem to found a solution for that. I build a beta for you. This should work on 64bit python with the 32 bit updater. It works for upload automation a little bit slower, but it should work.
Michel

**Comment by Ruediger3** [comment]
Hello Michel,
thanks a lot. Not sure you already built the Beta, but currently I do not see it. 

Cheers
Rüdiger

![2020-11-21_14h32_01](https://user-images.githubusercontent.com/65772654/99878544-7b00ad80-2c06-11eb-8987-c2274136c21a.png)

**Comment by mworion** [comment]
Rüdiger,

Made a release as the adjustments should be only in python64 is used. v0.220.1

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

true, this is extremely slow. There is a very high risk of accidental user interaction, which will make the update fail. Better to keep the error message, as long as it works.

The upload fails at following window:

![2020-11-21_15h55_03](https://user-images.githubusercontent.com/65772654/99880199-3ed34a00-2c12-11eb-8a28-390dca4409a8.png)

Logfile attached.
[mw4-2020-11-21.log](https://github.com/mworion/MountWizzard4/files/5577812/mw4-2020-11-21.log)

**Comment by mworion** [comment]
Rüdiger,
build 0.220.2 it gets not really simpler. The automation really give different Button labels for 32 and 64 bit. If 10micron changes their updater it might get a mess anyway. Let's see. There is hardly any chance to speedup or hide the windows.
I tried doing everything with 64bit. 
Michel

**Comment by Ruediger3** [comment]
Ok, now it finishes and is a bit faster. Don't spend too much time on it. It is minor, though very nice.
In worst case we can stay with 32. It throws some warnings, but works. Not nice, but who cares?

Cheers
Rüdiger
