### ISSUE TITLE
Satellite window: Open with selected sat

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#82]
Hi Michel,

a very minor improvement suggestion: Whenever I open satellite window I have to re-select the satellite via double click to populate it with data. By default it is always empty.

Suggestion: Open the window with the already selected satellite.

Thank you!

Cheers
Rüdiger

**Comment by mworion** [comment]
done with 0.211.0

**Comment by Ruediger3** [comment]
Fix confirmed. Many thanks!

Cheers
Rüdiger
