### ISSUE TITLE
Defined park position: Incomplete action

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#83]
Hi Michel,

I have found an major issue when using the function given in the first screenshot. It slews the mount to the give and correct position, but it only stops tracking instead of issuing the command "park at current position".
So the mount still executes any followed slew command instead of ignoring it, since it is parked. This logic must be changed in my opinion, since it is dangerous, since the mount is not parked, though the function claims it.

Thanks
Rüdiger

![2020-11-07_10h57_47](https://user-images.githubusercontent.com/65772654/98438136-7a392900-20e8-11eb-803f-f4afb3990b74.png)

![2020-11-07_10h57_53](https://user-images.githubusercontent.com/65772654/98438141-8624eb00-20e8-11eb-9fab-2559938c928c.png)

**Comment by Ruediger3** [comment]
Or introduce an option "issue 'park here' after slew". So you can decide what should happen. Default should be on.

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,

that's a very good, but basic Question. I have to think about it, because in other cases I ignore the Park state as well. E.g. you could start a model from parked position without unpark.

Michel

**Comment by Ruediger3** [comment]
Well, then it is definitely not a park position, but a simple QuickPos. Park means a safe position where the mount is in a **fused** state, where as currently the moment it is only doing a Alt/Az goto with stopped tracking - and this is something completely different and also separated in the mount's firmware.
An option field could solve the problem. 

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger,
implemented. See 0.220.0

**Comment by Ruediger3** [comment]
Hi Michel,
looks great! Thank you very much. I will test it, as soon I have the mount up and running again (it is in the shelter due to bad weather).

But we can close it and if there should be a problem (what I do not expect) we can reopen it.

Again many thanks, it is getting better and better with every release! Great work!
Cheers Rüdiger

**Comment by Ruediger3** [comment]
Hello Michel,
just tested and works as expected. Thx!
Enjoy your weekend!
Rüdiger
