### ISSUE TITLE
Settings for Astrometry.net local solver / Windows

### ISSUE THREAD

**Issue by hdiessner** [mworion/MountWizzard4#85]
In Previous version of MW (e.g. MW3) settings for astrometry.net were done by using the IP/Port like localhost:3000; in MW4 there is "Folder application" and "Folder astrometry index" required. What needs to be entered here to get it working?
If I enter the path for Astrometry.net Local Solver (containing e.g. the start_ansvr batch file)
and the Astrometry.net download directory for index files (containing the index...fits files)
I still get a red label on the Solver Tab (using Windows 10).

What files / directories do I need to look for?

**Comment by mworion** [comment]
Hi,
MW4 supports on windows the EKOS/KStars astrometry.net solver and ASTAP. I would recommend using the ASTAP solver as it comes with an Windows installer and solves in about 2s. If you have EKOS/KStars installed with local astrometry.net solver you could use it as well.
The installation of an local running server offering a web interface like nova.astrometry.net was a hurdle for many users. With ASTAP you have a fast local running solver for all platforms.
Hope this helps
Michel

**Comment by hdiessner** [comment]
Hi Michel,
thank you! switching to ASTAP did the trick :)
