### ISSUE TITLE
Need for support python 3.6, python3.7

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard4#89]
Please comment if there is any reason for keeping these versions. Probably there is some chance to update.
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
no need for backwards compatibility. Currently installed 3.8.6 / 64Bit.

Cheers
Rüdiger

**Comment by fredd2019** [comment]
Not aware of an issue with moving to 3.7.
Frederic

**Comment by airscottdenning** [comment]
Nope! Let 'em go!

**Comment by mworion** [comment]
Closing,

MW4 will support with its first release python 3.7 - 3.9

Michel
