### ISSUE TITLE
Impact Flip Slew Tol / Flip Guide Tol to "Generate Model Points"

### ISSUE THREAD

**Issue by kaythriemer** [mworion/MountWizzard4#9]
Hi Michel,
I have just some other additional questions.

It is possible to show and change the values Flip Slew Tol and Flip Guide Tol of the mount.
Possible values in MountWizzard4 are -20 to 20 for both settings.
I checked the User Manual for my mount and possible settings for my mount (GM2000HPS) are:
Flip Slew Tol : 0..30
Flip Guide Tol : 2..30
with the restriction that Flip Slew Tol <= Flip Guide Tol .
That means no negative values. but max value is 30.
Do you know, if possible values for this settings depending on mount type ?

The settings  Flip Slew Tol and Flip Guide Tol  has impact to the number of generated modelpoints, e.g. if I choose "Generate model points equally distributed".
If I activate "Auto delete points below horizon" it removes also points left and right beside the meridian depending on the Flip Slew Tol and Flip Guide Tol  values.
Can you explain why ?

Furthermore I have a question again to "Generate model points equally distributed".
If I chooses number of points = 50 -> 25 points will be generated for the model.
points 75 -> 36
points 100 -> 49
points 125 -> 61
.
.
That means only about the half of number of points will be generated ?
Probably it did not understand the system.

Thank you,
Kay.

**Comment by mworion** [comment]
Hallo Kay,

there is no way (out of the command protocol) to determine the possible limits from the mount. I checked the value for my GM1000HPSII, which is the same as yours (to be precise in my handbook Flip Slew is 1 to 30deg). So my guess is that all variants have the same value an I will adapt the min / max settings to that. The restriction flip / slew will be automatically applied from the mount computer, so no action needed.

> The settings Flip Slew Tol and Flip Guide Tol has impact to the number of generated modelpoints, e.g. if I choose "Generate model points equally distributed".
If I activate "Auto delete points below horizon" it removes also points left and right beside the meridian depending on the Flip Slew Tol and Flip Guide Tol values.
Can you explain why ?

Sure. As MW4 is designed to model at maximum speed, it stays away from all constraints which lead into stop or unnecessary flip of the mount. If you enable auto delete points below, MW4 will remove these points as well. So the text is misleading. Even if you have set max / min horizon limits, MW4 will delete points in this area.

> That means only about the half of number of points will be generated ?
Probably it did not understand the system.

Probably better to do it like generate on greater circle and don't tell any numbers. Reason why is simple. I run the algorithm over the full hemisphere and then delete unreachable point. You never know what the outcome is, because it's related to location, time etc.

Will change this as well in the next beta 0.147.7

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
thank you for you fast reply.

Thank you for adapting the limits for Flip Guide/Slew Tol in the next version of MW4.

OK, now I understand, that MW4 will maximize the speed. As I understand, a 10micron mount will slew to objects depending on Flip Slew Tol. That means if Flip Slew Tol is set to 30° it will slew to an object at 29° before (east side) the meridian using the wrong side, that the mount is able to track through the meridian.
So my idea is, instead removing the model points left and right beside the meridian , is it possible to use all generated points within the corridor but calculating the way, how they are slewed, depending on Flip Slew Tol. So that all points on the west side of the hemisphere including also the point from the east side within the corridor.
It is not easy to describe it clearly what I mean.

Deshalb noch mal kurz in deutsch, sorry.
Im Moment werden alle Punkte, die rechts und links des Meridians liegen und innerhalb der Flip Slew Tol liegen entfernt. Die Montierung fährt aber Punkte, die östlich des Meridians innerhalb dieser Flip Slew Tol liegen, bereits mit der West-Orientierung an. 
Wenn man das bei der Reihenfolge berücksichtigt, wie die Punkte beim Model erzeugen angefahren werden, dann müßte die Montierung trotzdem nicht immer umschwenken.
D.h. den westlichen Modelpunkten werden einfach die östlichen Modelpunkte zugeordnet und diese in der Reihenfolge wie diese angefahren werden berücksichtigt.

Just an idea, I dont know how complex it is, to implement this.

Thank you. 
Kay.

**Comment by mworion** [comment]
Kay,

Finally didn‘t get it. But I might be wrong. First, many recommendation don‘t set the tolerance not to really big numbers, say 3-5 degrees. If so, only few points are left out. This might be not e big deal.
Sorting points like the mount will use it (depending if you have a dome or not - wish: sort to low high) or the tolerances different etc. gets really complicated. In addition my understanding of the flip slew tolerance e.g. set to 30 deg means, if you are on the east side, that the mount will still slow over the meridian (or track if you select the other tolerance), but not before !. So the mount will always cross the meridian (shorter or longer) when slewing or tracking.

Does this make sense ?

Michel

**Comment by kaythriemer** [comment]
Hi Michel,
first of all thank you for your support.

I think in general we have the same understanding of the meaning if Flip Slew Tol and Flip Guide Tol.

Just a explanation for these two settings in my own words:

Flip Guide Tolerance: 
Imagine you are doing long exposure time photography of an object. During the photo session, the object will cross the meridian.  
If Flip Guide Tolerance is set to 0, the mount will stop tracking, when the object crosses the meridian.
If Flip Guide Tolerance is set to 25, the mount will still track the object until it is 25° behind the meridian on west side.
This parameter is used during tracking (guiding) an object. So you can follow the object longer.

Flip Slew Tolerance:
Imagine you want to photograph a object which is at this time 20° before meridian at east side.
If Flip Slew Tolerance is set to 0, the mount will slew to the target having the telescope on the west side of the mount pointing east. (As usual for a German mount). And some time later, when the object crosses the meridian, the mount has to flip.
If Flip Slew Tolerance is set to 25, the mount will slew to the target with the telescope on the east side of the mount (pointing west) and you are able to follow the object along the meridian transit without the need to flip  the mount.
This parameter is only used for slewing.

Now to my idea.
Is it possible to remove only model points below the horizon and keep the point s within Meridian limits and shift the start point to the first point east from meridian limit?
![MW4Model](https://user-images.githubusercontent.com/28596048/73384744-2503f780-42cc-11ea-805b-df6db78638bd.png)
I will try to explain it using attached picture.
Flip Slew Tol is set to 30. For that reason points 0 to 4 and 47 to 49 are within the meridian limits and will be actually removed if "Auto delete points below horizon" is activated.

My idea is to start the Model Build with the first point east from Meridian limits. (In my example point 5). Then follow the slew path to point 6, 7, 8, etc. After point 25 the mount will flip and slew to point 26, 27,..., 49 , 0,1,2,3. Because the mount will slew the points 0,1,2,3,4 with telescope on the east side of the mount (pointing west). 

So actual point of old model 5 will be point 0 in new model, 
actual 6->1
7->2
etc.
45->40
49->44
0->45
1->46
2->47
3->48
4->49

Using such a way to Build the Model should be also fast without unnecessary mount flips and also including points within the meridian limits.

Btw. I have no dome, for that reason I prefer Sorting East/West. I understand that the sorting High/Low is more useful with a dome.

Kay

Sorry, I don't want to needle you to much.

**Comment by mworion** [comment]
Kay,

got it now. I keep it in mind. To much work to implement this. I split the auto delete into two parts: horizon and meridian, which can be selected now separately.
v0.147.8
What discovered even set the tolerance to 20deg I could go up to 40deg with my mount. This is strange. Will discuss this with the 10micron guys.

Michel

**Comment by kaythriemer** [comment]
Michel,
motivated by your last statement I checked how far my mount will track/guide behind the meridian using different settings.
Here my findings:
Slew Guide Tol -> AZ -> behind meridian
2  -> 182°40' -> 2°40'
10 -> 193°42' -> 13°42'
20 -> 206°54' -> 26°54'
30 -> 219°02' -> 39°02'

As you can see, my mount is also tracking more than expected behind the meridian.

Kay.

One question, in v0.147.8 it is not yet possible to select horizon and meridian point removal separately ?

**Comment by mworion** [comment]
Kay,
missed to include it. Available in 0.147.9.
But It's not ok that the mounts track that far. It should be a security point to to crash in the pier.
Michel

**Comment by kaythriemer** [comment]
Michel,
I agree it is a security point, if the mount tracks to far.
But, i had a fallacy in determining how far the mount tracks behind the meridian.
I thought I can easily use the shown AZ coordinates, but this is wrong. I have to use RA value and calculate the angle depending on this.
Sorry I wanted to support you by giving my the values of my mount but the values above are wrong.
I will investigate again and send you the corrected values.
Kay.

**Comment by kaythriemer** [comment]
Michel, 
I recapitulate how I can easily find out how far the mount tracks behind the meridian.

The easiest way is to show the HA/DEC coordinates. 
![grafik](https://user-images.githubusercontent.com/28596048/73569853-857d6b00-446b-11ea-82a3-eeb7154bc20f.png)
The HA shows the angle behind the meridian, so no translation is necessary. 

Knowing this I measured again how long my mount tracks behind the meridian and it works es expected:
Slew Guide Tol -> HA
2° -> 1°55'
10° -> 9°55'
20°-> 19°55'
30°-> 29°55'
![grafik](https://user-images.githubusercontent.com/28596048/73570524-d17cdf80-446c-11ea-8cf9-3f7a7d2826a0.png)


So the Slew Guide Tolerance seems to be working with my mount correctly.

Kay
