### ISSUE TITLE
Override location settings (Enhancement)

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard4#90]
I recently posted on the INDI github page about the 10micron driver not setting Site Longitude correctly: setting Longitude on a client like Ekos only transfer to the mount hh and mm. But not ss (seconds).
So each time the driver is connected to the mount it updates the site location on the mount and the correct value has to be entered again on the handpad.
With a mount like the 10micron setting exact site location is important as it affects guiding.

Jasem explained that the original lx200 driver specifications only provide the hh mm format, without seconds (strange enough to me that's not the case for Latitude which include seconds too). 
Updating the driver specs could break compatibility with other devices.

It could be useful if MW4 stores the correct site location (including seconds) and, as an option, overrides the driver setting pushing a button.

Does any other 10micron owner experience the same behavior? 
Ferrante

**Comment by mworion** [comment]
Hi Ferrante, 
Is there not a switch disabling the site location update to the mount from EKOS ?
Michel

**Comment by fenriques** [comment]
hi Michel,
there's a 'Mount Updates Kstars' switch on the settings page of Kstars. 
But even selecting that option, the INDI driver updates the mount not just when INDI server starts but also when a new location is set.
ferrante

**Comment by mworion** [comment]
Hi Ferrante,

I would recommend to talk to Hans Lambermont (hans@lambermont.dyndns.org) and ask him about changing this behavior in the driver. He is the author of the original one and might be able to help. He is a very nice guy.

Michel

**Comment by fenriques** [comment]
Thanks for the advice Michel,  I will write to him.
Ferrante
