### ISSUE TITLE
3D printed cable brackets for 10Micron mount

### ISSUE THREAD

**Issue by airscottdenning** [mworion/MountWizzard4#92]
Thank you very much for providing these. Generally very successful. 

For the documentation: user will need two M6-32 x 16 mm screws to attach cable-holder-part1.stl to the mount, replacing the much too shallow screws that are removed from the mount housing.

A couple of minor comments:

* The T-bracket (cable-plate.stl) that you attach to your scope dovetail doesn't work for my setup and is likely only useful to you (specific to your scope, dovetail, and riser blocks). Requires a lot of vertical space between dovetail and scope and a particular hole pattern in the plate

* Cable holder parts 2 and 3 (cable-holder-part3.stl) are redundant. I prefer cable-holder-part2.stl because it fits better.

Probably no big deal for somebody printing their own parts, but I paid for two parts that I couldn't use from a commercial 3D print shop.

Thanks again!
Scott

**Comment by mworion** [comment]
Scott,

 thanks for the feedback, I add you comments to the documentation !
-> readme on github and docs: [https://github.com/mworion/MountWizzard4/blob/master/docs/source/mechanics/cables.rst](url)

Michel

**Comment by Ruediger3** [comment]
Hi Michel,
the provided link does not work for me :(
Greetings
Rüdiger

**Comment by mworion** [comment]
Updated the link...
