### ISSUE TITLE
Improvement: Alt/Az moves

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#94]
Hello Michel,

I would suggest following improvement.

The 10M supports via handbox direct Alt/Az slews. It would be great to have a direct input in MW4. The park/quick positions are no option, if you have to make many consecutive moves in a row, because you would have always to alter the saved positions. 

Optimal would be:
1. if you could toggle the slew pad already available in MW4 to Alt/Az mode 
![2020-12-15_08h40_32](https://user-images.githubusercontent.com/65772654/102185337-34267080-3eb1-11eb-80c9-661ff9350787.png)

2. two input fields for coordinates

What is it good for?
For example if you want to create a horizon map you have to slew to all 360° around and level to the horizon. To do this in precise fixed Az steps with keypad is very tedious. So an Alt/Az move control could massively ease this process.

You could target all the obstacle outlines very easy. You could even think about adding this point directly to the horizon map. That would absolutely gorgeous. For this I open another issue.

Thanks
Rüdiger

**Comment by mworion** [comment]
Hi Rüdiger,

there are no commands for moving in Alt / Az direction in the command protocol. This would be a long tail in implementation most likely that Filippo needs to implement the commands.

Michel

**Comment by Ruediger3** [comment]
Hi Michel,

Thats strange, since the hand box knows "Goto Alt/Az". And this is not implemented in the native protocol? Well then definitely that is an issue for Flilppo.
 
But could we at least implement something equal to the QuickPos/ParkPos? At least a field where I can enter the coords an hit slew? Instead of a continuous move having a Goto. That would also be big help.

Cheers
Rüdiger

**Comment by mworion** [comment]
Christmas!
![Bildschirmfoto 2020-12-17 um 18 55 26](https://user-images.githubusercontent.com/6632980/102524840-ce490d00-4099-11eb-8de9-f3ec66032874.png)
Testable in 0.220.4b7
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
YES! It must be X-Mas! What a wonderful gift :D
Thanks a lot. It looks great. I have installed it and will test is as soon the weather allows it.

Best wishes
Ruediger

**Comment by Ruediger3** [comment]
Hi Michel,

I am just testing and found an issue: If you initiate an Alt/Az move the mount starts tracking, regardless the tracking state before.

Cheers
Rüdiger

**Comment by mworion** [comment]
Rüdiger
0.220.4 will keep the tracking state. Will be available in 2 hours, test are running
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

installed but not tested yet due to weather. But I think we can close this request.
Thank you very much!

Cheers
Rüdiger
