### ISSUE TITLE
Improvement: Assisted horizon map creation - adding current poition to horizon map.

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#95]
Hello Michel,

related to improvement #94 I would appreciate following function for refining and creating the horizon map:

There could be a buttonin "Hemis" Window with the function "Adding the current mount's position to horizon map"

This would ease the creation of a horizon map, since all points could be slewed precisely with the scope. There is no need write it down, and add in manually to file in editor. This would be dramatic improvement and should not be so complicated to implement, since all basic functions are already there. 

For me and others with complex obstructed sky this would help a much. Also these points could be used for horizon models in other software like Stellarium, Card de Ciel. 

This function would be very useful and that is my X-Mas wish :) 

Thank you in advance!
Rüdiger

**Comment by mworion** [comment]
Good idea,

should be able to implement this !

Michel

**Comment by Ruediger3** [comment]
Great! Thanks a lot!
Ruediger

**Comment by mworion** [comment]
Christmas!
![Bildschirmfoto 2020-12-17 um 18 55 40](https://user-images.githubusercontent.com/6632980/102524606-85915400-4099-11eb-844d-a3f1228dabf1.png)
Testable in 0.220.4b7
Michel

**Comment by Ruediger3** [comment]
Hi Michel,
Thanks for the wonderful second gift! I will test is as soon the weather allows it.

BTW: Nina is working on a Advanced Sequencer trigger which uses the horizon line to control the imaging session. With this new function the horizon limits can be easily measured and used in multiple places. As soon as the weather allows it, I will model a very precise horizon line. Only to think about how to export the Alt/Az touples from the file to simple text file with one touple per line.

I will keep you updated :)

Best wishes
Rüdiger

**Comment by Ruediger3** [comment]
Hi Michel,
I have just created a real measured horizon map. Except the mount starts tracking after Alt/Az move it works great!
Cheers 
Rüdiger

![2020-12-18_15h53_53](https://user-images.githubusercontent.com/65772654/102628051-66ea9600-4149-11eb-

**Comment by mworion** [comment]
Rüdiger
0.220.4 will keep the tracking state. Will be available in 2 hours, test are running
Michel

**Comment by Ruediger3** [comment]
Hi Michel,

works as expected. Many thanks it is really useful. NINA with custom Horizon maps was released tonight. That I will test today.
Only one minor request is open, but for that I will place a dedicated issue.

Thanks again! Awesome work!

Cheers
Rüdiger
