### ISSUE TITLE
Imaging Window: CCD Temp and SQM wrong

### ISSUE THREAD

**Issue by Ruediger3** [mworion/MountWizzard4#97]
Hi Michel,

maybe a bug. CCD Temp is shown as 0.0, though it is -15. Please see screen shot. Not a big issue, but you may check.
Same with SQM. It shows 0.0 though it is 20.09. Also Filter numbering is wrong. Should be 1 not 0.

Cheers
Rüdiger

![2020-12-18_19h38_49](https://user-images.githubusercontent.com/65772654/102649090-e3d93800-4168-11eb-86a0-898174cc49bb.png)

**Comment by mworion** [comment]
Rüdiger,

you’re right. Normally I use the the FITS data for populating this vales. On ASCOM / ALPACA there is nothing. So I have to add these values myself.

Michel

**Comment by mworion** [comment]
Rüdiger
0.220.5 fixes this. 
Still MW4 will not be a full imaging application. But showing at least the values MW4 will show itself is necessary.
Michel
